import { preparedOpticalFixture } from "./prepared-optical-publication.ts";
import { preparedOpticalPublicationHash } from "../prepared-optical-publication.ts";
import { opticalPublicationContentHash } from "../optical-publication-content.ts";
import type { PreparedProgressiveOpticalPublication } from "../prepared-progressive-optical-publication.ts";

/** Structural black/opaque fixture only. Actual pixels and source ancestry
 * are admitted at the offline producer, not generated by this fixture. */
export function preparedProgressiveOpticalFixture(): PreparedProgressiveOpticalPublication {
  const parent = preparedOpticalFixture(), content = { bytes: 256, sha256: "3".repeat(64) };
  const rgba = { bytes: 1024 ** 2 * 4, sha256: "4".repeat(64) };
  const root: PreparedProgressiveOpticalPublication = {
    ...parent, schemaVersion: "prepared-observation-optical-publication-v2", imageVersion: "prepared-optical-v2",
    publicationId: "synthetic-progressive-prepared-v2",
    parent: { publicationHash: preparedOpticalPublicationHash(parent), publication: parent },
    fineGrid: { pixels: 1024, fieldDegrees: parent.levels.DETAIL.fieldDegrees, crpixFitsOneBased: 512.5,
      rgba, rgbaNpy: { bytes: rgba.bytes + 128, sha256: "5".repeat(64), format: "npy", shape: [1024, 1024, 4], dtype: "uint8", rowOrder: "top-first" },
      producerMetadata: content, producerReceipt: content, sourceRgbSha256: parent.source.decodedRgb.sha256,
      sourceAvmHash: opticalPublicationContentHash(parent.source.nominalAvm),
      geometricSupportPixels: 1024 ** 2, geometricBlackPixels: 1024 ** 2,
      scientificAvailability: "UNKNOWN", scientificValidity: "UNKNOWN", unit: "published-encoded-RGB" },
    processing: { ...parent.processing, producerVersion: "prepared-rgb-tan-progressive-v2",
      validation: "BOUND_SAME_SOURCE_GRIDS_AND_LEVELS_CHECKED", producerReceipt: content },
    levels: {
      OVERVIEW: { ...parent.levels.OVERVIEW, samplingGrid: "master",
        masterCrop: { boundsXYExclusive: [0, 0, 2048, 2048], boxFactor: 4 } },
      MEDIUM: { ...parent.levels.MEDIUM, ...content, pixels: 1024, crpixFitsOneBased: 512.5, samplingGrid: "master",
        masterCrop: { boundsXYExclusive: [512, 512, 1536, 1536], boxFactor: 1 },
        geometricMasterSupportPixels: 1024 ** 2, alphaPixels: { opaque: 1024 ** 2, partial: 0, zero: 0 } },
      DETAIL: { ...parent.levels.DETAIL, ...content, pixels: 1024, crpixFitsOneBased: 512.5, samplingGrid: "fine",
        masterRgbaSha256: rgba.sha256, masterCrop: { boundsXYExclusive: [0, 0, 1024, 1024], boxFactor: 1 },
        geometricMasterSupportPixels: 1024 ** 2, alphaPixels: { opaque: 1024 ** 2, partial: 0, zero: 0 } },
    },
  };
  return root;
}
