import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { buildSafetyCorrection, buildSpotSubmission, publishReview } from "@starward/domain/community";
import { colors, minimumTouchTarget, radii, spacing, type as typeToken } from "@starward/ui-system/tokens";
type Key = "new-spot-privacy" | "transient-report-expiry" | "safety-correction" | "media-sanitization" | "trust-and-moderation-status" | "multidimensional-review";
type Item = [string, string, string, string?]; const p = colors.planning;
const actions: Array<[Key,string,string]> = [["new-spot-privacy","community-submit-spot","新地点"],["transient-report-expiry","community-submit-report","现场实况"],["safety-correction","community-submit-correction","安全纠错"],["media-sanitization","community-upload-media","照片隐私"],["trust-and-moderation-status","community-open-trust","审核状态"],["multidimensional-review","community-open-review-form","多维评价"]];
function evidence(key: Key): Item[] {
  if(key==="new-spot-privacy"){const x=buildSpotSubmission({latitude:22.529,longitude:113.9468,landStatus:"private-unknown",requestedVisibility:"public-exact",duplicateCandidates:["西涌海滩东侧"]});return [["spot-location-precision","精确位置仅供审核 · 公开为模糊位置",`公开 ${x.publicCoordinate.latitude}, ${x.publicCoordinate.longitude}；原始 WGS84 来源=user-confirmed`,"疑似私人土地：必须核对权属、开放和坐标公开级别"],["spot-consent-scope","单独同意：审核员可见精确坐标","实景、拍摄时间/方向、停车/徒步、设施、遮挡、光污染和安全字段逐项确认"],["spot-submission-status",`草稿 ${x.draftId} · 审核 ${x.reviewId}`,"发现 1 个可能重复地点 · 人工审核前不会公开或成为安全结论"]];}
  if(key==="transient-report-expiry")return [["report-expiry","实况有效至 03:00 · TTL 2 小时","云量 18% · 起雾 · 银河可见；自动位置/时间已由用户核对","拥挤/道路 4h，临时设施 24h；阈值策略版本 moderation-v1"],["report-current-state","当前：厕所今晚关闭 · 待验证","有效期内影响今晚展示；03:00 后退出当前聚合","长期事实仍为“通常有厕所”，未被改写"],["report-source-time","来源：现场用户 · 01:00 · ±18 m","过期后保留不可变历史、来源、版本和审核记录"]];
  if(key==="safety-correction"){const x=buildSafetyCorrection({category:"closed-road",capturedAt:"2026-07-20T23:40:00+08:00",evidenceIds:["photo-17","track-5"]});return [["correction-safety-impact","安全影响：道路封闭 · P0",`工单 ${x.caseId} · 现场时间 23:40 · 证据 2 项`,"地点页与导航前立即显示“待核实警告”"],["correction-review-state","待核实 · 2 小时内初审","6 小时未确认则过期/降级；两个独立到访确认提高可信度"],["correction-original-version","原地点版本 11 已保留","不会宣称永久关闭；采纳只生成新版本并留下审计"]];}
  if(key==="media-sanitization")return [["media-location-stripped","位置已移除 · 设备序列已清理","公开副本只含用户确认的拍摄时间 00:42、方向 168° 和曝光 10s","短期凭证直传；原始对象仅获授权审核员可见"],["media-review-state","处理完成 · 人工审核中","上传成功 ≠ 审核通过；扫描、缩略、归属和审核均有独立状态"],["media-original-protected","原图受保护 · 不直接分发","EXIF 清理或扫描失败会隔离，绝不回退公开原图"]];
  if(key==="trust-and-moderation-status")return [["contributor-trust-level","匿名贡献者 · 等级 2","通过审核 6 次 · 争议率 8% · 两位独立到访确认","信誉只影响低风险短期发布，不能替代来源与新鲜度"],["moderation-visible-status","审核：需补充 · 存在争议","上传者看到缺少权属证明；普通用户只看到待核实、时间、确认数与争议"],["moderation-appeal-entry","补充证据 / 7 天内申诉响应","争议内容冻结自动聚合，原始证据和决定不被覆盖"]];
  const r=publishReview({darkness:4,access:3,photography:5,visitedAt:"2026-07-20",verifiedVisit:true});return [["review-darkness-rating","天空暗度 4/5 · 已填写","到访 2026-07-20 · 位置派生验证"],["review-access-rating","可达性 3/5 · 已填写","停车后步行 820 m；评价维度独立，不用综合星级掩盖风险"],["review-safety-rating","安全：未体验 · 保持空",`摄影 5/5 · 已填写；社交动作 ${r.socialActions.length} 项`,"无关注、粉丝、私信或通用动态入口"]];
}
function Evidence({item}:{item:Item}){return <View testID={item[0]} style={s.card}><Text style={s.cardTitle}>{item[1]}</Text><Text style={s.cardBody}>{item[2]}</Text>{item[3]?<Text style={s.meta}>{item[3]}</Text>:null}</View>}
export function CommunityScreen({fixture}:{fixture?:string}){const recommended=fixture?.split(":")[1] as Key|undefined;const[active,setActive]=useState<Key|null>(null);return <SafeAreaView testID="screen-community-contribution" style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>社区贡献 · 证据优先</Text><Text style={s.title}>把现场信息变成可核验的帮助</Text><Text style={s.subtitle}>地点、实况、照片和纠错分开保存来源、有效期与审核状态；社区内容不会覆盖硬安全信息。</Text><View style={s.actions}>{actions.map(([key,id,label])=><Pressable key={key} testID={id} onPress={()=>setActive(key)} style={({pressed})=>[s.action,recommended===key&&s.recommended,pressed&&s.pressed]}><Text style={s.actionText}>{label}</Text></Pressable>)}</View>{active?<View style={s.panel}>{evidence(active).map(item=><Evidence key={item[0]} item={item}/>)}</View>:<View style={s.empty}><Text style={s.emptyTitle}>贡献范围保持克制</Text><Text style={s.emptyBody}>只支持观星决策需要的地点、实况、图片、多维评价、纠错与行程分享，不建设通用信息流。</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:p.canvas},content:{padding:spacing.x2,paddingBottom:48,gap:spacing.x2},eyebrow:{color:p.primaryActive,fontSize:typeToken.label,fontWeight:"700"},title:{color:p.text,fontSize:typeToken.title,fontWeight:"700"},subtitle:{color:p.textSecondary,fontSize:typeToken.body,lineHeight:23},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.x1},action:{minHeight:minimumTouchTarget,justifyContent:"center",paddingHorizontal:14,borderWidth:1,borderColor:p.border,borderRadius:radii.pill,backgroundColor:p.surface},recommended:{borderColor:p.primaryActive},pressed:{opacity:.68},actionText:{color:p.text,fontWeight:"700"},panel:{gap:spacing.x1,padding:spacing.x2,borderRadius:radii.layer,backgroundColor:p.surface},card:{minHeight:92,padding:12,borderRadius:radii.control,backgroundColor:p.surfaceMuted},cardTitle:{color:p.text,fontWeight:"700"},cardBody:{marginTop:5,color:p.text,lineHeight:19},meta:{marginTop:5,color:p.textSecondary,fontSize:typeToken.caption,lineHeight:17},empty:{minHeight:170,justifyContent:"center",padding:spacing.x2,borderRadius:radii.layer,backgroundColor:p.surface},emptyTitle:{color:p.text,fontSize:typeToken.section,fontWeight:"700"},emptyBody:{marginTop:spacing.x1,color:p.textSecondary,lineHeight:21}});
