import test from "node:test";import assert from "node:assert/strict";
import {assertOpticalHipsManifest} from "./optical-hips-publication";
import {opticalHipsSources} from "./optical-hips-source";
import {assertOpticalHipsRights} from "@starward/miniapp-contracts";
const hash="a".repeat(64),did="ivo://CDS/P/Skymapper/DR4/color";
function root():any{return {schemaVersion:"starward-optical-hips-v2",publicationId:"local-skymapper",publicationHash:hash,scope:"TRIAL",processing:"Unchanged PNG",limitations:["Limited region"],sources:[{id:"skymapper-dr4",title:"SkyMapper DR4 color",provider:"ANU / CDS",originalDataUrl:"https://doi.org/10.25914/5M47-S621",originalRights:"CC BY4.0",originalRightsUrl:"https://creativecommons.org/licenses/by/4.0/",hipsRecordUrl:"https://alasky.cds.unistra.fr/MocServer/query?ID=CDS/P/Skymapper/DR4/color",hipsLicense:"ODbL-1.0",hipsDoi:null,hipsCreatorDid:did,format:"png",tileWidth:512,maxOrder:8}],shards:[{sourceId:"skymapper-dr4",order:8,dir:400000,file:"skymapper-dr4/Norder8/Dir400000/index.json",sha256:hash,bytes:300,tileCount:1,indexUrl:`/v2/sky/optical/${hash}/skymapper-dr4/8/400000/index`}]};}
test("v2 explicitly missing processed DOI retains real dataset DOI and HiPS identifier",()=>{const r=root();assertOpticalHipsManifest(r);const [original,processed]=opticalHipsSources(r,["skymapper-dr4"]);assert.equal(original!.sourceUrl,"https://doi.org/10.25914/5M47-S621");assert.equal(processed!.attribution!.url,r.sources[0]!.hipsRecordUrl);assert(processed!.attribution!.name?.includes(did));assert(!JSON.stringify(processed).includes("doi.org/null"));assert(!processed!.attribution!.name?.includes("10.25914/"));});
test("legacy v1 DOI source keeps its original DOI link and title",()=>{const r=root();r.schemaVersion="starward-optical-hips-v1";r.sources[0].hipsDoi="10.26093/cds/aladin/598a-0e";delete r.sources[0].hipsCreatorDid;assertOpticalHipsManifest(r);const processed=opticalHipsSources(r,["skymapper-dr4"])[1]!;assert.equal(processed.attribution!.url,"https://doi.org/10.26093/cds/aladin/598a-0e");assert.equal(processed.attribution!.name,"HiPS DOI 10.26093/cds/aladin/598a-0e");});
test("unknown DOI is explicit null only in v2 with a real identifier; malformed identity rejects",()=>{for(const mutate of [(r:any)=>r.schemaVersion="starward-optical-hips-v1",(r:any)=>r.sources[0].hipsDoi="",(r:any)=>delete r.sources[0].hipsDoi,(r:any)=>delete r.sources[0].hipsCreatorDid,(r:any)=>r.sources[0].hipsCreatorDid="https://example.org/identifier",(r:any)=>r.schemaVersion="starward-optical-hips-v3"]){const r=root();mutate(r);assert.throws(()=>assertOpticalHipsManifest(r),/optical_publication_invalid/);}});
test("v2 complete rights bind creator identifier to original properties and preserve content/database separation",()=>{
 const r=root(),master="https://example.org/master",file="skymapper-dr4/Norder8/Dir400000/index.json";
 const notice:any={schemaVersion:"starward-optical-hips-rights-v2",publicationHash:hash,scope:"TRIAL",offerChoice:"ODbL-1.0 4.6(b)",sources:[{sourceId:"skymapper-dr4",database:{title:"SkyMapper",creator:"CDS",copyright:"CNRS/Unistra",doi:null,creatorDid:did,license:"ODbL-1.0",licenseUrl:"https://opendatacommons.org/licenses/odbl/1-0/",recordUrl:r.sources[0].hipsRecordUrl,notice:"Separate database notice"},originalContent:{copyright:"ANU",grantUrl:"https://api.datacite.org/dois/10.25914/5M47-S621",rights:"CC BY4.0",acknowledgementUrl:"https://skymapper.anu.edu.au/how-to-cite/",acknowledgement:"Complete original acknowledgement",sourceAcknowledgement:"Original DR4 DOI 10.25914/5M47-S621",sourceProperties:{bytes:100,sha256:hash,utf8:`creator_did = ${did}\n`}},originalMaster:master,sourceInstancePolicy:"Copy only the public master"}],alterations:{type:"Exact finite subset",pixelBytes:"UNCHANGED",selectedTiles:[{sourceId:"skymapper-dr4",order:8,pixel:401329,originalUrl:master+"/Norder8/Dir400000/Npix401329.png",sha256:hash,bytes:611836,localPublishedFile:"skymapper-dr4/Norder8/Dir400000/Npix401329.png",exactVersionDownloadUrl:`/v2/sky/optical/${hash}/skymapper-dr4/8/401329`}],completeResultMetadata:{manifest:{file:"manifest.json",bytes:100,sha256:hash,utf8:"exact manifest"},indexes:[{file,bytes:300,sha256:hash,utf8:"exact index"}]},reproductionMethod:["Unchanged original PNG"]}};
 assertOpticalHipsRights(notice,r);const sources=opticalHipsSources(r,["skymapper-dr4"],notice);assert.equal(sources[0]!.license,"CC BY4.0");assert.equal(sources[1]!.license,"ODbL-1.0");assert(sources[0]!.attribution!.statements?.includes("Complete original acknowledgement"));
 for(const change of [(n:any)=>n.sources[0].database.creatorDid="ivo://CDS/other",(n:any)=>n.sources[0].database.doi="10.25914/5M47-S621",(n:any)=>n.sources[0].originalContent.sourceProperties.utf8="creator_did = ivo://CDS/other",(n:any)=>n.schemaVersion="starward-optical-hips-rights-v1"]){const bad=structuredClone(notice);change(bad);assert.throws(()=>assertOpticalHipsRights(bad,r),/optical_rights_invalid/);}
});
