const fs=require('node:fs');
function edit(p,fn){fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));}
const ctx='project_context/areas/main/screen-contracts/wechat-miniapp/';
edit(ctx+'spot-and-sky.md',s=>s.replace(/- `spot-terrain-horizon`主图[^\n]+/, '- `spot-terrain-horizon`按本轮反馈改为方形俯视地形图：中心为当前点、真北向上、东南西北显式标注，含距离圈和随尺度变化的比例尺。山体阴影/等高表达有来源的地理高程，不把装饰山景当数据。点击图面或操作方向滑块共享真北顺时针0–360°方位；蓝线与文字给出该方向最大遮挡仰角、控制遮挡点的位置/距离及有数据时的相对高差，不以最高海拔代替最大仰角。有负角保留其意义，无山名不编造。展开地平线不再作为本轮主图。').replace(/- `spot-directional-light`在同方位轴[^\n]+/, '- `spot-directional-light`在同一地理图上以独立半透明夜光栅格表达地表光源分布，独立开关及弱—强图例，与地形各自可读；不能把颜色强弱画成山高或解释为该方向天空亮度。保留年度、距离/方向读数、有效覆盖和来源，不写“东侧光害78%/朝这里保证更暗”。夜光辐亮度不是SQM/Bortle或实测天空辉光。').replace('方向点击、滑动和可访问的方向列表','方向点击、滑块和辅助技术操作').replace('图上无数据扇区留缺口','图上无数据扇区用斜纹/未知标记').replace('但点位曲线不随地图相机或小时标尺改变','但点位遮挡分析不随地图相机、俯视图缩放或小时标尺改变').replace('No-image panel corners: retain both top round corners even at large extent. The rounded-away pixels at the large panel\'s top boundary belong to its presentation shield, not to exposed-map dismissal; the header boundary remains continuous. Smaller extents retain intentional exposed-map navigation and their established drag/scroll rules.', '2026-09-13 panel geometry correction: large fills the available width with square outer top corners, for formal/draft/pending identities with or without valid media. This supersedes the earlier no-image large-rounding rule. Small/medium retain their rounded outer corners; inner content cards retain their own geometry. Do not paint a square shield behind a visibly rounded large panel. Preserve the continuous header/navigation boundary and established drag/scroll responsibilities.').replace('计算、发布、坐标及质量边界见', '尺度建议供本轮审阅：默认外圈半径5 km，可选2/20/50 km；“半径”指中心到外距离圈，方形四角不声称等于该距离。2 km适合近处排查，5 km兼顾近山和局部光源，20/50 km查看更远山体及光源。它们是展示尺度，不是所有影响的物理边界。缩放不得重新截短地形分析，图外控制遮挡点标明距离和“图外”；缺测不等于无遮挡/无光源。真实分析半径需按地形/覆盖验证后确定，演示30 km不构成固定充分范围。VIIRS约500m级栅格不能分辨单盏灯，远城辉光也可能超出50 km；不能用“2 km无光源”推断拍摄不受光污染。数据依据及可复核链接见[地形资源说明](../../../../../docs/design-resources/wechat-miniapp/map/terrain-2026-09-13/README.md#俯视图尺度与本轮修订)。\n\n计算、发布、坐标及质量边界见'));
edit(ctx+'shared-state-and-recovery.md',s=>s.replace('- 列表向左退出、详情由右进入；', '- 外壳进入采用淡入配合轻微放大，退出反向淡出缩小，遮罩同步。当前资源进入240ms、退出180ms、缩放.97→1，减少动态效果移除缩放/位移并即时完成。关闭完成前保留遮罩、焦点与返回拦截；快速关闭/重开接管当前视觉，过期完成回调不能关闭新会话，确认不能重复提交。此责任同时覆盖browse和select-one，不改变下方页面或计划草稿。\n- 列表向左退出、详情由右进入；'));
edit(ctx+'map-and-finder.md',s=>s.replace('## ', '## ')+ '\n2026-09-13外框修订：观星点信息large档在可用区域内全宽、顶部方角，正式/草稿/审核中、有图/无图一致；small/medium与内部内容卡片维持原几何。图层选择sheet采用单一全宽方角外壳，内部白色背景不能在圆角背后再叠方角。保持原高度随内容变化、时间尺、地形复选和LIGHT/TOTAL_CLOUD单选责任，不加入拖柄或新档位。\n');
edit('DESIGN.md',s=>s.replace('无顶部图片时三档均保留顶部圆角；large有全幅顶部图片时沿用图片构图','small/medium保留顶部圆角；large无论身份或有无图片均全宽方角，内部卡片不受影响').replace('无顶部图片时small/medium/large均保留顶部两角；large全幅图片按图片构图，无外阴影','small/medium保留顶部两角；large不论有无顶部图片均全宽方角，无外阴影').replace('日间采用稿由Map ADOPTED的layer-selector包给出：顶角18px且外层裁切','2026-09-13本轮图层修订为全宽方角单一外壳，取代历史顶角18px，不在圆角背后叠白色方框；高度基线仍由Map ADOPTED的layer-selector包给出').replace('展开地平线用北—东—南—西—北共轴与遮挡仰角，年度周边灯光独立色带','按本轮反馈采用真北向上的方形俯视地形图，标注东南西北/距离圈/比例尺，遮挡仰角与距离随查看方向读取；年度地表灯光在图上独立半透明叠加并有独立图例').replace('无顶部图片的三档spot panel保留顶部圆角（沿small/medium的采用几何）；有全幅顶部图片的page-like large才允许radius0；fixed layer sheet top radius28rpx','spot panel small/medium沿用圆角，large无论有无图片均radius0且全宽；本轮Map layer sheet采用全宽方角外壳').replace('2026-09-13完整需求修订边界：','2026-09-13 Modal动效修订：地图/计划共享天文事件Modal外壳淡入放大、淡出缩小，遮罩同步；内部列表/详情仍水平切换。关闭完成前保留模态拦截，取消/重开从当前视觉接管，减少动态效果免除缩放位移。参数与生命周期只在共享owner及当前资源维护。\n\n2026-09-13完整需求修订边界：'));
edit('project_context/architecture/runtime-and-domain.md',s=>s.replace('- 点位曲线与地图阴影共用数据来源', '- 点位俯视地形及遮挡剖面与地图阴影共用数据来源').replace('- 一个modal会话持有', '- 外壳动画由共享modal适配器拥有opening/open/closing阶段，退出完成后再撤销RootPortal与NativeBackBoundary、恢复焦点；重复确认只回调一次，重开取消旧动画/完成回调并从当前opacity/scale接管。减少动态效果移除缩放与位移。Web原型使用WAAPI与dialog顶层验证生命周期，不能直接作为WEAPP API方案，需在真实两入口验证。\n- 一个modal会话持有').replace('- 点位俯视地形及遮挡剖面与地图阴影共用数据来源', '- 地理查看半径与地形分析半径是两个参数：前端2/5/20/50 km只改变展示范围与比例尺，不重算或截断已返回的地平线。派生结果按方向保留最大仰角及对应距离/有效覆盖，图外点可作边界指示并明确“图外”，不能伪造为边界上的实际山体。30 km只作首轮演示/验证起点，后续以更远范围的角度收敛和样点覆盖验证确定真实分析上限；source响应显式携带该上限，不承诺无穷远完整性。点位小图固定北向/中心，以已有影像/Canvas或SVG等价绘制和按钮切尺度，不新增一个可漫游Map实例与面板竖向拖动争抢；具体WEAPP绘制与坐标配准需目标运行时试片验证。\n- 点位俯视地形及遮挡剖面与地图阴影共用数据来源'));
const terrain='docs/design-resources/wechat-miniapp/map/terrain-2026-09-13/README.md';
edit(terrain,s=>s.replace('所有曲线、方向灯光强弱','所有地形形状、方向灯光强弱').replace('曲线缺口不归零、灯光色带独立。方向滑块与点击曲线共享当前方位','现按本轮反馈改为俯视地形图，地形/夜光分项保留缺测与开关。方向滑块与点击图面共享当前方位')+`\n## 俯视图尺度与本轮修订\n\n本轮改为方形地理图、中心点固定/北向上，东南西北标注、距离圈和比例尺齐全。默认外圈半径5 km，另提供2/20/50 km；这些是本轮供审阅的UI尺度建议。地形阴影和夜光格网独立开关，方向线与遮挡仰角/控制点距离联动；图外控制山体仍参与读数，缺测用斜纹及文字标出。5 km用作局部概览，2 km看近山，20/50 km看更远山体/地表光源，不把50 km当光污染影响边界。\n\n[EOG年度VIIRS说明](https://eogdata.mines.edu/products/vnl/)给出15角秒、赤道约500m格网；可看光源分布，不能识别单盏路灯或直接给方向天空亮度。[NPS光污染说明](https://www.nps.gov/subjects/nightskies/lightpollution.htm)指出城市辉光可在很远处仍被观察到，因此1–2 km无源不足以判定拍摄无光害。[GRASS r.horizon](https://grass.osgeo.org/grass-stable/manuals/r.horizon.html)提供最大分析距离等参数及距离输出能力，须核对其角度/距离输出语义；当前演示30 km不代表验证过的充分分析范围。\n\n本轮同时修复large无图/草稿等身份外框为方角、图层sheet单一方角外壳。图中的椭圆山体和夜光格网只是可缩放交互fixture，没有取到该地点真实高程。Stitch旧节点仍是历史生成稿，尚未同步本轮俯视图；收敛采用与删除按项目资源生命周期执行，不能将其称为最新可实施资源。\n`);
edit('docs/design-resources/wechat-miniapp/shared/astronomical-event-modal/README.md',s=>s.replace('方向地平线/夜光','俯视地形/方向遮挡与夜光').replace('图层颜色与曲线是','地形形状、图层颜色与夜光格网是')+'\n本轮反馈修订：观星点large各身份、有图/无图均全宽方角；图层sheet单一方角外壳。地形改为北向上方形地理图（外圈半径5 km，2/20/50可切），分析读数不随视图截短。共享Modal进入240ms淡入+.97→1轻放大，退出180ms反向，遮罩同步；关闭完成后才释放焦点/模态拦截，快速重开取消旧关闭，减少动态效果即时呈现。上述仍是当前供审阅的完整增量资源，不是生产实施证明。\n');
