const fs=require('fs');const path=require('path');const root=process.cwd();
const read=p=>fs.readFileSync(p,'utf8');const write=(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)};
const base='docs/design-resources/wechat-miniapp/';
const files=['map/ADOPTED.md','plan/ADOPTED.md','events/ADOPTED.md','map/revisions/three-requirements-2026-09-13/README.md','plan/revisions/three-requirements-2026-09-13/README.md','map/terrain-2026-09-13/README.md','plan/event-modal-2026-09-13/README.md','shared/astronomical-event-modal/README.md'];
for(const f of files){let s=read(base+f);s=s.replaceAll('新增视觉供本轮审阅','新增视觉已于2026-09-13由用户确认采用').replaceAll('新视觉供本轮审阅','新视觉已于2026-09-13由用户确认采用').replaceAll('新修订待用户视觉审阅','新修订已于2026-09-13由用户确认采用').replaceAll('本次新增视觉待审阅','本次新增视觉已采用').replaceAll('新视觉供审阅','新视觉已采用').replaceAll('新修订供用户审阅','新修订已于2026-09-13由用户确认采用').replaceAll('当前供审阅的完整增量资源','当前已采用的完整增量资源').replaceAll('前两项新增视觉供本轮审阅','前两项新增视觉已采用').replaceAll('地图图层、角度和灯光为设计fixture','地图图层、地形与光污染为设计fixture');write(base+f,s);}
let s=read('project_context/areas/main/screen-contracts/wechat-miniapp.md');s=s.replace('包含地形、B行图标和天文事件Modal三个变更点','包含地形、B行图标、天文事件Modal，以及整体UI/UX校验与Context对齐补开发四个部分').replace('新视觉仍需用户审阅','本轮最终增量视觉已于2026-09-13获用户确认采用').replace('新增视觉审阅、既有图标采用与生产迁移分别记录','当前设计采用与生产迁移分别记录');
s+='\n## 整体UIUX与Context对齐补开发\n\n2026-09-13用户因上一轮实现漂移，明确把完整小程序的UI/UX校验、产品逻辑/技术架构/技术实现逻辑对齐与缺失功能补开发纳入本次同一需求。范围包括当前Map、Search、My、计划、创建/反馈、Sky及其现行子页面、共享组件、账户/权限/错误恢复流程；不是只验本轮地形和Modal，也不自动扩展到独立Native App或运营后台。\n\n以本Screen Contract及相关owner、DESIGN和各页面ADOPTED入口为依据，逐项核对现有实现和真实消费者，修复不一致与缺失功能，完成相关服务/契约/状态责任的必要补齐。核对记录服务于实际修复，不能仅交审计清单或用改写Context来掩盖缺失。已采用资源约束其声明范围；未展示主题/状态沿用所属Context，不能从日间截图推定已覆盖。既有完整基本信息、手势、媒体、时间、计划行程/提醒及身份隔离不得被局部重构删减。\n\n检查必须覆盖代表性身份与加载/空/失败/取消/返回/重复开关/前后台恢复，核对共享组件的全部实际消费者；对比同等视口、数据与状态下的采用资源和当前WEAPP结果，发现漂移即修复。协议/数据/权限由相应服务及适配层保证，页面不复制业务真值。静态原型、源码标记、单一截图或历史检查通过不证明当前产品完成。真实数据覆盖、原生地图叠加、设备动效/传感器等未验证项须具体列明，不能以缺失外部条件为由停止可独立完成的工作。\n\n需求说明与开发起点在[本轮开发说明](../../../../docs/requirements/miniapp-uiux-alignment-2026-09-13.md)；具体规则仍由上述既有owner持有。\n';write('project_context/areas/main/screen-contracts/wechat-miniapp.md',s);
s=read('project_context/architecture.md').replace('三项属于同一完整需求的实施边界，尚未完成生产迁移','上述三项与[整体UIUX及Context对齐补开发](areas/main/screen-contracts/wechat-miniapp.md#整体uiux与context对齐补开发)属于同一完整需求的实施边界；公共Tab视觉反馈一并迁移，设计已采用，生产迁移尚未完成');write('project_context/architecture.md',s);
s=read('project_context/global.md');s=s.replace('- Context owns intended product meaning','- Current Mini Program development scope includes the adopted terrain/icons/event-modal changes and whole-product UI/UX verification, Context alignment and missing implementation repairs; follow the [owning Screen Contract](areas/main/screen-contracts/wechat-miniapp.md#整体uiux与context对齐补开发). Design adoption does not establish implementation completion.\n- Context owns intended product meaning');write('project_context/global.md',s);
s=read('project_context/architecture/runtime-and-domain.md');s+='\n### Mini Program alignment and completion boundary\n\n本轮整体对齐要求由[Screen Contract](../areas/main/screen-contracts/wechat-miniapp.md#整体uiux与context对齐补开发)持有。实现时从现有页面/共享组件/状态协调器、miniapp-contracts、miniapp-api及既有数据管道追踪真实调用和职责，先辨明已有、偏离与缺失，再在原owner补齐。复用语义图标/资源映射、公共时间控件、Map单一呈现与Observation Context、事件目录/条件查询、计划聚合与贡献身份边界；不要将浏览器iframe原型当作生产架构，或新增第二套页面、存储、选中状态、天文算法与图标体系。公共Tab和Modal的共享呈现/交互必须覆盖实际消费者，业务提交仍属于计划/地图等原owner。\n\n新的地形数据处理/叠加是待生产集成能力；真实来源、坐标转换、缺测、版本/缓存、请求取消与预算需要在现有数据适配层验证，示意格网不能升级为产品数据。历史多关联计划按既定兼容编辑策略处理，不得为了单选无提示删除历史关联。检查代码依赖方向、状态生命周期、跨子包组件可加载性与最终小程序体积；低层模块不得导入feature/page。产品规则、架构边界与具体代码实现分别核实，局部源/原型通过不等于整体对齐。必要的重构以当前共享职责为限，不能借整体检查重新设计已采用UI。\n';write('project_context/architecture/runtime-and-domain.md',s);
s=read(base+'shared/astronomical-event-modal/review.html').replace('三项需求 · 交互设计预览','本轮已采用 · 交互设计资源').replace('新增视觉供本轮审阅','本轮视觉已确认采用');write(base+'shared/astronomical-event-modal/review.html',s);
const p=base+'shared/astronomical-event-modal/provenance.json';let j=JSON.parse(read(p));j.currentRevision.status='adopted by user on 2026-09-13';j.currentRevision.adoptionScope='Final incremental daytime Map/Plan/Terrain/Event Modal + shared Tabs; production not implemented';delete j.currentRevision.rejectedHost;j.exports=[];j.removedExploration='Rejected generated hosts/exports removed at adoption; current editable sources and live dependencies retained.';write(p,JSON.stringify(j,null,2)+'\n');
