const fs=require('node:fs'),base='docs/design-resources/wechat-miniapp/map/revisions/three-requirements-2026-09-13/preview';
const file=base+'/terrain.js';let s=fs.readFileSync(file,'utf8');
s=s.replace('geographic view and analysis extent are independent.','north-up geographic overview; no directional analysis UI.');
s=s.replace('周边地形与灯光','地形与光污染');
const start=s.indexOf('<div class="terrain-scales"'),end=s.indexOf('<svg class="terrain-plan-map"',start);
s=s.slice(0,start)+`<div class="terrain-radius"><div class="radius-heading"><label for="terrain-radius">查看半径</label><output id="radius-value" for="terrain-radius">5 <small>km</small></output></div><div class="radius-axis"><input id="terrain-radius" type="range" min="0" max="1000" step="1" value="285" aria-valuetext="5 公里"><div class="radius-ticks" aria-hidden="true">'+[2,5,10,20,50].map(r=>'<span style="left:'+Math.log(r/2)/Math.log(25)*100+'%">'+r+'</span>').join('')+'</div></div></div>`+s.slice(end);
s=s.replace('北向上地形和地表夜光示意图，可用下方滑块选择方向','北向上地形与光污染示意图，包含东南西北、距离圈和比例尺');
s=s.replace(/<line id="terrain-direction-ray"[^>]+\/><circle id="terrain-control-point"[^>]+\/>/,'');
const a=s.indexOf('<div class="terrain-map-layers">'),b=s.indexOf("';\nbefore.before(section)",a);
s=s.slice(0,a)+`<div class="terrain-map-layers" role="group" aria-label="显示图层">'+[['relief','terrain','地形'],['light','bulb','光污染']].map(([key,img,label])=>'<label class="terrain-layer-chip '+key+'"><input id="terrain-'+key+'-visible" type="checkbox" checked><img alt="" src="/docs/design-resources/wechat-miniapp/shared/icons/adopted/b-matte-256/assets/'+img+'--day--default.png"><span>'+label+'</span><i class="layer-check" aria-hidden="true"></i></label>').join('')+'</div><div class="terrain-legends"><span id="terrain-relief-key">地形 <i class="relief-key"></i> 低 — 高</span><span id="terrain-light-key">光污染 <i class="light-key"></i> 弱 — 强</span></div></div><details class="terrain-source"><summary>数据来源 <span>›</span></summary><p>光污染：年度卫星估算，反映光源分布，不等同于现场天空亮度。地形：高程模型。真实数据将标注来源、年份和覆盖范围。当前图形为设计示例。</p></details>`+s.slice(b);
s=s.replace("input=$('.direction-control');let radius=5;", "input=$('#terrain-radius');let radius=5;");
s=s.replace(/const heights=.+\n/,'');
const ds=s.indexOf('function direction()'),de=s.indexOf('function map()',ds);s=s.slice(0,ds)+s.slice(de);
s=s.replace("(radius*.4)+' km';direction();", "Number((radius*.4).toFixed(1))+' km';$('#radius-value').innerHTML=radius+' <small>km</small>';input.setAttribute('aria-valuetext',radius+' 公里');input.style.setProperty('--radius-progress',input.value/10+'%');");
const cs=s.indexOf("section.querySelectorAll('[data-range]')");s=s.slice(0,cs)+`input.oninput=()=>{radius=Math.round(2*Math.pow(25,Number(input.value)/1000)*10)/10;map();};
for(const [key,group] of [['relief','geography'],['light','light-cells']])$('#terrain-'+key+'-visible').onchange=e=>{$('#terrain-'+group).style.display=e.target.checked?'':'none';$('#terrain-'+key+'-key').hidden=!e.target.checked;};
map();return section;
}};
`;
fs.writeFileSync(file,s);
// Retire obsolete chart/direction/radio-like range styling; keep shared layer selector styles.
let css=fs.readFileSync(base+'/additions.css','utf8');css=css.replace(/#terrain \.chart-label[^{}]*\{[^{}]*\}|#terrain \.horizon[^{}]*\{[^{}]*\}|#terrain \.direction-output\{[^{}]*\}|#direction-angle\{[^{}]*\}|#terrain \.light-band\{[^{}]*\}|#terrain \.light-legend\{[^{}]*\}|#terrain \.terrain-scales[^{}]*\{[^{}]*\}|#terrain \.terrain-map-layers[^{}]*\{[^{}]*\}|#terrain \.terrain-light-key[^{}]*\{[^{}]*\}/g,'');
css=css.replace('cursor:crosshair','cursor:default');
css+=`\n/* Radius is the only slider; independent layer selections use compact illustrated chips. */
#terrain .terrain-radius{margin:16px 0 18px}#terrain .radius-heading{display:flex;align-items:baseline;justify-content:space-between;color:#879499;font-size:11px}#terrain #radius-value{font-size:23px;line-height:1.3;font-weight:500;color:#4c645c;font-variant-numeric:tabular-nums}#terrain #radius-value small{font-size:11px;font-weight:400;color:#8d9994;margin-left:3px}#terrain .radius-axis{margin:1px 10px 0}#terrain #terrain-radius{display:block;width:calc(100% + 20px);margin:0 -10px;--radius-progress:28.5%;touch-action:pan-y;cursor:ew-resize}#terrain #terrain-radius::-webkit-slider-runnable-track{height:4px;border-radius:4px;background:linear-gradient(90deg,#8ea699 var(--radius-progress),#e8eeeb var(--radius-progress))}#terrain #terrain-radius::-webkit-slider-thumb{width:22px;height:22px;margin-top:-9px;border:5px solid white;background:#869f91;box-shadow:0 1px 5px #45614b2b,0 0 0 1px #dae3dd;border-radius:50%}#terrain #terrain-radius::-moz-range-track{height:4px;background:#e8eeeb;border-radius:4px}#terrain #terrain-radius::-moz-range-progress{background:#8ea699;height:4px}#terrain #terrain-radius::-moz-range-thumb{height:12px;width:12px;border:5px solid white;background:#869f91;border-radius:50%}#terrain #terrain-radius:focus-visible{outline:2px solid #879e92;outline-offset:4px;border-radius:6px}#terrain .radius-ticks{position:relative;height:18px;margin-top:-1px;color:#98a69f;font-size:10px}#terrain .radius-ticks span{position:absolute;transform:translateX(-50%);padding-top:6px;font-variant-numeric:tabular-nums}#terrain .radius-ticks span:before{content:'';position:absolute;width:1px;height:3px;top:0;left:50%;background:#c9d4cd}
#terrain .terrain-map-layers{display:flex;gap:10px;margin-top:16px}#terrain .terrain-layer-chip{position:relative;flex:1;min-height:48px;display:flex;align-items:center;gap:8px;padding:0 10px;border:1px solid #e8ece9;border-radius:12px;color:#77847d;background:white;cursor:pointer;font-size:12px;transition:background .18s,border-color .18s}#terrain .terrain-layer-chip input{position:absolute;width:100%;height:100%;inset:0;opacity:0;margin:0;cursor:pointer}#terrain .terrain-layer-chip img{width:27px;height:27px;object-fit:contain;opacity:.65;transition:opacity .18s}#terrain .terrain-layer-chip:has(input:checked){background:#f0f5f0;border-color:#b7c9bc;color:#516b5d}#terrain .terrain-layer-chip.light:has(input:checked){background:#faf6eb;border-color:#dfd2ad;color:#8c7745}#terrain .terrain-layer-chip:has(input:checked) img{opacity:1}#terrain .terrain-layer-chip:has(input:focus-visible){outline:2px solid #8b9e95;outline-offset:2px}#terrain .layer-check{margin-left:auto;width:16px;height:16px;border-radius:50%;border:1px solid #ced6d0;display:grid;place-items:center;box-sizing:border-box}#terrain .terrain-layer-chip:has(input:checked) .layer-check{background:#819c89;border-color:#819c89}#terrain .terrain-layer-chip.light:has(input:checked) .layer-check{background:#b6a16b;border-color:#b6a16b}#terrain .terrain-layer-chip:has(input:checked) .layer-check:after{content:'';width:6px;height:3px;border-left:1.5px solid white;border-bottom:1.5px solid white;transform:translateY(-1px) rotate(-45deg)}#terrain .terrain-legends{display:flex;justify-content:space-between;gap:12px;padding-top:11px;color:#98a29b;font-size:9px}#terrain .terrain-legends>span{display:flex;align-items:center;gap:5px}#terrain .terrain-legends [hidden]{display:none}#terrain .terrain-legends i{height:5px;width:28px;border-radius:2px}#terrain .relief-key{background:linear-gradient(90deg,#d2dcc7,#a2b79b)}#terrain .light-key{background:linear-gradient(90deg,#eee6d0,#d8af53)}@media(prefers-reduced-motion:reduce){#terrain .terrain-layer-chip,#terrain .terrain-layer-chip img{transition:none}}\n`;
fs.writeFileSync(base+'/additions.css',css);
