/** Independent frozen-artifact review only: no browser, GPU, HTTP or production execution. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {inflateSync} from 'node:zlib';
import {builtinModules} from 'node:module';
import assert from 'node:assert/strict';
import ts from 'typescript';

const ROOT=fileURLToPath(new URL('../../../../',import.meta.url));
const task='.codex/work-items/cloud-sky-native-2026-09-22';
const source='output/playwright/cloud-sky-continuous-camera-resource-1002-r1';
const out=process.argv[2];assert.match(out??'',/^output\/continuous-camera-independent-1002-r\d+$/u);
assert(!fs.existsSync(path.join(ROOT,out)));fs.mkdirSync(path.join(ROOT,out));
const buffer=(p:string)=>fs.readFileSync(path.resolve(ROOT,p));
const text=(p:string)=>buffer(p).toString('utf8');
const json=(p:string)=>JSON.parse(text(p));
const hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const binding=(p:string)=>{const b=buffer(p);return{path:p,bytes:b.length,sha256:hash(b)};};
const inputs=new Map<string,ReturnType<typeof binding>>();
const admit=(p:string,expected?:{bytes?:number;sha256?:string})=>{const b=binding(p);if(expected?.sha256)assert.equal(b.sha256,expected.sha256,p);if(expected?.bytes!==undefined)assert.equal(b.bytes,expected.bytes,p);const prior=inputs.get(p);if(prior)assert.deepEqual(b,prior);inputs.set(p,b);return b;};
const identity=(b:any)=>({path:b.path,bytes:b.bytes,sha256:b.sha256});
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,out,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
try{
 const r=json(source+'/result.json');admit(source+'/result.json',{bytes:6931634,sha256:'5c9aa0fd01e6ec24a94168b8183f08ef40f4a30e0df3e28e7dab1aca9f250cdc'});
 assert.equal(r.status,'MEASURED_SOFTWARE_CAMERA_JOURNEY');assert.deepEqual(r.contractFailures,[]);assert.deepEqual(r.errors,[]);
 const before=json(source+'/source-binding-before.json'),after=json(source+'/source-binding-after.json');admit(source+'/source-binding-before.json');admit(source+'/source-binding-after.json');admit(source+'/inputs.json');
 assert.equal(path.resolve(before.absWorkingDir),path.resolve(ROOT));assert.deepEqual(r.sourceBindings,before.sourceBindings);assert.deepEqual(r.inputs,before.inputs);
 assert.deepEqual(r.sourceBindings.map(identity),after.sourceBindings);assert.deepEqual(r.inputs.map(identity),after.inputs);
 assert.deepEqual(before.preserved.map((b:any)=>({path:b.path,sha256:b.sha256})),after.preserved.map((b:any)=>({path:b.path,sha256:b.sha256})));assert.equal(before.preserved.length,6);
 for(const b of [...r.sourceBindings,...r.inputs,...before.preserved])admit(b.path,b);
 for(const b of r.sourceBindings){assert.equal(path.relative(ROOT,path.resolve(ROOT,b.path)).replaceAll('\\','/'),b.path);admit(source+'/source-inputs/'+b.path,b);}
 const virtual=['controlled:react','controlled:@tarojs/taro','controlled:@/hooks/use-resource-query','controlled:@/services/api-client','task-page-images.ts'];
 assert.deepEqual(r.virtualInputs.map((b:any)=>b.inputKey).sort(),virtual.slice().sort());assert.deepEqual(r.virtualInputs,before.virtualInputs);
 const meta=json(source+'/metafile.json');admit(source+'/metafile.json');const realMeta=Object.keys(meta.inputs).filter(p=>!virtual.includes(p));
 for(const key of realMeta){const b=r.sourceBindings.find((b:any)=>b.metafileInput===key);assert(b,key);assert.equal(b.resolvedAbsolute,path.resolve(ROOT,key));assert.equal(b.path,path.relative(ROOT,path.resolve(ROOT,key)).replaceAll('\\','/'));}
 admit(source+'/bundle.js',{sha256:r.compiledSha256});
 const executed=text(source+'/executed-script.mts.txt');admit(source+'/executed-script.mts.txt',{bytes:61147,sha256:'8f8a3a8258bd7b1171215edd4a4b91a60204cf620e601a5e303b9bf60cd82d7f'});
 const draftPath=task+'/scripts/experience-continuous-camera-resource-journey-2026-10-02.draft.mts';admit(draftPath,{bytes:61316,sha256:'13bd429941e30a2dbbf7fa4fd3c627db1b6a2395b04b68b4b61b6f57fc4a167a'});
 assert.equal(text(draftPath).replace('// DRAFT ONLY: parent has not authorized its one actual run. No output/browser/GPU can start.\n','').replace("throw new Error('DRAFT_ONLY_CONTINUOUS_JOURNEY_NOT_EXECUTION_AUTHORIZED');\n",''),executed,'only authorized two-line guard removal');
 assert(!executed.includes('const contributionExecutor='));assert(!fs.existsSync(path.join(ROOT,source,'executor-pixel-oracle.js.txt')));
 for(const name of ['runtime','gpu','stable-context','journey','final'])admit(source+'/executor-'+name+'.js.txt');
 const node=json(source+'/node-preparation-binding.json'),nodeMeta=json(source+'/node-preparation-metafile.json');
 for(const name of ['node-preparation-binding.json','node-preparation-metafile.json','node-preparation-entry.ts.txt','node-preparation-unexecuted-bundle.js'])admit(source+'/'+name);
 assert.deepEqual(node.bindings,before.nodePreparationBindings);assert.deepEqual(node.virtualInputs,before.nodeVirtualInputs);assert.equal(node.virtualInputs.length,1);
 assert.equal(node.virtualInputs[0].inputKey,'task-node-preparation.ts');assert.equal(node.virtualInputs[0].sha256,hash(text(source+'/node-preparation-entry.ts.txt')));
 for(const b of node.bindings){assert.equal(b.resolvedAbsolute,path.resolve(ROOT,b.nodeMetafileInput));assert.equal(b.path,path.relative(ROOT,b.resolvedAbsolute).replaceAll('\\','/'));assert(!b.path.startsWith('../'));admit(source+'/'+b.snapshot,b);assert(r.inputs.some((i:any)=>i.path===b.path&&i.sha256===b.sha256));}
 assert.deepEqual(Object.keys(nodeMeta.inputs).filter((p:string)=>p!=='task-node-preparation.ts').sort(),node.bindings.map((b:any)=>b.nodeMetafileInput).sort());
 const nodeExternal=[...new Set(Object.values(nodeMeta.outputs).flatMap((o:any)=>o.imports.filter((i:any)=>i.external).map((i:any)=>i.path)))];assert.deepEqual(node.externalImports,nodeExternal);
 assert.deepEqual(node.declaredUnusedFrameworkOptionalExternals,['class-validator','class-transformer']);for(const name of nodeExternal as string[])assert(builtinModules.includes(name)||builtinModules.includes(name.replace(/^node:/,''))||['class-validator','class-transformer'].includes(name));
 for(const suffix of ['services/sky-report-catalog.ts','features/sky/sky-time-presentation.ts','features/sky/sky-stellar-scene.ts','src/deep-sky-imagery.ts','src/sdss-optical-imagery.ts'])assert(node.bindings.some((b:any)=>b.path.endsWith(suffix)));
 const preparedText=text(source+'/prepared-browser-context.json'),prepared=JSON.parse(preparedText);admit(source+'/prepared-browser-context.json');
 const preparedInput=r.inputs.find((i:any)=>i.path===source+'/prepared-browser-context.json');assert(preparedInput);assert.equal(hash(preparedText.slice(0,-1)),preparedInput.canonicalBodySha256);assert.equal(JSON.stringify(prepared)+'\n',preparedText);assert.equal(prepared.at,prepared.current.context.at);
 const runtime=json(source+'/runtime-metadata-and-offers.json');admit(source+'/runtime-metadata-and-offers.json');assert.equal(runtime.assets.length,116);
 const offers=new Map<string,any>();for(const a of runtime.assets){admit(a.path,a);assert(!offers.has(a.id));offers.set(a.id,a);}
 for(const route of Object.keys(runtime.metadata)){const m=runtime.metadata[route],i=r.inputs.find((b:any)=>b.route===route);assert(i,route);assert.equal(m.bytes,i.bytes);assert.equal(m.sha256,i.sha256);assert.deepEqual(m.body,json(i.path));}
 const inventory=json('output/shared-resource-reading-1002-r1/result.json');admit('output/shared-resource-reading-1002-r1/result.json',{sha256:'f654a0161b272ebb6330fafe1c59c307f519309b1b4336cb49fc4a8202fa97f4'});assert.equal(inventory.images.length,278);for(const a of inventory.images)admit(a.file,a);
 const publicationBinding='output/active-retention-adoption-independent-1002-r2/binding.json';admit(publicationBinding,{sha256:'f1ceadaa7ae6b29f2589caae855aa2fe52406397621f85942fd16d336e114c23'});const published=json(publicationBinding).assets;assert.equal(published.length,281);for(const a of published)admit(a.path,a);

 // Actual page source AST, including all image initializers, three selected effects and release.
 const pagePath='apps/wechat-miniapp/src/features/sky/spot-sky-page.tsx',pageText=text(source+'/source-inputs/'+pagePath),ast=ts.createSourceFile(pagePath,pageText,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const all:ts.Node[]=[];const walk=(n:ts.Node)=>{all.push(n);ts.forEachChild(n,walk);};walk(ast);
 const one=(predicate:(n:ts.Node)=>boolean,label:string)=>{const found=all.filter(predicate);assert.equal(found.length,1,label);return found[0]!;};
 const names=['[deepSkyImageAsset, storeDeepSkyImageAsset]','[canvasDeepSkyImage, storeCanvasDeepSkyImage]','deepSkyImageFileRef','canvasDeepSkyImageRef','deepSkyRecoveryFileRef','setDeepSkyImageAsset','setCanvasDeepSkyImage','retireDeepSkyDecode','[deepSkyImageState, setDeepSkyImageState]','deepSkyImageFailureRef','[deepSkyImageRetry, setDeepSkyImageRetry]','selectedDeepSkyEntry','deepSkyRegistrationReady','desiredDeepSkyImageLevel'];
 const variables=names.map(name=>one(n=>ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>d.name.getText(ast)===name),name).getText(ast));
 const effects=['deepSkyImageFileRef.current?.release();','return startDeepSkyImageRequest({','const subscriptions = owned.map','const image = node.createImage()'].map(needle=>one(n=>ts.isCallExpression(n)&&n.expression.getText(ast)==='useEffect'&&Boolean(n.arguments[0]?.getText(ast).includes(needle)),needle).getText(ast)+';');
 const selected=variables.join('\n')+'\n'+effects.join('\n');assert.equal(text(source+'/actual-selected-page-statements.ts.txt'),selected);admit(source+'/actual-selected-page-statements.ts.txt');
 const entry=text(source+'/extracted-page-entry.ts.txt');admit(source+'/extracted-page-entry.ts.txt');assert(entry.includes(selected));
 const release=one(n=>ts.isPropertyAssignment(n)&&n.name.getText(ast)==='releaseContext'&&n.initializer.getText(ast).includes('canvasGenerationRef.current++'),'release') as ts.PropertyAssignment;
 assert.equal(text(source+'/actual-page-release-context.ts.txt'),release.initializer.getText(ast));admit(source+'/actual-page-release-context.ts.txt');assert(entry.includes('const releaseContext='+release.initializer.getText(ast)));
 for(const name of ['optical','sdssOptical','wideField','moonTexture','marsTexture','mercuryTexture','jupiterBands','saturnBands','uranusBands','neptuneBands','galacticImage','artwork','landscapeImage']){const d=one(n=>ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>d.name.getText(ast)===name),name) as ts.VariableStatement;assert(entry.includes(`const ${name}=globalThis.__controlled.tag(${JSON.stringify(name)},()=>(${d.declarationList.declarations[0]!.initializer!.getText(ast)}));`),name);}
 const taps=[{path:'apps/wechat-miniapp/src/features/sky/use-sky-artwork.ts',file:'diagnostic-hook.ts.txt',strip:(s:string)=>s.replace('  globalThis.__controlled.hook({active,hash,wanted,byteBudget,retainedFallbackIds,owner:loader.current,value});\n','')},{path:'apps/wechat-miniapp/src/services/sky-public-image-cache.ts',file:'diagnostic-cache.ts.txt',strip:(s:string)=>s.replace('function createActualSkyPublicImageCache(','export function createSkyPublicImageCache(').replace(/\nexport function createSkyPublicImageCache\(\.\.\.a:Parameters[\s\S]*$/u,'')},{path:'apps/wechat-miniapp/src/features/sky/sky-artwork-loader.ts',file:'diagnostic-loader.ts.txt',strip:(s:string)=>s.replace(/    __measure\(\)\{[^\n]*\},\n/u,'')}];
 for(const t of taps){const original=text(source+'/source-inputs/'+t.path),diagnostic=text(source+'/'+t.file),info=r.instrumented.find((b:any)=>b.path===t.path);assert(info);admit(source+'/'+t.file,{sha256:info.taskDiagnosticSha256});assert.equal(hash(original),info.originalSha256);assert.equal(t.strip(diagnostic),original,'read-only tap '+t.path);}

 // Self-contained PNG chunk CRC, zlib and inverse five filters, independently of author helpers.
 const crc32=(b:Uint8Array)=>{let c=0xffffffff;for(const x of b){c^=x;for(let k=0;k<8;k++)c=c&1?(c>>>1)^0xedb88320:c>>>1;}return(c^0xffffffff)>>>0;};
 const decode=(b:Buffer)=>{assert.deepEqual(b.subarray(0,8),Buffer.from([137,80,78,71,13,10,26,10]));let at=8,width=0,height=0,done=false;const chunks:Buffer[]=[];while(at<b.length){assert(at+12<=b.length);const n=b.readUInt32BE(at),tag=b.toString('ascii',at+4,at+8),end=at+12+n;assert(end<=b.length);assert.equal(crc32(b.subarray(at+4,end-4)),b.readUInt32BE(end-4));const data=b.subarray(at+8,end-4);if(tag==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);assert.deepEqual([...data.subarray(8)],[8,6,0,0,0]);}if(tag==='IDAT')chunks.push(data);at=end;if(tag==='IEND'){assert.equal(n,0);done=true;break;}}assert(done);assert.equal(at,b.length);assert.equal(width,390);assert.equal(height,844);const stride=width*4,z=inflateSync(Buffer.concat(chunks),{maxOutputLength:(stride+1)*height});assert.equal(z.length,(stride+1)*height);const result=Buffer.alloc(stride*height);for(let y=0;y<height;y++){const filter=z[y*(stride+1)]!;assert(filter<=4);for(let x=0;x<stride;x++){const a=x>=4?result[y*stride+x-4]!:0,up=y?result[(y-1)*stride+x]!:0,ul=x>=4&&y?result[(y-1)*stride+x-4]!:0;let p=0;if(filter===1)p=a;if(filter===2)p=up;if(filter===3)p=(a+up)>>1;if(filter===4){const q=a+up-ul,da=Math.abs(q-a),db=Math.abs(q-up),dc=Math.abs(q-ul);p=da<=db&&da<=dc?a:db<=dc?up:ul;}result[y*stride+x]=(z[y*(stride+1)+x+1]!+p)&255;}}return result;};
 const differences=(a:Buffer,b:Buffer)=>{assert.equal(a.length,b.length);let changedBytes=0,changedPixels=0,maxChannelDifference=0;for(let i=0;i<a.length;i+=4){let changed=false;for(let k=0;k<4;k++){const d=Math.abs(a[i+k]!-b[i+k]!);if(d){changedBytes++;changed=true;maxChannelDifference=Math.max(maxChannelDifference,d);}}if(changed)changedPixels++;}return{changedBytes,changedPixels,maxChannelDifference,fullBytesExact:changedBytes===0};};
 const imageIdentities=new Map<number,any>();const sourceInfo=(s:any)=>{assert(s&&Number.isInteger(s.objectId));const offer=offers.get(s.offeredId);assert(offer,'offered source '+s.offeredId);for(const key of ['sha256','width','height'])assert.equal(s[key],offer[key]);assert.equal(s.status,'decoded');const facts={objectId:s.objectId,offeredId:s.offeredId,sha256:s.sha256,path:s.path,width:s.width,height:s.height,status:s.status};const old=imageIdentities.get(s.objectId);if(old)assert.deepEqual(facts,old);else imageIdentities.set(s.objectId,facts);return facts;};
 const allocations=new Map<number,{bytes:number;source:any}>(),textureHistory=new Map<number,any>(),frames:any[]=[];let maximumLive=0;
 const ledger=(g:any,label:string,events=g.events)=>{let live=[...allocations.values()].reduce((n,a)=>n+a.bytes,0),peak=live,uploadBytes=0,copyBytes=0,deletedBytes=0;const coexistence:any[]=[];for(const e of events){assert(Number.isInteger(e.textureId)&&e.textureId>0,'actual texture identity '+label);const prior=allocations.get(e.textureId),oldBytes=prior?.bytes??0;
  if(e.operation==='source-upload'||e.operation==='gpu-copy'){const facts=sourceInfo(e.source);const known=textureHistory.get(e.textureId);if(known)assert.deepEqual(facts,known);else textureHistory.set(e.textureId,facts);if(e.operation==='source-upload'){assert.equal(e.bytes,e.source.width*e.source.height*4);uploadBytes+=e.bytes;}else{assert([...allocations].some(([id,a])=>id!==e.textureId&&a.source.objectId===facts.objectId),'copy source has actual concurrent allocation');copyBytes+=e.bytes;coexistence.push({copiedTextureId:e.textureId,sourceObjectId:facts.objectId,otherTextures:[...allocations].filter(([id,a])=>id!==e.textureId&&a.source.objectId===facts.objectId).map(([id,a])=>({id,bytes:a.bytes})),copyBytes:e.bytes});}live+=e.bytes-oldBytes;allocations.set(e.textureId,{bytes:e.bytes,source:facts});}
  else{assert.equal(e.operation,'delete');assert.equal(e.bytes,oldBytes);if(e.source){const facts=sourceInfo(e.source);assert.deepEqual(facts,textureHistory.get(e.textureId));}allocations.delete(e.textureId);live-=oldBytes;deletedBytes+=oldBytes;}assert.equal(e.liveBytes,live,label);assert(live>=0);peak=Math.max(peak,live);}
  assert.equal(live,g.liveBytes);const retained=new Map<number,{bytes:number;source:any}>();for(const a of g.retained){assert(!retained.has(a.textureId));retained.set(a.textureId,{bytes:a.bytes,source:sourceInfo(a.source)});}assert.deepEqual([...allocations].sort((a,b)=>a[0]-b[0]),[...retained].sort((a,b)=>a[0]-b[0]));assert.equal(g.aliveTextures,retained.size);assert.equal(g.peakBytes,peak);
  for(const d of g.draws??[])if(d.source){assert(Number.isInteger(d.textureId));assert.deepEqual(sourceInfo(d.source),textureHistory.get(d.textureId));}maximumLive=Math.max(maximumLive,peak);const facts={label,uploadBytes,copyBytes,deletedBytes,peakBytes:peak,liveBytes:live,retainedTextures:retained.size,copyCoexistence:coexistence};frames.push(facts);return facts;};
 const conditionNames=['anchor-north-45','east-horizon-45','south-below-45','south-below-side-45','wide-139','dome','return-start-45','return-80-45','return-160-45','return-240-45','anchor-settled-45','anchor-warm-45'];assert.deepEqual(r.rows.map((x:any)=>x.condition.name),conditionNames);assert.equal(r.rows.length,12);
 const conditions=json(source+'/conditions.json');admit(source+'/conditions.json');const pixels:Buffer[]=[],rows:any[]=[];let clock=0,previousRefs:any=null,previousGpu:any=null;
 for(let n=0;n<r.rows.length;n++){const row=r.rows[n],stem=source+'/'+row.condition.name;admit(stem+'.json');assert.deepEqual(json(stem+'.json'),row);const actual=json(stem+'.actual-observations.json');admit(stem+'.actual-observations.json');const{rgba,capture,...body}=actual;assert.deepEqual(body,Object.fromEntries(Object.entries(row).filter(([key])=>!['rgbaSha256','pngSha256'].includes(key))));
  const raw=buffer(stem+'.rgba'),png=buffer(stem+'.png');admit(stem+'.rgba',{sha256:row.rgbaSha256});admit(stem+'.png',{sha256:row.pngSha256});assert.equal(raw.length,390*844*4);assert.deepEqual(raw,Buffer.from(rgba,'base64'));assert.deepEqual(png,Buffer.from(capture.split(',')[1],'base64'));const decoded=decode(png);for(let y=0;y<844;y++)assert.deepEqual(decoded.subarray(y*1560,(y+1)*1560),raw.subarray((843-y)*1560,(844-y)*1560));pixels.push(raw);
  assert.deepEqual(row.referenceIdentity,previousRefs??row.referenceIdentity);previousRefs=row.referenceIdentity;assert(row.referenceIdentity.stableCanonicalUnchanged);assert.equal(row.referenceIdentity.canvasGeneration,1);assert.equal(row.referenceIdentity.canvasRevision,1);
  clock+=conditions.conditions[n].delta;assert.equal(row.condition.camera.clock,clock);assert.equal(row.condition.camera.intent,'follow');assert.equal(row.condition.camera.liveAlignment,'auto');assert.deepEqual(row.condition.center,{x:195,y:422});const actualFov=n===5?720/Math.PI*Math.atan(844/(390*.92)):n===4?139:45;assert.equal(row.condition.fov,actualFov);
  const basis=row.condition.basis;for(const vector of [basis.right,basis.up,basis.forward])assert(Math.abs(vector.reduce((s:number,x:number)=>s+x*x,0)-1)<1e-12);for(const[a,b]of[[basis.right,basis.up],[basis.right,basis.forward],[basis.up,basis.forward]])assert(Math.abs(a.reduce((s:number,x:number,i:number)=>s+x*b[i],0))<1e-12);
  const ray=row.groundView.visualCenterRay;assert.deepEqual(ray,basis.forward);const altitude=Math.asin(Math.max(-1,Math.min(1,ray[2])))*180/Math.PI,t=Math.max(0,Math.min(1,(altitude+15)/30)),opacity=t*t*(3-2*t);assert.equal(row.groundView.visualCenterAltitudeDeg,altitude);assert.equal(row.groundView.viewOpacity,opacity);
  assert.equal(row.ready.hooks.length,13);assert.equal(row.gates.localOpticalFixtureEnabled,false);assert.equal(row.gates.selectedReference,'M:31');assert.equal(row.gates.desiredDeepSkyImageLevel,null);assert.equal(row.sdssState.requested,false);assert.equal(row.gates.galaxyPageEnabled,row.condition.fov<60);assert.equal(row.surveySources.w3.pageEnabled,true);
  const eligibleRefs=row.ready.hooks.flatMap((h:any)=>h.entries.filter((e:any)=>e.current).map((e:any)=>e.image));const unique=new Map(eligibleRefs.map((i:any)=>[i.objectId,sourceInfo(i)]));assert.equal(eligibleRefs.length,row.ready.decodedOwnerReferences);assert.equal(unique.size,row.ready.decodedUniqueImages);assert.equal([...unique.values()].reduce((s:number,i:any)=>s+i.width*i.height*4,0),row.ready.decodedSourceRgbaModel);
  assert.equal(row.ready.coldFileOwnerEntries,row.ready.hooks.reduce((s:number,h:any)=>s+h.entries.filter((e:any)=>e.state==='cold').length,0));for(const h of row.ready.hooks){assert(!h.loading);for(const a of h.wanted){const matches=runtime.assets.filter((o:any)=>o.sha256===a.sha256&&o.bytes===a.bytes&&o.width===a.width&&o.height===a.height);assert.equal(matches.length,1,'exact offered content '+h.name+'/'+a.id);const offer=matches[0];for(const key of ['sha256','bytes','width','height'])assert.equal(a[key],offer[key]);}for(const i of [...h.ready,...h.retainedReady])sourceInfo(i);}
  let imageTransferBytes=0,metadataTransferBytes=0;for(const transfer of row.transfers){assert(transfer.completed);if(transfer.type==='image'){const offer=runtime.assets.find((a:any)=>a.sha256===transfer.sha256);assert(offer);assert.equal(transfer.bytes,offer.bytes);imageTransferBytes+=transfer.bytes;}else{assert.equal(transfer.type,'metadata');const m=runtime.metadata[transfer.route];assert(m,transfer.route);assert.equal(transfer.sha256,m.sha256);assert.equal(transfer.bytes,m.bytes);metadataTransferBytes+=transfer.bytes;}}
  assert.equal(row.passes.length,2);const metrics=[];for(const p of row.passes){assert.equal(p.glError,0);assert.deepEqual(p.paintedSources,{sdss:null,selected:null});assert.equal(p.sourceCredit.deepSkyImagePresented,false);assert.equal(p.sourceCredit.sdssOpticalStatus,'NONE');assert.equal(p.sourceCredit.sdssOpticalCurrentImagePresented,false);assert.deepEqual(p.sourceCredit.labels,{selected:null,sdss:null});metrics.push(ledger(p,row.condition.name+'/'+p.pass));assert.deepEqual(p.landscapeFacts.viewOpacity,row.groundView.viewOpacity);}previousGpu=row.passes[1];assert.deepEqual(row.gpuAtBoundary.events,previousGpu.events);assert.deepEqual(row.gpuAtBoundary.retained,previousGpu.retained);
  const cacheBytes=row.cacheInventory.reduce((s:number,a:any)=>s+a.bytes,0);assert(cacheBytes>=row.ready.cache[0].bytes);assert(row.ready.counters.nativeCallbackPeak<=2);assert.deepEqual(row.gpuFailures,[]);
  rows.push({name:row.condition.name,phase:row.condition.camera.phase,actualCenterAltitudeDeg:altitude,viewOpacity:opacity,paintedMask:row.passes[1].landscapeFacts.paintedMask,landscapeReadiness:row.passes[1].landscapeFacts.readiness,readyDecodedRgbaModel:row.ready.decodedSourceRgbaModel,readyFileLeases:row.ready.cache[0].leased,coldFileEntries:row.ready.coldFileOwnerEntries,encodedCacheBytes:row.ready.cache[0].bytes,imageTransferBytes,metadataTransferBytes,newImageObjects:row.newDecodes.map((i:any)=>({objectId:i.objectId,offeredId:i.offeredId,current:i.current})),warmUploadBytes:metrics[1].uploadBytes,metrics});
 }
 const final=json(source+'/actual-final-owner.json');admit(source+'/actual-final-owner.json');assert.deepEqual(final,r.final);assert(final.stableCanonicalUnchanged&&final.sameRuntimeOwners);assert(previousGpu);assert.deepEqual(final.gpu.events.slice(0,previousGpu.events.length),previousGpu.events);const finalEvents=final.gpu.events.slice(previousGpu.events.length);const finalGpu={...final.gpu,events:finalEvents,draws:[]};ledger(finalGpu,'actual-final-release',finalEvents);assert.equal(final.gpu.liveBytes,0);assert.equal(final.gpu.aliveTextures,0);assert(final.cache.every((c:any)=>c.leased===0&&c.running===0&&c.pending===0&&c.reserved===0));assert.equal(final.counters.nativeRunning,0);assert.equal(final.counters.decodedPending,0);assert.equal(final.nativeCurrent.filter((i:any)=>i.current).length,0);
 const returns=[10,11].map(index=>({name:r.rows[index].condition.name,...differences(pixels[0]!,pixels[index]!)}));assert.deepEqual(returns,r.returnComparisons);const returned=json(source+'/actual-return-observations.json');admit(source+'/actual-return-observations.json');assert.deepEqual(returned.comparisons,returns);
 const normalFrames=frames.slice(0,24),result={status:'INDEPENDENT_FROZEN_CAMERA_JOURNEY_READBACK_PASS',authorResult:binding(source+'/result.json'),actualExecutedScript:binding(source+'/executed-script.mts.txt'),normalPngAndBottomUpRgbaExact:12,normalTextureIdentityLedgers:24,finalReleaseLedger:true,sourceBindings:r.sourceBindings.length,realBrowserGraphInputs:realMeta.length,explicitBrowserVirtualInputs:virtual.length,nodeGraphInputs:node.bindings.length,nodeVirtualInputs:1,optionalUnusedNodeFrameworkExternals:node.declaredUnusedFrameworkOptionalExternals,actualByteOffers:offers.size,currentImageInventoryPreserved:278,oldPublishedInventoryPreserved:281,preservedFiles:6,allStableReferenceFacts:r.rows[0].referenceIdentity,returnComparisons:returns,normal:{sourceUploadBytes:normalFrames.reduce((s,f)=>s+f.uploadBytes,0),copyBytes:normalFrames.reduce((s,f)=>s+f.copyBytes,0),maximumLogicalPeak:maximumLive,maximumFrameEnd:Math.max(...normalFrames.map(f=>f.liveBytes)),warmSourceUploadBytes:normalFrames.filter((_,i)=>i%2===1).reduce((s,f)=>s+f.uploadBytes,0)},rows,final:{logicalTextureBytes:0,textureCount:0,fileLeases:0,validNativeImageReferences:0,cache:final.cache,counters:final.counters},limits:[
  'Frozen-source/raw readback only. No browser, new GPU draw, source request, test replay or production edit. Metadata graph is not a runtime loaded-module trace; only the two uncalled Nest optional framework branches are explicitly excluded.',
  'Twelve finite readiness-settled states, each two normal submissions. Logical camera increments are independent of fixed astronomy instant and real readiness wall time; not gesture, continuous animation, FPS or first-usable timing.',
  'All FOV>=45, selected M31/SDSS/LOCAL inactive. Extracted selected/SDSS source-credit predicates are not whole-page UI or W3/galaxy source acceptance. Draw-bound texture identities do not identify photographic contributions on unrelated primitives.',
  'Actual full scene pixels and same-Canvas resource return do not certify scientific source quality, target WEAPP interactions/decode/FS, driver/native/physical-GC memory, all-view maximums, 200DAU capacity or final experience. Diagnostic strong image references preclude GC inference. Encoded zero-lease cache is intentionally persistent.'
 ]};
 const bindings=[...inputs.values()],afterReview=bindings.map(b=>binding(b.path));assert.deepEqual(afterReview,bindings);fs.writeFileSync(path.join(ROOT,out,'result.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});fs.writeFileSync(path.join(ROOT,out,'binding.json'),JSON.stringify({inputsBefore:bindings,inputsAfter:afterReview,unchanged:true},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({result:binding(out+'/result.json'),binding:binding(out+'/binding.json'),normal:result.normal,returnComparisons:returns}));
}catch(cause){fs.writeFileSync(path.join(ROOT,out,'failed.json'),JSON.stringify({status:'FAILED_INDEPENDENT_READER',message:String(cause),bindings:[...inputs.values()]},null,2)+'\n',{flag:'wx'});throw cause;}
