/** One actual legacy scene fixture, solely to diagnose the review harness failure. */
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';
import * as contracts from '../../../../packages/miniapp-contracts/src/index.ts';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),OUT='output/sdss-science-frame-realm-diagnosis-1002-r1',prefix='apps/wechat-miniapp/src/features/sky/',scene=prefix+'sky-scene-render.ts',fixture='output/sdss-science-frame-handoff-1002-r1/executed-scene-test-before-fixture-repair.ts.txt';
assert(!fs.existsSync(path.join(ROOT,OUT)));fs.mkdirSync(path.join(ROOT,OUT));
const raw=(p:string)=>fs.readFileSync(path.join(ROOT,p)),bind=(p:string)=>{const bytes=raw(p);return{path:p,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};},inputs=[bind(scene),bind(fixture)];
assert.equal(inputs[0]!.sha256,'9d4343b3f3fae121ee4fc2b244112ad8cf7d886c949ffbf869746535f9a1e4f7');
const compile=(p:string)=>ts.transpileModule(raw(p).toString('utf8'),{fileName:p,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const sceneJs=compile(scene),fixtureJs=compile(fixture),names=new Set<string>();
for(const text of [sceneJs,fixtureJs]){const ast=ts.createSourceFile('compiled.js',text,ts.ScriptTarget.Latest,true);const walk=(n:ts.Node)=>{if(ts.isCallExpression(n)&&n.expression.getText(ast)==='require'&&ts.isStringLiteral(n.arguments[0]!))names.add(n.arguments[0].text);ts.forEachChild(n,walk);};walk(ast);}
const dependencies:Record<string,any>={'@starward/miniapp-contracts':contracts};
for(const n of names){if(n in dependencies||['node:assert/strict','node:test','./sky-scene-render'].includes(n))continue;assert(n.startsWith('./'),n);const p=path.posix.join(prefix,n)+'.ts';inputs.push(bind(p));dependencies[n]=await import(pathToFileURL(path.join(ROOT,p)).href);}
const name="leaving the image's whole field clears both credits without reporting a load failure";
function observe(sharedRealm:boolean){const events:any[]=[],sceneExports={},fixtureExports={};const register=(label:string,run:()=>void)=>{if(label!==name)return;try{run();events.push({name:label,status:'passed'});}catch(e){events.push({name:label,status:'failed',error:String(e)});}};const context=vm.createContext({sceneExports,fixtureExports,sceneRequire(n:string){assert(n in dependencies,n);return dependencies[n];},fixtureRequire(n:string){if(n==='node:assert/strict')return assert;if(n==='node:test')return register;if(n==='./sky-scene-render')return sceneExports;assert(n in dependencies,n);return dependencies[n];}});vm.runInContext('(function(exports,require){'+sceneJs+'})(sceneExports,sceneRequire);',context);const other=sharedRealm?context:vm.createContext({fixtureExports,fixtureRequire:(context as any).fixtureRequire});vm.runInContext('(function(exports,require){'+fixtureJs+'})(fixtureExports,fixtureRequire);',other);assert.equal(events.length,1);return events[0];}
const separate=observe(false),shared=observe(true);assert.equal(separate.status,'failed');assert.match(separate.error,/same structure but are not reference-equal/u);assert.equal(shared.status,'passed');assert.deepEqual(inputs.map(x=>bind(x.path)),inputs);
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,OUT,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
fs.writeFileSync(path.join(ROOT,OUT,'result.json'),JSON.stringify({status:'REVIEW_HARNESS_REALM_DIAGNOSIS_CLOSED',separateSceneFixtureRealms:separate,sharedSceneFixtureRealm:shared,inputsBefore:inputs,inputsAfter:inputs.map(x=>bind(x.path)),scope:'Exactly one existing legacy fixture, unchanged assertions, actual scene and direct dependencies. Cross-realm plain object prototypes explain the fourth r1 harness failure. No product source change, no GPU/HTTP/native; this is not a full dependency graph or product acceptance.'},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify(bind(OUT+'/result.json')));
