/** Independent AST/effect lifecycle probe; no GPU, transport, image decoding or production edits. */
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import ts from 'typescript';
import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {startDeepSkyImageRequest} from '../../../../apps/wechat-miniapp/src/features/sky/deep-sky-image-request';
import {registerSkyNativeImageLifetime,skyNativeImageIsCurrent} from '../../../../apps/wechat-miniapp/src/features/sky/sky-artwork-loader';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),task='.codex/work-items/cloud-sky-native-2026-09-22';
const pagePath='apps/wechat-miniapp/src/features/sky/spot-sky-page.tsx',oldPath='output/playwright/cloud-sky-selected-full-hook-1002-r3/source-inputs/'+pagePath;
const out=process.argv[2];assert.match(out??'',/^output\/selected-entry-dependency-independent-1002-r\d+$/u);assert(!fs.existsSync(path.join(ROOT,out)));fs.mkdirSync(path.join(ROOT,out));
const read=(p:string)=>fs.readFileSync(path.join(ROOT,p)),sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const bind=(p:string)=>{const b=read(p);return{path:p,bytes:b.length,sha256:sha(b)};};const json=(p:string)=>JSON.parse(read(p).toString());
const sources=[pagePath,oldPath,'apps/wechat-miniapp/src/features/sky/deep-sky-image-request.ts','apps/wechat-miniapp/src/features/sky/sky-artwork-loader.ts','packages/miniapp-contracts/src/deep-sky-image-publication.ts','packages/miniapp-contracts/src/sky-image-display-support.ts',
 'apps/wechat-miniapp/src/features/sky/deep-sky-image-lifecycle.test.ts','output/playwright/cloud-sky-selected-full-hook-1002-r3/discovery-M-31.json','output/playwright/cloud-sky-selected-full-hook-1002-r3/discovery-M-51.json',
 'workers/miniapp-api/assets/deep-sky/manifest.json','workers/miniapp-api/assets/deep-sky/publications/87ab6341b43d660e3c93a2430994c0f38b409dafa86216e7e3313e98cdbbc073.json'];
const bindings=sources.map(bind);for(let i=0;i<sources.length;i++)fs.copyFileSync(path.join(ROOT,sources[i]!),path.join(ROOT,out,i+'-'+path.basename(sources[i]!)+'.txt'),fs.constants.COPYFILE_EXCL);
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,out,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
const current=read(pagePath).toString(),old=read(oldPath).toString();assert.equal(sha(current),'0a6c31e6ffe9a91c6aa5cc51959e27d70e9e754108d966ad27bfde0b50c1f24a');
const comment='  // Catalog refreshes preserve image ownership when objectRef and level stay the same.'+(current.includes('\r\n')?'\r\n':'\n');assert.equal(current.split(comment).length,2);
const reverse=current.replace(comment,'').replace('[pageVisible, deepSkyImageAsset, deepSkyImageRetry, desiredDeepSkyImageLevel, selectedDeepSkyEntry?.objectRef]','[pageVisible, deepSkyImageAsset, deepSkyImageRetry, desiredDeepSkyImageLevel, selectedDeepSkyEntry]')
 .replace('[deepSkyImageAsset, canvasDeepSkyImage, selectedDeepSkyEntry?.objectRef, desiredDeepSkyImageLevel, setCanvasDeepSkyImage]','[deepSkyImageAsset, canvasDeepSkyImage, selectedDeepSkyEntry, desiredDeepSkyImageLevel, setCanvasDeepSkyImage]')
 .replace('[pageVisible, canvasNodeRevision, deepSkyImageAsset, selectedDeepSkyEntry?.objectRef, desiredDeepSkyImageLevel, retireDeepSkyDecode]','[pageVisible, canvasNodeRevision, deepSkyImageAsset, selectedDeepSkyEntry, desiredDeepSkyImageLevel, retireDeepSkyDecode]');assert.equal(reverse,old);
const parse=(s:string)=>ts.createSourceFile('page.tsx',s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const capture=(s:string)=>{const a=parse(s),effects=new Map<string,ts.CallExpression>(),vars=new Map<string,ts.Expression>();const visit=(n:ts.Node)=>{
 if(ts.isCallExpression(n)&&n.expression.getText(a)==='useEffect')for(const [name,needle] of [['request','return startDeepSkyImageRequest({'],['retire','const subscriptions = owned.map'],['decode','const image = node.createImage()']])if(n.arguments[0]?.getText(a).includes(needle)){assert(!effects.has(name));effects.set(name,n);}
 if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&['setDeepSkyImageAsset','setCanvasDeepSkyImage','retireDeepSkyDecode'].includes(n.name.text)){assert(n.initializer&&ts.isCallExpression(n.initializer));vars.set(n.name.text,n.initializer.arguments[0]!);}ts.forEachChild(n,visit);};visit(a);assert.equal(effects.size,3);assert.equal(vars.size,3);return{a,effects,vars};};
const oldAST=capture(old),newAST=capture(current);for(const n of ['request','retire','decode'])assert.equal(oldAST.effects.get(n)!.arguments[0]!.getText(oldAST.a),newAST.effects.get(n)!.arguments[0]!.getText(newAST.a));
const evaluate=(code:string,b:any)=>vm.runInNewContext(ts.transpileModule('('+code+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,{...b,registerSkyNativeImageLifetime});
const driver=(source:string,name:string)=>{const c=capture(source),effect=c.effects.get(name)!;const code='{run:'+effect.arguments[0]!.getText(c.a)+',deps:'+effect.arguments[1]!.getText(c.a)+'}';let deps:any[]|undefined,cleanup:(()=>void)|undefined,executions=0;
 return{commit(b:any){const next=evaluate(code,b);if(!deps||deps.length!==next.deps.length||deps.some((v,i)=>!Object.is(v,next.deps[i]))){cleanup?.();cleanup=next.run()||undefined;deps=Array.from(next.deps);executions++;}},dispose(){cleanup?.();cleanup=undefined;},get executions(){return executions;}};};
const discoveries:any={};for(const ref of ['M:31','M:51'])discoveries[ref]=json('output/playwright/cloud-sky-selected-full-hook-1002-r3/discovery-'+ref.replace(':','-')+'.json');
const archive=json(sources.at(-1)!);const archiveHash=sha(JSON.stringify(archive));
const fixtures:any[]=[];
const owned=(ref='M:31',level='DETAIL',version:any=discoveries[ref],samePath?:string)=>{const raw=version.levels?version:archive.entries.find((e:any)=>e.objectRef===ref),d=raw.levels[level];let current=true,releases=0,unsubscribes=0;const listeners=new Set<()=>void>();
 const publicationHash=version===archive?archiveHash:version.publicationHash,publicationId=version===archive?archive.publicationId:version.publicationId;
 const value:any={reference:ref,level,fieldDegrees:d.fieldDegrees,pixelSize:d.pixels,publicationHash,sourceId:'imagery:'+publicationId+':'+publicationHash,tempFilePath:samePath??'/controlled/'+d.sha256+'.jpg',isCurrent:()=>current,
  release(){if(!current)return;current=false;releases++;listeners.clear();},onRetire(fn:()=>void){if(!current){fn();return()=>{};}listeners.add(fn);return()=>{if(listeners.delete(fn))unsubscribes++;};}};
 const control={value,retire(){if(!current)return;current=false;for(const fn of [...listeners])fn();listeners.clear();},get releases(){return releases;},get unsubscribes(){return unsubscribes;},get listeners(){return listeners.size;}};fixtures.push(control);return control;};
const decoder=(source:string)=>{const images:any[]=[],leases:any[]=[],calls:any[]=[];const coarse=owned('M:31','OVERVIEW'),fine=owned();leases.push(coarse,fine);let b:any;
 const makeNode=()=>({createImage(){const image:any={width:512,height:512,onload:null,onerror:null,src:''};images.push(image);return image;}});
 b={pageVisible:true,canvasNodeRevision:1,canvasGenerationRef:{current:1},canvasNodeRef:{current:makeNode()},selectedDeepSkyEntry:{objectRef:'M:31',displayName:'M31'},desiredDeepSkyImageLevel:'DETAIL',deepSkyImageAsset:fine.value,
  deepSkyImageFileRef:{current:fine.value},canvasDeepSkyImageRef:{current:null},deepSkyRecoveryFileRef:{current:coarse.value},canvasDeepSkyImage:null,deepSkyImageFailureRef:{current:null},
  storeDeepSkyImageAsset(value:any){b.deepSkyImageAsset=value;},storeCanvasDeepSkyImage(value:any){b.canvasDeepSkyImage=value;},setDeepSkyImageState(value:string){calls.push(['state',value]);b.state=value;}};
 const c=capture(source);for(const name of ['setDeepSkyImageAsset','setCanvasDeepSkyImage','retireDeepSkyDecode'])b[name]=evaluate(c.vars.get(name)!.getText(c.a),b);
 // Establish an actually owned coarse bitmap in this current Canvas; no extra decode is hidden from counters.
 const coarseImage:any={width:256,height:256,onload:null,onerror:null};b.setCanvasDeepSkyImage({...coarse.value,image:coarseImage,canvasGeneration:1});
 const decode=driver(source,'decode'),retire=driver(source,'retire');const commit=(changes:any={})=>{Object.assign(b,changes);retire.commit(b);decode.commit(b);};
 return{b,images,leases,calls,coarse,fine,makeNode,commit,dispose(){retire.dispose();decode.dispose();b.setDeepSkyImageAsset(null);b.setCanvasDeepSkyImage(null);},get painted(){return b.canvasDeepSkyImageRef.current;}};};
const requestProbe=async(source:string)=>{const waiting:any[]=[],events:any[]=[],demands:any[]=[],acquired:any[]=[];let b:any;
 b={pageVisible:true,selectedDeepSkyEntry:{objectRef:'M:31',displayName:'M31'},desiredDeepSkyImageLevel:'DETAIL',deepSkyImageAsset:null,deepSkyImageRetry:0,deepSkyImageFailureRef:{current:null},
  setDeepSkyImageAsset(a:any){b.deepSkyImageAsset=a;},setDeepSkyImageState(v:any){events.push(['state',v]);},recordAcceptanceDiagnostic(...v:any[]){events.push(['diagnostic',...v]);},
  beginDeepSkyImageDemand(){let live=true;const listeners=new Set<()=>void>();const d={isCurrent:()=>live,onRetire(f:()=>void){listeners.add(f);return()=>{listeners.delete(f);};},release(){live=false;listeners.clear();},retire(){if(!live)return;live=false;for(const f of [...listeners])f();}};demands.push(d);return d;},
  getDeepSkyImageDiscovery(ref:string,signal:AbortSignal){return new Promise(resolve=>waiting.push({reference:ref,signal,resolve}));},
  acquireDeepSkyImage(d:any,pub:string){const ref=d.file.split('/')[0].replace('-',':'),level=d.file.includes('-overview.')?'OVERVIEW':d.file.includes('-medium.')?'MEDIUM':'DETAIL';const x=owned(ref,level,discoveries[ref]);assert.equal(x.value.publicationHash,pub);acquired.push(x);return{promise:Promise.resolve({filePath:x.value.tempFilePath,isCurrent:x.value.isCurrent,onRetire:x.value.onRetire,release:x.value.release}),cancel(){events.push(['acquisition-cancel']);}};},
  startDeepSkyImageRequest(input:any){events.push(['start',input.reference,input.level]);return startDeepSkyImageRequest(input);}};
 const h=driver(source,'request');h.commit(b);const first=waiting[0];h.commit({...b,selectedDeepSkyEntry:{...b.selectedDeepSkyEntry,displayName:'new same ref'}});
 const afterRefresh={starts:events.filter(e=>e[0]==='start').length,cancelled:first.signal.aborted};for(const pending of waiting.splice(0))pending.resolve(discoveries[pending.reference]);for(let i=0;i<8;i++)await Promise.resolve();const ready=b.deepSkyImageAsset;
 h.dispose();ready?.release();for(const x of acquired)x.value.release();return{afterRefresh,acquisitions:acquired.length,readyPublication:ready?.publicationHash??null,readyField:ready?.fieldDegrees??null};};
const freshProbe=(source:string)=>{const h=decoder(source);h.commit();const fn=h.images.at(-1).onload;h.commit({selectedDeepSkyEntry:{objectRef:'M:31',displayName:'refreshed'}});const counts={images:h.images.length,callbackPreserved:h.images.at(-1).onload===fn};h.dispose();return counts;};
const failureProbe=(source:string)=>{const h=decoder(source);h.commit();h.images.at(-1).onerror();h.commit({selectedDeepSkyEntry:{objectRef:'M:31',displayName:'refreshed'}});const result={images:h.images.length,state:h.b.state};h.dispose();return result;};
try{
 const before={request:await requestProbe(old),pendingDecode:freshProbe(old),failedDecode:failureProbe(old)},after={request:await requestProbe(current),pendingDecode:freshProbe(current),failedDecode:failureProbe(current)};
 assert.deepEqual(after.request.afterRefresh,{starts:1,cancelled:false});assert.equal(after.request.acquisitions,1);assert.equal(after.request.readyPublication,discoveries['M:31'].publicationHash);assert.equal(after.request.readyField,discoveries['M:31'].levels.DETAIL.fieldDegrees);
 assert.deepEqual(after.pendingDecode,{images:1,callbackPreserved:true});assert.deepEqual(after.failedDecode,{images:1,state:'ERROR'});assert.equal(before.request.afterRefresh.starts,2);assert.equal(before.request.afterRefresh.cancelled,true);assert.equal(before.pendingDecode.images,2);assert.deepEqual(before.failedDecode,{images:2,state:'LOADING'});
 const cases:any[]=[];
 const h=decoder(current);h.commit();const pending=h.images.at(-1);h.commit({selectedDeepSkyEntry:{objectRef:'M:31',displayName:'changed metadata label'}});assert.equal(h.images.length,1);pending.onload();const bitmap=h.painted.image;h.commit();const subscribed=h.fine.unsubscribes;h.commit({selectedDeepSkyEntry:{objectRef:'M:31',displayName:'again'}});assert.equal(h.images.length,1);assert.equal(h.painted.image,bitmap);assert.equal(h.fine.unsubscribes,subscribed);assert(skyNativeImageIsCurrent(bitmap));
 cases.push({name:'same entry reserialization preserves pending callback, ready bitmap and retirement subscriptions',images:1,bitmapCurrent:true});
 const next=owned('M:31','DETAIL',archive,h.fine.value.tempFilePath);h.leases.push(next);h.b.setDeepSkyImageAsset(next.value);h.commit();assert.equal(h.images.length,2);assert.equal(h.painted.image,bitmap);h.images.at(-1).onload();assert.equal(h.painted.publicationHash,archiveHash);assert.equal(h.painted.sourceId,next.value.sourceId);assert.equal(h.painted.fieldDegrees,next.value.fieldDegrees);assert.notEqual(next.value.release,h.fine.value.release);h.commit();
 cases.push({name:'same filename new metadata lease still decodes and publishes its actual archived publication identity',oldPublication:discoveries['M:31'].publicationHash,newPublication:archiveHash,images:2});
 const latest=h.painted.image,lastOnload=latest.onload;h.b.canvasGenerationRef.current++;h.b.canvasNodeRef.current=h.makeNode();h.commit({canvasNodeRevision:2});assert.equal(h.images.length,3);assert(!skyNativeImageIsCurrent(latest));lastOnload?.();assert.equal(h.painted.image,latest);h.images.at(-1).onload();assert.notEqual(h.painted.image,latest);assert.equal(h.painted.canvasGeneration,2);h.commit();
 cases.push({name:'new Canvas generation always redecodes same valid lease and rejects old registered bitmap',images:3,newGeneration:2,oldBitmapCurrent:false});
 const beforeHide=h.painted.image;h.commit({pageVisible:false});assert.equal(h.painted,null);assert(h.b.deepSkyRecoveryFileRef.current.isCurrent());assert(!('image' in h.b.deepSkyRecoveryFileRef.current));h.b.canvasNodeRef.current=null;h.b.canvasGenerationRef.current++;h.commit({pageVisible:true,canvasNodeRevision:3});assert.equal(h.images.length,3);h.b.canvasNodeRef.current=h.makeNode();h.b.canvasGenerationRef.current=4;h.commit({canvasNodeRevision:4});assert.equal(h.images.length,4);h.images.at(-1).onload();assert.equal(h.painted.publicationHash,archiveHash);assert.notEqual(h.painted.image,beforeHide);h.commit();
 cases.push({name:'hide strips bitmap but keeps file through node gap, showing fresh Canvas recovers metadata',images:4,recoveryPublication:archiveHash});
 // A clear fence is represented by the same onRetire/isCurrent contract, not by guessed brightness or filename.
 const clearLate=h.images.at(-1).onload;next.retire();assert.equal(h.painted,null);clearLate?.();assert.equal(h.painted,null);h.commit({selectedDeepSkyEntry:{objectRef:'M:31',displayName:'refresh after clear'}});assert.equal(h.images.length,4);assert.equal(h.b.state,'ERROR');
 cases.push({name:'retired public lease clears pixels, rejects saved late callback and report refresh does not restart decode',images:4,state:'ERROR'});h.dispose();
 const f=decoder(current);f.commit();const oldLate=f.images.at(-1).onload;f.images.at(-1).width=511;f.images.at(-1).onload();assert.equal(f.b.state,'ERROR');assert.equal(f.painted.reference,'M:31');assert.equal(f.painted.level,'OVERVIEW');f.commit({selectedDeepSkyEntry:{objectRef:'M:31',displayName:'refresh after dimension failure'}});assert.equal(f.images.length,1);assert.equal(f.b.state,'ERROR');
 const retry=owned();f.leases.push(retry);f.b.setDeepSkyImageAsset(retry.value);f.commit();oldLate?.();assert.equal(f.painted.level,'OVERVIEW');f.images.at(-1).onload();assert.equal(f.b.state,'READY');assert.equal(f.painted.release,retry.value.release);f.commit();
 cases.push({name:'dimension failure preserves actual coarse owner, same-ref report does not retry, explicit lease retry replaces it',images:2,readyAfterExplicitRetry:true});f.dispose();
 const level=decoder(current);level.commit();const previous=level.images.at(-1).onload;level.commit({desiredDeepSkyImageLevel:'MEDIUM'});previous();assert.equal(level.painted.level,'OVERVIEW');assert.equal(level.images.length,1);level.dispose();cases.push({name:'changed level cancels old decode even while its matching file is still supplied',lateFinePublished:false});
 const object=decoder(current);object.commit();const foreign=object.images.at(-1).onload;object.commit({selectedDeepSkyEntry:{objectRef:'M:51',displayName:'M51'}});foreign();assert.equal(object.painted,null);assert.equal(object.images.length,1);object.dispose();cases.push({name:'changed object clears independent old-object recovery and fences old callback',oldObjectPainted:false});
 const mutate=(dep:string)=>{const c=capture(current),e=c.effects.get('decode')!,d=e.arguments[1]!.getText(c.a);assert(d.includes(dep));const target=d.split(dep+', ').join('');assert.notEqual(target,d);return current.slice(0,e.arguments[1]!.getStart(c.a))+target+current.slice(e.arguments[1]!.end);};
 const mutants:any[]=[];for(const dep of ['deepSkyImageAsset','canvasNodeRevision']){const source=mutate(dep),m=decoder(source);m.commit();m.images.at(-1).onload();m.commit();const initial=m.images.length;
  if(dep==='deepSkyImageAsset'){const x=owned('M:31','DETAIL',archive,m.fine.value.tempFilePath);m.leases.push(x);m.b.setDeepSkyImageAsset(x.value);m.commit();}
  else{m.b.canvasGenerationRef.current++;m.b.canvasNodeRef.current=m.makeNode();m.commit({canvasNodeRevision:2});}
  assert.equal(m.images.length,initial,'mutation loses necessary decode trigger');mutants.push({removedDependency:dep,sha256:sha(source),detected:true,unchangedImages:initial,expectedNewImages:initial+1});fs.writeFileSync(path.join(ROOT,out,'mutant-'+dep+'.tsx.txt'),source,{flag:'wx'});m.dispose();}
 const six=json(task+'/tmp/resume-preserved-hashes-2026-10-01.json');for(const b of six)assert.equal(bind(b.path).sha256,b.sha256);
 assert.deepEqual(sources.map(bind),bindings);const result={status:'INDEPENDENT_SELECTED_ENTRY_DEPENDENCY_FIX_PASS',page:bind(pagePath),oldPage:bind(oldPath),wholePageReverseByteEqual:true,allThreeEffectBodiesUnchanged:true,before,after,cases,mutants,preservedSix:true,
  limits:['Actual source AST closures/dependency arrays and file/bitmap callbacks execute in a controlled VM effect scheduler. Real startDeepSkyImageRequest performs actual contract validation/snapshot and asynchronous acquisition, but transport/acquisition/clear lease signals and native Image sizes are controlled. No new byte transfer, GPU, WEAPP runtime, service or image quality acceptance.',
  'Old r3 softwareGPU remains bound to old page a713 generation, never upgraded to the new page. This review proves trigger/lifecycle semantics; root49 affected checks/TSC and historical real client/cache race evidence are separate evidence owners. Archive identity is real previously admitted raw publication, same encoded filename is deliberately reused to expose metadata/lease variation.',
  'Task-only mutants remove only one real decode dependency. They demonstrate the effect has a necessary metadata/generation trigger; they are not deployed code or externally obtained sources. Weak-current checks do not measure driver memory or GC.']};
 fs.writeFileSync(path.join(ROOT,out,'result.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});fs.writeFileSync(path.join(ROOT,out,'binding.json'),JSON.stringify({before:bindings,after:sources.map(bind),six:six.map((b:any)=>bind(b.path)),unchanged:true},null,2)+'\n',{flag:'wx'});
 console.log(JSON.stringify({result:bind(out+'/result.json'),binding:bind(out+'/binding.json'),cases:cases.length,mutants:mutants.length,before,after}));
}catch(cause){fs.writeFileSync(path.join(ROOT,out,'failed.json'),JSON.stringify({status:'FAILED_INDEPENDENT_PROBE',message:String(cause),bindings},null,2)+'\n',{flag:'wx'});throw cause;}
