/** Independent frame/page/complete-scene trace. No GPU, HTTP or native image. */
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {createRequire,isBuiltin} from 'node:module';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';
import * as contracts from '../../../../packages/miniapp-contracts/src/index.ts';
import {skySdssOpticalFrame} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-frame.ts';
import {createSkyViewBasis} from '../../../../apps/wechat-miniapp/src/features/sky/sky-view-projection.ts';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),OUT=process.argv[2];assert.match(OUT??'',/^output\/sdss-science-frame-independent-1002-r\d+$/u);assert(!fs.existsSync(path.join(ROOT,OUT!)));fs.mkdirSync(path.join(ROOT,OUT!));
const raw=(p:string)=>fs.readFileSync(path.join(ROOT,p)),hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),binding=(p:string)=>{const b=raw(p);return{path:p,bytes:b.length,sha256:hash(b)};},inputs=new Map<string,ReturnType<typeof binding>>();
const admit=(p:string,e?:{bytes?:number;sha256?:string})=>{const b=binding(p);if(e?.bytes!==undefined)assert.equal(b.bytes,e.bytes,p);if(e?.sha256)assert.equal(b.sha256,e.sha256,p);inputs.set(p,b);return b;};
const save=(p:string,v:unknown)=>fs.writeFileSync(path.join(ROOT,OUT!,p),JSON.stringify(v,null,2)+'\n',{flag:'wx'});fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,OUT!,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
try{
 const prefix='apps/wechat-miniapp/src/features/sky/',scene=prefix+'sky-scene-render.ts',page=prefix+'spot-sky-page.tsx',helper=prefix+'sky-sdss-optical-frame.ts',test=prefix+'sky-sdss-optical-scene.test.ts',old='output/sdss-science-frame-handoff-1002-r1/executed-scene-test-before-fixture-repair.ts.txt';
 for(const p of [scene,page,helper,test,old,'output/sdss-science-frame-handoff-1002-r1/executed-scene-before-fixture-repair.ts.txt','output/sdss-science-frame-handoff-1002-r1/scene-before-fixture-repair.log'])admit(p);
 assert.equal(binding(scene).sha256,'9d4343b3f3fae121ee4fc2b244112ad8cf7d886c949ffbf869746535f9a1e4f7');assert.equal(binding(page).sha256,'960b9e0ae7c0a2ac6b69fdada5feb104d06acd63cc4b6b7d168c130492fa42ad');assert.equal(binding(helper).sha256,'1d9b99447b47c21311797bf22bf9d712862bfd5c9ac5fd41c0e323e08e7f5422');
 assert.deepEqual(raw(scene),raw('output/sdss-science-frame-handoff-1002-r1/executed-scene-before-fixture-repair.ts.txt'));
 // Bind the runtime source closure of these bounded owners, including barrel
 // exports and resolved non-builtin libraries. Page is an AST input, not a
 // whole page execution; do not claim its React/Taro graph was exercised.
 const graphSeen=new Set<string>(),graphEdges:any[]=[],builtinNames=new Set<string>();
 const bindGraph=(absolute:string)=>{absolute=fs.realpathSync(absolute);const relative=path.relative(ROOT,absolute).replaceAll('\\','/');assert(!relative.startsWith('../'),'source outside ROOT '+absolute);if(graphSeen.has(relative))return;graphSeen.add(relative);admit(relative);if(absolute.endsWith('.json'))return;const text=ts.transpileModule(fs.readFileSync(absolute,'utf8'),{fileName:absolute,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,ast=ts.createSourceFile('runtime.js',text,ts.ScriptTarget.Latest,true),names=new Set<string>();const scan=(n:ts.Node)=>{if(ts.isCallExpression(n)&&n.expression.getText(ast)==='require'&&ts.isStringLiteral(n.arguments[0]!))names.add(n.arguments[0].text);ts.forEachChild(n,scan);};scan(ast);const require=createRequire(absolute);for(const name of names){if(isBuiltin(name)){builtinNames.add(name);continue;}let resolved:string;if(name.startsWith('.')){const candidate=path.resolve(path.dirname(absolute),name),matches=[candidate,candidate+'.ts',candidate+'.tsx',candidate+'.js',path.join(candidate,'index.ts'),path.join(candidate,'index.js')].filter(p=>fs.existsSync(p)&&fs.statSync(p).isFile());assert(matches.length>=1,'unresolved relative runtime import '+relative+' '+name);resolved=matches[0]!;}else resolved=require.resolve(name);graphEdges.push({importer:relative,request:name,resolved:path.relative(ROOT,resolved).replaceAll('\\','/')});bindGraph(resolved);}};
 for(const p of [scene,helper,'packages/miniapp-contracts/src/index.ts',prefix+'sky-sdss-optical-selection.ts'])bindGraph(path.join(ROOT,p));
 for(const p of [prefix+'sky-sdss-optical-frame.test.ts',prefix+'sky-sdss-optical-page.test.ts','output/sdss-science-frame-handoff-1002-r1/current-source-snapshot-bindings.json'])admit(p);
 save('actual-owner-runtime-source-graph.json',{sourceFiles:[...graphSeen],edges:graphEdges,builtinNames:[...builtinNames],scope:'Static emitted-import closure of actually used scene/helper/selection and contract barrel. Source admission occurs before behavioral execution and is rechecked afterward. Page itself is only an AST input; compiler/tsx/framework tooling graph is not claimed as product execution.'});
 const PUB='output/sdss-science-optical-writer-1002-r1/publication',publication=JSON.parse(raw(PUB+'/manifest.json').toString('utf8'));admit(PUB+'/manifest.json',{sha256:'3eaf04b366827c86ece835f48ed37089d5406be2ed4d73c2252960e7e9aa1dd5'});contracts.assertSdssScienceOpticalManifest(publication,'M:51',publication.publicationHash);for(const a of Object.values(publication.levels)as any[])admit(PUB+'/'+a.file,a);
 const preservation=JSON.parse(raw('output/sdss-science-optical-writer-1002-r1/binding-before.json').toString('utf8'));for(const b of [...preservation.oldAssets,...preservation.preserved])admit(b.path,b);
 const freeze=(v:any)=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};freeze(publication);
 const image={identity:'actual-ready-detail-structural-sentinel'},parent={identity:'actual-ready-medium-structural-sentinel'},loaded={image,renderedLevel:'DETAIL' as const,renderedAsset:publication.levels.DETAIL,publication,coarser:{image:parent,level:'MEDIUM' as const,asset:publication.levels.MEDIUM}};
 const frame=skySdssOpticalFrame(loaded);assert(frame&&'sciencePublication'in frame);assert.strictEqual(frame.sciencePublication,publication);assert.strictEqual(frame.asset,publication.levels.DETAIL);assert.strictEqual(frame.coarser!.asset,publication.levels.MEDIUM);assert.strictEqual(frame.coarser!.image,parent);assert(Object.isFrozen(frame)&&Object.isFrozen(frame.coarser));
 assert.equal(frame.asset.sampleAvailability,'joint-area-alpha');assert.equal(frame.asset.crpixFitsOneBased,256.5);assert.equal(frame.asset.masterRgbSha256,frame.coarser!.asset.masterRgbSha256);assert.equal(frame.asset.masterAvailabilitySha256,frame.coarser!.asset.masterAvailabilitySha256);
 for(const change of [{renderedAsset:publication.levels.MEDIUM},{renderedAsset:{...publication.levels.DETAIL}},{image:null},{renderedLevel:null},{publication:undefined}])assert.equal(skySdssOpticalFrame({...loaded,...change}),null);
 const badParent=skySdssOpticalFrame({...loaded,coarser:{...loaded.coarser,asset:{...publication.levels.MEDIUM}}});assert(badParent&&'sciencePublication'in badParent&&badParent.coarser===null);assert.strictEqual(badParent.image,image);
 const coarseOnly=skySdssOpticalFrame({...loaded,image:parent,renderedLevel:'MEDIUM',renderedAsset:publication.levels.MEDIUM,coarser:null});assert(coarseOnly&&'sciencePublication'in coarseOnly);assert.strictEqual(coarseOnly.asset,publication.levels.MEDIUM);assert.equal(coarseOnly.fieldDegrees,publication.levels.MEDIUM.fieldDegrees);
 const legacyPath='workers/miniapp-api/assets/deep-sky/sdss-m51/manifest.json';admit(legacyPath);const legacyRaw=JSON.parse(raw(legacyPath).toString('utf8'));contracts.assertSdssOpticalPublication(legacyRaw,'M:51');const legacy={...legacyRaw,publicationHash:contracts.SDSS_OPTICAL_PUBLICATIONS['M:51'].publicationHash};
 const legacyFrame=skySdssOpticalFrame({...loaded,publication:legacy,renderedAsset:legacy.levels.DETAIL,coarser:{image:parent,level:'MEDIUM',asset:legacy.levels.MEDIUM}});assert(legacyFrame&&!('sciencePublication'in legacyFrame)&&!('asset'in legacyFrame));assert.equal(legacyFrame.fieldDegrees,legacy.levels.DETAIL.fieldDegrees);
 const ast=ts.createSourceFile(page,raw(page).toString('utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),all:ts.Node[]=[];const walk=(n:ts.Node)=>{all.push(n);ts.forEachChild(n,walk);};walk(ast);
 const calls=all.filter((n):n is ts.CallExpression=>ts.isCallExpression(n)&&n.expression.getText(ast)==='canvasLifecycle.request');assert.equal(calls.length,1);const arg=calls[0]!.arguments[0];assert(arg&&ts.isObjectLiteralExpression(arg));const item=arg.properties.find((n):n is ts.PropertyAssignment=>ts.isPropertyAssignment(n)&&n.name.getText(ast)==='sdssOpticalImage');assert(item);
 const expression=item.initializer.getText(ast),evaluate=(code:string,globals:object)=>vm.runInNewContext(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,globals);
 const queued=evaluate('('+expression+')',{skySdssOpticalFrame,sdssOptical:loaded,mode:'NIGHT',canvasData:{}});assert.strictEqual(queued.sciencePublication,publication);assert.strictEqual(queued.asset,publication.levels.DETAIL);assert.strictEqual(queued.coarser.asset,publication.levels.MEDIUM);for(const state of [{mode:'OBSERVATION',canvasData:{}},{mode:'NIGHT',canvasData:undefined}])assert.equal(evaluate('('+expression+')',{skySdssOpticalFrame,sdssOptical:loaded,...state}),null);
 fs.writeFileSync(path.join(ROOT,OUT!,'actual-page-queued-expression.ts.txt'),expression+'\n',{flag:'wx'});
 const compiled=(p:string,text=raw(p).toString('utf8'))=>ts.transpileModule(text,{fileName:p,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 const js=compiled(scene),requires=new Set<string>();const ja=ts.createSourceFile('scene.js',js,ts.ScriptTarget.Latest,true);const scan=(n:ts.Node)=>{if(ts.isCallExpression(n)&&n.expression.getText(ja)==='require'&&ts.isStringLiteral(n.arguments[0]!))requires.add(n.arguments[0].text);ts.forEachChild(n,scan);};scan(ja);
 const imports:Record<string,any>={'@starward/miniapp-contracts':contracts};for(const name of requires){if(name in imports)continue;assert(name.startsWith('./'),'unsupported dependency '+name);const p=path.posix.join(prefix,name)+'.ts';admit(p);imports[name]=await import(pathToFileURL(path.join(ROOT,p)).href);}
 const guard=' && !("sciencePublication" in sdssOpticalImage)';assert.equal(raw(scene).toString('utf8').split(guard).length,2);const mutant=raw(scene).toString('utf8').replace(guard,' /* independent bounded guard removal */');assert(!mutant.includes(guard));fs.writeFileSync(path.join(ROOT,OUT!,'mutated-science-legacy-guard.ts.txt'),mutant,{flag:'wx'});
 const sceneModule=(text:string)=>{const exports:Record<string,any>={};vm.runInNewContext(compiled(scene,text),{exports,require(n:string){assert(n in imports,n);return imports[n];}});return exports;};
 const current=sceneModule(raw(scene).toString('utf8')),changed=sceneModule(mutant);
 const time='2026-09-25T00:00:00.000Z',point=[0,0,40,0,40.1,359.9,40],report={hourly:[{at:time}],skyScene:{state:'UNAVAILABLE',frames:[],deepSky:{state:'AVAILABLE',catalog:{imageRegistration:'ICRS_TAN_NORTH_0_1_V1',entries:[{objectRef:'M:51'}]},frames:[{at:time,state:'AVAILABLE',points:[point]}]}},targetFrames:[]};
 const observe=(draw:any,optical:any)=>{const submissions:any[]=[],failures:any[]=[],finish={count:0};let source:any=null;const w3={identity:'independent-W3-structural-image'};const surface=new Proxy({},{get(_t,key){return key==='artwork'?(object:any,_reg:any,_view:any,opacity:any,_tint:any,composite:any)=>{submissions.push({object,opacity,composite});return true;}:key==='finish'?()=>{finish.count++;}:()=>undefined;}});const args:any[]=Array(35).fill(undefined);args[0]=surface;args[1]=report;args[2]=time;args[3]=null;args[4]=null;args[5]=390;args[6]=844;args[7]='NIGHT';args[8]=(_s:any,value:any)=>source=value;args[10]=.05;args[11]={reference:'M:51',level:'DETAIL',fieldDegrees:.25,image:w3};args[12]=createSkyViewBasis(0,130,0)!;args[30]=optical;args[31]=(object:any)=>failures.push(object);draw(...args);return{submissions,failures,finish:finish.count,source,w3};};
 const valid=observe(current.drawSkyScene,frame);assert.deepEqual(valid.submissions.map(r=>r.object),[valid.w3]);assert.equal(valid.source.sdssOpticalImage,null);assert.strictEqual(valid.source.deepSkyImage,valid.w3);assert.equal(valid.failures.length,0);assert.equal(valid.finish,1);
 const invalid=observe(changed.drawSkyScene,frame);assert.deepEqual(invalid.submissions.map(r=>r.object),[parent,image]);assert(invalid.submissions.every(r=>r.composite==='optical-cutout'));assert.strictEqual(invalid.source.sdssOpticalImage,image);assert.equal(invalid.source.deepSkyImage,null);assert.equal(invalid.finish,1);
 const compatible=observe(current.drawSkyScene,legacyFrame);assert.deepEqual(compatible.submissions.map(r=>r.object),[parent,image]);assert.strictEqual(compatible.source.sdssOpticalImage,image);
 const runFixture=(p:string,sceneText:string)=>{const results:any[]=[],register=(name:string,run:()=>void)=>{if(name.startsWith('science availability'))return;try{run();results.push({name,status:'passed'});}catch(e){results.push({name,status:'failed',error:String(e)});}};const sceneExports:Record<string,any>={},fixtureExports:Record<string,any>={};const context=vm.createContext({sceneExports,fixtureExports,sceneRequire(name:string){assert(name in imports,'scene dependency '+name);return imports[name];},fixtureRequire(name:string){if(name==='node:assert/strict')return assert;if(name==='node:test')return register;if(name==='./sky-scene-render')return sceneExports;assert(name in imports,'fixture dependency '+name);return imports[name];}});vm.runInContext('(function(exports,require){\n'+compiled(scene,sceneText)+'\n})(sceneExports,sceneRequire);',context);vm.runInContext('(function(exports,require){\n'+compiled(p)+'\n})(fixtureExports,fixtureRequire);',context);return results;};
 if(!imports['./sky-sdss-optical-selection']){const p=prefix+'sky-sdss-optical-selection.ts';admit(p);imports['./sky-sdss-optical-selection']=await import(pathToFileURL(path.join(ROOT,p)).href);}
 const oldCurrent=runFixture(old,raw(scene).toString('utf8')),oldRemoved=runFixture(old,mutant),repairedCurrent=runFixture(test,raw(scene).toString('utf8')),repairedRemoved=runFixture(test,mutant);
 save('legacy-fixture-comparisons.json',{oldCurrent,oldGuardRemoved:oldRemoved,repairedCurrent,repairedGuardRemoved:repairedRemoved,scienceFixtureOmittedAndIndependentlyChecked:true,sameRealmForFixtureAndScene:true});save('scene-observations.json',{current:valid,guardRemoved:invalid,legacy:compatible});
 const expected=['fully covered M51 images lose visible credits only after the foreground actually paints','a fully covered narrow viewport loses credit even when image edges extend into open sky offscreen','foreground covering the fine field still credits the exposed wider optical field'];
 assert.deepEqual(oldCurrent.filter(r=>r.status==='failed').map(r=>r.name),expected);assert.deepEqual(oldRemoved,oldCurrent);assert(repairedCurrent.every(r=>r.status==='passed'));assert.deepEqual(repairedRemoved,repairedCurrent);
 const before=[...inputs.values()];assert.deepEqual(before.map(r=>binding(r.path)),before);
 save('result.json',{status:'INDEPENDENT_SCIENCE_FRAME_HANDOFF_PASS',helper:binding(helper),page:binding(page),scene:binding(scene),realPublicationHash:publication.publicationHash,metadata:{sameMaster:true,realFineAndCoarseDescriptors:true,invalidFineRejected:true,invalidParentIndependent:true,coarseOnlyOwnDescriptor:true,legacySemanticsPreserved:true,pageActualQueuedExpression:true,observationAndAbsentDataNull:true},scene:{currentScienceSubmissions:valid.submissions.length,currentScienceCredit:false,currentW3Fallback:true,guardRemovedScienceSubmissions:invalid.submissions.length,guardRemovedPrematureCredit:true,legacyFineAndCoarsePasses:compatible.submissions.length},legacyFixtures:{originalLegacyCases:oldCurrent.length,originalFailedNames:expected,sameFailuresWithoutNewGuard:true,repairedLegacyCases:repairedCurrent.length,repairedAllPass:true},scope:['Actual frame helper and page queued-expression AST use real admitted writer metadata and structural image sentinels, not native decode. Complete actual scene modules execute against controlled catalog directions/terrain fixtures and surface submission callbacks, not pixels/GPU.','Guard mutation proves legacy artwork/source-credit calls would accept scientific availability PNGs prematurely. It does not adopt a science drawing/group/source-credit implementation or certify actual rendered contribution. No new HTTP, GPU, source downloads, UI/native or quality acceptance.']});save('binding.json',{inputsBefore:before,inputsAfter:before.map(r=>binding(r.path)),unchanged:true});console.log(JSON.stringify({result:binding(OUT!+'/result.json'),binding:binding(OUT!+'/binding.json')}));
}catch(cause){save('failed.json',{error:String(cause),inputs:[...inputs.values()]});throw cause;}
