import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {skyArtworkLevelsFragment} from '../../../../apps/wechat-miniapp/src/features/sky/sky-artwork-level-composition';
const root=process.cwd(),out='output/contribution-receipt-root-readback-1002-r1',task='.codex/work-items/cloud-sky-native-2026-09-22',p='output/playwright/cloud-sky-contribution-receipt-1002-r1/',owner='apps/wechat-miniapp/src/features/sky/sky-gpu-artwork-contributions.ts';
const sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),read=async(p:string)=>JSON.parse(await fs.readFile(p,'utf8')),bind=async(p:string)=>{const b=await fs.readFile(p);return {path:p.replaceAll('\\','/'),bytes:b.length,sha256:sha(b)};};
await fs.mkdir(out,{recursive:true});await assert.rejects(fs.access(out+'/result.json'),{code:'ENOENT'});
const result=await read(p+'result.json'),actual=await read(p+'current.json'),historical=await fs.readFile('output/contribution-getter-lifetime-independent-1002-r1/owner-before.ts.txt','utf8'),current=await fs.readFile(owner,'utf8');
assert.equal(sha(historical),'2182203ff6597e471b3158991fdf14b4f38a4f5ad1e88c97986fc7fa20606545');assert.equal(sha(current),'87467f231b709599befc57113e30d4c69c3d34d8782a95c1ecdeb2505b61c4dc');
const begin=current.indexOf('  const currentEntry = (draw: SkyArtworkLevelsDraw) => {'),end=current.indexOf('\n\n  return {',begin);assert(begin>0&&end>begin);
const withoutNewGetters=(current.slice(0,begin)+current.slice(end+1)).replace('return currentEntry(draw)?.qualification','return entries.get(draw)?.qualification').replace('const entry = currentEntry(draw);','const entry = entries.get(draw);');assert.equal(withoutNewGetters,historical,'only getter currentness changed since actual base GPU');
assert.deepEqual(result.before,result.after);const sources:any[]=[];for(const old of result.before){const now=await bind(old.path);if(old.path===owner){assert.equal(old.sha256,sha(historical));sources.push({historical:old,current:now,exception:'Exact getter-only delta verified against saved218 owner. New mechanism has separate affected GPU/controlled evidence.'});}else{assert.deepEqual(now,old);sources.push(now);}}
const rendererText=await fs.readFile('apps/wechat-miniapp/src/features/sky/sky-gpu-renderer.ts','utf8'),ray=/const skyRay = `([\s\S]*?)`;/.exec(rendererText)?.[1];assert(ray);
const oldShader=(await read('output/playwright/cloud-sky-contribution-fbo-1002-r1/actual-raw.json')).shaders.actualFragment;assert.equal(skyArtworkLevelsFragment(ray),oldShader,'default display shader changed');
const comparisons=[];for(const c of result.comparisons){const names=c.name.split('→'),a=actual.captures.find((x:any)=>x.name===names[0]),b=actual.captures.find((x:any)=>x.name===names[1]);assert(a&&b);const x=await fs.readFile(a.raw.path),y=await fs.readFile(b.raw.path);assert(x.equals(y));comparisons.push({name:c.name,bytes:x.length,sha256:sha(x)});}
const lifetime=await read('output/playwright/cloud-sky-contribution-lifetime-1002-r1/actual.json'),lifetimeResult=await read('output/playwright/cloud-sky-contribution-lifetime-1002-r1/result.json'),post=await read('output/playwright/cloud-sky-contribution-lifetime-1002-r2/actual.json'),postResult=await read('output/playwright/cloud-sky-contribution-lifetime-1002-r2/result.json');
assert.equal(lifetime.failure,null);assert.deepEqual(lifetime.checks.filter((x:any)=>!x.pass).map((x:any)=>x.name),['postdraw-finished-keeps-qualified-but-zero-unknown']);assert.equal(lifetimeResult.allPassed,false);assert.equal(lifetimeResult.normalFaultPixels.unequal,0);
const base=await fs.readFile('output/playwright/cloud-sky-contribution-lifetime-1002-r1/base.rgba'),faulted=await fs.readFile('output/playwright/cloud-sky-contribution-lifetime-1002-r1/read-failure.rgba');assert(base.equals(faulted));assert(postResult.allPassed&&post.onlyPost&&post.checks.every((x:any)=>x.pass));
const white=await fs.readFile('output/playwright/cloud-sky-contribution-lifetime-1002-r2/postdraw.rgba');assert.equal(white.length,96*128*4);for(let y=0;y<128;y++)for(let x=0;x<96;x++)for(let c=0;c<4;c++)assert.equal(white[(y*96+x)*4+c],c===3?255:y>=120?[4,8,16][c]:255);
const ledger=new Map<number,{kind:string,bytes:number}>();let peak=0;for(const e of actual.events){if(e.event==='create')ledger.set(e.id,{kind:e.kind,bytes:0});if(e.event==='delete')ledger.delete(e.id);if(e.event==='allocate'||e.event==='copy'){const r=ledger.get(e.id);assert(r&&r.kind==='texture');r.bytes=e.bytes;}peak=Math.max(peak,[...ledger.values()].reduce((s,r)=>s+r.bytes,0));}assert.equal(ledger.size,0);assert.equal(peak,16360568);
const high=actual.rows.find((x:any)=>x.name==='high-dpr');assert.equal(high.plan.total,15803512);assert.equal(high.resources.logicalTextureBytes-high.plan.total,557056);
const budget=await read('output/contribution-budget-regression-1002-r1/result.json');assert(budget.actualBeforeFailed&&budget.currentPassed);
const reserved=await read(task+'/tmp/resume-preserved-hashes-2026-10-01.json');for(const r of reserved)assert.equal((await bind(r.path)).sha256,r.sha256);
const bundlePath='apps/wechat-miniapp/dist/weapp/sky/detail/index.js',bundleRaw=await fs.readFile(bundlePath,'utf8'),bundleStat=await fs.stat(bundlePath),ownerStat=await fs.stat(owner);assert(bundleStat.mtimeMs>=ownerStat.mtimeMs);assert(bundleRaw.includes('resetArtworkContributions')&&bundleRaw.includes('currentEntry'));
const inputs=[p+'result.json',p+'current.json','output/contribution-getter-lifetime-independent-1002-r1/owner-before.ts.txt','output/contribution-getter-lifetime-independent-1002-r1/result.json','output/contribution-budget-regression-1002-r1/result.json','output/playwright/cloud-sky-contribution-lifetime-1002-r1/result.json','output/playwright/cloud-sky-contribution-lifetime-1002-r1/actual.json','output/playwright/cloud-sky-contribution-lifetime-1002-r2/result.json','output/playwright/cloud-sky-contribution-lifetime-1002-r2/actual.json','apps/wechat-miniapp/src/features/sky/sky-gpu-artwork-contributions.test.ts',out+'/checks.json'];
const sealed={sources,artifacts:await Promise.all(inputs.map(bind)),onlyGetterDelta:true,defaultDisplayShaderExact:true,comparisons,ledger:{peakLogicalTextureBytes:peak,final:ledger.size},highDpr:{auxiliaryLogicalBytes:high.plan.total,sourceResidentBytes:557056,totalLogicalTextureBytes:high.resources.logicalTextureBytes},lifetime:{r1OverallFailed:true,failedOracle:'image transform treated normalized UV as source-pixel scale; source returned positive correctly for a subpixel rectangle',otherR1ChecksPass:true,normalFaultBytes:base.length,normalFaultEqual:true,r2OnlyCorrectedPostDraw:true,whiteBytes:white.length,fullWhiteAndNavigationExact:true},attributeWitness:{beforeFailed:result.witness.beforeFailed,afterPositive:result.witness.afterPositive,meaning:'Software GPU negative diagnostic; not a fail-before claim.'},budgetWitness:{actualBeforeFailed:true,currentPassed:true},preserved:reserved,watch:{bundle:await bind(bundlePath),bundleUpdatedUtc:bundleStat.mtime.toISOString(),ownerUpdatedUtc:ownerStat.mtime.toISOString(),newGetterAndRendererMarkers:true,scope:'Read-only existing watch emission only; terminal unattached/PID/current IDE/native/WXML/clean candidate unverified.'},scope:'Read-only actual saved sources/outputs/receipts; no shader, GPU, native, provider, old suite or IDE reexecution.'};
await fs.writeFile(out+'/result.json',JSON.stringify(sealed,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({result:await bind(out+'/result.json'),historicalSources:sources.length,shaderExact:true,comparisonCount:comparisons.length,ledger:sealed.ledger,watchBundle:sealed.watch.bundle}));
