/** Independent actual Scene/page/lifecycle controls; no GPU/network/native execution. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import {build} from 'esbuild';
import {assertSdssScienceOpticalManifest} from '@starward/miniapp-contracts';
import {drawSkyScene} from '../../../../apps/wechat-miniapp/src/features/sky/sky-scene-render';
import {createSkyCanvasLifecycle} from '../../../../apps/wechat-miniapp/src/features/sky/sky-canvas-lifecycle';
import {copySkyDeepAuxiliaryDecisions,sameSkyDeepAuxiliaryDecisions,skyDeepAuxiliaryDecisionOpacity,deepSkyAuxiliaryOpacity} from '../../../../apps/wechat-miniapp/src/features/sky/sky-deep-auxiliary-visibility';
import {liveSkyOpticalCompletion,sameSkyOpticalCompletion,sameSkyOpticalInput} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-completion';
import {createSkyArtworkLoader,registerSkyNativeImageLifetime} from '../../../../apps/wechat-miniapp/src/features/sky/sky-artwork-loader';
import {skySdssOpticalFrame} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-frame';
import {resolvedSkyBodyReferences} from '../../../../apps/wechat-miniapp/src/features/sky/sky-body-label-presentation';
import {resolveSkySceneFrame,resolveSkyDeepSkyScene} from '../../../../apps/wechat-miniapp/src/features/sky/sky-stellar-scene';
import {projectHorizontalPoint} from '../../../../apps/wechat-miniapp/src/features/sky/sky-scene-projection';
import {paintedSkyPointVisible,pickPaintedSkyObjects} from '../../../../apps/wechat-miniapp/src/features/sky/sky-object-picking';
import {skyStarAppearance} from '../../../../apps/wechat-miniapp/src/features/sky/sky-star-appearance';
import {skySolarLightAt} from '../../../../apps/wechat-miniapp/src/features/sky/sky-solar-light';

const ROOT=path.resolve(fileURLToPath(new URL('../../../../',import.meta.url))), OUT=path.join(ROOT,'output/common-opacity-independent-1002-r2');
assert(!fs.existsSync(OUT));fs.mkdirSync(OUT);
const sky='apps/wechat-miniapp/src/features/sky/', script=fileURLToPath(import.meta.url);
const read=(p:string)=>fs.readFileSync(path.resolve(ROOT,p)),json=(p:string)=>JSON.parse(read(p).toString('utf8'));
const sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const binding=(p:string)=>{const absolute=path.resolve(ROOT,p),b=fs.readFileSync(absolute);return{path:path.relative(ROOT,absolute).replaceAll('\\','/'),bytes:b.length,sha256:sha(b)};};
const save=(name:string,value:any)=>fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});
fs.copyFileSync(script,path.join(OUT,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
const pageText=read(sky+'spot-sky-page.tsx').toString('utf8'), oldPagePath='output/optical-completion-consumer-independent-1002-r5/page-source.tsx.txt';
const oldPageText=read(oldPagePath).toString('utf8');
function parse(text:string){const source=ts.createSourceFile('page.tsx',text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),props=new Map<string,ts.Expression>(),vars=new Map<string,ts.Expression>();const effects:ts.CallExpression[]=[];
  function walk(n:ts.Node){if(ts.isCallExpression(n)&&n.expression.getText(source)==='createSkyCanvasLifecycle'){assert(ts.isObjectLiteralExpression(n.arguments[0]));for(const p of n.arguments[0].properties)if(ts.isPropertyAssignment(p)&&['paint','presented','failed','invalidated','sameScene'].includes(p.name.getText(source)))props.set(p.name.getText(source),p.initializer);}
    if(ts.isVariableDeclaration(n)&&n.initializer)vars.set(n.name.getText(source),n.initializer);
    if(ts.isCallExpression(n)&&n.expression.getText(source)==='useEffect')effects.push(n);ts.forEachChild(n,walk);}walk(source);return{source,props,vars,effects};}
const ast=parse(pageText),oldAst=parse(oldPageText);
const compile=(text:string,env:any)=>vm.runInNewContext(ts.transpileModule(`(${text})`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,env);
const reportPath='.codex/work-items/cloud-sky-native-2026-09-22/tmp/current-native-report-2026-10-01.json', report=json(reportPath).data;
const preparedPath='output/playwright/cloud-sky-science-scene-1002-r3/prepared-input.json',prepared=json(preparedPath), at=prepared.at;
const priorObservationsPath='output/playwright/cloud-sky-science-scene-1002-r3/observations.json',basis=json(priorObservationsPath).basis;
const publicationPath='output/sdss-science-optical-writer-1002-r1/publication/manifest.json',publication=json(publicationPath);
assertSdssScienceOpticalManifest(publication,'M:51',publication.publicationHash);
const major=report.skyScene.deepSky.catalog.entries.find((x:any)=>x.objectRef==='M:51').majorAxisArcmin;
assert.equal(major,13.71);
const fine={width:512,height:512},coarse={width:512,height:512};
function optical(image:any=fine){return{image,reference:'M:51',publicationHash:'actual-controlled-legacy',level:'DETAIL',fieldDegrees:.0568888889};}
function surface(){const calls:any[]=[],discs:any[]=[];let throwFinish=false;const value=new Proxy({begin(){calls.push('begin');},artwork(image:any){calls.push({kind:'artwork',image});return true;},disc(...args:any[]){discs.push(args);},finish(){calls.push('finish');if(throwFinish)throw Error('controlled_finish_failure');}}, {get:(o:any,k)=>k in o?o[k]:()=>true});return{value,calls,discs,fail(){throwFinish=true;}};}
function scene(input:any=optical(),fov=2.2,height=844,width=390,extra:any={}){const s=surface();let snapshot:any=null,sources:any=null,done=0;
  const args:any[]=Array(37).fill(undefined);Object.assign(args,{0:s.value,1:report,2:at,5:width,6:height,7:'NIGHT',8:(p:any,q:any)=>{snapshot=p;sources=q;},9:()=>done++,10:fov,12:basis,30:input,34:{enabled:false},35:{horizontal:false,equatorial:false}},extra);
  drawSkyScene(...args as any);return{s,snapshot,sources,done};}
function harness(options:{page?:ReturnType<typeof parse>;paintText?:string}={}){const page=options.page??ast;let id=0,fov=2.8,size={width:390,height:844};const jobs=new Map<number,{callback:()=>void;delay:number}>(),attempts:Array<()=>void>=[],scenes:any[]=[];
  const gen={current:1},pending={current:null as any},picking={current:null as any},state={frame:null as any,camera:null as any,size:{width:0,height:0},error:null as any,inspections:[] as any[]},s=surface();
  const env:any={Error,copySkyDeepAuxiliaryDecisions,sameSkyDeepAuxiliaryDecisions,liveSkyOpticalCompletion,sameSkyOpticalCompletion,sameSkyOpticalInput,resolvedSkyBodyReferences,
    canvasGenerationRef:gen,pendingSkyPaintRef:pending,paintedSkyObjectsRef:picking,orientation:{latestPresentation:{current:null},presented:{current:null}},orientationController:{snapshot:()=>({})},manualBasisRef:{current:null},zoomRef:{current:fov},viewportInsetsRef:{current:{}},reducedMotionRef:{current:false},
    browsingTimerRef:{current:null},resolveSkyCanvasView:()=>({verticalFovDeg:fov,progress:1,center:{x:size.width/2,y:size.height/2},localView:basis,intent:'manual'}),browsingCamera:{update:()=>({view:basis,animating:false})},
    setPresentedSkyFrame:(x:any)=>{state.frame=typeof x==='function'?x(state.frame):x;},setPresentedCamera:(x:any)=>{state.camera=typeof x==='function'?x(state.camera):x;},setCanvasSize:(x:any)=>{state.size=typeof x==='function'?x(state.size):x;},setCanvasError:(x:any)=>{state.error=x;},canvasDrawRevisionRef:{current:0},publishAcceptanceSkySceneInspection:(_o:any,v:any)=>state.inspections.push(v),
    EMPTY_SKY_IMAGES:new Map(),setSolarLightUnavailable:()=>{},setMoonDiscUnavailable:()=>{},setPlanetDiscUnavailable:()=>{},setSunDiscUnavailable:()=>{},setGalacticBandUnavailable:()=>{},setLandscapeUnavailable:()=>{},
    drawSkyScene:(...args:any[])=>{const paint=args[8],complete=args[9],seen:any={};args[8]=(p:any,q:any)=>{seen.snapshot=p;seen.sources=q;paint(p,q);};args[9]=()=>attempts.push(complete);drawSkyScene(...args as any);scenes.push(seen);}};
  const context=vm.createContext(env),callback=(name:string)=>vm.runInContext(ts.transpileModule(`(${name==='paint'&&options.paintText?options.paintText:page.props.get(name)!.getText(page.source)})`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
  const lifecycle=createSkyCanvasLifecycle<any,object>({measure:done=>done(size),createContext:()=>s.value,releaseContext:()=>{gen.current++;},paint:callback('paint'),sameScene:callback('sameScene'),presented:callback('presented'),invalidated:callback('invalidated'),failed:callback('failed')},{schedule(cb,delay){jobs.set(++id,{callback:cb,delay});return id;},cancel(h){jobs.delete(h as number);}});
  const frame={data:report,frameAt:at,mode:'NIGHT',sceneReady:true,nativeImageGeneration:1,orientationRevision:0,verticalFovDeg:fov,heading:null,pose:null,owner:'independent-controlled',inspection:{spotId:'actual-report'},sdssOpticalImage:optical(),deepSkyImage:null,coordinateGrids:{horizontal:false,equatorial:false},landscapeEnabled:false};
  lifecycle.ready();const step=()=>{const job=[...jobs].find(([,x])=>x.delay===0);assert(job);jobs.delete(job[0]);job[1].callback();};
  const dom=(pageAst:ReturnType<typeof parse>=page)=>{const data=state.frame?.data,view=state.camera;return compile(pageAst.vars.get('visibleNamedCatalogObjects')!.getText(pageAst.source),{resolveSkySceneFrame,resolveSkyDeepSkyScene,skyStarAppearance,skySolarLightAt,projectHorizontalPoint,paintedSkyPointVisible,skyDeepAuxiliaryDecisionOpacity,deepSkyAuxiliaryOpacity,
      paintedData:data,paintedAt:state.frame?.frameAt,presentedSceneCurrent:Boolean(state.frame),currentViewBasis:view?.basis,canvasSize:state.size,presentedFov:view?.fov,presentedCenter:view?.center,presentedSkyFrame:state.frame,presentedSkyVisibility:picking.current,mode:'NIGHT',sensorHeadingForScene:null,devicePose:null,
      presentedSdssOptical:liveSkyOpticalCompletion(state.frame?.sdssOptical),sdssOpticalImagePresented:Boolean(liveSkyOpticalCompletion(state.frame?.sdssOptical)),deepSkyImagePresented:false});};
  return{lifecycle,frame,state,picking,gen,pending,scenes,attempts,s,env,step,dom,setFov(value:number){fov=value;env.zoomRef.current=value;},setSize(value:any){size=value;},complete(){attempts.at(-1)!();},queue(value:any=frame){lifecycle.request(value);step();}};
}
const controls:any[]=[],mutants:any[]=[],cleanup:Array<()=>void>=[];let before:any[]=[];
const control=(name:string,fn:()=>unknown)=>controls.push({name,status:'passed',facts:fn()});
try{
  const graph=await build({absWorkingDir:ROOT,entryPoints:[sky+'sky-scene-render.ts',sky+'sky-canvas-lifecycle.ts',sky+'sky-artwork-loader.ts'],outdir:path.join(OUT,'nonwritten-build'),bundle:true,write:false,metafile:true,platform:'node',format:'esm',tsconfig:path.join(ROOT,'apps/wechat-miniapp/tsconfig.json')});
  const inputs=new Set(Object.keys(graph.metafile!.inputs).map(x=>path.relative(ROOT,path.resolve(ROOT,x)).replaceAll('\\','/')));
  for(const p of [script,sky+'spot-sky-page.tsx',sky+'use-sky-artwork.ts',sky+'use-sky-sdss-optical.ts',sky+'sky-sdss-optical-frame.ts',oldPagePath,reportPath,preparedPath,priorObservationsPath,publicationPath,'apps/wechat-miniapp/tsconfig.json','.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-pre-aid-common-opacity-owner-review-2026-10-02.md','.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-pre-aid-common-opacity-owner-binding-2026-10-02.json'])inputs.add(path.relative(ROOT,path.resolve(ROOT,p)).replaceAll('\\','/'));
  const protectedPaths=['apps/wechat-miniapp/src/content/settings/display-mode-control.tsx','apps/wechat-miniapp/src/content/settings/display-mode-gesture.test.ts','apps/wechat-miniapp/src/content/settings/display-mode-gesture.ts','apps/wechat-miniapp/src/content/settings/index.tsx','workers/miniapp-api/src/miniapp-infrastructure.test.ts','workers/miniapp-api/src/outbox-worker.ts'];protectedPaths.forEach(p=>inputs.add(p));
  before=[...inputs].sort().map(binding);save('binding-before.json',before);save('metafile.json',graph.metafile);
  const expected:any={'sky-deep-auxiliary-visibility.ts':'25054c2d5c14ce64cbae0950a16fff7c39fba6a11a5b132f0241f1ce1e1f6d54','sky-object-picking.ts':'3a5720b9fd63e6c2c24eb68be235a8f2a16523eef49517a57681a90ba778c461','sky-scene-render.ts':'e11b2bdbbb1cd419511f468830bfe203a45626be7fb3efd86e6dd13399447eca','spot-sky-page.tsx':'522d3ef3518ac9739a13ea019e7de68f8d21c14cd4629f1d9c74fd09ad3dbc88'};
  for(const [file,hash]of Object.entries(expected))assert.equal(binding(sky+file).sha256,hash);
  assert.equal(binding(oldPagePath).sha256,'d8234b9d160513f0754bc7d37e5e49a18c97fcbad8c69381fe5353143ad2831d');
  fs.writeFileSync(path.join(OUT,'page-source.tsx.txt'),pageText,{flag:'wx'});save('actual-page-callbacks.json',Object.fromEntries([...ast.props].map(([k,v])=>[k,v.getText(ast.source)])));
  control('actual Scene ring scalar, frozen decisions and independent picking survive zero/failed images',()=>{const facts=[];for(const fov of [6,2.2,1,2.2,6]){const p=scene(optical(),fov),opacity=skyDeepAuxiliaryDecisionOpacity(p.snapshot.deepSkyAuxiliaryDecisions,'M:51')!;assert.equal(opacity,deepSkyAuxiliaryOpacity(fov,844,major,true));assert(Object.isFrozen(p.snapshot.deepSkyAuxiliaryDecisions));assert(p.snapshot.deepSkyAuxiliaryDecisions.every(Object.isFrozen));const target=p.snapshot.objects.find((x:any)=>x.reference==='M:51');assert(target);const ring=p.s.discs.find((x:any)=>x[0]===target.x&&x[1]===target.y&&x[2]===3.2);if(opacity>.01){assert(ring);assert.equal(ring[4],.9*opacity);}else assert.equal(ring,undefined);assert(pickPaintedSkyObjects(p.snapshot,{x:target.x,y:target.y,frameAt:at,catalogVersion:p.snapshot.catalogVersion,catalogHash:p.snapshot.catalogHash}).some(x=>x.reference==='M:51'));facts.push({fov,opacity,ring:Boolean(ring),pickable:true});}
    assert.equal(skyDeepAuxiliaryDecisionOpacity(scene(null,1).snapshot.deepSkyAuxiliaryDecisions,'M:51'),1);return facts;});
  control('accepted same-source FOV/height changes publish actual new decisions; missing membership is not fallback one',()=>{const h=harness();h.queue();assert.equal(h.state.frame,null);h.complete();const first=h.state.frame,opacity=skyDeepAuxiliaryDecisionOpacity(first.deepSkyAuxiliaryDecisions,'M:51');assert(opacity!>0&&opacity!<1);const label=h.dom().find((x:any)=>x.reference==='M:51');assert(label);assert.equal(label.auxiliaryOpacity,opacity);
    h.setFov(2.2);h.queue({...h.frame,verticalFovDeg:2.2});h.complete();assert.notStrictEqual(h.state.frame,first);assert.strictEqual(h.state.frame.sdssOptical.field.image,fine);assert.equal(skyDeepAuxiliaryDecisionOpacity(h.state.frame.deepSkyAuxiliaryDecisions,'M:51'),deepSkyAuxiliaryOpacity(2.2,844,major,true));
    const record=h.state.frame.deepSkyAuxiliaryDecisions;h.setSize({width:390,height:600});h.lifecycle.resize();h.frame.nativeImageGeneration=h.gen.current;h.queue({...h.frame,verticalFovDeg:2.2});h.complete();assert.notDeepEqual(h.state.frame.deepSkyAuxiliaryDecisions,record);assert.equal(skyDeepAuxiliaryDecisionOpacity(h.state.frame.deepSkyAuxiliaryDecisions,'M:51'),deepSkyAuxiliaryOpacity(2.2,600,major,true));
    h.state.frame={...h.state.frame,deepSkyAuxiliaryDecisions:[]};assert(!h.dom().some((x:any)=>x.reference==='M:51'));h.lifecycle.dispose();return{firstOpacity:opacity,height:600,sameImage:true,absentRecordDoesNotExposeLabel:true};});
  control('native retirement after Scene finish does not restore DOM before accepted replacement; exact old page exposes mismatch',()=>{const live={current:true},image={},retire=registerSkyNativeImageLifetime(image,()=>live.current);cleanup.push(retire);const h=harness();h.frame.sdssOpticalImage=optical(image);h.queue();const staged=skyDeepAuxiliaryDecisionOpacity(h.scenes[0].snapshot.deepSkyAuxiliaryDecisions,'M:51');live.current=false;retire();h.complete();assert.equal(h.state.frame.sdssOptical,null);assert.equal(skyDeepAuxiliaryDecisionOpacity(h.state.frame.deepSkyAuxiliaryDecisions,'M:51'),staged);const modern=h.dom().find((x:any)=>x.reference==='M:51'),old=h.dom(oldAst).find((x:any)=>x.reference==='M:51');assert.equal(modern.auxiliaryOpacity,staged);assert.equal(old.auxiliaryOpacity,1);assert.notEqual(staged,1);
    h.queue({...h.frame,sdssOpticalImage:null});assert.equal(h.dom().find((x:any)=>x.reference==='M:51').auxiliaryOpacity,staged);h.complete();assert.equal(h.dom().find((x:any)=>x.reference==='M:51').auxiliaryOpacity,1);const newTarget=h.scenes.at(-1).snapshot.objects.find((x:any)=>x.reference==='M:51');assert(h.s.discs.some(x=>x[0]===newTarget.x&&x[1]===newTarget.y&&x[2]===3.2&&x[4]===.9));h.lifecycle.dispose();return{stagedCanvasOpacity:staged,modernDomWhileSourceGone:modern.auxiliaryOpacity,exactOldDomWrongOpacity:old.auxiliaryOpacity,replacementCanvasAndDom:1};});
  control('retirement shared loader emits new map and actual page draw effect queues replacement, not a manual request',()=>{let ready:any,retireHandler:any,released=0,live=true,changed:any[]=[],currentState:any;const image={},owner=createSkyArtworkLoader({start(_asset:any,callback:any){ready=callback;return()=>{};},changed(state){changed.push(state);currentState=state;}}),asset={id:'M51',sha256:'a'.repeat(64),width:512,height:512};owner.update([asset]);ready({image,isCurrent:()=>live,release(){released++;},onRetire(handler:any){retireHandler=handler;return()=>{retireHandler=undefined;};}});assert.strictEqual(currentState.images.get('M51'),image);const oldMap=currentState.images;
    const h=harness();h.frame.sdssOpticalImage=optical(image);h.queue();h.complete();const initial=h.state.frame.deepSkyAuxiliaryDecisions;live=false;const signal=retireHandler;signal();assert.notStrictEqual(currentState.images,oldMap);assert.equal(currentState.images.size,0);assert.equal(currentState.failed,true);assert.equal(released,1);
    const draw=ast.vars.get('draw')!;assert(ts.isCallExpression(draw));const drawBody=draw.arguments[0],deps=draw.arguments[1]!.getText(ast.source);for(const key of ['sdssOptical.image','sdssOptical.coarser','canvasDeepSkyImage'])assert(deps.includes(key));const effect=ast.effects.find(e=>e.arguments[0]!.getText(ast.source).includes('canvasLifecycle.setMounted(Boolean(contextComplete'));assert(effect);let submitted:any=null;
    const env={publishAcceptanceSkySceneInspection:()=>{},skySceneInspectionOwnerRef:{current:'controlled'},canvasFrameInfo:{inspection:{}},report:{data:{dataState:'AVAILABLE'},isError:false},reportData:report,devicePose:null,sensorHeadingForScene:null,manualBasisRef:{current:basis},manualBasis:basis,skySceneHasContent:()=>true,constellationFrame:null,canvasDrawRevisionRef:{current:0},canvasLifecycle:{request(frame:any,hide:any){submitted=frame;h.lifecycle.request(frame,hide);},setMounted(v:boolean){h.lifecycle.setMounted(v);}},canvasNodeRevision:1,orientation:{snapshot:{presentationRevision:0}},row:{at},mode:'NIGHT',verticalFovDeg:2.8,canvasDeepSkyImage:null,sdssOptical:{image:currentState.images.get('M51')??null},skySdssOpticalFrame,artwork:{images:new Map()},constellationsEnabled:false,landscapeEnabled:false,coordinateGrids:{horizontal:false,equatorial:false},hipsTiles:[],moonTexture:{image:null},marsTexture:{image:null},mercuryTexture:{image:null},jupiterBands:{image:null},saturnBands:{image:null},neptuneBands:{image:null},uranusBands:{image:null},galacticImage:{image:null},landscapeImage:{panorama:null,mask:null,opacity:0,loading:false,failed:false},stellarSupplement:{frame:null},previousCanvasModeRef:{current:'NIGHT'},contextComplete:true,activeContext:{},nativeCanvasMounted:true};
    compile(effect.arguments[0].getText(ast.source),{...env,draw:compile(drawBody.getText(ast.source),env)})();assert(submitted);assert.equal(submitted.sdssOpticalImage,null);h.step();assert.deepEqual(h.state.frame.deepSkyAuxiliaryDecisions,initial);h.complete();assert.equal(skyDeepAuxiliaryDecisionOpacity(h.state.frame.deepSkyAuxiliaryDecisions,'M:51'),1);owner.dispose();h.lifecycle.dispose();return{changedMap:true,sourceRelease:released,actualPageEffectSubmitted:true,replacementAcceptedOpacity:1};});
  control('rejected late completion/failed replacement cannot publish restored records',()=>{const facts=[];for(const action of ['hide','resize','remount','new-scene','dispose']){const h=harness();h.queue();if(action==='hide')h.lifecycle.hide();else if(action==='resize')h.lifecycle.resize();else if(action==='remount')h.lifecycle.setMounted(false);else if(action==='new-scene')h.lifecycle.request({...h.frame,mode:'DAY'});else h.lifecycle.dispose();h.complete();assert.equal(h.state.frame,null);assert.equal(h.picking.current,null);facts.push(action);h.lifecycle.dispose();}
    const h=harness();h.queue();h.complete();h.s.fail();h.queue({...h.frame,sdssOpticalImage:null});assert.equal(h.state.frame,null);assert.match(h.state.error,/controlled_finish_failure/);assert(!h.scenes.at(-1).snapshot.deepSkyAuxiliaryDecisions.some((x:any)=>x.reference==='M:51'&&x.opacity===1));h.lifecycle.dispose();return{rejected:facts,failedReplacementUnavailable:true};});
  control('science valid black/global positive/partial receipts never enter legacy auxiliary readability',()=>{const facts=[];for(const q of [{fine:'has',coarse:'empty',any:'has'},{fine:'has',coarse:'has',any:'has'},{fine:'unknown',coarse:'unknown',any:'unknown'}]){const a={},b={},frame=skySdssOpticalFrame({publication,image:a,renderedLevel:'DETAIL',renderedAsset:publication.levels.DETAIL,coarser:{image:b,level:'MEDIUM',asset:publication.levels.MEDIUM}}),s=surface();const actual:any=s.value;actual.artworkLevels=()=>({submitted:true,finePrepared:true,coarsePrepared:true});actual.artworkLevelsQualification=()=>q;actual.artworkLevelsContribution=()=>({completed:true,qualification:q,finePhoto:'positive',coarsePhoto:'positive'});const r=scene(frame,1,844,390,{0:actual,36:{surface:actual,reference:'M:51',publicationHash:publication.publicationHash}});assert.equal(skyDeepAuxiliaryDecisionOpacity(r.snapshot.deepSkyAuxiliaryDecisions,'M:51'),1);facts.push({qualification:q.any,opacity:1});}return{facts,scope:'Actual Scene/helper with controlled receipt surface, not a new GPU/scientific display trial.'};});
  control('bounded equality mutation recreates stale same-source decisions; bounded final-source recompute recreates mismatch',()=>{const paint=ast.props.get('paint')!.getText(ast.source),guard='sameSkyDeepAuxiliaryDecisions(previous.deepSkyAuxiliaryDecisions, deepSkyAuxiliaryDecisions) &&';assert.equal(paint.split(guard).length,2);const bypass=paint.replace(guard,'');fs.writeFileSync(path.join(OUT,'mutant-ignore-opacity-equality.ts.txt'),bypass,{flag:'wx'});const h=harness({paintText:bypass});h.queue();h.complete();const first=h.state.frame;h.setFov(2.2);h.queue({...h.frame,verticalFovDeg:2.2});h.complete();assert.strictEqual(h.state.frame,first);const expectedOpacity=skyDeepAuxiliaryDecisionOpacity(h.scenes.at(-1).snapshot.deepSkyAuxiliaryDecisions,'M:51');assert.notEqual(skyDeepAuxiliaryDecisionOpacity(h.state.frame.deepSkyAuxiliaryDecisions,'M:51'),expectedOpacity);mutants.push({name:'equality record guard removed',staleOpacity:skyDeepAuxiliaryDecisionOpacity(h.state.frame.deepSkyAuxiliaryDecisions,'M:51'),actualCanvasOpacity:expectedOpacity,detected:true});h.lifecycle.dispose();return mutants;});
  control('record immutability/ambiguity/invalidity and current linear lookup cost are explicit',()=>{const original=[{reference:'M:51',opacity:0},{reference:'M:31',opacity:.5}],copied=copySkyDeepAuxiliaryDecisions(original);original[0].opacity=1;assert.equal(copied[0].opacity,0);assert(Object.isFrozen(copied)&&copied.every(Object.isFrozen));for(const records of [undefined,[],[{reference:'M:51',opacity:NaN}],[{reference:'M:51',opacity:-1}],[{reference:'M:51',opacity:2}],[{reference:'M:51',opacity:1},{reference:'M:51',opacity:1}]])assert.equal(skyDeepAuxiliaryDecisionOpacity(records,'M:51'),null);
    const r=scene(),catalog=report.skyScene.deepSky.catalog.entries.length,points=resolveSkyDeepSkyScene(report.skyScene,at)?.frame.points?.length??0,records=r.snapshot.deepSkyAuxiliaryDecisions.length;let visits=0;const actualRecords=r.snapshot.deepSkyAuxiliaryDecisions;const instrumented={*[Symbol.iterator](){for(const record of actualRecords){visits++;yield record;}}} as any;for(const point of resolveSkyDeepSkyScene(report.skyScene,at)!.frame.points!){const entry=report.skyScene.deepSky.catalog.entries[point[0]];skyDeepAuxiliaryDecisionOpacity(instrumented,entry.objectRef);}assert.equal(visits,points*records);return{catalogEntries:catalog,framePoints:points,projectedDecisionRecords:records,actualLookupElementVisits:visits,complexity:'O(frame points × projected decisions), current-input operation count only; no native wall/FPS claim.',scaleReassessment:'If admitted catalogs or wide projected sets materially grow, prepare one immutable lookup owner/index per accepted snapshot; no current benchmark or invented future size.'};});
  const after=before.map(x=>binding(x.path));assert.deepEqual(after,before);save('binding-after.json',after);
  save('result.json',{status:'INDEPENDENT_BOUNDED_COMMON_OPACITY_REVIEW_PASSED',controls,mutants,bindings:before.length,production:expected,oldExactPage:binding(oldPagePath),limits:['No GPU/browser/HTTP/native/IDE work. Actual Scene commands and accepted page AST run with controlled surface and callback timing.','The real source/report/publication bytes are bound; controlled image objects and surface success are not native decoding or visible photometry.','Current curve is unchanged tuning, not a newly adopted local readability/contrast threshold. Science remains opacity 1 and normal page default science remains closed.','Source retirement triggers are qualified through actual loader emit and actual page effect; React scheduling timing and physical native resource retirement are not certified.','Complete natural zoom experience, target composition/accessibility, local science readability, PSF/colour/image quality and native performance/capacity remain open.']});
  console.log(JSON.stringify({output:path.relative(ROOT,OUT),result:binding(path.join(OUT,'result.json')),binding:binding(path.join(OUT,'binding-before.json')),controls:controls.length}));
}catch(error){save('failed.json',{error:String(error),stack:(error as Error).stack,controls,mutants,before});throw error;}finally{cleanup.forEach(fn=>fn());}
