import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {build} from 'esbuild';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const root=process.cwd(),task='.codex/work-items/cloud-sky-native-2026-09-22',script=path.relative(root,fileURLToPath(import.meta.url)).replaceAll('\\','/'),entry=task+'/scripts/experience-contribution-lifetime-browser-2026-10-02.ts',prior='output/playwright/cloud-sky-contribution-receipt-1002-r1/';
const out=path.resolve(process.argv.find(x=>x.startsWith('--output='))?.slice(9)??'output/playwright/cloud-sky-contribution-lifetime-1002-r1'),rel=path.relative(root,out).replaceAll('\\','/');assert(rel&&!rel.startsWith('..')&&!path.isAbsolute(rel));await assert.rejects(fs.access(out),{code:'ENOENT'});await fs.mkdir(out,{recursive:true});
const sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),bind=async(p:string)=>{const b=await fs.readFile(p);return {path:p.replaceAll('\\','/'),bytes:b.length,sha256:sha(b)};},write=(n:string,v:any)=>fs.writeFile(path.join(out,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
let browser:any=null,before:any[]=[],after:any[]=[];
try{
 const input=JSON.parse(await fs.readFile(prior+'prepared-input.json','utf8')),old=JSON.parse(await fs.readFile(prior+'inputs-before.json','utf8')),files=[script,entry,prior+'prepared-input.json',prior+'inputs-before.json'];
 input.images=await Promise.all(input.images.map(async(a:any)=>{const source=old.before.find((p:any)=>p.sha256===a.sha256);assert(source);files.push(source.path);const b=await fs.readFile(source.path);assert.equal(sha(b),a.sha256);return {...a,data:'data:image/png;base64,'+b.toString('base64')};}));
 const b=await build({entryPoints:[path.resolve(entry)],bundle:true,write:false,metafile:true,platform:'browser',format:'iife',globalName:'contributionLifetimeTrial',target:'es2022',tsconfig:'apps/wechat-miniapp/tsconfig.json'}),bundle=b.outputFiles[0]!.text;
 files.push(...Object.keys(b.metafile!.inputs).filter(p=>!p.startsWith('<')));before=await Promise.all([...new Set(files)].map(bind));await write('inputs-before.json',{before,metafile:b.metafile});await fs.writeFile(path.join(out,'executable.js'),bundle,{flag:'wx'});
 const {chromium}=createRequire(import.meta.url)('C:/Users/777/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader']});const page=await browser.newPage({viewport:{width:96,height:128}}),errors:string[]=[];page.on('pageerror',(e:any)=>errors.push(String(e)));await page.setContent('<canvas width="96" height="128"></canvas>');await page.addScriptTag({content:bundle});
 const onlyPost=process.argv.includes('--post-only');const actual=await page.evaluate((i:any)=>(globalThis as any).contributionLifetimeTrial.run(i),{...input,onlyPost}),captures=[];for(const c of actual.captures){await fs.writeFile(path.join(out,c.name+'.rgba'),Buffer.from(c.rgba,'base64'),{flag:'wx'});await fs.writeFile(path.join(out,c.name+'.png'),Buffer.from(c.png.split(',')[1],'base64'),{flag:'wx'});captures.push({name:c.name,width:c.width,height:c.height,raw:await bind(rel+'/'+c.name+'.rgba'),png:await bind(rel+'/'+c.name+'.png')});}
 await write('actual.json',{...actual,captures,errors,onlyPost});after=await Promise.all(before.map(p=>bind(p.path)));let normalFaultPixels:any=null,postDrawPixels:any=null;
 if(!onlyPost){const base=await fs.readFile(path.join(out,'base.rgba')),faulted=await fs.readFile(path.join(out,'read-failure.rgba'));let unequal=0;for(let i=0;i<base.length;i++)if(base[i]!==faulted[i])unequal++;normalFaultPixels={bytes:base.length,unequal,pass:unequal===0&&base.length===faulted.length};}
 else{const pixels=await fs.readFile(path.join(out,'postdraw.rgba'));let unequal=0;for(let y=0;y<128;y++)for(let x=0;x<96;x++)for(let c=0;c<4;c++){const expected=c===3?255:y>=120?[4,8,16][c]:255;if(pixels[(y*96+x)*4+c]!==expected)unequal++;}postDrawPixels={bytes:pixels.length,unequal,pass:unequal===0,scope:'actual full opaque white normalized-UV transform plus top-eight navigation background'};}
 const allPassed=actual.failure===null&&errors.length===0&&actual.checks.every((x:any)=>x.pass)&&JSON.stringify(before)===JSON.stringify(after)&&(onlyPost?postDrawPixels.pass:normalFaultPixels.pass);await write('result.json',{before,after,actual:await bind(rel+'/actual.json'),bundle:{bytes:Buffer.byteLength(bundle),sha256:sha(bundle)},normalFaultPixels,postDrawPixels,allPassed,scope:actual.scope});
 console.log(JSON.stringify({result:await bind(rel+'/result.json'),allPassed,failure:actual.failure,failed:actual.checks.filter((x:any)=>!x.pass),final:actual.final}));assert(allPassed,'lifetime affected checks failed; observations retained');
}catch(e){await write('failed.json',{error:String(e),before,after});throw e;}finally{await browser?.close();}
