/** Independent saved production-receipt outputs only. No browser or GL execution. */
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {inflateSync} from 'node:zlib';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import ts from 'typescript';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),DIR='output/playwright/cloud-sky-contribution-receipt-1002-r1',OUT='output/contribution-receipt-independent-1002-r2';assert(!fs.existsSync(path.join(ROOT,OUT)));fs.mkdirSync(path.join(ROOT,OUT));
const read=(p:string)=>fs.readFileSync(path.join(ROOT,p)),hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),bind=(p:string)=>{const b=read(p);return{path:p,bytes:b.length,sha256:hash(b)};},json=(p:string)=>JSON.parse(read(p).toString('utf8')),save=(p:string,v:any)=>fs.writeFileSync(path.join(ROOT,OUT,p),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,OUT,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
const result=json(DIR+'/result.json'),before=json(DIR+'/inputs-before.json'),after=json(DIR+'/inputs-after.json');assert.equal(bind(DIR+'/result.json').sha256,'509cb3ef5e67e6d7244d42eb7cd8d2bb341f6ad2599c0a7c0ef911cf5d8ab164');assert.deepEqual(result.before,result.after);assert.deepEqual(before.before,result.before);assert.deepEqual(after.after,result.before);assert.equal(after.unchanged,true);
const inventory=fs.readdirSync(path.join(ROOT,DIR)).map(n=>bind(DIR+'/'+n));
for(const b of before.bundles){assert.equal(hash(read(DIR+'/'+b.variant+'.js')),b.bundleBinding.sha256);assert.equal(read(DIR+'/'+b.variant+'.js').length,b.bundleBinding.bytes);for(const p of Object.keys(b.metafile.inputs)){assert(!p.startsWith('<'));const q=path.relative(ROOT,path.resolve(ROOT,p)).replaceAll('\\','/');assert(q&&!q.startsWith('..')&&!path.isAbsolute(q));assert(result.before.some((v:any)=>v.path===q),'unbound graph '+q);}}
const decoder='output/contribution-fbo-independent-1002-r2/executed-script.mts.txt',ast=ts.createSourceFile('independent.ts',read(decoder).toString('utf8'),ts.ScriptTarget.Latest,true),nodes=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='png'||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>d.name.getText(ast)==='crc32'));assert.equal(nodes.length,2);const decode=vm.runInNewContext(ts.transpileModule(nodes.map(n=>n.getText(ast)).join('\n')+'\npng;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,{read,inflateSync,Buffer,assert});
const captures:any[]=[],variantResults:any[]=[],allLedgers:any[]=[];
const stats=(raw:Buffer)=>{let rgbNonBackground=0;const max=[0,0,0,0],nonzero=[0,0,0,0];for(let i=0;i<raw.length;i++){max[i%4]=Math.max(max[i%4]!,raw[i]!);if(raw[i])nonzero[i%4]++;if(i%4===0&&(raw[i]!==4||raw[i+1]!==8||raw[i+2]!==16))rgbNonBackground++;}return{max,nonzero,rgbNonBackground};};
for(const variant of ['before-attribute-repair','current']){const v=json(DIR+'/'+variant+'.json');assert.deepEqual(bind(result.observations.find((b:any)=>b.path.endsWith('/'+variant+'.json')).path),result.observations.find((b:any)=>b.path.endsWith('/'+variant+'.json')));assert.equal(v.failure,null);assert.deepEqual(v.pageErrors,[]);
 for(const c of v.captures){assert.deepEqual(bind(c.raw.path),c.raw);assert.deepEqual(bind(c.png.path),c.png);const raw=read(c.raw.path),image=decode(c.png.path);assert.equal(raw.length,c.width*c.height*4);assert.equal(image.w,c.width);assert.equal(image.h,c.height);for(let y=0;y<image.h;y++)assert(image.rgba.subarray(y*image.w*4,(y+1)*image.w*4).equals(raw.subarray((image.h-1-y)*image.w*4,(image.h-y)*image.w*4)));captures.push({variant,name:c.name,width:c.width,height:c.height,rgbaBytes:raw.length,pngAllPixelsExactYflip:true,...stats(raw)});}
 const live=new Map<number,{kind:string,bytes:number}>(),ledger:any[]=[],sample:any[]=[],resources=()=>{const counts:any={texture:0,framebuffer:0,buffer:0,program:0,shader:0};let logicalTextureBytes=0;for(const a of live.values()){counts[a.kind]++;logicalTextureBytes+=a.bytes;}return{counts,logicalTextureBytes};};let peak=0,normalDraws=0,signalDraws=0,reductionDraws=0,readbacks=0;
 for(let i=0;i<v.events.length;i++){const e=v.events[i];if(e.event==='create'){assert(!live.has(e.id));live.set(e.id,{kind:e.kind,bytes:0});}else if(e.event==='delete'){assert(live.has(e.id),'delete unknown '+e.id);assert.equal(live.get(e.id)!.kind,e.kind);assert.equal(live.get(e.id)!.bytes,e.bytes);live.delete(e.id);}else if(e.event==='allocate'||e.event==='copy'){assert(live.has(e.id));assert.equal(live.get(e.id)!.kind,'texture');if(e.event==='allocate')assert.equal(e.bytes,e.w*e.h*4);live.get(e.id)!.bytes=e.bytes;}else if(e.event==='draw'){assert(live.has(e.program)&&live.get(e.program)!.kind==='program');if(e.framebuffer!==null)assert(live.has(e.framebuffer)&&live.get(e.framebuffer)!.kind==='framebuffer');if(e.framebuffer===null)normalDraws++;else if(e.signal)signalDraws++;else reductionDraws++;}else if(e.event==='read'){readbacks++;assert.equal(e.w,1);assert.equal(e.h,1);}peak=Math.max(peak,resources().logicalTextureBytes);ledger.push({index:i,phase:e.phase,event:e.event,...resources()});
  for(const row of v.rows){if(i+1===row.eventsTo){assert.deepEqual(resources(),row.resources);const p=Math.max(...ledger.slice(row.eventsFrom,i+1).map(x=>x.logicalTextureBytes));assert.equal(p,row.peakLogicalTextureBytes);sample.push({name:row.name,at:i+1,...resources(),peakLogicalTextureBytes:p});}}
 }
 assert.deepEqual(resources().counts,v.final.counts);assert.equal(resources().logicalTextureBytes,v.final.logicalTextureBytes);assert(Object.values(v.final.counts).every(n=>n===0));assert.equal(v.final.logicalTextureBytes,0);assert.equal(v.final.glError,0);assert.equal(v.final.contextLost,false);
 const stateChecks=v.checks.filter((c:any)=>c.name.endsWith('state-restored'));assert(stateChecks.length>0);for(const c of stateChecks){assert.deepEqual(c.details.normal,c.details.after,c.name);assert.equal(c.pass,true);}
 const retirement=v.checks.filter((c:any)=>c.name.endsWith('.retired-no-credit'));for(const c of retirement){assert.equal(c.details.completed,false);assert.equal(c.details.finePhoto,'unknown');assert.equal(c.details.coarsePhoto,'unknown');}
 allLedgers.push({variant,ledger});variantResults.push({variant,events:v.events.length,peakLogicalTextureBytes:peak,normalDraws,signalDraws,reductionDraws,onePixelReads:readbacks,rowCheckpoints:sample,stateChecks:stateChecks.length,retirementChecks:retirement.length,final:resources()});
}
const current=json(DIR+'/current.json'),row=(n:string)=>current.rows.find((r:any)=>r.name===n),raw=(n:string)=>read(current.captures.find((c:any)=>c.name===n).raw.path);
const comparisons=[];for(const n of ['plain-pair','budget-rejected','signal-compile','fbo-initial','fbo-chain']){assert(raw('disabled').equals(raw(n)));comparisons.push({a:'disabled',b:n,allBytesEqual:true,bytes:raw(n).length});}assert(raw('high-dpr-disabled').equals(raw('high-dpr')));comparisons.push({a:'high-dpr-disabled',b:'high-dpr',allBytesEqual:true,bytes:raw('high-dpr').length});assert(read(DIR+'/before-attribute-repair.real-pair.rgba').equals(raw('real-pair')));
const plan=(w:number,h:number,g:number)=>{let scratch=0,W=w,H=h;while(W>1||H>1){W=Math.ceil(W/2);H=Math.ceil(H/2);scratch+=W*H*4;}return{signal:w*h*4,scratch,total:w*h*4*g+scratch};};for(const r of current.rows)assert.deepEqual(r.plan,plan(r.physical[0],r.physical[1],['multi-group','group-limit'].includes(r.name)?2:1));assert.equal(row('high-dpr').plan.total,15803512);
const unknown={completed:false,qualification:{fine:'unknown',coarse:'unknown',any:'unknown'},finePhoto:'unknown',coarsePhoto:'unknown'};for(const n of ['disabled','budget-rejected','signal-compile','fbo-initial','fbo-chain'])assert.deepEqual(row(n).result,unknown);for(const n of ['signal-compile','fbo-initial','fbo-chain']){assert.equal(row(n).injected,true);assert.equal(row(n).recovered.completed,true);assert.equal(row(n).recovered.finePhoto,'positive');const e=current.events.filter((e:any)=>e.phase===n+'.latched');assert(!e.some((e:any)=>e.event==='draw'&&e.signal));assert(!e.some((e:any)=>e.event==='allocate'&&e.w===96&&e.h===128));}
assert.equal(row('normal-gl-error').result.completed,false);assert(row('normal-gl-error').error.includes('sky_gpu_draw_failed'));assert.deepEqual(row('black-fine').qualification,{fine:'has',coarse:'empty',any:'has'});assert.deepEqual(row('black-coarse').qualification,{fine:'empty',coarse:'has',any:'has'});for(const n of ['black-fine','black-coarse']){assert.equal(row(n).result.finePhoto,'unknown');assert.equal(row(n).result.coarsePhoto,'unknown');assert(raw(n).equals(raw('joint-empty')));}
assert.deepEqual(row('joint-empty').qualification,{fine:'empty',coarse:'empty',any:'empty'});assert.deepEqual(row('joint-partial').qualification,{fine:'has',coarse:'has',any:'has'});assert.equal(row('joint-partial').result.finePhoto,'positive');assert.equal(row('joint-partial').result.coarsePhoto,'positive');assert.equal(row('multi-group').result.finePhoto,'unknown');assert.equal(row('multi-group').secondResult.finePhoto,'positive');assert.equal(row('group-limit').secondQualification.any,'unknown');assert.equal(row('group-limit').result.finePhoto,'unknown');assert(raw('multi-group').equals(raw('group-limit')));
const context=current.checks.filter((c:any)=>c.name.startsWith('actual-context')||c.name==='restored-new-owner-no-stale-token');assert.equal(context.length,3);for(const c of context)assert.equal(c.pass,true);assert.equal(context[0].details.receipt.completed,false);assert(context[0].details.error.includes('sky_gpu_context_lost'));
assert.equal(result.witness.beforeFailed,false);assert.equal(result.witness.afterPositive,true);const currentQualification=result.before.map((v:any)=>({executed:v,current:bind(v.path),same:JSON.stringify(v)===JSON.stringify(bind(v.path))}));const six=json('.codex/work-items/cloud-sky-native-2026-09-22/tmp/resume-preserved-hashes-2026-10-01.json');for(const p of six)assert.equal(bind(p.path).sha256,p.sha256);
assert.deepEqual(inventory.map(b=>bind(b.path)),inventory);save('recomputed-ledgers.json',allLedgers);save('binding.json',{outputInventoryBefore:inventory,outputInventoryAfter:inventory.map(b=>bind(b.path)),actualExecutedBeforeAfter:result.before,actualDependencyGraphInputs:before.bundles.map((b:any)=>({variant:b.variant,count:Object.keys(b.metafile.inputs).length})),currentQualification,independentDecoder:bind(decoder),preservedSix:six});
save('result.json',{status:'INDEPENDENT_HISTORICAL_2182203_RECEIPT_READBACK_WITH_GETTER_GAP_OPEN',actualResult:bind(DIR+'/result.json'),captures,comparisons,variants:variantResults,fullPhysicalPlans:current.rows.map((r:any)=>({name:r.name,physical:r.physical,plan:r.plan})),facts:{defaultAuxiliaryReads:current.events.slice(row('disabled').eventsFrom,row('disabled').eventsTo).filter((e:any)=>e.event==='read').length,unknownNotEmptyOnRefusalOrFault:true,validBlackQualificationIndependentOfPhoto:true,partialSelectsBothReported:true,laterUnprobedGroupStillAttenuatesEarlier:true,normalErrorPropagates:true,actualLossBeforeFinishAndReconstruction:true,beforeAttributeWitnessFailed:false,beforeAttributeNormalImageExactAfter:true},limitations:['New private FBO full/intermediate RGBA is not exported: cannot independently reconstruct new qualification/photo maxima from saved signal texels. Independently decoded normal pixels and identity/resource/state checkpoints do not replace that missing signal array.','Actual new draw events omit sampler/uniform/VBO receipts; same prepared objects are traced from source owner, not a second native setter readback.','Context loss here occurs before finish. Independent pure controlled owner exposed completed getter currentness gap after finish; remains open pending repair.','No generic mathematical NONE/post-clamp RGB delta, normal science/W3/page credit, driver/native memory/FPS/quality/adoption is certified.']});console.log(JSON.stringify({result:bind(OUT+'/result.json'),binding:bind(OUT+'/binding.json')}));
