/** Pure controlled-GL lifecycle replay. No shader execution, GPU, or pixels claimed. */
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import ts from 'typescript';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),OUT='output/contribution-getter-lifetime-independent-1002-r2';assert(!fs.existsSync(path.join(ROOT,OUT)));fs.mkdirSync(path.join(ROOT,OUT));
const owner='apps/wechat-miniapp/src/features/sky/sky-gpu-artwork-contributions.ts',composition='apps/wechat-miniapp/src/features/sky/sky-artwork-level-composition.ts';
const hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),read=(p:string)=>fs.readFileSync(path.join(ROOT,p)),bind=(p:string)=>{const b=read(p);return{path:p,bytes:b.length,sha256:hash(b)};};
const before=[owner,composition].map(bind),source=read(owner).toString('utf8');assert.equal(before[0]!.sha256,'87467f231b709599befc57113e30d4c69c3d34d8782a95c1ecdeb2505b61c4dc');
fs.writeFileSync(path.join(ROOT,OUT,'owner-before.ts.txt'),source,{flag:'wx'});fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,OUT,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
const compile=(s:string)=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const compositionExports:any={};vm.runInNewContext(compile(read(composition).toString('utf8')),{exports:compositionExports});
const exports:any={};vm.runInNewContext(compile(source),{exports,Float32Array,Uint8Array,require:(p:string)=>{if(p==='twgl.js')return{createProgramInfoFromProgram:(_gl:any,program:any)=>({program}),setBuffersAndAttributes:()=>{},setUniforms:()=>{},drawBufferInfo:()=>{}};if(p==='./sky-artwork-level-composition')return compositionExports;throw Error('unexpected_import:'+p);}});
function controlledGl(){let id=0,lost=false,contextQueries=0;const codes=new Map<string,number>([['NO_ERROR',0],['ZERO',0],['ONE',1]]);let code=100;const C=(n:string)=>{if(!codes.has(n))codes.set(n,code++);return codes.get(n)!;};const attr={id:-1},live=new Map<any,string>();
 const create=(kind:string)=>{const o={id:++id};live.set(o,kind);return o;},remove=(o:any)=>live.delete(o);
 const state:any={drawingBufferWidth:1,drawingBufferHeight:1,getError:()=>0,isContextLost:()=>{contextQueries++;return lost;},isEnabled:()=>false,getAttribLocation:()=>0,
  getParameter:(n:number)=>{const key=[...codes].find(x=>x[1]===n)?.[0];switch(key){case 'FRAMEBUFFER_BINDING':case 'CURRENT_PROGRAM':case 'TEXTURE_BINDING_2D':return null;case 'COLOR_WRITEMASK':return[true,true,true,true];case 'MAX_TEXTURE_SIZE':return 4096;case 'MAX_VIEWPORT_DIMS':return[4096,4096];case 'VIEWPORT':case 'SCISSOR_BOX':return[0,0,1,1];case 'ARRAY_BUFFER_BINDING':return attr;case 'ACTIVE_TEXTURE':return C('TEXTURE0');case 'MAX_VERTEX_ATTRIBS':return 1;case 'COLOR_CLEAR_VALUE':return[0,0,0,0];case 'BLEND_SRC_RGB':case 'BLEND_SRC_ALPHA':return 1;case 'BLEND_DST_RGB':case 'BLEND_DST_ALPHA':return 0;case 'BLEND_EQUATION_RGB':case 'BLEND_EQUATION_ALPHA':return C('FUNC_ADD');default:throw Error('unexpected_parameter:'+key);}},
  getVertexAttrib:(_i:number,n:number)=>{if(n===C('VERTEX_ATTRIB_ARRAY_BUFFER_BINDING'))return attr;if(n===C('VERTEX_ATTRIB_ARRAY_SIZE'))return 2;if(n===C('VERTEX_ATTRIB_ARRAY_TYPE'))return C('FLOAT');if(n===C('VERTEX_ATTRIB_ARRAY_ENABLED'))return true;return 0;},getVertexAttribOffset:()=>0,
  getShaderParameter:()=>true,getProgramParameter:()=>true,checkFramebufferStatus:()=>C('FRAMEBUFFER_COMPLETE'),readPixels:(_x:number,_y:number,_w:number,_h:number,_f:number,_t:number,b:Uint8Array)=>b.set([10,0,255,0]),
  createProgram:()=>create('program'),createShader:()=>create('shader'),createBuffer:()=>create('buffer'),createTexture:()=>create('texture'),createFramebuffer:()=>create('framebuffer'),deleteProgram:remove,deleteShader:remove,deleteBuffer:remove,deleteTexture:remove,deleteFramebuffer:remove};
 for(const name of ['activeTexture','bindTexture','bindFramebuffer','viewport','useProgram','bindBuffer','vertexAttribPointer','enableVertexAttribArray','disableVertexAttribArray','enable','disable','blendFuncSeparate','blendEquationSeparate','scissor','colorMask','clearColor','shaderSource','compileShader','attachShader','bindAttribLocation','linkProgram','detachShader','texParameteri','texImage2D','framebufferTexture2D','bufferData','drawArrays','clear'])state[name]=()=>{};
 const gl=new Proxy(state,{get(t,p){if(p in t)return t[p];if(typeof p==='string'&&/^[A-Z0-9_]+$/.test(p))return C(p);throw Error('unexpected_gl:'+String(p));}});
 return{gl,lose:()=>{lost=true;},contextQueries:()=>contextQueries,live:()=>live.size};}
const rows=[];
for(const change of ['context-loss-after-finish','resize-after-finish']){const m=controlledGl(),o=exports.createSkyGpuArtworkContributions(m.gl,{auxiliaryBytesLimit:4,maxGroups:1}),draw=Object.freeze({submitted:true,finePrepared:true,coarsePrepared:false});o.begin();o.capture(draw,{program:{program:{}},buffer:{},primitive:4,uniforms:{},vertex:'void main(){}',cameraRay:''});o.finish();const original=JSON.parse(JSON.stringify(o.contribution(draw)));assert.equal(original.completed,true);assert.equal(original.finePhoto,'positive');const queries=m.contextQueries();if(change.startsWith('context'))m.lose();else m.gl.drawingBufferWidth=2;const after=JSON.parse(JSON.stringify(o.contribution(draw))),qualification=JSON.parse(JSON.stringify(o.qualification(draw)));assert.equal(after.completed,false);assert.equal(after.finePhoto,'unknown');assert.equal(qualification.any,'unknown');rows.push({change,original,after,qualification,getterContextQueries:m.contextQueries()-queries,completedCreditRemains:after.completed&&after.finePhoto==='positive',controlledReadback:[10,0,255,0],scope:'Real unchanged owner, controlled GL method results and TWGL calls. Tests API currentness only; no rendered-pixel/native proof.'});o.dispose();assert.equal(m.live(),0);}
const after=before.map(b=>bind(b.path));assert.deepEqual(after,before);const result={status:'INDEPENDENT_CONTROLLED_API_LIFETIME_FIX_VERIFIED',rows,inputsBefore:before,inputsAfter:after,scope:'Only exact completed-token getter gap. Readback is explicit fixture, not real pixels; no production edits/GPU/network.'};fs.writeFileSync(path.join(ROOT,OUT,'result.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(bind(OUT+'/result.json')));
