/** Exact readonly joins plus one older-pose/duplicate acceptance control. No GPU. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import ts from 'typescript';
import {drawSkyScene} from '../../../../apps/wechat-miniapp/src/features/sky/sky-scene-render';
import {createSkyCanvasLifecycle} from '../../../../apps/wechat-miniapp/src/features/sky/sky-canvas-lifecycle';
import {copySkyDeepAuxiliaryDecisions,sameSkyDeepAuxiliaryDecisions} from '../../../../apps/wechat-miniapp/src/features/sky/sky-deep-auxiliary-visibility';
import {liveSkyOpticalCompletion,sameSkyOpticalCompletion,sameSkyOpticalInput} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-completion';
import {resolvedSkyBodyReferences} from '../../../../apps/wechat-miniapp/src/features/sky/sky-body-label-presentation';
import {createSkyViewBasis} from '../../../../apps/wechat-miniapp/src/features/sky/sky-view-projection';
const ROOT=path.resolve(fileURLToPath(new URL('../../../../',import.meta.url))),OUT=path.join(ROOT,'output/common-opacity-independent-closure-1002-r1'),sky='apps/wechat-miniapp/src/features/sky/';assert(!fs.existsSync(OUT));fs.mkdirSync(OUT);
const read=(p:string)=>fs.readFileSync(path.resolve(ROOT,p)),json=(p:string)=>JSON.parse(read(p).toString('utf8')),sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const bind=(p:string)=>{const a=path.resolve(ROOT,p),b=fs.readFileSync(a);return{path:path.relative(ROOT,a).replaceAll('\\','/'),bytes:b.length,sha256:sha(b)};};const save=(n:string,v:any)=>fs.writeFileSync(path.join(OUT,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(OUT,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
const main='output/common-opacity-independent-1002-r2',extra='output/common-opacity-independent-addendum-1002-r2',author='output/common-preaid-opacity-owner-1002-r1';
const beforeSets=[json(main+'/binding-before.json'),json(extra+'/binding-before.json')];const paths=new Set<string>(beforeSets.flatMap(rows=>rows.map((v:any)=>v.path)));
const authorBindings=json(author+'/source-bindings.json');for(const entry of authorBindings.bindings){paths.add(entry.path);if(entry.executionCopy)paths.add(entry.executionCopy);}
for(const folder of [main,extra,author,'output/common-opacity-independent-1002-r1','output/common-opacity-independent-addendum-1002-r1'])for(const f of fs.readdirSync(path.resolve(ROOT,folder)))if(fs.statSync(path.resolve(ROOT,folder,f)).isFile())paths.add(folder+'/'+f);
paths.add(path.relative(ROOT,fileURLToPath(import.meta.url)).replaceAll('\\','/'));paths.add('.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-pre-aid-common-opacity-development-2026-10-02.md');
const before=[...paths].sort().map(bind);save('binding-before.json',before);
try{
  for(const rows of beforeSets)for(const entry of rows)assert.deepEqual(bind(entry.path),entry);
  for(const folder of [main,extra])assert.deepEqual(json(folder+'/binding-before.json'),json(folder+'/binding-after.json'));
  let copied=0;for(const entry of authorBindings.bindings){const current=bind(entry.path);assert.equal(current.bytes,entry.bytes);assert.equal(current.sha256,entry.sha256);if(entry.executionCopy){const copy=bind(entry.executionCopy);assert.equal(copy.bytes,entry.bytes);assert.equal(copy.sha256,entry.sha256);copied++;}}
  assert.equal(copied,15);const checks=read(author+'/checks.log').toString('utf8');assert(/tests 59/.test(checks)&&/pass 59/.test(checks)&&/fail 0/.test(checks));const mutant=read(author+'/equality-mutant.log').toString('utf8');assert(mutant.includes('notStrictEqual'));assert.equal(json(author+'/typecheck-result.json').exitCode,0);
  const helperSource=ts.createSourceFile('base.mts',read(main+'/executed-script.mts.txt').toString('utf8'),ts.ScriptTarget.Latest,true),helperNames=['parse','optical','surface','harness'];const helpers=helperSource.statements.filter(n=>ts.isFunctionDeclaration(n)&&helperNames.includes(n.name!.text));assert.equal(helpers.length,4);
  const report=json('.codex/work-items/cloud-sky-native-2026-09-22/tmp/current-native-report-2026-10-01.json').data,prepared=json('output/playwright/cloud-sky-science-scene-1002-r3/prepared-input.json'),basis=json('output/playwright/cloud-sky-science-scene-1002-r3/observations.json').basis,pageText=read(sky+'spot-sky-page.tsx').toString('utf8');
  const env:any={assert,ts,vm,report,at:prepared.at,basis,fine:{},drawSkyScene,createSkyCanvasLifecycle,copySkyDeepAuxiliaryDecisions,sameSkyDeepAuxiliaryDecisions,liveSkyOpticalCompletion,sameSkyOpticalCompletion,sameSkyOpticalInput,resolvedSkyBodyReferences};const context=vm.createContext(env);
  vm.runInContext(ts.transpileModule(helpers.map(n=>n.getText(helperSource)).join('\n')+'\nthis.parse=parse;this.harness=harness;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);env.ast=env.parse(pageText);
  const h=env.harness();h.queue();const firstSnapshot=h.scenes[0].snapshot,oldDone=h.attempts[0],newView=createSkyViewBasis(0,130,0)!;
  h.env.resolveSkyCanvasView=()=>({verticalFovDeg:2.8,progress:1,center:{x:195,y:422},localView:newView,intent:'manual'});h.env.browsingCamera.update=(x:any)=>({view:x.localView,animating:false});h.lifecycle.request({...h.frame,pose:{basis:newView}});
  oldDone();assert.strictEqual(h.state.camera.basis,basis);assert.deepEqual(h.state.frame.deepSkyAuxiliaryDecisions,firstSnapshot.deepSkyAuxiliaryDecisions);assert.notStrictEqual(h.state.frame.deepSkyAuxiliaryDecisions,firstSnapshot.deepSkyAuxiliaryDecisions);
  h.step();const second=h.scenes[1].snapshot;h.complete();assert.strictEqual(h.state.camera.basis,newView);assert.deepEqual(h.state.frame.deepSkyAuxiliaryDecisions,second.deepSkyAuxiliaryDecisions);const accepted=h.state.frame;oldDone();h.complete();assert.strictEqual(h.state.frame,accepted);assert.equal(h.state.inspections.length,2);h.lifecycle.dispose();
  const calls:any={opticalHook:[],scene:[],rendererOptions:[],artworkContributionsProperties:0};function walk(n:ts.Node){if(ts.isCallExpression(n)){const name=n.expression.getText(env.ast.source);if(name==='useSkySdssOptical')calls.opticalHook.push(n.arguments.length);if(name==='drawSkyScene')calls.scene.push(n.arguments.length);if(name==='createSkyGpuRenderer')calls.rendererOptions.push(n.arguments[2]?.getText(env.ast.source)??null);}if(ts.isPropertyAssignment(n)&&n.name.getText(env.ast.source)==='artworkContributions')calls.artworkContributionsProperties++;ts.forEachChild(n,walk);}walk(env.ast.source);
  assert.deepEqual(calls.opticalHook,[5]);assert.deepEqual(calls.scene,[36]);assert.equal(calls.artworkContributionsProperties,0);save('normal-page-callers.json',calls);
  const after=before.map(x=>bind(x.path));assert.deepEqual(after,before);save('binding-after.json',after);save('result.json',{status:'INDEPENDENT_COMMON_OPACITY_CURRENT_SOURCE_CLOSURE_PASSED',bindings:before.length,joins:{main:beforeSets[0].length,addendum:beforeSets[1].length,author:authorBindings.bindings.length,authorExactSourceCopies:copied},actualAdditionalControl:{olderPoseAcceptedOwnViewAndDecisions:true,separateFrozenPageCopy:true,newPoseAcceptedOwnRecords:true,duplicateOldAndNewCompletionCannotRewrite:true,acceptedPackets:2},normalDefault:calls,authorReadback:{focusedChecks:59,typecheck:'author silent actual exit0 saved after observation',equalityMutant:'actual log useful failure, independent own mutation separately passed'},limits:['No GPU/network/native/IDE or author59/TSC rerun.','Author tests use controlled 11-arcmin catalog, partial legacy metadata fixture; independent main/addendum use cached real 13.71-arcmin M51/report.', 'Main r1 preflight axis guess and addendum r1 missing fixture setter are preserved failures; neither is a production defect.', 'Toolchain identity is prebound for addendum r2 only, not retrospective build reproduction for main r2.', 'No new local readability rule, default science route, target-runtime behavior or quality/complete experience certification.']});console.log(JSON.stringify({result:bind(path.join(OUT,'result.json')),binding:bind(path.join(OUT,'binding-before.json'))}));
}catch(error){save('failed.json',{error:String(error),stack:(error as Error).stack,before});throw error;}
