/** Saved uniforms/source pixels → independent numeric diagnostic; no WebGL. */
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import {inflateSync} from 'node:zlib';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),DIR='output/playwright/cloud-sky-contribution-fbo-1002-r1',OUT='output/contribution-fbo-selection-independent-1002-r1';assert(!fs.existsSync(path.join(ROOT,OUT)));fs.mkdirSync(path.join(ROOT,OUT));
const read=(p:string)=>fs.readFileSync(path.join(ROOT,p)),hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),bind=(p:string)=>{const b=read(p);return{path:p,bytes:b.length,sha256:hash(b)};},json=(p:string)=>JSON.parse(read(p).toString('utf8'));
const raw=json(DIR+'/actual-raw.json'),prepared=json(DIR+'/prepared-input.json'),receipt=json(DIR+'/result.json');
const decoder='output/contribution-fbo-independent-1002-r2/executed-script.mts.txt',ast=ts.createSourceFile('independent.ts',read(decoder).toString('utf8'),ts.ScriptTarget.Latest,true);const nodes=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='png'||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>d.name.getText(ast)==='crc32'));assert.equal(nodes.length,2);const decode=vm.runInNewContext(ts.transpileModule(nodes.map(n=>n.getText(ast)).join('\n')+'\npng;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,{read,inflateSync,Buffer,assert});
const frozen=read(DIR+'/renderer-original.ts').toString('utf8'),rendererAst=ts.createSourceFile('renderer.ts',frozen,ts.ScriptTarget.Latest,true);const find=(name:string)=>rendererAst.statements.filter(ts.isVariableStatement).flatMap(s=>Array.from(s.declarationList.declarations)).find(d=>d.name.getText(rendererAst)===name)!.initializer!.getText(rendererAst);const skyRay=vm.runInNewContext(find('skyRay'));
const owner='apps/wechat-miniapp/src/features/sky/sky-artwork-level-composition.ts';assert.equal(bind(owner).sha256,receipt.before.find((b:any)=>b.path===owner).sha256);const exports:any={};vm.runInNewContext(ts.transpileModule(read(owner).toString('utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports});assert.equal(exports.skyArtworkLevelsFragment(skyRay),raw.shaders.actualFragment);
const sourceInputs=Object.entries(prepared.product.levels).filter(([level])=>['OVERVIEW','MEDIUM'].includes(level)).map(([level,asset]:any)=>{const found=receipt.before.find((p:any)=>p.sha256===asset.sha256&&p.bytes===asset.bytes);assert(found);const image=decode(found.path);assert.equal(image.w,512);assert.equal(image.h,512);let non255=0;for(let i=3;i<image.rgba.length;i+=4)if(image.rgba[i]!==255)non255++;assert.equal(non255,0);return{level,path:found.path,image};});
const rgba=(name:string)=>read(DIR+'/'+name+'.rgba');
const cpuRows:any[]=[];
for(const row of raw.rows.filter((v:any)=>v.condition)){const group=row.groupCaptures[0],u=Object.fromEntries(group.uniforms.map((v:any)=>[v.name,v.value])),actual=rgba(row.condition.name+'.group.signal');const modelRows=[];
 for(const precision of ['float64-on-actual-f32-uniforms','explicit-nonFMA-fround']){const F=precision.startsWith('float64')?(n:number)=>n:Math.fround,add=(a:number,b:number)=>F(F(a)+F(b)),mul=(a:number,b:number)=>F(F(a)*F(b)),div=(a:number,b:number)=>F(F(a)/F(b)),dot=(a:number[],b:number[])=>add(add(mul(a[0]!,b[0]!),mul(a[1]!,b[1]!)),mul(a[2]!,b[2]!));let mismatchedSelection=0,maxPhotoByteDelta=0,photoByteDifferences=0,fineCount=0,coarseCount=0,noneCount=0;const firstMismatch:any[]=[];
  const sample=(name:string,ray:number[])=>{if(u['u_'+name+'Ready']<.5)return null;const c=[0,1,2].map(i=>dot(u['u_'+name+'Row'+i],ray)),sum=add(add(c[0]!,c[1]!),c[2]!);if(Math.abs(sum)<1e-7||div(u['u_'+name+'Determinant'],sum)<=0)return null;const uv=[div(dot(c,u['u_'+name+'AnchorU']),sum),div(dot(c,u['u_'+name+'AnchorV']),sum)];if(uv.some(v=>v<0||v>1))return null;const sampler=group.samplers.find((s:any)=>s.name==='u_'+name+'Image'),source=sampler.binding.source;if(source.startsWith('task-valid-black'))return{rgb:[0,0,0],uv};const image=sourceInputs.find(v=>v.level===source)!.image,b=sampler.binding,x0=b.x??0,y0=b.y??0,W=b.width,H=b.height;const coordinates=uv.map((v,i)=>mul(F(v-u['u_'+name+'Origin'][i]),u['u_'+name+'Scale'][i]));const sx=coordinates[0]!*W-.5,sy=coordinates[1]!*H-.5,left=Math.floor(sx),low=Math.floor(sy),tx=sx-left,ty=sy-low;const rgb=[0,1,2].map(channel=>{const tex=(x:number,y:number)=>image.rgba[((Math.max(0,Math.min(H-1,y))+y0)*512+Math.max(0,Math.min(W-1,x))+x0)*4+channel]/255;return(tex(left,low)*(1-tx)+tex(left+1,low)*tx)*(1-ty)+(tex(left,low+1)*(1-tx)+tex(left+1,low+1)*tx)*ty;});return{rgb,uv};};
  for(let y=0;y<128;y++)for(let x=0;x<96;x++){const pixel=[x+.5,128-y-.5],p=[div(F(pixel[0]-u.u_center[0]),u.u_scale),F(-div(F(pixel[1]-u.u_center[1]),u.u_scale))],square=dot([p[0]!,p[1]!,0],[p[0]!,p[1]!,0]),denom=add(1,square),camera=[div(mul(2,p[0]!),denom),div(mul(2,p[1]!),denom),div(F(1-square),denom)],ray=[0,1,2].map(i=>add(add(mul(u.u_right[i],camera[0]!),mul(u.u_up[i],camera[1]!)),mul(u.u_forward[i],camera[2]!)));const fine=sample('fine',ray),coarse=fine?null:sample('coarse',ray),selected=fine??coarse,index=(y*96+x)*4;const expectedFine=fine?255:0,expectedAny=selected?255:0;if(fine)fineCount++;else if(coarse)coarseCount++;else noneCount++;if(actual[index+2]!==expectedFine||actual[index+3]!==expectedAny){mismatchedSelection++;if(firstMismatch.length<6)firstMismatch.push({x,y,expectedFine,actualFine:actual[index+2]});}const strength=selected?Math.round(Math.max(...selected.rgb)*u.u_opacity*255):0,expected=[fine?strength:0,coarse?strength:0];for(let c=0;c<2;c++){const delta=Math.abs(expected[c]!-actual[index+c]!);maxPhotoByteDelta=Math.max(maxPhotoByteDelta,delta);if(delta)photoByteDifferences++;}}
  modelRows.push({precision,fineCount,coarseCount,noneCount,mismatchedSelection,maxPhotoByteDelta,photoByteDifferences,firstMismatch,scope:'Diagnostic of this fixed saved 96x128 view. Driver FMA/interpolation/rounding not certified; residuals are retained, no claimed universal GPU error bound.'});}
 cpuRows.push({condition:row.condition.name,sourcePhotoShaderExact:true,models:modelRows});}
const paths=[decoder,owner,DIR+'/result.json',DIR+'/actual-raw.json',DIR+'/prepared-input.json',DIR+'/renderer-original.ts',...sourceInputs.map(v=>v.path),...raw.rows.filter((v:any)=>v.condition).map((v:any)=>DIR+'/'+v.condition.name+'.group.signal.rgba')],before=[...new Set(paths)].map(bind);assert.deepEqual(before.map(v=>bind(v.path)),before);fs.copyFileSync(fileURLToPath(import.meta.url),path.join(ROOT,OUT,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);fs.writeFileSync(path.join(ROOT,OUT,'result.json'),JSON.stringify({status:'INDEPENDENT_SAVED_SELECTION_SHADER_NUMERIC_DIAGNOSTIC',sourceShaderGeneratorAndSavedFragmentExact:true,cpuRows,inputsBefore:before,inputsAfter:before.map(v=>bind(v.path)),scope:'No GPU execution; standalone unchanged production fragment generator and frozen old renderer skyRay only. Current raw-plane registration is never invoked or credited. Numeric residuals preserve floating/interpolation uncertainty, not a new acceptance decision.'},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(bind(OUT+'/result.json')));
