/** Independent saved-output + actual Scene callback review. No GPU/network. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {inflateSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import ts from 'typescript';
import {assertSdssScienceOpticalManifest} from '@starward/miniapp-contracts';
import {drawSkyScene} from '../../../../apps/wechat-miniapp/src/features/sky/sky-scene-render';
import {skySdssOpticalFrame} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-frame';
import {submitSkySceneScienceOptical} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-science-scene';
import {registerSkyScienceOpticalField} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-science-registration';
import {registerSkyNativeImageLifetime,skyNativeImageIsCurrent} from '../../../../apps/wechat-miniapp/src/features/sky/sky-artwork-loader';
import {exactSkyObservationFrame} from '../../../../apps/wechat-miniapp/src/features/sky/sky-observation-frame';

const ROOT=path.resolve(fileURLToPath(new URL('../../../../',import.meta.url)));
const OUT='output/science-scene-independent-1002-r2',folder=path.join(ROOT,OUT);
assert(!fs.existsSync(folder));fs.mkdirSync(folder);
const read=(p:string)=>fs.readFileSync(path.join(ROOT,p)),json=(p:string)=>JSON.parse(read(p).toString('utf8'));
const sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const bind=(p:string)=>{const b=read(p);return{path:p.replaceAll('\\','/'),bytes:b.length,sha256:sha(b)};};
const save=(name:string,value:any)=>fs.writeFileSync(path.join(folder,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(folder,'executed-script.mts.txt'),fs.constants.COPYFILE_EXCL);
const generations=['output/playwright/cloud-sky-science-scene-1002-r3','output/playwright/cloud-sky-science-scene-1002-r4','output/playwright/cloud-sky-science-scene-1002-r5'];
const expectedResults=['f0e62032e24197756c36078e1118d7f9847c4a8a4122c2e7a37291fdf6102d8d',null,'e539a425243b5d7fd590ea265e2cd1f6e1cdf3bf98c52b7ea60128b18b62f6ce'];
const sky='apps/wechat-miniapp/src/features/sky/';
const decoder='output/contribution-fbo-independent-1002-r2/executed-script.mts.txt';
const decoderAst=ts.createSourceFile('independent.ts',read(decoder).toString('utf8'),ts.ScriptTarget.Latest,true);
const decoderNodes=decoderAst.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='png'||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>d.name.getText(decoderAst)==='crc32'));
assert.equal(decoderNodes.length,2);
const png=vm.runInNewContext(ts.transpileModule(decoderNodes.map(n=>n.getText(decoderAst)).join('\n')+'\npng;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,{read,inflateSync,Buffer,assert});
const publicationPath='output/sdss-science-optical-writer-1002-r1/publication/manifest.json';
const freeze=(x:any):any=>{if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};
const publication=freeze(json(publicationPath));assertSdssScienceOpticalManifest(publication,'M:51',publication.publicationHash);
const reportPath='.codex/work-items/cloud-sky-native-2026-09-22/tmp/current-native-report-2026-10-01.json';
const report=json(reportPath).data,prepared=json(generations[0]+'/prepared-input.json');
const observation=exactSkyObservationFrame(report,prepared.at);assert(observation);
const historicalInventories=generations.flatMap(d=>fs.readdirSync(path.join(ROOT,d)).map(n=>bind(d+'/'+n)));
const generationsReadback:any[]=[],controls:any[]=[],mutations:any[]=[];let before:any[]=[];
const retirement:Array<()=>void>=[];
try{
  const graph=await build({absWorkingDir:ROOT,entryPoints:[sky+'sky-scene-render.ts',sky+'sky-sdss-science-scene.ts',sky+'sky-sdss-optical-frame.ts'],outdir:path.join(folder,'nonwritten-bundle'),bundle:true,write:false,metafile:true,platform:'node',format:'esm',tsconfig:path.join(ROOT,'apps/wechat-miniapp/tsconfig.json')});
  const paths=new Set<string>(Object.keys(graph.metafile!.inputs).map(p=>path.relative(ROOT,path.resolve(ROOT,p)).replaceAll('\\','/')));
  for(const p of [path.relative(ROOT,fileURLToPath(import.meta.url)).replaceAll('\\','/'),decoder,publicationPath,reportPath,sky+'sky-sdss-science-scene.test.ts',sky+'sky-gpu-renderer.ts',sky+'sky-gpu-textures.ts',sky+'sky-gpu-artwork-contributions.ts',sky+'spot-sky-page.tsx','apps/wechat-miniapp/tsconfig.json','output/sdss-science-scene-consumer-1002-r1/source-bindings.json','output/sdss-science-scene-consumer-1002-r1/actual-writer-test.log'])paths.add(p);
  for(const d of generations){const r=json(d+'/result.json');for(const entry of r.before)if(!entry.path.includes('/scripts/experience-science-scene-'))paths.add(entry.path);}
  for(const b of historicalInventories)paths.add(b.path);
  before=[...paths].sort().map(bind);save('binding-before.json',before);save('current-metafile.json',graph.metafile);
  assert.equal(bind(sky+'sky-scene-render.ts').sha256,'2d9ca9e04c62291a7224b3c78e02d6c8aec4a0ad5cace98ac79e33c37bcacf57');
  assert.equal(bind(sky+'sky-sdss-science-scene.ts').sha256,'c38c7b06f87689595a2ecee9097e83bf1948dd5aaa0b0e730963974c60fecb7d');
  assert.equal(bind(sky+'sky-sdss-science-scene.test.ts').sha256,'eeaec02db21829e87698e0c99d52a1b13df3506477d7b5e456c2a4f38843daac');
  for(let i=0;i<generations.length;i++){
    const d=generations[i]!,r=json(d+'/result.json'),o=json(d+'/observations.json'),input=json(d+'/inputs-before.json');
    // r4's exact result identity is recorded, not inferred from its partial PASS.
    if(i!==1)assert.equal(bind(d+'/result.json').sha256,expectedResults[i]);
    assert.deepEqual(r.before,r.after);assert.deepEqual(r.before,input.before);assert.equal(new Set(r.before.map((v:any)=>v.path)).size,r.before.length);
    assert.deepEqual(bind(r.observations.path),r.observations);assert.equal(sha(read(d+'/executed-bundle.js')),input.bundle.sha256);assert.equal(read(d+'/executed-bundle.js').length,input.bundle.bytes);
    const sourceMismatches=[];for(const b of r.before){if(JSON.stringify(bind(b.path))!==JSON.stringify(b)){assert(b.path.includes('/scripts/experience-science-scene-'));sourceMismatches.push(b.path);}}
    for(const [file,entry] of Object.entries(input.metafile.inputs) as any[]){assert(!file.startsWith('<'));const p=path.relative(ROOT,path.resolve(ROOT,file)).replaceAll('\\','/');assert(!p.startsWith('..'));const b=r.before.find((v:any)=>v.path===p);assert(b,'unbound graph '+p);assert.equal(b.bytes,entry.bytes);}
    if(i<2){const snapshot=d+(i===0?'/failed-oracle-browser-source.ts.txt':'/failed-origin-browser-source.ts.txt');const original=r.before.find((b:any)=>b.path.endsWith('/experience-science-scene-browser-2026-10-02.ts'));assert.equal(bind(snapshot).sha256,original.sha256);assert.equal(bind(snapshot).bytes,original.bytes);}
    const p=json(d+'/prepared-input.json');assert.equal(p.at,prepared.at);assert.equal(p.publicationHash,publication.publicationHash);assert.deepEqual(p.images,prepared.images);assert.deepEqual(bind(p.reportBinding.path),p.reportBinding);
    assert.equal(report.observationFrames.filter((v:any)=>v.at===p.at).length,1);assert.equal(o.at,p.at);assert.equal(o.publicationHash,p.publicationHash);
    for(const image of p.images){assert.equal(bind(image.file).sha256,image.sha256);assert.equal(bind(image.file).bytes,image.bytes);if(image.id!=='W3'){const a=publication.levels[image.id];assert.equal(a.sha256,image.sha256);assert.equal(a.bytes,image.bytes);assert(image.file.endsWith('/'+a.file));}}
    const captures=[];for(const c of o.captures){assert.deepEqual(bind(c.raw.path),c.raw);assert.deepEqual(bind(c.png.path),c.png);const rgba=read(c.raw.path),decoded=png(c.png.path);assert.equal(decoded.w,c.width);assert.equal(decoded.h,c.height);assert.equal(rgba.length,c.width*c.height*4);for(let y=0;y<c.height;y++)assert(decoded.rgba.subarray(y*c.width*4,(y+1)*c.width*4).equals(rgba.subarray((c.height-1-y)*c.width*4,(c.height-y)*c.width*4)));captures.push({name:c.name,width:c.width,height:c.height,allPngCrcInflateFiltersAndYflipPixelsExact:true,raw:c.raw,png:c.png});}
    const live=new Map<number,{kind:string,bytes:number,attached:boolean}>(),snapshots:any[]=[];let peak=0,attachedPeak=0;const total=()=>{const counts:any={texture:0,framebuffer:0,buffer:0,program:0,shader:0};let bytes=0,attached=0;for(const v of live.values()){counts[v.kind]++;if(v.kind==='texture'){bytes+=v.bytes;if(v.attached)attached+=v.bytes;}}return{counts,logicalTextureBytes:bytes,logicalAttachedTextureBytes:attached};};
    for(let k=0;k<o.events.length;k++){
      const row=o.rows.find((v:any)=>v.eventsFrom===k);if(row){assert.equal(live.size,0);peak=0;attachedPeak=0;}
      const e=o.events[k];if(e.event==='create'){assert(!live.has(e.id));live.set(e.id,{kind:e.kind,bytes:0,attached:false});}
      else if(e.event==='delete'){const old=live.get(e.id);assert(old);assert.equal(old.kind,e.kind);assert.equal(old.bytes,e.bytes);live.delete(e.id);}
      else if(e.event==='allocate'||e.event==='copy'){const t=live.get(e.id)!;assert.equal(t.kind,'texture');if(e.event==='allocate')assert.equal(e.bytes,e.width*e.height*4);t.bytes=e.bytes;}
      else if(e.event==='attach'){assert.equal(live.get(e.framebuffer)?.kind,'framebuffer');if(e.texture!==null){assert.equal(live.get(e.texture)?.kind,'texture');live.get(e.texture)!.attached=true;}}
      else if(e.event==='read'){if(e.framebuffer!==null)assert.equal(live.get(e.framebuffer)?.kind,'framebuffer');}
      else assert.fail('unknown event '+e.event);
      const state=total();peak=Math.max(peak,state.logicalTextureBytes);attachedPeak=Math.max(attachedPeak,state.logicalAttachedTextureBytes);
      const end=o.rows.find((v:any)=>v.eventsTo===k+1);if(end){assert.equal(peak,end.peakLogicalTextureBytes);assert.equal(attachedPeak,end.peakLogicalAttachedTextureBytes);snapshots.push({name:end.name,peakLogicalTextureBytes:peak,peakEverAttachedLiveTextureBytes:attachedPeak,end:state});}
    }
    assert.deepEqual(total(),{counts:o.final.counts,logicalTextureBytes:o.final.logicalTextureBytes,logicalAttachedTextureBytes:o.final.logicalAttachedTextureBytes});assert.equal(live.size,0);assert.equal(o.final.glError,0);assert.equal(o.final.contextLost,false);assert.equal(o.failure,null);assert.deepEqual(o.pageErrors,[]);
    for(const row of o.rows){assert.deepEqual(row.disposed,{counts:o.final.counts,logicalTextureBytes:0,logicalAttachedTextureBytes:0});assert.equal(row.glError,0);assert(row.draws.length<=1);for(const q of row.q){assert.equal(q.drawId,row.draws[0].id);assert.equal(q.finished,false);}for(const receipt of row.receipts){assert.equal(receipt.drawId,row.draws[0].id);assert.equal(receipt.finished,true);}if(row.error){assert.equal(row.published,null);assert.equal(row.completed,0);assert.equal(row.receipts.length,0);}else{assert.equal(row.completed,1);assert(row.published.snapshotPresent);const optical=row.published.sources.optical;if(optical){assert.equal(optical.kind,'science');assert.equal(optical.reference,publication.objectRef);assert.equal(optical.publicationHash,publication.publicationHash);for(const field of optical.fields){assert.equal(field.assetExact,true);assert.equal(field.imageExact,true);assert(publication.levels[field.level]);}}}}
    const failedChecks=o.checks.filter((v:any)=>!v.pass).map((v:any)=>v.name);if(i===0){assert.equal(r.allPassed,false);assert.deepEqual(failedChecks,['default-no-group-no-aux','late-occlusion-withdraws-credit-not-spectral-selection']);assert.equal(o.rows.length,13);}else if(i===1){assert.equal(r.allPassed,false);assert.deepEqual(failedChecks,['late-opaque.actual-complete-opaque-and-navigation-output','late-occlusion-withdraws-credit-not-spectral-selection']);assert.equal(o.rows.length,2);}else{assert.equal(r.allPassed,true);assert.deepEqual(failedChecks,[]);assert.equal(o.rows.length,1);}
    generationsReadback.push({directory:d,result:bind(d+'/result.json'),rows:o.rows.length,captures,ledgerEvents:o.events.length,identityLedgerPeaks:snapshots,final:total(),failedChecks,allPassed:r.allPassed,sourceMismatches,realMetafileInputs:Object.keys(input.metafile.inputs).length,prePostBindings:r.before.length});
  }
  const old=json(generations[0]+'/observations.json'),noIntent=json(generations[1]+'/observations.json').rows[0],late=json(generations[2]+'/observations.json').rows[0];
  const row=(name:string)=>old.rows.find((v:any)=>v.name===name),fieldSlots=(v:any)=>v.published?.sources.optical?.fields.map((f:any)=>f.slot)??[],ir=(v:any)=>v.published?.sources.infrared;
  assert(read(generations[0]+'/actual-pair.rgba').equals(read(generations[0]+'/probe-budget-denied.rgba')));
  for(const n of ['complete-ready-empty','whole-unsubmitted'])assert(read(generations[0]+'/no-intent.rgba').equals(read(generations[0]+'/'+n+'.rgba')));
  assert(read(generations[0]+'/no-intent.rgba').equals(read(generations[1]+'/no-intent.rgba')));
  assert.deepEqual(fieldSlots(row('actual-pair')),['fine','coarse']);assert.deepEqual(fieldSlots(row('actual-ready-medium')),['fine','coarse']);assert.equal(row('actual-ready-medium').published.sources.optical.fields[0].level,'MEDIUM');
  const denied=row('probe-budget-denied');assert(denied.draws[0].submitted);assert.equal(denied.q[0].value.any,'unknown');assert.equal(denied.published.sources.optical,null);assert.equal(ir(denied),false);assert.deepEqual(denied.failed,[]);
  const failedEmpty=row('expected-fine-unprepared-coarse-empty');assert.equal(failedEmpty.draws[0].finePrepared,false);assert.equal(failedEmpty.q[0].value.any,'empty');assert.equal(ir(failedEmpty),false);assert.deepEqual(failedEmpty.failed,['fine']);
  assert.equal(ir(row('complete-ready-empty')),true);assert.equal(ir(row('whole-unsubmitted')),true);assert.equal(row('whole-unsubmitted').q.length,0);assert.equal(row('whole-unsubmitted').receipts.length,0);
  const black=row('valid-black-fine');assert.equal(black.q[0].value.fine,'has');assert.equal(black.q[0].value.coarse,'empty');assert.deepEqual(fieldSlots(black),[]);assert.equal(ir(black),false);assert.deepEqual(black.failed,[]);assert.deepEqual(fieldSlots(row('partial-fine-coarse')),['fine','coarse']);
  assert.equal(noIntent.draws.length,0);assert.equal(noIntent.q.length,0);assert.equal(noIntent.receipts.length,0);assert.equal(noIntent.peakLogicalAttachedTextureBytes,1048576);
  const noEvents=json(generations[1]+'/observations.json').events.slice(noIntent.eventsFrom,noIntent.eventsTo);assert.equal(noEvents.filter((v:any)=>v.event==='read').length,0);assert.equal(noEvents.filter((v:any)=>v.event==='copy').length,1);
  assert.equal(late.q[0].value.any,'has');assert.deepEqual(fieldSlots(late),[]);assert.equal(ir(late),false);assert(!late.calls.some((v:any)=>v.image==='W3'));assert.deepEqual(late.failed,[]);
  const covered=read(generations[2]+'/late-opaque.rgba');let whitePixels=0,navPixels=0;for(let y=0;y<844;y++)for(let x=0;x<390;x++){const offset=(y*390+x)*4,expected=y>=836?[8,13,23,255]:[255,255,255,255];for(let c=0;c<4;c++)assert.equal(covered[offset+c],expected[c]);if(y>=836)navPixels++;else whitePixels++;}
  const high=row('actual-high-dpr'),[hw,hh]=high.physical;let w=hw,h=hh,scratch=0;do{w=Math.ceil(w/2);h=Math.ceil(h/2);scratch+=w*h*4;}while(w>1||h>1);assert.deepEqual(high.plannedAuxiliary,{signal:hw*hh*4,scratch,total:hw*hh*4+scratch});assert.equal(high.plannedAuxiliary.total,15803512);assert.equal(high.peakLogicalAttachedTextureBytes,15803512);const highReads=old.events.slice(high.eventsFrom,high.eventsTo).filter((v:any)=>v.event==='read');assert.equal(highReads.length,2);assert(highReads.every((v:any)=>v.width===1&&v.height===1));
  const surface=(options:any={})=>{let finished=false,published:any=null,completed=0;const calls:any[]=[],failure:any[]=[],disc:any[]=[];let exactDraw:any;
    const actual:any=new Proxy({
      begin(){calls.push('begin');},artwork(image:any){calls.push(image===infrared?'W3':'legacy-artwork');return true;},
      artworkLevels(levels:any){calls.push('group');options.onGroup?.(levels);exactDraw=Object.freeze(options.draw??{submitted:true,finePrepared:!!levels.fine,coarsePrepared:!!levels.coarse});return exactDraw;},
      artworkLevelsQualification(draw:any){assert.strictEqual(draw,exactDraw);assert.equal(finished,false);calls.push('qualification');return options.qualification??{fine:'has',coarse:'has',any:'has'};},
      artworkLevelsContribution(draw:any){assert.strictEqual(draw,exactDraw);assert.equal(finished,true);calls.push('contribution');return options.receipt??{completed:true,qualification:options.qualification??{fine:'has',coarse:'has',any:'has'},finePhoto:'positive',coarsePhoto:'positive'};},
      disc(...args:any[]){disc.push(args);},finish(){calls.push('finish');if(options.throwFinish)throw Error('independent-finish-failure');finished=true;},
    },{get:(object,key)=>key in object?object[key]:()=>true});
    return{actual,calls,failure,disc,get output(){return published;},get completed(){return completed;},failed:(image:any)=>{failure.push(image);options.onFailure?.(image);},painted:(_snapshot:any,sources:any)=>{assert(finished);calls.push('painted');published=sources;},done:()=>{assert(finished);calls.push('done');completed++;}};};
  const infrared={width:512,height:512};
  const currentBasis=old.basis,view={basis:currentBasis,verticalFovDeg:.18};
  const world=()=>{const fine={width:512,height:512},coarse={width:512,height:512};const retireFine=registerSkyNativeImageLifetime(fine,()=>true),retireCoarse=registerSkyNativeImageLifetime(coarse,()=>true);retirement.push(retireFine,retireCoarse);const frame=skySdssOpticalFrame({publication,image:fine,renderedLevel:'DETAIL',renderedAsset:publication.levels.DETAIL,coarser:{image:coarse,level:'OVERVIEW',asset:publication.levels.OVERVIEW}})!;return{fine,coarse,frame,retireFine,retireCoarse};};
  const paint=(s:any,w:any,changes:any={})=>{const args:any[]=Array(37).fill(undefined);Object.assign(args,{0:s.actual,1:report,2:prepared.at,5:390,6:844,7:'NIGHT',8:s.painted,9:s.done,10:.18,11:{reference:'M:51',level:'DETAIL',fieldDegrees:.25,image:infrared},12:currentBasis,30:w.frame,31:s.failed,34:{enabled:false},35:{horizontal:false,equatorial:false},36:{surface:s.actual,reference:publication.objectRef,publicationHash:publication.publicationHash}},changes);return drawSkyScene(...args as any);};
  const control=(name:string,run:()=>any)=>controls.push({name,status:'passed',facts:run()});
  control('failure callback retires other originally-ready slot before submission',()=>{const facts=[];for(const start of ['fine','coarse']){const w=world();if(start==='fine')w.retireFine();else w.retireCoarse();const s=surface({onFailure:(image:any)=>{if(image===w.fine)w.retireCoarse();else w.retireFine();}});paint(s,w);assert(!s.calls.includes('group'));assert(!s.calls.includes('qualification'));assert.deepEqual(s.failure,[start==='fine'?w.fine:w.coarse,start==='fine'?w.coarse:w.fine]);assert.strictEqual(s.output.deepSkyImage,infrared);assert.equal(s.output.sdssOptical,null);assert.equal(s.completed,1);facts.push({firstRetired:start,distinctFailures:s.failure.length,group:0,independentUnavailableW3:true});}return facts;});
  control('post-selection failure callback retires independent prepared coarse without EMPTY or W3 rewrite',()=>{const facts=[];for(const q of ['empty','has']){const w=world(),qualification={fine:'empty',coarse:q,any:q},s=surface({draw:{submitted:true,finePrepared:false,coarsePrepared:true},qualification,receipt:{completed:true,qualification,finePhoto:'unknown',coarsePhoto:q==='has'?'positive':'unknown'},onFailure:(image:any)=>{assert.strictEqual(image,w.fine);w.retireCoarse();}});paint(s,w);assert.deepEqual(s.failure,[w.fine]);assert(!s.calls.includes('W3'));assert.equal(s.output.sdssOptical.kind,'science');assert.equal(s.output.sdssOptical.participatingFields.length,0);assert.equal(s.output.sdssOptical.receipt.qualification.any,q);assert(s.calls.indexOf('qualification')<s.calls.indexOf('finish'));assert(s.calls.indexOf('finish')<s.calls.indexOf('contribution'));facts.push({actualPreparedCoarse:q,originalFineFailed:true,lateRetiredCoarseFields:0,selectedW3:false});}return facts;});
  control('failure callback exception cannot publish an unfinished source',()=>{const w=world();w.retireFine();const s=surface({onFailure:()=>{throw Error('independent-failure-callback');}});assert.throws(()=>paint(s,w),/independent-failure-callback/);assert(!s.calls.includes('finish'));assert.equal(s.output,null);assert.equal(s.completed,0);return{finish:0,source:0,completed:0};});
  control('precise context/ref/hash/asset mismatch stays outside science and legacy PNG passes',()=>{const facts=[];for(const key of ['context','reference','hash','asset','parentOrder']){const w=world(),s=surface(),port={surface:s.actual,reference:publication.objectRef,publicationHash:publication.publicationHash};const changes:any={};if(key==='context')port.surface=surface().actual;else if(key==='reference')port.reference='M:63';else if(key==='hash')port.publicationHash='0'.repeat(64);else if(key==='asset')changes[30]={...w.frame,asset:{...publication.levels.DETAIL}};else changes[30]={...w.frame,coarser:{...w.frame.coarser,level:'DETAIL',asset:publication.levels.DETAIL,fieldDegrees:publication.levels.DETAIL.fieldDegrees}};changes[36]=port;paint(s,w,changes);assert(!s.calls.includes('group'));assert(!s.calls.includes('legacy-artwork'));assert.deepEqual(s.failure,[]);assert.strictEqual(s.output.deepSkyImage,infrared);facts.push(key);}return facts;});
  const helper=read(sky+'sky-sdss-science-scene.ts').toString('utf8').replaceAll('\r\n','\n');
  const load=(text:string)=>{const exports:any={};vm.runInNewContext(ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:(name:string)=>{if(name==='./sky-artwork-loader')return{skyNativeImageIsCurrent};if(name==='./sky-sdss-science-registration')return{registerSkyScienceOpticalField};throw Error('unexpected runtime '+name);}});return exports.submitSkySceneScienceOptical as typeof submitSkySceneScienceOptical;};
  control('bounded independent mutation detects post-callback native recheck and expected-ready permission',()=>{
    const guard='  if (fine && !skyNativeImageIsCurrent(expected.fine.image)) { fail(expected.fine); fine = null; }\n  if (coarse && expected.coarse && !skyNativeImageIsCurrent(expected.coarse.image)) { fail(expected.coarse); coarse = null; }';
    assert.equal(helper.split(guard).length,2);const bypass=helper.replace(guard,'');fs.writeFileSync(path.join(folder,'mutant-no-post-callback-native-recheck.ts.txt'),bypass,{flag:'wx'});
    const run=(fn:typeof submitSkySceneScienceOptical)=>{const w=world();w.retireCoarse();let group=0;const s=surface({onGroup:(levels:any)=>{group++;assert(levels.fine);assert.equal(skyNativeImageIsCurrent(levels.fine.image),false);}});fn(s.actual,{surface:s.actual,reference:publication.objectRef,publicationHash:publication.publicationHash},w.frame,observation,view,(image:any)=>{if(image===w.coarse)w.retireFine();});return group;};
    assert.equal(run(load(helper)),0);assert.equal(run(load(bypass)),1);mutations.push({name:'post-callback native recheck removed',actualCurrentGroup:0,actualMutantRetiredNativeGroup:1,detected:true,scope:'Construction fence, controlled downstream group; no GPU execution.'});
    const expected='!!fine && draw.finePrepared && (!expected.coarse || (!!coarse && draw.coarsePrepared)) &&';assert.equal(helper.split(expected).length,2);const bypassExpected=helper.replace(expected,'true &&');fs.writeFileSync(path.join(folder,'mutant-prepared-only-empty.ts.txt'),bypassExpected,{flag:'wx'});
    const runExpected=(fn:typeof submitSkySceneScienceOptical)=>{const w=world(),s=surface({draw:{submitted:true,finePrepared:false,coarsePrepared:true},qualification:{fine:'empty',coarse:'empty',any:'empty'}});return fn(s.actual,{surface:s.actual,reference:publication.objectRef,publicationHash:publication.publicationHash},w.frame,observation,view)?.allowInfrared;};
    assert.equal(runExpected(load(helper)),false);assert.equal(runExpected(load(bypassExpected)),true);mutations.push({name:'expected-ready guard removed',actualCurrentW3Allowed:false,actualMutantW3Allowed:true,detected:true});return mutations;
  });
  const page=ts.createSourceFile('page.tsx',read(sky+'spot-sky-page.tsx').toString('utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let hookArgs:any[]=[],gpuOptions:any[]=[],sceneArgs:any[]=[],proxyTokens=0;
  function walk(n:ts.Node){if(ts.isCallExpression(n)){const name=n.expression.getText(page);if(name==='useSkySdssOptical')hookArgs.push(n.arguments.map(a=>a.getText(page)));if(name==='createSkyGpuRenderer')gpuOptions.push(n.arguments[2].getText(page));if(name==='drawSkyScene')sceneArgs.push(n.arguments.map(a=>a.getText(page)));}if(ts.isPropertyAssignment(n)&&n.name.getText(page)==='artworkContributions')proxyTokens++;ts.forEachChild(n,walk);}walk(page);
  assert.equal(hookArgs.length,1);assert.equal(hookArgs[0].length,5);assert.equal(gpuOptions.length,1);assert.equal(proxyTokens,0);assert(sceneArgs.every(args=>args.length===36));save('normal-page-callers.json',{hookArgs,gpuOptions,sceneArgCounts:sceneArgs.map(a=>a.length),artworkContributionsOptionCount:proxyTokens,scope:'Exact current page calls, not target-runtime rendering.'});
  assert.deepEqual(historicalInventories.map(b=>bind(b.path)),historicalInventories);const after=before.map(b=>bind(b.path));assert.deepEqual(after,before);save('binding-after.json',after);
  save('result.json',{status:'INDEPENDENT_BOUNDED_EXPLICIT_SCIENCE_SCENE_DEVELOPMENT_REVIEW_PASSED',generations:generationsReadback,controls,mutations,bindings:before.length,lateOpaque:{whitePixels,navPixels,allPixels:329160,priorQualification:'has',finalPhoto:'unknown',fields:0,retroactiveSelectedW3:false},highDpr:{drawingBuffer:[hw,hh],signalBytes:hw*hh*4,scratchBytes:scratch,auxiliaryBytes:15803512,actualOnePixelReads:highReads.length,allLogicalTexturePeak:high.peakLogicalTextureBytes},limits:['No new GPU/HTTP/native/IDE work. Actual outputs belong to software WebGL explicit task port only, other optional scene imagery absent.','r3/r4 remain overall failed historical outputs; only r4 no-intent and r5 late-opaque repair scopes close those controls.','r3/r4 historical host runner text was not saved; exact browser snapshots, executed bundle and input hash receipts exist. Historical tsconfig/toolchain identities were not prebound; this review adds current-only tsconfig identity, not retrospective reproducibility.','Trace records allocation/copy/attach/object IDs and external group identity, not a new second native sampler/uniform/VBO setter readback. Previously reviewed shared prepared submission joins are reused by exact source.','Reported texture bytes are logical RGBA allocation; ever-attached-live byte peak includes normal source-window copy FBO and is not by itself an auxiliary classification.','Global photo participation is not local readability or guaranteed unsaturated final color difference. Natural aid fade, normal default science adoption, source quality/PSF/brown/finite footprint, native total memory/IO/fps and final experience remain open.']});
  console.log(JSON.stringify({result:bind(OUT+'/result.json'),binding:bind(OUT+'/binding-before.json'),controls:controls.length,pngs:generationsReadback.reduce((n,r)=>n+r.captures.length,0),events:generationsReadback.reduce((n,r)=>n+r.ledgerEvents,0)}));
}catch(error){save('failed.json',{error:String(error),stack:(error as Error).stack,controls,mutations,generationsReadback,before});throw error;}finally{retirement.forEach(fn=>fn());}
