/** Bounded CPU ownership observation; no browser/GL/native pixel proof. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),base='.codex/work-items/cloud-sky-native-2026-09-22';
const out=path.join(ROOT,'output/native-image-membership-observation-1003-r1');await fs.mkdir(out,{recursive:false});
const hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const bind=async(p:string)=>{const b=await fs.readFile(path.join(ROOT,p));return {path:p,bytes:b.length,sha256:hash(b)};};
await fs.copyFile(fileURLToPath(import.meta.url),path.join(out,'executed-script.mts.txt'));
const originalResultPath='output/playwright/cloud-sky-complete-resource-1003-r2/result.json',original=await fs.readFile(path.join(ROOT,originalResultPath)),r=JSON.parse(original.toString());
assert.equal(hash(original),'80a2270a1d922f86019a9518ba7ef249aeff0603e9676ca709df6b7d9b8c04c3');
const source=r.inputs.find((p:any)=>p.sha256==='fd6afeebba748eb84a15c0aea2a8ce0e363571685c6b181c8511f2bb5459bb32'&&p.transport==='ACTUAL_LOCAL_PUBLISHED_BYTES_OFFER_ONLY');assert(source);
const bytes=await fs.readFile(path.join(ROOT,source.path));assert.equal(bytes.length,source.bytes);assert.equal(hash(bytes),source.sha256);
const runtimePath='apps/wechat-miniapp/src/services/sky-public-image-runtime.ts',runtime=await fs.readFile(path.join(ROOT,runtimePath),'utf8');
const budget=Number(runtime.match(/const ENCODED_BYTE_BUDGET = (\d+) \* 1024 \* 1024;/)![1])*1024*1024,maxFile=Number(runtime.match(/const MAX_FILE_BYTES = (\d+) \* 1024 \* 1024;/)![1])*1024*1024;
const entry=`export {startSkyArtworkRequest} from './apps/wechat-miniapp/src/features/sky/sky-artwork-request';
export {createSkyArtworkLoader,skyNativeImageIsCurrent,taskNativeLifetime} from './apps/wechat-miniapp/src/features/sky/sky-artwork-loader';
export {createSkyPublicImageCache} from './apps/wechat-miniapp/src/services/sky-public-image-cache';`;
let registryOriginal='',registryObserved='';
const bundle=await build({absWorkingDir:ROOT,stdin:{contents:entry,loader:'ts',resolveDir:ROOT,sourcefile:'native-membership-entry.ts'},bundle:true,write:false,metafile:true,platform:'node',format:'esm',tsconfig:path.join(ROOT,'apps/wechat-miniapp/tsconfig.json'),plugins:[{name:'readonly-original-lifetime-membership',setup(b){b.onLoad({filter:/[\\/]sky-artwork-loader\.ts$/},async a=>{registryOriginal=await fs.readFile(a.path,'utf8');registryObserved=registryOriginal+`\nexport function taskNativeLifetime(image:object){const value=nativeImageLifetimes.get(image);return {registered:Boolean(value),retired:value?.retired??null,callbackCurrent:value?.current?.()??null,apiCurrent:skyNativeImageIsCurrent(image)};}\n`;return {contents:registryObserved,loader:'ts'};});}}]});
assert(registryOriginal);await fs.writeFile(path.join(out,'actual-entry.ts.txt'),entry,{flag:'wx'});await fs.writeFile(path.join(out,'actual-registry-readonly.ts.txt'),registryObserved,{flag:'wx'});await fs.writeFile(path.join(out,'bundle.mjs'),bundle.outputFiles[0]!.text,{flag:'wx'});await fs.writeFile(path.join(out,'metafile.json'),JSON.stringify(bundle.metafile,null,2)+'\n',{flag:'wx'});
const bindings:any[]=[];for(const key of Object.keys(bundle.metafile!.inputs)){if(key==='native-membership-entry.ts')continue;const p=path.relative(ROOT,path.resolve(ROOT,key)).replaceAll('\\','/');assert(p&&!p.startsWith('../')&&!path.isAbsolute(p));const row=await bind(p);bindings.push(row);const snapshot=path.join(out,'source-inputs',p);await fs.mkdir(path.dirname(snapshot),{recursive:true});await fs.copyFile(path.join(ROOT,p),snapshot);}
for(const p of [source.path,runtimePath,base+'/scripts/observe-native-image-membership-2026-10-03.mts','tools/run-node.cjs','node_modules/esbuild/package.json'])bindings.push(await bind(p));
await fs.writeFile(path.join(out,'bindings-before.json'),JSON.stringify(bindings,null,2)+'\n',{flag:'wx'});
const api=await import(new URL('file:///'+path.join(out,'bundle.mjs').replaceAll('\\','/')));
const files=new Map<string,ArrayBuffer>(),events:any[]=[],images:any[]=[],state:any[]=[];
const descriptor={environment:'e'.repeat(64),url:'https://fixture.invalid/existing-landscape-detail.png',format:'png',bytes:source.bytes,sha256:source.sha256,width:source.width,height:source.height};
const asset={...descriptor,id:'landscape:detail'};
const filesystem={async mkdir(){},async list(root:string){return [...files.keys()].filter(p=>p.startsWith(root+'/')).map(p=>p.slice(root.length+1));},async size(p:string){assert(files.has(p));return files.get(p)!.byteLength;},async read(p:string,length:number){assert(files.has(p));return files.get(p)!.slice(0,length);},async write(p:string,b:ArrayBuffer){files.set(p,b.slice(0));},async rename(a:string,b:string){assert(files.has(a));files.set(b,files.get(a)!);files.delete(a);},async remove(p:string){files.delete(p);}};
const cache=api.createSkyPublicImageCache({fs:filesystem,root:'/owned/sky-public-images-v1',session:'membership',byteBudget:budget,maxFileBytes:maxFile,transfer(){events.push({kind:'actual-cache-transfer-offer',bytes:bytes.length,sha256:source.sha256});return {promise:Promise.resolve(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)),cancel(){events.push({kind:'transfer-cancel'});}};}});
await cache.ready();
const canvas={createImage(){const image={src:'',onload:null,onerror:null,width:source.width,height:source.height};images.push(image);return image;}};
const loader=api.createSkyArtworkLoader({start(a:any,ready:any,fail:any){return api.startSkyArtworkRequest({asset:a,url:a.url,format:'png',canvas,acquire:()=>cache.acquire(descriptor),ready,fail});},changed(value:any){state.push(value);}});
const wait=async(test:()=>boolean)=>{for(let n=0;n<250;n++){if(test())return;await Promise.resolve();}throw Error('bounded actual request preparation');};
const snapshot=(phase:string,image:any)=>({phase,lifetime:api.taskNativeLifetime(image),productionCallbackAttached:typeof image.onload==='function',currentOwnerImages:[...state.at(-1)?.images.keys()??[]],cache:cache.inspect()});
loader.update([asset]);await wait(()=>images.length===1&&typeof images[0].onload==='function');const imageA=images[0],lateA=imageA.onload,observations=[snapshot('before-cancel',imageA)];
assert.equal(cache.inspect().leased,1);assert.equal(api.taskNativeLifetime(imageA).registered,false);
loader.update([]);observations.push(snapshot('after-actual-loader-cancel',imageA));assert.equal(imageA.onload,null);assert.equal(cache.inspect().leased,0);
lateA();observations.push(snapshot('late-unadmitted-native-callback',imageA));assert.equal(api.taskNativeLifetime(imageA).registered,false);assert.equal(api.skyNativeImageIsCurrent(imageA),true);assert.equal(state.at(-1).images.size,0);
loader.update([asset]);await wait(()=>images.length===2&&typeof images[1].onload==='function');const imageB=images[1];imageB.onload();observations.push(snapshot('actual-successful-registration',imageB));assert.equal(api.taskNativeLifetime(imageB).registered,true);assert.equal(api.skyNativeImageIsCurrent(imageB),true);assert.equal(state.at(-1).images.get(asset.id),imageB);
loader.dispose();observations.push(snapshot('after-actual-owner-dispose',imageB));assert.equal(api.taskNativeLifetime(imageB).retired,true);assert.equal(api.skyNativeImageIsCurrent(imageB),false);assert.equal(cache.inspect().leased,0);
await cache.clear();const cleanup={cache:cache.inspect(),files:[...files.keys()]};assert.equal(cleanup.cache.bytes,0);assert.equal(cleanup.cache.leased,0);
const exactR2Matches=r.rows.flatMap((row:any)=>[...row.states,...row.passes.map((p:any)=>p.state)].flatMap((s:any)=>s.hooks.flatMap((h:any)=>h.entries.filter((e:any)=>e.image?.objectId===26))));
const r2Uploads=r.final.fullGlLedger.events.filter((e:any)=>e.source?.objectId===26);
const oldOracleWouldFail=api.skyNativeImageIsCurrent(imageA),membershipOracleWouldReject=api.taskNativeLifetime(imageA).registered&&api.skyNativeImageIsCurrent(imageA);assert(oldOracleWouldFail);assert.equal(membershipOracleWouldReject,false);
const after=await Promise.all(bindings.map(b=>bind(b.path)));assert.deepEqual(after,bindings);await fs.writeFile(path.join(out,'bindings-after.json'),JSON.stringify(after,null,2)+'\n',{flag:'wx'});
const result={status:'OBSERVED_ACTUAL_CPU_OWNERSHIP_SEMANTICS',observations,events,cleanup,mutant:{oldAllCreatedApiCurrentWouldFlagUnownedImage:oldOracleWouldFail,registeredOwnerPredicateCorrectlyExcludesIt:!membershipOracleWouldReject},originalR2:{result:{path:originalResultPath,bytes:original.length,sha256:hash(original)},status:r.status,exitStatusRemainsFailed:true,image26OwnerEntryOccurrences:exactR2Matches.length,image26GpuUploadOccurrences:r2Uploads.length,directImage26WeakMapEvidence:'UNKNOWN; this new CPU control does not retrospectively observe that old browser instance'},registryObservation:{originalSha256:hash(registryOriginal),taskReadonlySha256:hash(registryObserved)},bindings,scope:'Actual cache/loader/request cancellation-before-onload + queued late callback + success/retirement control using real bound PNG bytes and controlled image objects/MapFS. Read-only export peeks actual WeakMap; no production change, new browser/GPU/native decoding/physical GC or old r2 reclassification. New main measurement can distinguish registered owner membership from legacy unmanaged draw eligibility.'};
await fs.writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({output:path.relative(ROOT,out).replaceAll('\\','/'),result:await bind('output/native-image-membership-observation-1003-r1/result.json'),boundSources:bindings.length,observations:observations.length,r2Image26Registry:'UNKNOWN'}));
