// Independent current-owner CPU controls + saved-output reader. No browser/GPU/HTTP/source decoding.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {inflateSync} from 'node:zlib';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {registerSkyPreparedOpticalFootprints} from '../../../../apps/wechat-miniapp/src/features/sky/sky-prepared-optical-footprint.ts';
import {skyPreparedOpticalFrame} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-frame.ts';
import {OBSERVATION_FRAME_FORMAT} from '../../../../packages/miniapp-contracts/src/index.ts';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..');
const task='.codex/work-items/cloud-sky-native-2026-09-22',source='output/playwright/cloud-sky-prepared-report-display-1003-r1';
const out='output/prepared-report-footprint-independent-1003-r2';
assert(!fs.existsSync(path.resolve(ROOT,out)));fs.mkdirSync(path.resolve(ROOT,out));
const read=p=>fs.readFileSync(path.resolve(ROOT,p)),sha=b=>createHash('sha256').update(b).digest('hex');
const json=p=>JSON.parse(read(p).toString('utf8'));
const binding=p=>{const b=read(p);return{path:p,bytes:b.length,sha256:sha(b)};};
const inputs=new Map();
const admit=(p,expected={})=>{const b=binding(p);if(expected.bytes!==undefined)assert.equal(b.bytes,expected.bytes,p);if(expected.sha256)assert.equal(b.sha256,expected.sha256,p);if(inputs.has(p))assert.deepEqual(b,inputs.get(p));inputs.set(p,b);return b;};
const write=(name,value)=>fs.writeFileSync(path.resolve(ROOT,out,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});
fs.copyFileSync(fileURLToPath(import.meta.url),path.resolve(ROOT,out,'executed-reader.mts'),fs.constants.COPYFILE_EXCL);

// Reused independent CRC/zlib/filter reader; neither author's image helper nor browser decoding is invoked.
const crc32=b=>{let c=0xffffffff;for(const x of b){c^=x;for(let k=0;k<8;k++)c=c&1?(c>>>1)^0xedb88320:c>>>1;}return(c^0xffffffff)>>>0;};
function png(b,width,height){
 assert.deepEqual(b.subarray(0,8),Buffer.from([137,80,78,71,13,10,26,10]));let at=8,ended=false,header=false;const chunks=[],filters=new Set();
 while(at<b.length){assert(at+12<=b.length);const n=b.readUInt32BE(at),tag=b.toString('ascii',at+4,at+8),end=at+12+n;assert(end<=b.length);assert.equal(crc32(b.subarray(at+4,end-4)),b.readUInt32BE(end-4));const d=b.subarray(at+8,end-4);
  if(tag==='IHDR'){assert(!header&&at===8);assert.equal(n,13);assert.equal(d.readUInt32BE(0),width);assert.equal(d.readUInt32BE(4),height);assert.deepEqual([...d.subarray(8)],[8,6,0,0,0]);header=true;}if(tag==='IDAT'){assert(header);chunks.push(d);}at=end;if(tag==='IEND'){assert.equal(n,0);ended=true;break;}}
 assert(ended&&header);assert.equal(at,b.length);const stride=width*4,z=inflateSync(Buffer.concat(chunks),{maxOutputLength:(stride+1)*height});assert.equal(z.length,(stride+1)*height);const rgba=Buffer.alloc(stride*height);
 for(let y=0;y<height;y++){const filter=z[y*(stride+1)];assert(filter<=4);filters.add(filter);for(let x=0;x<stride;x++){const a=x>=4?rgba[y*stride+x-4]:0,u=y?rgba[(y-1)*stride+x]:0,ul=x>=4&&y?rgba[(y-1)*stride+x-4]:0;let p=0;if(filter===1)p=a;if(filter===2)p=u;if(filter===3)p=(a+u)>>1;if(filter===4){const q=a+u-ul,da=Math.abs(q-a),du=Math.abs(q-u),dul=Math.abs(q-ul);p=da<=du&&da<=dul?a:du<=dul?u:ul;}rgba[y*stride+x]=(z[y*(stride+1)+x+1]+p)&255;}}
 return{rgba,filters:[...filters].sort()};
}
function diff(a,b){assert.equal(a.length,b.length);let rgbPixels=0,rgbaPixels=0,bytes=0,max=0;for(let i=0;i<a.length;i+=4){let rgb=false,any=false;for(let c=0;c<4;c++){const d=Math.abs(a[i+c]-b[i+c]);if(d){any=true;if(c<3)rgb=true;bytes++;max=Math.max(max,d);}}if(rgb)rgbPixels++;if(any)rgbaPixels++;}return{rgbPixels,rgbaPixels,changedBytes:bytes,maxChannelDifference:max,exact:bytes===0};}
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),multiply=(m,v)=>[0,1,2].map(i=>dot(m.slice(i*3,i*3+3),v));
const basis=(ra,dec)=>{ra*=Math.PI/180;dec*=Math.PI/180;return{c:[Math.cos(dec)*Math.cos(ra),Math.cos(dec)*Math.sin(ra),Math.sin(dec)],e:[-Math.sin(ra),Math.cos(ra),0],n:[-Math.sin(dec)*Math.cos(ra),-Math.sin(dec)*Math.sin(ra),Math.cos(dec)]};};
const uv=(rows,ray)=>{const z=dot(rows[2],ray);return z>0?[dot(rows[0],ray)/z,dot(rows[1],ray)/z]:null;};
function controls(pub,physical,saved){
 const observation={...physical,format:OBSERVATION_FRAME_FORMAT},g=pub.source.nominalAvm;
 const ready=(publication=pub,level='DETAIL')=>{const value=skyPreparedOpticalFrame({image:{width:512,height:512},renderedLevel:level,renderedAsset:publication.levels[level],publication,coarser:null});assert(value);return value;};
 const native=ready(),registered=registerSkyPreparedOpticalFootprints(native,observation);assert(registered);
 const directSource=(u,v)=>{const x=u*(g.decodedShapeWidthHeight[0]-1)+1-g.crpixFitsOneBased[0],y=(1-v)*(g.decodedShapeWidthHeight[1]-1)+1-g.crpixFitsOneBased[1],a=g.rotation*Math.PI/180,te=(g.cdeltDegrees[0]*Math.cos(a)*x-g.cdeltDegrees[1]*Math.sin(a)*y)*Math.PI/180,tn=(g.cdeltDegrees[0]*Math.sin(a)*x+g.cdeltDegrees[1]*Math.cos(a)*y)*Math.PI/180,{c,e,n}=basis(...g.referenceValue);return c.map((c,i)=>c+te*e[i]+tn*n[i]);};
 const directMaster=(u,v)=>{const {c,e,n}=basis(pub.center.raDeg,pub.center.decDeg),h=Math.tan(pub.levels.OVERVIEW.fieldDegrees*Math.PI/360);return c.map((c,i)=>c+h*(1-2*u)*e[i]+h*(1-2*v)*n[i]);};
 const probes=[[0,0],[1,0],[0,1],[1,1],[.5,.5],[.5,0],[1,.5],[.5,1],[0,.5]];
 const shear={...observation,equatorialToEnu:[1,4e-7,0,0,1,0,0,0,1]},frames=[observation,shear];let maxSource=0,maxMaster=0,maxSavedSource=0,maxSavedMaster=0,maxAnti=0,fixedError=0;const samples=[];
 const fixed=registerSkyPreparedOpticalFootprints(native,{...observation,equatorialToEnu:[1,0,0,0,1,0,0,0,1]});assert(fixed);
 for(const obs of frames){const actual=registerSkyPreparedOpticalFootprints(native,obs);assert(actual);for(const point of probes){for(const [name,ray,size]of[['source',directSource(...point),g.decodedShapeWidthHeight],['master',directMaster(...point),[2048,2048]]]){const enu=multiply(obs.equatorialToEnu,ray),result=uv(actual[name],enu);assert(result);const error=Math.max(...result.map((v,i)=>Math.abs(v-point[i])*(name==='source'?size[i]-1:size[i])));assert(error<2e-6);if(name==='source')maxSource=Math.max(maxSource,error);else maxMaster=Math.max(maxMaster,error);let savedError=null;if(obs===observation){const value=uv(saved[name],enu);assert(value);savedError=Math.max(...value.map((v,i)=>Math.abs(v-point[i])*(name==='source'?size[i]-1:size[i])));assert(savedError<2e-6);if(name==='source')maxSavedSource=Math.max(maxSavedSource,savedError);else maxSavedMaster=Math.max(maxSavedMaster,savedError);}const opposite=uv(actual[name],enu.map(x=>-x));assert.equal(opposite,null);maxAnti++;const wrong=uv(fixed[name],enu);if(wrong)fixedError=Math.max(fixedError,...wrong.map((v,i)=>Math.abs(v-point[i])*size[i]));samples.push({frame:obs===observation?'actual-report':'finite-nonorthogonal',plane:name,uv:point,errorSourcePixels:error,savedBrowserErrorPixels:savedError});}}}
 assert(fixedError>100);
 const variants=['OVERVIEW','MEDIUM','DETAIL'].map(level=>registerSkyPreparedOpticalFootprints(ready(pub,level),observation));variants.forEach(v=>assert.deepEqual(v,registered));
 assert(Object.isFrozen(registered)&&Object.isFrozen(registered.equatorialToEnu));for(const rows of[registered.source,registered.master]){assert(Object.isFrozen(rows));rows.forEach(row=>assert(Object.isFrozen(row)));}assert.throws(()=>{registered.source[0][0]=42;},TypeError);
 const mutableObs=structuredClone(observation),held=registerSkyPreparedOpticalFootprints(native,mutableObs);assert(held);mutableObs.equatorialToEnu[0]+=1;assert.deepEqual(held.equatorialToEnu,observation.equatorialToEnu);
 const reject=[];const test=(name,value,obs=observation)=>{assert.equal(registerSkyPreparedOpticalFootprints(value,obs),null,name);reject.push(name);};
 test('null-frame',null);test('missing-report',native,null);test('foreign-ref',{...native,reference:'M:82'});test('wrong-pin',{...native,publicationHash:'0'.repeat(64)});test('cloned-descriptor',{...native,asset:{...native.asset}});test('wrong-family',{...native,preparedPublication:{...pub,imageVersion:'science-optical-v2'}});test('reflected-report',native,{...observation,equatorialToEnu:[-1,0,0,0,1,0,0,0,1]});test('nonfinite-report',native,{...observation,equatorialToEnu:[NaN,0,0,0,1,0,0,0,1]});
 for(const[name,change]of[['zero-source-scale',p=>p.source.nominalAvm.cdeltDegrees[0]=0],['unknown-accuracy',p=>p.source.nominalAvm.accuracy='UNKNOWN'],['source-single-pixel',p=>p.source.nominalAvm.decodedShapeWidthHeight[1]=1],['foreign-master-field',p=>p.master.fieldDegrees*=2]]){const p=structuredClone(pub);change(p);test(name,{...native,preparedPublication:p,asset:p.levels.DETAIL});}
 assert.deepEqual(registerSkyPreparedOpticalFootprints(native,observation),registered);
 // Useful bounded mutation, explicitly not a reconstructed historical owner: restore its escaped strict equality.
 const exactFieldMutant=(frame,obs)=>frame.preparedPublication.master.fieldDegrees===frame.preparedPublication.levels.OVERVIEW.fieldDegrees?registerSkyPreparedOpticalFootprints(frame,obs):null;
 assert.notEqual(pub.master.fieldDegrees,pub.levels.OVERVIEW.fieldDegrees);assert.equal(exactFieldMutant(native,observation),null);
 let maxDoubleRowResidual=0;for(const name of['source','master'])for(let i=0;i<3;i++){assert.deepEqual(registered[name][i].map(Math.fround),saved[name][i].map(Math.fround));for(let j=0;j<3;j++)maxDoubleRowResidual=Math.max(maxDoubleRowResidual,Math.abs(registered[name][i][j]-saved[name][i][j]));}
 return{actualRows:registered,savedBrowserRows:saved,independentOriginalCdCrotaCrpixNativeAndMotherRays:samples,maxSourcePixels:maxSource,maxMotherPixels:maxMaster,maxSavedSourcePixels:maxSavedSource,maxSavedMotherPixels:maxSavedMaster,crossRuntimeDoubleRowResidual:maxDoubleRowResidual,crossRuntimeRowsRoundToSameFloat32:true,antipodeRejects:maxAnti,fixedIcrsOnActualEnuCounterexamplePixels:fixedError,allReadyLodsUseSameWholeFootprint:true,immutableSnapshot:true,rejected:reject,validRecoveryAfterRejection:true,restoredStrictEqualityMutation:{current:'HAS_GEOMETRY',mutant:null,masterField:pub.master.fieldDegrees,overviewField:pub.levels.OVERVIEW.fieldDegrees,label:'Bounded wrapper mutation, not exact saved historical source replay'},scope:'36 finite native/TAN raw-rays across actual report and admitted nonorthogonal matrix. Nominal geometry only; not absolute astrometry, full-grid or continuous GPU precision proof.'};
}

try{
 admit(fileURLToPath(import.meta.url));admit('tools/run-node.cjs');admit(process.execPath);
 for(const name of fs.readdirSync(path.resolve(ROOT,source)))if(fs.statSync(path.resolve(ROOT,source,name)).isFile())admit(source+'/'+name);
 admit(source+'/result.json',{bytes:25785,sha256:'5177aade2564a403a6ae6ac1f13ce06a6c32274df5535adc86fbf11b208e7ddc'});
 const r=json(source+'/result.json'),host=json(source+'/inputs-before.json'),parsed=json(source+'/parsed-inputs.json');assert.equal(r.status,'PASSED_TASK_ONLY_PREPARED_DISPLAY_CANDIDATE_PIXELS_NOT_ADOPTED');assert.deepEqual(r.errors,[]);assert.deepEqual(host,json(source+'/inputs-after.json'));assert.deepEqual(parsed,json(source+'/parsed-inputs-after.json'));assert.equal(host.length,19);assert.equal(parsed.length,98);for(const b of[...host,...parsed])admit(b.path,b);
 const authorPath=task+'/scripts/experience-prepared-report-display-2026-10-03.mjs';assert.deepEqual(read(authorPath),read(source+'/executed-script.mjs'));
 const protectedPath=task+'/tmp/resume-preserved-hashes-2026-10-01.json';admit(protectedPath);for(const b of json(protectedPath)){admit(b.path,b);assert(host.some(x=>x.path===b.path&&x.sha256===b.sha256));}
 const require=createRequire(path.resolve(ROOT,'apps/wechat-miniapp/package.json')),ts=require('typescript');assert.equal(ts.version,'5.9.3');
 const entry=read(source+'/executed-browser-entry.ts').toString('utf8'),ast=ts.createSourceFile('entry.ts',entry,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);assert.equal(ast.parseDiagnostics.length,0);const nodes=[];const walk=n=>{nodes.push(n);ts.forEachChild(n,walk);};walk(ast);
 const declaration=name=>{const all=nodes.filter(n=>ts.isVariableDeclaration(n)&&n.name.getText(ast)===name);assert.equal(all.length,1,name);return all[0].initializer;};
 const pub=JSON.parse(declaration('publication').getText(ast)),data=JSON.parse(declaration('data').getText(ast)),physical=JSON.parse(declaration('physicalObservation').getText(ast));assert.deepEqual(physical,json(source+'/physical-report.json'));assert.deepEqual(physical,r.physicalObservation);const manifestPath='output/prepared-optical-publication-1003-r4/publication/manifest.json';admit(manifestPath,{sha256:'23faa1521ae39a6a7d92f36c87ebf691a75b6bd7b91a3654e9b24f63f4d793f1'});assert.deepEqual(pub,json(manifestPath));
 const calls=nodes.filter(n=>ts.isCallExpression(n)&&n.expression.getText(ast)==='createSkyGpuRenderer');assert.equal(calls.length,1);assert.deepEqual(calls[0].arguments.map(n=>n.getText(ast)),['gl','1','{imageFailed:image=>failed.push(Object.entries(images).find(([,x])=>x===image)?.[0])}']);
 for(const s of["skyScene:{state:'UNAVAILABLE',catalog:null",'sunAltitudeDeg:-24','registerSkyPreparedOpticalFootprints(frame,physicalObservation)','commonFootprints.at!==at','commonFootprints.equatorialToEnu.some','gl.getUniform(gl.getParameter(gl.CURRENT_PROGRAM),location)','if(condition.retireFine)active[condition.level]=false','renderer.dispose();retire.forEach(fn=>fn())'])assert(entry.includes(s),s);
 const changed=parsed.filter(b=>b.sha256!==b.executedSha256);assert.equal(changed.length,2);const recipe=json(source+'/task-display-recipe.json'),transformRecords=[];
 for(const b of changed){const original=read(b.path).toString('utf8'),name=path.basename(b.path),executed=read(source+'/executed-task-'+name);let expected;
  if(name==='sky-artwork-level-composition.ts')expected=original.replace('    uniform float u_opacity;','    uniform float u_opacity;\n    '+recipe.recipe).replace('      float contribution = max(max(rgb.r,rgb.g),rgb.b);','      float sourceContribution = max(max(rgb.r,rgb.g),rgb.b);\n      float contribution = sourceContribution*preparedDisplayWeight(ray,rgb);').replace('      vec3 straight = contribution > 0.0 ? rgb/contribution : vec3(0.0);','      vec3 straight = sourceContribution > 0.0 ? rgb/sourceContribution : vec3(0.0);');
  else{assert.equal(name,'sky-gpu-renderer.ts');const marker='u_opacity:Math.min(1,opacity), ...uniforms("coarse",coarse), ...uniforms("fine",fine),',extra='u_preparedFootprintsReady:levels.taskPreparedFootprints ? 1 : 0, ...Object.fromEntries(["source","master"].flatMap(name=>[0,1,2].map(i=>["u_"+name+"FootprintRow"+i,levels.taskPreparedFootprints?.[name]?.[i]??[0,0,0]]))),';assert.equal(original.split(marker).length,2);expected=original.replace(marker,marker+'\n          '+extra);}
  assert.equal(executed.toString('utf8'),expected);assert.equal(sha(executed),b.executedSha256);assert.equal(executed.length,b.executedBytes);transformRecords.push({original:binding(b.path),executed:binding(source+'/executed-task-'+name),exactOnlyDeclaredTransform:true});}
 assert.equal(recipe.geometryAlpha,'UNCHANGED');assert.equal(recipe.scientificAvailability,'UNKNOWN');assert(recipe.recipe.includes('if(sourceCoordinates.z<=0.0 || masterCoordinates.z<=0.0) return 0.0;'));assert(!recipe.recipe.includes('scientific'));
 const meta=json(source+'/bundle-metafile.json');assert.deepEqual(Object.keys(meta.inputs).filter(k=>k!=='<stdin>').sort(),parsed.map(b=>b.path).sort());for(const b of parsed)assert.equal(meta.inputs[b.path].bytes,b.executedBytes);assert.equal(Object.values(meta.outputs).length,1);assert.equal(Object.values(meta.outputs)[0].bytes,read(source+'/executed-browser-bundle.js').length);assert.equal(Object.values(meta.outputs)[0].imports.length,0);
 const direct=controls(pub,physical,r.rows[0].commonFootprints);write('actual-owner-controls.json',direct);
 const sourcePng=[];for(const[level,a]of Object.entries(pub.levels)){const p='output/prepared-optical-publication-1003-r4/publication/'+a.file,b=read(p);admit(p,a);assert.deepEqual(Buffer.from(data[level].split(',')[1],'base64'),b);const d=png(b,512,512),counts={opaque:0,partial:0,zero:0};for(let i=3;i<d.rgba.length;i+=4)counts[d.rgba[i]===255?'opaque':d.rgba[i]===0?'zero':'partial']++;assert.deepEqual(counts,a.alphaPixels);assert.equal(a.displayAlpha,'geometric-source-area');assert.equal(a.scientificAvailability,'UNKNOWN');sourcePng.push({level,encoded:binding(p),decodedRgbaSha256:sha(d.rgba),alphaPixels:counts,filters:d.filters});}assert.equal(sourcePng.reduce((s,b)=>s+b.encoded.bytes,0),1315239);
 const rows=[],raws=new Map();for(const row of r.rows){const name=row.condition.name,stem=source+'/'+name;admit(stem+'.rgba',row.rgba);admit(stem+'.png',row.png);admit(stem+'-baseline.rgba',{bytes:390*844*4,sha256:row.baselineRgbaSha256});const raw=read(stem+'.rgba'),bg=read(stem+'-baseline.rgba'),d=png(read(stem+'.png'),390,844);assert.equal(raw.length,1316640);for(let y=0;y<844;y++)assert.deepEqual(d.rgba.subarray(y*1560,(y+1)*1560),raw.subarray((843-y)*1560,(844-y)*1560));const effect=diff(raw,bg);assert.equal(effect.rgbPixels,row.differentPixels);assert.equal(effect.rgbaPixels,effect.rgbPixels);for(let i=3;i<raw.length;i+=4)assert.equal(raw[i],255);assert.equal(row.error,0);assert.equal(row.done,1);assert.equal(row.completed,null);assert.equal(row.liveTextureObjects,0);assert.equal(row.textureObjects.created,row.textureObjects.deleted);assert.deepEqual(row.commonFootprints,direct.savedBrowserRows);
  const names=['source','master'].flatMap(p=>[0,1,2].map(i=>'u_'+p+'FootprintRow'+i));assert.deepEqual(row.footprintUniforms.map(u=>u.name),row.condition.wrongPort?[]:names);for(const u of row.footprintUniforms){const match=/u_(source|master)FootprintRow([0-2])/.exec(u.name),expected=direct.savedBrowserRows[match[1]][Number(match[2])];assert.deepEqual(u.supplied,expected);assert.deepEqual(u.stored,expected.map(Math.fround));}
  assert.deepEqual(json(stem+'-actual-summary.json'),{condition:row.condition,error:row.error,done:row.done,failed:row.failed,completed:row.completed,textureObjects:row.textureObjects});raws.set(name,raw);rows.push({condition:row.condition,rgba:binding(stem+'.rgba'),png:binding(stem+'.png'),pngFilters:d.filters,rgbaExactPngYFlip:true,effectVersusOwnBackground:effect,uniforms:row.footprintUniforms,textureObjects:row.textureObjects,currentDisposeTextures:0,completed:null});}
 assert.deepEqual(raws.get('retired-detail-coarse'),raws.get('medium-only-same-view'));assert.deepEqual(raws.get('wrong-family-port'),read(source+'/wrong-family-port-baseline.rgba'));const fineEffect=diff(raws.get('detail-parent-rotated'),raws.get('medium-only-same-view'));assert(fineEffect.rgbPixels>0);
 const dev=[];for(const dir of['output/prepared-footprint-registration-1003-r1','output/prepared-footprint-registration-1003-r2']){for(const name of fs.readdirSync(path.resolve(ROOT,dir)))if(fs.statSync(path.resolve(ROOT,dir,name)).isFile())admit(dir+'/'+name);const before=json(dir+'/inputs-before.json');assert.deepEqual(before,json(dir+'/inputs-after.json'));if(dir.endsWith('r2'))for(const b of before)admit(b.path,b);dev.push({generation:dir,result:json(dir+'/result.json'),selectedBindingsExact:true});}assert(read('output/prepared-footprint-registration-1003-r1/registration-tests.stdout.log').toString().includes('actual: null'));assert(read('output/prepared-footprint-registration-1003-r2/registration-tests.stdout.log').toString().includes('pass 12'));
 const priorIndependent='output/prepared-footprint-display-independent-1003-r3/result.json';admit(priorIndependent,{sha256:'ef61f193fd052385cc104e506f7faacf43785fb4b9cfc8d19d3978801ab0913d'});const nominal=json(priorIndependent).displayReview.geometry;assert.equal(nominal.masterNpy.sha256,pub.master.rgbaNpy.sha256);admit(nominal.sourceRawJpegHashOnly.path,nominal.sourceRawJpegHashOnly);admit(nominal.sourceRawXmp.path,nominal.sourceRawXmp);admit(nominal.masterNpy.path,nominal.masterNpy);
 const metaPrior=json('output/prepared-information-independent-1003-r1/inputs-before.json');admit('output/prepared-information-independent-1003-r1/inputs-before.json');for(const p of['workers/miniapp-api/src/prepared-optical-imagery.ts','workers/miniapp-api/src/sdss-optical-imagery.ts','workers/miniapp-api/src/celestial-object-information.ts','workers/miniapp-api/src/miniapp-service.ts','apps/wechat-miniapp/src/services/api-client.ts','apps/wechat-miniapp/src/services/celestial-information-response.ts','apps/wechat-miniapp/src/services/celestial-information-presentation.ts']){const b=metaPrior.find(b=>path.resolve(ROOT,b.path)===path.resolve(ROOT,p));assert(b);admit(p,b);}
 const originalNoFootprint=read('apps/wechat-miniapp/src/features/sky/sky-gpu-renderer.ts').toString('utf8');assert(!originalNoFootprint.includes('taskPreparedFootprints'));assert(!read('apps/wechat-miniapp/src/features/sky/sky-artwork-level-composition.ts').toString('utf8').includes('u_preparedFootprintsReady'));
 const mutation=Buffer.from(raws.get('detail-parent-rotated'));mutation[2048]^=1;assert(diff(mutation,raws.get('detail-parent-rotated')).changedBytes===1);
 for(const name of fs.readdirSync(path.resolve(ROOT,'output/prepared-report-footprint-independent-1003-r1')))admit('output/prepared-report-footprint-independent-1003-r1/'+name);
 const before=[...inputs.values()],after=before.map(b=>binding(b.path));assert.deepEqual(before,after);write('bindings.json',{inputsBefore:before,inputsAfter:after,unchanged:true});
 write('result.json',{status:'INDEPENDENT_BOUND_REPORT_FOOTPRINT_AND_SAVED_UNIFORMS_PASS_NOT_ADOPTED',owner:binding('apps/wechat-miniapp/src/features/sky/sky-prepared-optical-footprint.ts'),authorResult:binding(source+'/result.json'),physicalReport:physical,publication:binding(manifestPath),publicationHash:pub.publicationHash,helperControls:binding(out+'/actual-owner-controls.json'),sourcePng,fullFrames:rows,realFineEffect:fineEffect,uniformReadbacks:30,originalToExecutedTransforms:transformRecords,parserInputs:98,hostInputs:19,currentInputs:before.length,protectedCurrentExact:6,metadataOwnersCurrentExact:7,developmentHistory:dev,priorClosedNominalGeometryReused:binding(priorIndependent),singleChangedByteDetection:true,allCurrentBeforeAfterExact:true,visual:'Actually inspected actual-report OVERVIEW and rolled DETAIL. Colour ratios and rotated spiral structure are visible; rectangle is muted on controlled dark background. Weak outskirts attenuation and cross-LOD/tone/fullcomposition/edge quality are unresolved.',limits:['Only nominal AVM/linear TAN geometry; original 5arcsec publisher note is unverified, not new physical accuracy','No full source/TAN grid, shader Float32 coverage proof, original JPEG/FITS decode or reprojection repeated','Only six wrapped texture-object counters with dispose0; no complete buffer/FBO/byte/driver/native memory ledger or capacity proof','Controlled catalog UNAVAILABLE and NIGHT sun altitude input, not an actual full-scene astronomical report/interactive journey','All six optical completions null under original aux-disabled policy; no full visible credit or page/Hook/accepted lifecycle evidence','8% edge/luma display remains task-only/unadopted, geometric alpha unchanged and science UNKNOWN','Selected parser/host receipts plus frozen bundle; no complete loaded vendor/tool trace or independently reproducible build assertion','Historical R1 exact owner source was not saved in its output; actual failure logs and recorded SHA retained, wrapper equality mutation clearly separate']});
 console.log(JSON.stringify({result:binding(out+'/result.json'),bindings:binding(out+'/bindings.json'),controls:binding(out+'/actual-owner-controls.json'),inputs:before.length,maxSourcePixels:direct.maxSourcePixels,maxMotherPixels:direct.maxMotherPixels,fixedIcrsError:direct.fixedIcrsOnActualEnuCounterexamplePixels,fineEffect}));
}catch(error){write('failed.json',{status:'FAILED_INDEPENDENT_READER_OR_CONTROL',message:String(error),inputs:[...inputs.values()]});throw error;}
