"""Keep measured units and the remaining live page/Scene dependency in their owners."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[4];TASK=ROOT/'.codex/work-items/cloud-sky-native-2026-09-22'
summary=('新增[隔离业务冷入口/真实编码出口](evidence/experience-business-cold-encoded-http-2026-10-03.md)：当前controller/service/Etag/filter与缓存Caddy实际26响应，测试仓库1正式点/天气明确fixture，AQ实际adapter合成transport无供应商请求，BSC8404/OpenNGC51与地形PNG复用真源。context/report/catalog四入口795677编码B/2107704解码B，12业务冷读2689271编码B；栏目/地形按需不冒每DAU必取。四304零正文、recent no-store仍200、AQ暖不增合成调用、提案本人/越权/错context与地形PARTIAL/light未知均实测。r1progress/r2overview任务断言失败保持，r3完成HTTP后因Caddy空user_id断言失败，当前仅修该断言未重HTTP；保存raw/gzip/log multiset读回核全26响应与源pins、非空身份/decoded当已传控制拒绝，非独审。新增部分单位账本r2保旧model与总量未知，r1误字段失败保持；旧R5不只预report，还预BSC/figures/positions，不混不同epoch/表示层，joint编码总量null。无生产源码改/共享BFF写入重启/导出下载/部署采用。\n\n')
next_step=('当前唯一下一依赖仍是D：隔离业务context/report/environment/map/terrain与编码正文单位已取得，接下来复用现有实际page/Scene owner，接隔离真实context/report/BSC/constellation/position HTTP，令普通业务与实际Sky需求同场消费并记录真实编码正文与时刻；不只重放请求或复测旧R5/cohort，不把预注入figures/positions当完整冷进入，不混不同context/time/epoch/表示层或假设WEAPP Accept-Encoding已验。fixture业务/合成provider只供开发，不冒真实population/权限费用；不写共享BFF，不200DAU当200并发。预期配置/公网12Mbps/CPU-RSS/DB-Redis-outbox-media及月费/流量/180GB总盘仍未验。远端actual mounts/receipts、rollback/Sky-backup全集未知，不重复SSH/runtime矩阵/旧库存/HTTPdryrun，不清理/部署/发布。B完整图质/rights/背景/绿晕/弱结构/coverage、三级显示/信用加工/独审/批量出版/Source Back仍须交付；matching不采用/不循环参数。ordinary science/Prepared registry空，HST矩形FAILED/M82完整输入缺；actual page/native/Android/iOS/newMoon及全产品物理资源义务不缩减。')
p=TASK/'PLAN.md';s=p.read_text(encoding='utf-8');assert '隔离业务冷入口/真实编码出口' not in s
lines=s.splitlines();i=next(i for i,l in enumerate(lines) if l.startswith('当前唯一下一依赖仍是D：'));lines[i]=summary.rstrip()+'\n\n'+next_step
s='\n'.join(lines)+'\n';s=s.replace('D当前isolated ordinary-business完整context/report/environment/map/terrain冷入口与编码出口；部分200DAU模型已开发，远端/全集/容量及B完整图质未验','D实际page/Scene接隔离context/report/catalog/figures/positions并与普通业务同场消费；已测业务编码单位，远端/全集/容量及B完整图质未验',1);p.write_text(s,encoding='utf-8')
p=TASK/'CONTINUE-CLOUD-SKY.md';s=p.read_text(encoding='utf-8');anchor='新增[全小程序200DAU输入/计量边界]';i=s.index(anchor);end=s.index('\n\n',i)
s=s[:end+2]+summary+s[end+2:];s=s.replace('current-execution-state-2026-10-03-r41.json','current-execution-state-2026-10-03-r42.json');p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/deployment/decisions-and-verification.md';s=p.read_text(encoding='utf-8');anchor='## Remaining Decisions And External Inputs';assert anchor in s
entry=('An isolated current business HTTP lane through the existing cached Caddy has supplied measured context/report/catalog/map/content/environment/terrain encoded response units, with gzip/identity and conditional/no-store semantics checked against saved raw bytes and actual privacy-filtered log sizes. Business population/weather are explicit fixtures; an actual AQ adapter with synthetic transport is not supplier evidence. Existing real BSC/OpenNGC/terrain input identities remain separate. The old software Scene preloads report, attached BSC, figures and selected positions; different contexts/epochs and callback-vs-encoded layers must not be added into a claimed joint journey. Actual WEAPP encoding, live page/Scene mixed consumption, production population/provider/host costs and capacity remain unverified. Task final privacy assertion failure is retained; byte/log readback does not count as independent review. See [measured units and remaining consumers](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-business-cold-encoded-http-2026-10-03.md).\n\n')
s=s.replace(anchor,entry+anchor,1);p.write_text(s,encoding='utf-8')
p=TASK/'scripts/capture-current-execution-2026-10-03.ps1';s=p.read_text(encoding='utf-8')
files=['experience-business-cold-egress-2026-10-03.mts','readback-business-cold-egress-2026-10-03.py','build-business-cold-unit-ledger-2026-10-03.py','record-business-cold-continuity-2026-10-03.py']
s=s.replace('$sources = @(\n','$sources = @(\n'+''.join('  "$taskRoot/scripts/'+v+'",\n' for v in files),1)
results=['output/business-cold-egress-1003-r1/failure.json','output/business-cold-egress-1003-r2/failure.json','output/business-cold-egress-1003-r3/failure.json',
 'output/business-cold-egress-1003-r3/inputs-before.json','output/business-cold-egress-1003-r3/caddy.log','output/business-cold-egress-readback-1003-r1/result.json',
 'output/business-cold-unit-ledger-1003-r1/failed.json','output/business-cold-unit-ledger-1003-r2/result.json']
s=s.replace('$results = @(\n','$results = @(\n  "$taskRoot/evidence/experience-business-cold-encoded-http-2026-10-03.md",\n'+''.join("  '"+v+"',\n" for v in results),1)
lines=s.splitlines()
for i,l in enumerate(lines):
 if l.strip().startswith("toolObserved='"):
  lines[i]="    toolObserved='Isolated current controller/service/filter/Etag and cached local Caddy completed26 HTTP units: fixture1formal spot/weather/recent, actualAQadapter controlledsynthetictransport, realBSC8404/OpenNGC51/terrainPNG. Context/report/catalog4units795677encoded B/2107704decoded B,12coldbusiness2689271encoded B; optionalcontent/terrain not perDAU.4conditional304/no-store200/AQwarm noadded syntheticcalls/privateproposal andcontext guards/terrainPARTIAL-lightUNKNOWN observed. r1progress/r2overview task assertions failed; r3 final task privacy assertion failed on emptyuser_id AFTER26HTTP semanticchecks; all failures retained. Only empty-or-absent policy corrected, not HTTP rerun. Savedraw/gzip/status-size-logmultiset/currentpins readback passes; nonemptyidentity anddecoded-as-delivered controls reject, not independent review. Newpartialunitledger r1schemaexpectationfailure retained/r2usesactual oldcapacityfield. R5preloadsreport/BSC/figures/positions; no differentepochs or representationlayers summed, jointencodedjourney null. Productcode/sharedBFF/protected unchanged, no export/download/suppliercall/restart/SSH/deploy/adoption. Native/quality/provider/wholecost/capacity/review gaps remain.'"
 if l.strip().startswith("next='"):
  lines[i]="    next='PLAN D: actual page/Scene consume isolated live context/report/BSC/constellation/position HTTP plus ordinary business demand, measure encoded bodies/timing/coldwarmfailure optional units; no request-onlyreplay as Scene/firstusable or oldR5/cohortrepeat. Different context/time/epoch/representation not added. Fixture not population/provider entitlement/cost. WEAPPencoding/zstd, sharedBFFsource, expected production/mixedDBRedisoutboxmedia/12Mbps/CPU-RSS/monthlycost/full180GB/remote mountsreceiptsrollbackSkybackup unknown. No200DAU as200concurrent, sharedwrite/restart/SSHloop/cleanup/deploy/publish. Bcompletequality/rights/weakstructure/coverage/publicationBack, emptyordinaryregistry, native/devices/resources and independentreview remain open.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
baseline=json.loads((TASK/'evidence/current-execution-state-2026-10-03-r41.json').read_text(encoding='utf-8'));count=0
for v in baseline['currentSources']:
 if v['path'].startswith(('data-pipelines/','workers/','apps/','packages/','tools/deployment/')):
  raw=(ROOT/v['path']).read_bytes();assert len(raw)==v['bytes'] and hashlib.sha256(raw).hexdigest()==v['sha256'];count+=1
print(json.dumps({'productionFilesExactAgainstR41':count,'next':'D_actual_live_page_scene_and_ordinary_business','goal':'active_unbudgeted'}))
