"""Keep current model scope and one actual mixed-consumer dependency."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[4];TASK=ROOT/'.codex/work-items/cloud-sky-native-2026-09-22'
name='experience-whole-miniapp-cost-inputs-2026-10-03.md'
summary=('新增[全小程序200DAU输入/计量边界](evidence/'+name+')：复用r40 exact186源/保护pins及R5，不重跑服务/HTTP/库存。109接口/13家族逐项保权限/实际使用未知，额外平台/包分发/投稿媒体/审核/天气/DB/worker/磁盘费用角色显式。R5已预注入837654B report，不能冷callback当完整进入；成功冷正文表示1391986B、28步12801829B，四失败/取消182456B拟供应量不冒已传/零量。10/20×12Mbps只按记录表示且不再压缩的条件算术，Caddy原gzip/zstd/真实编码与first usable未知。天气/预警/AQ/近期Geo及区域日期实际cache单位分开，不按DAU或旧90%hits缩放。旧model/场景保原，r1状态字面量误用失败保留、r3细化压缩限定；completion-only计量mutation检出，Decimal/109合同/17源snapshot读回通过，非独审/容量。whole月流量/月费/180GB余量均UNKNOWN；历史820/1080改明确历史，不补价/采购/部署。\n\n')
next_step=('当前唯一下一依赖仍是D：source-bound全小程序200DAU部分输入模型已开发，先直读当前isolated ordinary-business HTTP/context/report/environment/map/terrain消费者的formal/proposal权限、真实population及provider/cache边界；补完整冷入口已预注入report/业务read序列及body/编码出口，再把实际Sky需求接混合harness。开发provider fixture须显式，不冒正式数据/实际天气/目标生产；不写共享业务Context，不200DAU当200并发，不旧static cohort当10/20混合/first usable验收。远端actual mounts/receipts、rollback/Sky-backup全集/物理保留未知，不重复SSH/runtime矩阵/旧库存/HTTP/dry-run，不清理/部署/发布。DB backup-v1不冒Sky备份，当前/获准旧URL/来源/未知继续保留。B完整图质开放，matching不采用/不循环参数，背景/绿晕/弱结构/coverage、三级显示/来源权益信用加工/独审/批量出版/Source Back仍须交付。ordinary science/Prepared registry空，HST矩形FAILED/M82完整输入缺；actual page/native/Android/iOS/newMoon、全产品总资源/180GB余量、预期配置容量义务不缩减。')
p=TASK/'PLAN.md';s=p.read_text(encoding='utf-8');assert '全小程序200DAU输入/计量边界' not in s
lines=s.splitlines();i=next(i for i,l in enumerate(lines) if l.startswith('当前唯一下一依赖仍是D：'));lines[i]=summary.rstrip()+'\n\n'+next_step
s='\n'.join(lines)+'\n';s=s.replace('D全小程序200DAU成本/混合容量模型的缺失实际输入；文件引用和非deploy绑定已开发，远端/全集及B完整图质未验','D当前isolated ordinary-business完整context/report/environment/map/terrain冷入口与编码出口；部分200DAU模型已开发，远端/全集/容量及B完整图质未验',1);p.write_text(s,encoding='utf-8')
p=TASK/'CONTINUE-CLOUD-SKY.md';s=p.read_text(encoding='utf-8');i=s.index('新增[非deploy实际current/runtime消费者修复]');end=s.index('\n\n',i)
s=s[:end+2]+summary+s[end+2:];s=s.replace('current-execution-state-2026-10-03-r40.json','current-execution-state-2026-10-03-r41.json');p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/deployment/decisions-and-verification.md';s=p.read_text(encoding='utf-8');anchor='## Remaining Decisions And External Inputs';assert anchor in s
entry=('Whole-miniapp cost modelling must preserve demand units and missing families. A controlled Sky scene that preloads its report does not supply the complete context/report/catalog cold-network path. Successful callback representation lengths are not encoded wire/provider-metered egress; failed/aborted offered bytes remain unknown delivery. Existing Caddy zstd/gzip must be accounted before interpreting 12Mbps body-volume arithmetic. Contract coverage does not establish active permission/data/usage; native platform/package origins, contribution media/review, ordinary authenticated business, provider requests and host storage stay separate. Weather uses actual rounded-point/configuration, on-demand validity, cache pressure/restart and separate Geo/history-date units, not DAU proportional scaling or a generic CDN hit assumption. Current task model binds these units but leaves whole-product monthly bytes/cash/free disk/capacity unknown. See [source-bound input and missing consumer scope](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/'+name+').\n\n')
s=s.replace(anchor,entry+anchor,1);p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/product-profile.md';s=p.read_text(encoding='utf-8');old='- Mini Program planning reference is approximately CNY 820/month with the annual/commitment discounts or CNY 1080/month at standard rates. These figures include specified production/test compute and use calendar-month average DAU and distinct queried positions, including private points and cloud grids. Show annual upfront cash, actual entitlements, excluded acquisition/operation work and reassessment conditions. This Mini Program decision does not change native App selection or authorize spending.'
new='- The earlier Mini Program CNY 820/month discounted and CNY 1080/month standard totals are historical source/cost examples, not the current 200-DAU forecast or an adopted spending ceiling. Current whole-miniapp 200DAU and intended production/test resources are owned by [deployment capacity decisions](deployment/decisions-and-verification.md#current-capacity-target-200-dau-2026-10-02); actual operating cost remains unverified. Recalculate independent queried-position/provider demand, public/private/cloud-grid usage, ordinary business/media and actual host/delivery invoices. Show annual upfront cash, entitlements, excluded acquisition/operation work and reassessment conditions. This does not change native App selection or authorize spending.'
assert old in s;s=s.replace(old,new,1);p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/external-capabilities.md';s=p.read_text(encoding='utf-8');old='下列为采用报告的固定规划算例，非供应商包价、实际账单、容量证明或开支授权。按自然月实际请求重算，年付仅表示折后月均消耗，不表示每月现金支付。'
new='下列为采用报告的历史固定规划算例，非当前200DAU预测、供应商包价、实际账单、容量证明或开支授权。当前全小程序200DAU与预期生产4核16GB/12Mbps/2000GB月出流量/180GB SSD、测试4GB由[deployment owner](deployment/decisions-and-verification.md#current-capacity-target-200-dau-2026-10-02)维护，不按旧DAU/机器/CDN或价目同比缩放。天气实际调用按独立请求坐标/配置、有效期、访问、缓存压力/重启、Geo与区域历史日期单独核算；whole月费仍未核。按自然月实际请求重算，年付仅表示折后月均消耗，不表示每月现金支付。'
assert old in s;s=s.replace(old,new,1);p.write_text(s,encoding='utf-8')
p=TASK/'scripts/capture-current-execution-2026-10-03.ps1';s=p.read_text(encoding='utf-8')
items=['project_context/product-profile.md','project_context/external-capabilities.md','packages/miniapp-contracts/api/miniapp.operations.json','workers/miniapp-api/src/weather-provider.ts','workers/miniapp-api/src/air-quality-provider.ts','workers/miniapp-api/src/recent-weather-provider.ts','workers/miniapp-api/src/computation-cache.ts','apps/wechat-miniapp/src/services/spot-environment-client.ts']
items=[v for v in items if "'"+v+"'" not in s and '"'+v+'"' not in s]
s=s.replace('$sources = @(\n','$sources = @(\n'+''.join("  '"+v+"',\n" for v in items)+'  "$taskRoot/scripts/build-whole-miniapp-cost-inputs-2026-10-03.py",\n  "$taskRoot/scripts/readback-whole-miniapp-cost-inputs-2026-10-03.py",\n  "$taskRoot/scripts/record-whole-miniapp-cost-continuity-2026-10-03.py",\n',1)
results=['output/whole-miniapp-cost-inputs-1003-r1/failed.json','output/whole-miniapp-cost-inputs-1003-r2/result.json','output/whole-miniapp-cost-inputs-1003-r3/result.json','output/whole-miniapp-cost-inputs-1003-r3/readback.json','output/whole-miniapp-cost-inputs-1003-r3/mutation-output.txt']
s=s.replace('$results = @(\n','$results = @(\n  "$taskRoot/evidence/'+name+'",\n'+''.join("  '"+v+"',\n" for v in results),1)
lines=s.splitlines()
for i,l in enumerate(lines):
 if l.strip().startswith("toolObserved='"):
  lines[i]="    toolObserved='Source-bound partial whole-miniapp200DAU model developed from saved R5/current contracts/providers, no new HTTP/exports/download/reprocess.109operation contracts/13families explicit, activation/permissions/ordinary business/media/platform/package/provider/host costs not inferred. Preloaded report837654B not cold network; successful cold callback representation1391986B/full28step12801829B;182456offered failed/aborted bytes excluded, actual delivery unknown.10/20x12Mbps conditional recorded-length/no-further-encoding arithmetic, not online lower bound/first usable: existing Caddy gzip/zstd and actual wire unknown. Actual QWeather point/config/expiry/pressure/Geo/history units separate from DAU. Old model retained; r1 wrong status literal failure retained/r3 compression semantics refined. Completion-only accounting mutation rejects;109identities/Decimal/17source snapshots root readback pass, not independent review. Historical820/1080explicitly superseded as current cost. Whole monthly egress/cash/free disk/capacity unknown. No cleanup/deploy/publish/restart/supplier calls/SSH retry. All prior quality/native/device/review gaps preserved.'"
 if l.strip().startswith("next='"):
  lines[i]="    next='PLAN D: inspect current isolated ordinary-business HTTP/context/report/environment/map/terrain formal/proposal permissions/population/provider/cache consumer; fill preloaded cold report/context/read/encoded-output gaps, then combine actual Sky demand in mixed harness. Explicit fixtures not formal/provider/production evidence; no shared business Context mutations. No200DAU as200concurrent/old static cohorts as10/20mixed/first usable. Remote mounts/receipts/full rollback/Sky-backup/physical disk unknown; no repeated SSH/runtime/oldinventory/HTTPdryrun/cleanup/deploy. All admitted URLs/source/unknown retain. B complete quality/source/publication/Back, empty ordinary registry, native/devices/resources/180GB/expected capacity and independent review remain open.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
baseline=json.loads((TASK/'evidence/current-execution-state-2026-10-03-r40.json').read_bytes());count=0
for v in baseline['currentSources']:
 if v['path'].startswith(('data-pipelines/','workers/','apps/','packages/','tools/deployment/')):
  p=ROOT/v['path'];assert p.stat().st_size==v['bytes'] and hashlib.sha256(p.read_bytes()).hexdigest()==v['sha256'];count+=1
print(json.dumps({'productionFilesExactAgainstR40':count,'model':'PARTIAL_NO_TOTAL_COST_OR_CAPACITY','next':'D_actual_ordinary_cold_read_and_encoded_output'}))
