"""Keep the sole dependency current after real solar/pending consumers."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[4];TASK=ROOT/'.codex/work-items/cloud-sky-native-2026-09-22'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
prior=read(TASK/'evidence/current-execution-state-2026-10-03-r47.json');checked=[]
for v in prior['currentSources']+prior['protected']:
 if v['path'].startswith(('apps/','workers/','packages/','tools/deployment/','data-pipelines/')):
  b=(ROOT/v['path']).read_bytes();assert len(b)==v['bytes']and hashlib.sha256(b).hexdigest()==v['sha256'],v['path'];checked.append(v['path'])
r=read(ROOT/'output/playwright/cloud-sky-solar-pending-readback-1003-r2/result.json');assert r['currentSourcePinsExact']==271 and len(r['frames'])==82
summary=('新增[月面行星与活动page迟到读取](evidence/experience-solar-and-pending-page-2026-10-03.md)：r13复用final271源/同encodedowner，对当前真实方位角径作Moon与7planet新家族路径，6planet+Moon真实出版影像绑定GPU draw/金星现有解析外观；普通Prepared仍空。nativeUTF8真实read完成后扣delivery，pagehide只保1读取lease→迟到callback0/旧SAO无loaded-pending/无新accepted；回调次序源tile不同均按实际hash/index核。首次pendinghide返回task少一次绘制，粗Moontrue但readyimage0保FAILED；r14只补该次restore-before-ready/正向image，5帧真Moon恢复，不重planet矩阵；合计41软件帧/PNG-RGBA/当前pins/清理核，Moon暖取无图片HTTP/新decode。r13独立模型峰ownerRGBA10502144/pending8388608/MapFS7849435B，cache55/7807911B，GLtexture-buffer8404992/384B分层不求物理总；clear剩26B空inventory。两次base3×304；r13 80完成7725520B/6取消未知，r14 25完成2709950B/5取消且日志29≠30最后断言FAILED，成功multiset全匹配/4取消已记输出+1无日志不填零。根固定firsttilebytes误假设失败保留，r2改exactsource读回；无产品/其他业务源变化/保护6保持，非原生/物理/质量/成本容量/独审。\n\n')
next_step=('当前唯一下一依赖仍是D：同一encodedowner五组合与太阳系实际参与/活动pagehide-late已开发核，下一项核实际文件clear/generation与QueryClient/QueryObserver消费者、page隐藏再进入/显式重试恢复。已读当前clearTemporaryApiCache/cache-policy/useResourceQuery，临时根表缺sao-index；先复现实际影响而非用受控queryMap宣布通过，再做Sky范围必要修复，保持其他业务逻辑/账户天气策略与6设置-outbox保护项。复用final源/真实publication，同帧/租约/hash/完整写入/粗回退/迟到取消保留；r13第一Moon无图/r14日志数断言失败和根readback误firsttile保持，成功纹理draw或根通过不倒改epoch。无必要不重已完成五组合/solar/old9/fullcold/静态合同/加工下载或猜新框架；按总参与实测再决定queue/decode/warmcache/lifecycle优化。旧二进制JSONrollback/完整引用retention/full200MB、native公开时间/手势/来源Back/跟随校准/WXMLFAILED/Android+iOS新Moon、物理峰/whole200DAU费用月流量/CPU-RSS-DB-Redis-outbox-media/12Mbps10-20mixed容量/180GB和独审仍开放。B完整背景接缝绿晕弱结构配准覆盖/来源加工/批量出版及rights未过，Prepared/science registry空/HST矩形FAILED/M82缺输入；不采用候选/重复加工/DevTools启动循环，不提交推送采购云部署发布或缩减目标。')
p=TASK/'PLAN.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();i=next(i for i,l in enumerate(lines)if l.startswith('当前唯一下一依赖仍是D：'));lines[i]=summary.rstrip()+'\n\n'+next_step;s='\n'.join(lines)+'\n'
old='D已核最终源码page单owner五组合与分项静态出口；补月面行星实际参与及活动请求hide取消迟到，完整图质/原生/物理/回滚/容量未验';assert old in s
s=s.replace(old,'D已核单owner五组合、太阳系参与及pagehide迟到；补实际clear与Query缓存恢复，完整图质/原生/物理/回滚/容量未验',1);p.write_text(s,encoding='utf-8')
p=TASK/'CONTINUE-CLOUD-SKY.md';s=p.read_text(encoding='utf-8');anchor='新增[最终SAO/影像单owner实际pageScene]';i=s.index(anchor);end=s.index('\n\n',i);s=s[:end+2]+summary+s[end+2:];s=s.replace('current-execution-state-2026-10-03-r47.json','current-execution-state-2026-10-03-r48.json');p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/architecture/runtime-and-domain.md';s=p.read_text(encoding='utf-8');old='Actual solar participation and active pending-page cancellation/late delivery still need bounded current-path evidence.';assert old in s
new=('A bounded subsequent actual-page lane has supplied corresponding solar texture GPU participation for Moon, Mercury, Mars and the four OPAL planet families, plus the adopted analytic Venus appearance, using existing publications and current server body geometry. A real completed native SAO UTF8 read held at delivery survives page hide only as its single file lease; late delivery releases the lease without publishing into retired page/loader owners. Task restoration initially accepted a coarse Moon with no ready texture; that failed fact remains, and only the affected restore submission/positive-image readiness was repaired. These are controlled software/native-port development results, not physical total, whole native journey or scientific calibration. Actual file clear and Query-cache generation recovery remain unverified and must use actual Query consumers rather than the task Map. See [solar and late page evidence](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-solar-and-pending-page-2026-10-03.md).')
s=s.replace(old,new,1);p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/areas/main/screen-contracts/wechat-miniapp/spot-and-sky.md';s=p.read_text(encoding='utf-8');anchor='见[单owner页面证据]';i=s.index(anchor);end=s.index('\n',i)
s=s[:end]+' 后续Moon/7planet路径已核各真实影像/解析外观实际GPU参与和pagehide后迟到读取拒绝；首次恢复粗Moon无ready image失败保持，单项修task后有真texture。实际clear/Query恢复、完整UI与物理/质量仍缺，见[太阳系增量](../../../../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-solar-and-pending-page-2026-10-03.md)。'+s[end:];p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/deployment/decisions-and-verification.md';s=p.read_text(encoding='utf-8');anchor='A subsequent final-source extracted-page lane verified';i=s.index(anchor);end=s.index('\n\n',i)
s=s[:end]+' A later solar/pending-page lane also saw a cancelled request without a Caddy access log, while all completed receipt status/size pairs matched; count equality is not a valid invariant for pre-response cancellation. Missing/cancelled physical receipt bytes remain unknown. This observation does not support extrapolated monthly flow or capacity; see [saved solar protocol accounting](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-solar-and-pending-page-2026-10-03.md).'+s[end:];p.write_text(s,encoding='utf-8')
p=TASK/'scripts/capture-current-execution-2026-10-03.ps1';s=p.read_text(encoding='utf-8')
names=['build-solar-pending-page-2026-10-03.mjs','experience-solar-pending-page-2026-10-03.mts','build-solar-pending-return-2026-10-03.mjs','experience-solar-pending-return-2026-10-03.mts','readback-solar-pending-page-2026-10-03.py','record-solar-pending-continuity-2026-10-03.py']
add=''.join(f'  "$taskRoot/scripts/{n}",\n'for n in names)
for n in ['apps/wechat-miniapp/src/services/cache-policy.ts','apps/wechat-miniapp/src/services/query-client.ts','apps/wechat-miniapp/src/hooks/use-resource-query.ts']:
 if f"'{n}'"not in s:add+=f"  '{n}',\n"
s=s.replace('$sources = @(\n','$sources = @(\n'+add,1)
evidence=['.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-solar-and-pending-page-2026-10-03.md']
for rev in [13,14]:
 for n in ['executed-script.mts','final-owner.json','caddy.log','inputs-before.json','conditions.json','reused-build.json','api-inputs.json','source-binding-before.json']:
  evidence.append(f'output/playwright/cloud-sky-live-mixed-1003-r{rev}/'+n)
for n in ['result.json','wire-requests.json','delivery-accounting.json','inputs-after.json','pending-return-missing-image.json','solar-moon-pending-hide.json','solar-moon-warm-return-hidden.json','solar-moon-warm-return.json']:evidence.append('output/playwright/cloud-sky-live-mixed-1003-r13/'+n)
for n in ['live-failure.json','solar-moon-pending-return-corrected.json']:evidence.append('output/playwright/cloud-sky-live-mixed-1003-r14/'+n)
for n in ['executed-readback.py','failure.json']:evidence.append('output/playwright/cloud-sky-solar-pending-readback-1003-r1/'+n)
evidence.append('output/playwright/cloud-sky-solar-pending-readback-1003-r2/result.json')
for n in evidence:assert(ROOT/n).is_file(),n
s=s.replace('$results = @(\n','$results = @(\n'+''.join(f"  '{n}',\n"for n in evidence),1)
lines=s.splitlines()
for i,l in enumerate(lines):
 if l.strip().startswith("toolObserved='"):lines[i]="    toolObserved='r47 exact246current+6protected/workspaceHEADbranch; priorprogress. Samefinal271sourcebundles/oneencodedowner, current astronomy bodyvalues with testastronomy fixtureconfig. r13newMoon+7planet/warmMoon, r14onlyaffectedpending-return restoration/positiveMoonimage,41softwarePNG-RGBAframes sameframe. CorrespondingactualMoon-Mercury-Mars-4OPALreadyimages boundGPUdraws/Venusadoptedanalytic noimageclaim; no newsourceprocessing/rebuild/export/download. ActualnativeUTF8 helddelivery acrosspagehide preserves1readlease thenlate0/nooldSAOloadedpending/noacceptedframe. FirsttaskpendingreturnMoonready0/coarseMoontrue failedretained; onlytaskcorrectedsubmission andreadypositive5frames. Rootfirsttilefixed8684assumptionfailedretained; actualcallback32084or8684 exacthash-index-source readback. r13modelsownerRGBA10502144/pending8388608/MapFS7849435B/cache55-7807911B/GLtexture-buffer8404992-384B separate notphysical. r13success80-7725520B/cancel6; r14success25-2709950B/cancel5/log29vs30aggregateFAILEDretained, allsuccessmultisetmatch/4canceloutputlogs+1missing notzero. Both3basewarm304; finaldataqueueleasesretiredSAOGL0/emptyinventory26. ActualclearQuerygeneration unresolved, temporaryrootsnosao-index sourceobservation needsconsumerrepro; controlledqueryMapnotproof. No productsource/otherbusinesslogic changes/protected6exact/BFFwatchrestart/phone/deploy/adoption; independentreview missing.'"
 if l.strip().startswith("next='"):lines[i]="    next='PLAN D actualfileclear-generation plusrealQueryClient-QueryObserver/useResourceQuery pagehide-return/retry consumers; currenttemporaryrootsabsentsao-index inspect/reprobeforeSky-onlyfix, neverbroadordinarypolicyorprotectedsettings-outboxedits. Sameowner/nativelease/scientificbytes/coarsefallback invariants. No replaycompletedfive/solar/old9/fullcold/staticcontract or guessedframework/paidfacility. r13Moonready0/r14countfailed/rootfirsttilefailure epochsretained. OldbinaryJSONrollback/full200MB/fullretentionrefs/nativegesture-time-followcalibration-sourceBack/WXMLFAILED/Android-iOS-newMoon/physicaltotal/whole200DAUcostmonthlyflow/CPU-RSS-DB-Redis-outbox-media/12Mbps10-20capacity/180GB/Bfullqualityrights-publication/independentreview remain. Goalactiveunbudgeted; no otherbusinesslogic/commitpushdeployadoption.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'priorProductPinsExact':len(set(checked)),'protected6Exact':True,'goal':'active_unbudgeted','priorTurn':'progress','next':'D_actual_clear_query_generation'}))
