"""Record current measurement exceptions, affected repairs and actual remaining dependency."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[4];TASK=ROOT/'.codex/work-items/cloud-sky-native-2026-09-22'
previous=json.loads((TASK/'evidence/current-execution-state-2026-10-03-r43.json').read_text(encoding='utf-8'));count=0
for v in previous['currentSources']+previous['protected']:
 if v['path'].startswith(('data-pipelines/','workers/','apps/','packages/','tools/deployment/')):
  b=(ROOT/v['path']).read_bytes();assert len(b)==v['bytes']and hashlib.sha256(b).hexdigest()==v['sha256'];count+=1
summary=('新增[当前HTTP组合与全景/地景边界](evidence/experience-live-combination-and-dome-boundary-2026-10-03.md)：r4复用当前bundles/270精确源，9段54软件帧/94成功HTTP编码7583930B，图层/细化原生callback受控失败保MEDIUM→真实重试DETAIL、0/1/60秒跟踪拒旧及取消回原刻、最终owner退休已核，非公网断流/公共时间UI。较大旅程三个暖200在async storage已补时仍有，具体memory/disk淘汰原因未知。根读回r1抓到DOME字符串回退45，旧R5同名也45，不当历史全景；readiness中间帧/transition顶层值不冒稳定。r5仅两项受影响task入口修数值skyDomeFieldOfView及等待加载readiness1，实际267.87503292753496°/progress1与45返回、23帧/编码4423994B、PNG-RGBA/源/最终活动资源核，实际图已查看；45朝上不与alpha相交时opacity0合法，仍不替代地平相交材质完整fade/return。r1失败保留/r2核具体失败事实，不重9段/完整冷矩阵、不改生产/其他业务逻辑/预算或部署。\n\n')
next_step=('当前唯一下一依赖仍是D：先读实际response-cache memory/disk key与存储/压力owner，解释较大真实旅程async storage已补仍三个200的miss；用新有界淘汰证据，不循环9段/完整冷矩阵或凭猜测改预算/队列/缓存。复用已修数值全景和loaded-readiness端口，补地平相交视角下稳定材质渐隐/返回及实际取消迟到消费者组合。只改Sky及必需共享依赖，不改其他业务逻辑；普通业务仅隔离现有消费者。各epoch编码/解码/物理层分开，fixture/test-astronomy不冒真实population/provider费用或物理校准，200DAU不当200并发。公共时间/实际UI-Back/WXML失败、Android+iOS/newMoon、物理端云峰/CPU-RSS/DB-Redis-outbox-media/WEAPPencoding/12Mbps/10-20完整混合冷入口/月流量月费180GB与remote mounts-receipts-fullrollback/Skybackup仍缺，不循环SSH/DevTools或清理部署发布。B完整图质/背景接缝绿晕弱结构配准覆盖/rights/三级显示加工来源/批量出版与独审继续开放，ordinary Prepared/science registry空、HST矩形FAILED/M82完整输入缺；matching不采用，不重复下载/无变化加工，不缩减完整体验和最终验收。')
p=TASK/'PLAN.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();i=next(i for i,l in enumerate(lines)if l.startswith('当前唯一下一依赖仍是D：'));lines[i]=summary.rstrip()+'\n\n'+next_step
s='\n'.join(lines)+'\n';old='D当前实际HTTP/page-Scene补时间跟踪、图层全景渐隐、细化失败保粗及取消返回组合；最小交集和有限暖持久化已核，真实压力/物理/容量与B完整图质未验'
assert old in s;s=s.replace(old,'D解释当前真实较大旅程暖200的实际缓存压力owner，并补相交视角材质渐隐返回/取消迟到；数值全景task入口已修，物理/容量与B完整图质未验',1)
old='A受控page/Scene冷暖、全景/地景、选中失败保粗、图层/时间/跟踪、来源遮挡/hide与返回资源已开发核对'
assert old in s;s=s.replace(old,'A受控page/Scene冷暖、选中失败保粗、图层/时间/跟踪、来源遮挡/hide与返回资源已有开发核；旧R5标称全景实际45°的task输入缺口已明确，最新数值全景及loaded-readiness仅修受影响软件边界',1);p.write_text(s,encoding='utf-8')
p=TASK/'CONTINUE-CLOUD-SKY.md';s=p.read_text(encoding='utf-8');anchor='新增[当前API/实际软件Scene与混合测量端口]';i=s.index(anchor);end=s.index('\n\n',i);s=s[:end+2]+summary+s[end+2:];s=s.replace('current-execution-state-2026-10-03-r43.json','current-execution-state-2026-10-03-r44.json');p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/areas/main/screen-contracts/wechat-miniapp/spot-and-sky.md';s=p.read_text(encoding='utf-8');anchor='## 全景浏览、影像质量与端云性能（2026-10-02）';assert anchor in s
entry=('当前软件开发证据须按实际数值相机与已绘帧识别：旧R5标称full-sphere条件曾把task字符串DOME传入数值合同，实际45°，不能认证全景。任务端口已改用既有skyDomeFieldOfView并等待加载readiness1；这只核有限软件边界，视角渐隐、图像加载渐入与alpha/实际视场相交分别核，不能以朝上不相交的opacity0判图像坏，也不能以稳定加载验完整材质返回或native体验。当前真实HTTP较大旅程仍有暖200，须读实际缓存owner压力再调整。见[当前边界与保留缺口](../../../../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-live-combination-and-dome-boundary-2026-10-03.md)。\n\n')
assert '旧R5标称full-sphere'not in s;s=s.replace(anchor+'\n\n',anchor+'\n\n'+entry,1);p.write_text(s,encoding='utf-8')
p=TASK/'scripts/capture-current-execution-2026-10-03.ps1';s=p.read_text(encoding='utf-8');files=['build-live-combination-runner-2026-10-03.mjs','experience-live-combination-2026-10-03.mts','readback-live-combination-2026-10-03.py','build-live-dome-readiness-runner-2026-10-03.mjs','experience-live-dome-readiness-2026-10-03.mts','readback-live-dome-readiness-2026-10-03.py','record-live-combination-continuity-2026-10-03.py']
s=s.replace('$sources = @(\n','$sources = @(\n'+''.join(f'  "$taskRoot/scripts/{name}",\n'for name in files),1)
evidence=['.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-live-combination-and-dome-boundary-2026-10-03.md','output/playwright/cloud-sky-live-mixed-1003-r4/result.json','output/playwright/cloud-sky-live-mixed-1003-r4/inputs-before.json','output/playwright/cloud-sky-live-mixed-1003-r4/inputs-after.json','output/playwright/cloud-sky-live-mixed-1003-r4/final-owner.json','output/playwright/cloud-sky-live-combination-readback-1003-r1/failed.json','output/playwright/cloud-sky-live-combination-readback-1003-r1/executed-script.py','output/playwright/cloud-sky-live-combination-readback-1003-r2/result.json','output/playwright/cloud-sky-live-mixed-1003-r5/result.json','output/playwright/cloud-sky-live-mixed-1003-r5/inputs-before.json','output/playwright/cloud-sky-live-mixed-1003-r5/inputs-after.json','output/playwright/cloud-sky-live-mixed-1003-r5/final-owner.json','output/playwright/cloud-sky-live-dome-readiness-readback-1003-r1/result.json']
for name in evidence:assert (ROOT/name).is_file(),name
s=s.replace('$results = @(\n','$results = @(\n'+''.join(f"  '{name}',\n"for name in evidence),1)
lines=s.splitlines()
for i,l in enumerate(lines):
 if l.strip().startswith("toolObserved='"):lines[i]="    toolObserved='Current source270 exact actualHTTP/softwareScene9newconditions54frames:94success encoded7583930B, tasknativecallbackfail afterHTTPdispatch retainsMEDIUM/publicretryDETAIL;0-1-60sectracking rejects stale/canceloriginal, finalowner retired. Largerjourney3warm200 remains with asyncstoragecorrect, exactcachepressurecause unknown. Rootreadbackr1caught DOMEstring actual45 and oldR5same45, failedfactsretained/readbackr2records exception. Readinessloading/intermediatechildren separate fromviewfade. Only2affectedtaskcases corrected numeric ownermax267.87503292753496/progress1 and actualloadedreadiness1:23frames encoded4423994B/PNG-RGBA/currentpins/retirement, actualdomeviewseen. Abovehorizon45 view noalpha intersection may legitimatelypublishopacity0; no complete materialreturn/native/quality/capacity claim. No productcode/otherbusinesslogic/sharedBFFwrite-restart/download/SSH/deploy/adoption. Independentreview missing.'"
 if l.strip().startswith("next='"):lines[i]="    next='PLAN D: observe actual response-cache memorydiskkeys/storagepressure afterlargerlivejourney3warm200; newboundedcause/evictionevidence, no9condition/fullcoldreplay or guessedqueuebudgetcache optimisation. Use corrected numericDOME/loadedreadiness ports for actualintersecting-view materialfade-return/cancel-lateconsumers. Skyandnecessarysharedonly; otherbusinesslogicforbidden, ordinaryisolatedconsumersonly. OldR5namedfullsphere45notproof, testastronomyfixture preserved, differentepochsandrepresentationnotadded. NativeUIBack/WXMLfailure/devices/newMoon/physicaltotal/WEAPPencoding/12Mbps/10-20coldcapacity/productionCPU-RSS-DB-Redis-outbox-media/whole200DAUcostflow180GB/remotemountreceiptrollbackSkybackup/qualityrightsfullpublication/independentreview open. No SSH-DevToolsloop/cleanup/deploy/publish/adoption.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'productionProtectedExactAgainstR43':count,'goal':'active_unbudgeted','otherBusinessLogicChanged':False,'next':'D_cache_pressure_owner_and_intersecting_material_fade_return'}))
