"""Record bounded page result; retain full requirements and failed runner epoch."""
from pathlib import Path
import json, hashlib
ROOT=Path(__file__).resolve().parents[4]; TASK=ROOT/'.codex/work-items/cloud-sky-native-2026-09-22'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
prior=read(TASK/'evidence/current-execution-state-2026-10-03-r46.json')
checked=[]
for v in prior['currentSources']+prior['protected']:
    if v['path'].startswith(('apps/','workers/','packages/','tools/deployment/','data-pipelines/')):
        b=(ROOT/v['path']).read_bytes()
        assert len(b)==v['bytes'] and hashlib.sha256(b).hexdigest()==v['sha256'],v['path']
        checked.append(v['path'])
r=read(ROOT/'output/playwright/cloud-sky-shared-page-readback-1003-r2/result.json')
assert r['sourcePinsCurrentExact']==271 and len(r['frames'])==40 and r['warmStatuses']==[304]*3
summary=('新增[最终SAO/影像单owner实际pageScene](evidence/experience-final-shared-page-owner-2026-10-03.md)：page174/API150去重271当前源精确，task转发唯一实际runtime，每条件同一缓存实例/共同32MiB。仅五受影响冷宽场/数值全天/M51细化/来源hide-Back/宽场hide暖返回，20软件帧PNG-RGBA/同帧/返回保持，实际SDSS DETAIL+parent/W3 READY及宽场SAO绘制、3基础暖304；clear后活动图像/SAO/GL/租约退休，留26B空inventory。MapFS含暂存峰5598741B、图像RGBA模型14680064B/pending8388608B、GL texture/buffer各峰14680064/156636B分层不求物理总量。月面/行星未实际加载，参与家族不冒完整全集。实际静态JSON GET/hash/HEAD0/3040通过；最后aggregate计量断言FAILED保留，73完成接收6311671B/3取消未知，Caddy6338325含HEAD记20而收到0、3未匹配200/8878；根partition读回不倒改runner，未重HTTP。builder尾console/HEAD gunzip/复制metadata冲突/根credit层级错误保历史，后续task修复。无产品源/其他业务逻辑修改/共享BFF重启/下载加工部署采用；受控原生与softwareGL非WXML/物理/独审/容量。\n\n')
next_step=('当前唯一下一依赖仍是D：最终同一encoded owner的page/Scene已核五受影响组合，下一项补真实月面/行星家族参与以及活动page请求hide/取消/迟到结果，复用已缓存真源/current端口，以有界增量核同帧、encoded/parsed/decode/native/GPU/临时与退休；本次空的太阳系Hook不冒全家族通过。不要重五段/旧九段/fullcold矩阵或推测优化。按实际总参与和瓶颈再决定queue/decode/暖缓存与必要生命周期提取；维持完整性/租约/generation/迟到取消/粗层保留。静态JSON实际GET/HEAD/304已开发核，取消传输与HEAD Caddy bookkeeping分开；r12 aggregate仍FAILED，根保存读回不倒改epoch。旧二进制回滚JSON inventory/完整引用retention、全小程序200MB、native公开时间/手势/来源Back/跟随校准、WXML失败、Android+iOS/新版Moon、物理峰/whole200DAU端云月流量费用/生产CPU-RSS-DB-Redis-outbox-media/12Mbps10-20混合容量/180GB及独审仍开放。B完整背景接缝绿晕弱结构配准覆盖/来源加工/批量出版及rights未过，Prepared/science registry空/HST矩形FAILED/M82缺输入；不采用候选、不重复下载/无变化加工/DevTools启动循环。只改Sky及必要共享依赖，其他业务逻辑禁止，不提交推送采购云部署发布，不缩减完整目标。')
p=TASK/'PLAN.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();i=next(i for i,l in enumerate(lines) if l.startswith('当前唯一下一依赖仍是D：'));lines[i]=summary.rstrip()+'\n\n'+next_step;s='\n'.join(lines)+'\n'
old='D已开发SAO静态/共同文件持久owner并核有界实际压力暖304及迟到读；补最终源码实际page多家族单owner冷暖/返回/clear组合，原生/物理/回滚/容量与B完整图质未验';assert old in s
s=s.replace(old,'D已核最终源码page单owner五组合与分项静态出口；补月面行星实际参与及活动请求hide取消迟到，完整图质/原生/物理/回滚/容量未验',1);p.write_text(s,encoding='utf-8')
p=TASK/'CONTINUE-CLOUD-SKY.md';s=p.read_text(encoding='utf-8');anchor='新增[SAO标准静态与共同文件owner]';i=s.index(anchor);end=s.index('\n\n',i);s=s[:end+2]+summary+s[end+2:];s=s.replace('current-execution-state-2026-10-03-r46.json','current-execution-state-2026-10-03-r47.json');p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/architecture/runtime-and-domain.md';s=p.read_text(encoding='utf-8');old='Actual page/Scene image+SAO integration must use one encoded owner across task modules.';assert old in s
new=('Final source full API and extracted actual page/Scene integration has now been development-executed through one encoded owner across explicit task module forwarding. Five affected cold/warm, numeric full-sphere, selected fine and source/hide-return conditions preserve same-frame bindings and release active owners on hide/clear. This is controlled React/Taro/native/software GL evidence, not complete native UI or physical resources; solar image hooks did not load here. Encoded files/staging, parsed-publication JSON/numeric models, decoded/native images and GPU handle models remain separate. HEAD body receipts and cancelled-response log writes are separately accounted; the original aggregate assertion remains failed. Actual solar participation and active pending-page cancellation/late delivery still need bounded current-path evidence. See [single-owner page result and measurement limits](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-final-shared-page-owner-2026-10-03.md).')
s=s.replace(old,new,1);p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/areas/main/screen-contracts/wechat-miniapp/spot-and-sky.md';s=p.read_text(encoding='utf-8');anchor='详[当前源与组合缺口]';i=s.index(anchor);end=s.index('\n',i)
entry=' 当前最终源码已补五受影响actual page/software Scene单owner冷暖与来源/hide返回，PNG与同帧/资源退休读回成立；月面/行星未加载、活动请求迟到组合/完整原生UI仍缺，不能称全家族或最终验收。见[单owner页面证据](../../../../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-final-shared-page-owner-2026-10-03.md)。'
s=s[:end]+entry+s[end:];p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/deployment/decisions-and-verification.md';s=p.read_text(encoding='utf-8');anchor='SAO v2 published raw JSON now joins';i=s.index(anchor);end=s.index('\n\n',i)
entry=(' A subsequent final-source extracted-page lane verified actual static JSON hash/GET, zero-body HEAD and conditional304 on the same existing artifact. It also observed a gzip HEAD Caddy size20 with client body0 and three cancelled requests with unmatched logged output but unknown physical receipts; these are kept separate from successful received encoding. This fixes task accounting, not infrastructure deployment or final capacity. See [saved partitioned readback](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-final-shared-page-owner-2026-10-03.md).')
s=s[:end]+entry+s[end:];p.write_text(s,encoding='utf-8')
p=TASK/'scripts/capture-current-execution-2026-10-03.ps1';s=p.read_text(encoding='utf-8')
names=['build-shared-page-bundles-2026-10-03.mjs','shared-page-bundle-generated-2026-10-03.mts','build-shared-page-journey-2026-10-03.mjs','experience-shared-page-journey-2026-10-03.mts','readback-shared-page-owner-2026-10-03.py','record-shared-page-continuity-2026-10-03.py']
add=''.join(f"  '$taskRoot/scripts/{n}',\n".replace("'$taskRoot",'"$taskRoot').replace("',\n",'",\n') for n in names)
s=s.replace('$sources = @(\n','$sources = @(\n'+add,1)
evidence=[str((TASK/'evidence/experience-final-shared-page-owner-2026-10-03.md').relative_to(ROOT)).replace('\\','/')]
for n in ['live-failure.json','final-owner.json','executed-script.mts','static-json-contract.json','caddy.log','reused-build.json','shared-runtime-forwarding.json','shared-runtime-forwarding.ts.txt','api-file-cache.original.ts','api-file-cache.observed.ts','api-inputs.json','source-binding-before.json','inputs-before.json','conditions.json']: evidence.append('output/playwright/cloud-sky-live-mixed-1003-r12/'+n)
for n in ['executed-build.mts','build-failure.json','live-failure.json','executed-script.mts']:evidence.append('output/playwright/cloud-sky-live-mixed-1003-r11/'+n)
for n in ['result.json']: evidence.append('output/playwright/cloud-sky-shared-page-readback-1003-r2/'+n)
for n in ['executed-readback.py','failure.json']:evidence.append('output/playwright/cloud-sky-shared-page-readback-1003-r1/'+n)
for n in evidence: assert (ROOT/n).is_file(),n
s=s.replace('$results = @(\n','$results = @(\n'+''.join(f"  '{n}',\n" for n in evidence),1)
lines=s.splitlines()
for i,l in enumerate(lines):
    if l.strip().startswith("toolObserved='"):lines[i]="    toolObserved='Finalsource271union actualpage174/API150 taskbundles sameactualpublicruntime/onecache32MiB. Fiveaffectedconditions20softwareframes actualcold-wide/numericdome267.875/selectedSDSSDETAILparent-W3READY/sourcehideBack-widehidewarm; PNG-RGBA/sameframe/return exact. Warmbase3x304; staticJSONhashGET19433/gzip8574-HEAD0-3040. r12aggregateFAILEDretained:73received6311671B/3cancelunknown; Caddy6338325 includesHEADlogged20 receipt0 plus3unmatched200/8878, partitionrootreadback holds/noHTTPReplay. Modelpeaks ownerRGBA14680064/pending8388608/MapFS5598741, GPUtexture-buffer14680064/156636 separate notphysical; cache49/5560715 beforeclear then0/emptyinventory26, activeimages-SAOLoaders-GPU-leasesretire. Solarhooksnoimages/fullfamilyopen, controlledReactTaroquerynativeclocksoftwareGL/testastronomyfixtures notnativeUI. Buildfinalconsole/HEADgunzip/metadata-copy/readbackcredit-shape failures retained. No productsource/otherbusinesslogic changes/protected6exact/BFFrestart/downloadprocessing/export/deploy/adoption; independenteview missing.'"
    if l.strip().startswith("next='"):lines[i]="    next='PLAN D boundedcurrentactualMoon/planet participation and activepagehide-cancel-late across sameencodedowner, realsource reuse/familytemporary-retiredresources. Nofivecase/oldnine/fullcoldmatrix replay, guessedoptimisation or newpaidfacility. StaticHEAD304 developmentdone but cancellationreceiptunknown/HEADlogseparate; r12aggregatefailed epoch retained. OldbinaryJSONrollback/full200MB/retentionfullrefs/nativegesture-time-followcalibration-sourceBack/WXMLFAILED/Android-iOS-newMoon/physicaltotal/whole200DAUcost-monthflow/productionCPU-RSS-DB-Redis-outbox-media/12Mbps10-20capacity/180GB/Bfullqualityrights-publication/independentreview remain. OnlySkynecessaryshared, nootherbusinesslogic/commitpushdeployadoption.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'priorProductPinsExact':len(set(checked)),'protected6Exact':True,'goal':'active_unbudgeted','priorTurn':'progress','next':'D_solar_participation_and_pending_page_lifecycle'}))
