"""Record the bounded real-query fix and move the sole dependency forward."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[4]
TASK=ROOT/'.codex/work-items/cloud-sky-native-2026-09-22'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
prior=read(TASK/'evidence/current-execution-state-2026-10-03-r48.json')
allowed={'apps/wechat-miniapp/src/services/cache-policy.ts'}
for v in prior['currentSources']+prior['protected']:
 if v['path'].startswith(('apps/','workers/','packages/','tools/deployment/','data-pipelines/')) and v['path'] not in allowed:
  b=(ROOT/v['path']).read_bytes();assert len(b)==v['bytes']and hashlib.sha256(b).hexdigest()==v['sha256'],v['path']
r=read(ROOT/'output/playwright/cloud-sky-real-query-clear-readback-1003-r2/result.json')
assert r['currentSourcePinsExact']==272 and r['protectedExact']==6 and len(r['frames'])==16
summary=('新增[实际Query清理与page返回恢复](evidence/experience-real-query-clear-recovery-2026-10-03.md)：实际QueryClient/Observer与API clear先复现两失败，生产仅sao-index临时根及SAO Hook交付对象identity修复；其他业务逻辑/6保护保持，40受影响检查、4修测试类型后检查与App TS通过。r16当前page176/API150去重272精确源、实际useResourceQuery/同一QueryClient/Observer optimistic-subscribe-options端口、两受影响冷-clear-hide-return/8软件帧；clear后store无SAO索引/cache0-epoch1，回程同hash新identity59→114、两次324点/正向实际绘制、稳定RGBA精确、旧loader/native身份退休、final活动文件-租约-SAO-GL0/epoch2/26B空inventory。独立模型峰RGBA14680064/pending2097152/MapFS1425598B/leases16，GLtexture-buffer13500416-60348B非物理总。62完成编码3971662B/1取消，Caddy3980540B含取消200-8878未知客户端接收；实际清理后的report200-225858B、BSC/figures304符合其失效政策，不混旧暖200。r15任务错用rootQuery版本失败保持，只修App版本API导出并重编API，page复用；根readback首轮归档额外字段误比失败保留，r2核真实pins/来源/PNG-RGBA/清理。受控React端口不是完整useQuery-provider-JSX/reportHook/SettingsUI/WEAPP/物理/图质/容量/独审，无依赖更新/其他业务/共享BFF-watch重启/发布。\n\n')
next_step=('当前唯一下一依赖仍是D：实际API clear、真实Query消费者及隐藏回程已有上述有界开发证据，下一项直接核旧image-only二进制回退遇到当前v2 JSON库存的保留/预算/再升级/清理。复用封存旧源和已取得真实文件，先执行实际旧owner与当前owner，区分不识别的孤儿/旧pointer/新合法命中；复现后才修Sky文件责任，不泛改账户天气或6设置-outbox保护项，不凭猜测加另一个owner/预算。完整React useQuery-provider/公开UI与原生clear重试仍未验，当前控制端口不认证它们。原五组合/solar/old9/clear两场/静态合同与无变化源加工不重放；同帧、科学来源、完整性、租约、取消迟到和粗层回退保持。全小程序200MB/完整引用retention/物理总峰、native时间-手势-来源Back-跟随校准/WXMLFAILED/Android+iOS新Moon、whole200DAU费用月流量/CPU-RSS-DB-Redis-outbox-media/12Mbps10-20mixed容量/180GB和独审仍开放。B完整背景接缝绿晕弱结构配准覆盖/来源加工/批量出版及rights未过，Prepared/science registry空/HST矩形FAILED/M82缺输入；不采用、下载重复加工、DevTools启动循环、提交推送采购云部署发布或缩减目标。')
p=TASK/'PLAN.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();i=next(i for i,l in enumerate(lines)if l.startswith('当前唯一下一依赖仍是D：'));lines[i]=summary.rstrip()+'\n\n'+next_step;s='\n'.join(lines)+'\n'
old='D已核单owner五组合、太阳系参与及pagehide迟到；补实际clear与Query缓存恢复，完整图质/原生/物理/回滚/容量未验';assert old in s
s=s.replace(old,'D已核单owner组合及实际Query清理返回；核旧二进制JSON库存回退，完整图质/原生/物理/容量未验',1);p.write_text(s,encoding='utf-8')
p=TASK/'CONTINUE-CLOUD-SKY.md';s=p.read_text(encoding='utf-8');anchor='新增[月面行星与活动page迟到读取]';i=s.index(anchor);end=s.index('\n\n',i);s=s[:end+2]+summary+s[end+2:];s=s.replace('current-execution-state-2026-10-03-r48.json','current-execution-state-2026-10-03-r49.json');p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/architecture/runtime-and-domain.md';s=p.read_text(encoding='utf-8');old='Actual file clear and Query-cache generation recovery remain unverified and must use actual Query consumers rather than the task Map.';assert old in s
new=('Temporary API clear now removes only the SAO index query in addition to its existing policy: the validated index carries a file-generation capability even when its publication hash is immutable. `use-sky-stellar-supplement` binds loader lifetime and exposed state to the delivered publication object, so a same-hash refresh cannot preserve a retired capability. Actual QueryClient/QueryObserver/useResourceQuery and API clear plus controlled page/software Scene demonstrate hidden-page return with a new capability and the same source rows; full React useQuery/provider, Settings UI and native recovery remain unverified. No other business cache policy changes. See [real Query recovery](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-real-query-clear-recovery-2026-10-03.md).')
s=s.replace(old,new,1);p.write_text(s,encoding='utf-8')
p=ROOT/'project_context/areas/main/screen-contracts/wechat-miniapp/spot-and-sky.md';s=p.read_text(encoding='utf-8');old='实际clear/Query恢复、完整UI与物理/质量仍缺，见[太阳系增量]';assert old in s
s=s.replace(old,'实际clear/Query隐藏回程已由真实QueryClient/Observer/useResourceQuery与受控page软件路径开发验证，索引新代次/旧loader退休/同源实际绘制保持；完整React-provider/SettingsUI/WEAPP与物理/质量仍缺。见[Query恢复](../../../../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-real-query-clear-recovery-2026-10-03.md)，太阳系证据仍见[太阳系增量]',1);p.write_text(s,encoding='utf-8')
p=TASK/'scripts/capture-current-execution-2026-10-03.ps1';s=p.read_text(encoding='utf-8')
names=['build-real-query-page-bundles-2026-10-03.mjs','real-query-page-bundle-generated-2026-10-03.mts','build-real-query-clear-journey-2026-10-03.mjs','experience-real-query-clear-journey-2026-10-03.mts','rebuild-real-query-api-2026-10-03.mjs','real-query-api-rebuild-generated-2026-10-03.mts','readback-real-query-clear-2026-10-03.py','record-real-query-clear-continuity-2026-10-03.py']
addition=''.join(f'  "$taskRoot/scripts/{n}",\n'for n in names)
for n in ['apps/wechat-miniapp/src/features/sky/use-sky-stellar-supplement.ts','apps/wechat-miniapp/src/features/sky/sky-stellar-supplement-owner.test.ts','apps/wechat-miniapp/src/features/sky/sky-stellar-clear-recovery.test.ts']:
 if f"'{n}'"not in s:addition+=f"  '{n}',\n"
s=s.replace('$sources = @(\n','$sources = @(\n'+addition,1)
evidence=['.codex/work-items/cloud-sky-native-2026-09-22/evidence/experience-real-query-clear-recovery-2026-10-03.md']
for n in ['clear-query-trace.json','failed-before.json','inputs-before.json','source-before-0.txt','source-before-1.txt','source-before-2.txt','source-before-3.txt','type-failure.json','task-checkpoint-admission-failure.json','runner-before-transition-admission.mts']:
 evidence.append('output/sky-clear-query-recovery-1003-r1/'+n)
for n in ['result.json','actual-api-clear.json','executed-script.mts','executed-api-rebuild.mts','final-owner.json','caddy.log','inputs-before.json','inputs-after.json','reused-page.json','authorised-input-transitions.json','api-inputs.json','source-binding-before.json','delivery-accounting.json','clear-hidden.json','query-cold-wide.json','query-clear-wide-return.json']:
 evidence.append('output/playwright/cloud-sky-live-mixed-1003-r16/'+n)
evidence.append('output/playwright/cloud-sky-live-mixed-1003-r15/live-failure.json')
for n in ['failed.json','executed-script.py']:evidence.append('output/playwright/cloud-sky-real-query-clear-readback-1003-r1/'+n)
evidence.append('output/playwright/cloud-sky-real-query-clear-readback-1003-r2/result.json')
for n in evidence:assert(ROOT/n).is_file(),n
s=s.replace('$results = @(\n','$results = @(\n'+''.join(f"  '{n}',\n"for n in evidence),1)
lines=s.splitlines()
for i,l in enumerate(lines):
 if l.strip().startswith("toolObserved='"):lines[i]="    toolObserved='r48 current255pins/protected6 workspacebranchHEAD exact, only pinned cache-policy changed plus separately archived SAO Hook/test changes. Actual API clear/QueryClient-Observer regression2failed-before; Sky sao-index root and deliveredpublication identity onlyproductfix. 40affectedpass; optional-testtype repair4pass plusAppTS. r15taskroot5.101.4QueryObserver vsapp5.90.20core failure retained; fixAPIexportapp5.90.21 onlyAPIrebuild150/page176reused, union272exact and oneencodedowner. r16actualuseResourceQuery/realsharedQueryClientObserver effect-port/cold-clear-hide-return2conditions8softwarePNG-RGBAframes. ClearstoreabsentSAO/cache0epoch1/26B; returnnewidentity59-114samehash324points/positivepaint/identicalstableRGBA/newnativeidentities/oldloaderretired. PeaksRGBA14680064-pending2097152-MapFS1425598leases16 andGLtexture13500416buffer60348 separate models notphysicaltotal. Successful62encoded3971662B/log3980540B/cancel1extra2008878clientreceiptunknown; afterdeliberateclear report200225858B/BSCfigures304. FinaldataqueueleasesSAOGL0epoch2/26B. Rootr1extraarchivefieldcomparisonfailedretained/r2exactsource-bytes-frame-query-resource-readback. FullReactuseQuery-provider-JSX/reportHook/SettingsUI-nativeUI unverified; protected6exact/nootherbusinesslogic/dependencyupdate/sharedBFFwatchrestart/phone/commitpushdeployadoption; independentreviewmissing.'"
 if l.strip().startswith("next='"):lines[i]="    next='PLAN D actualold-image-only-owner rollback/currentv2JSONinventory retention-budget-reupgrade-clear with archivedoldsource andrealcachedfiles; reprobeforeSky-onlyrepair, noextraownerorbudget/otherbusinesslogic/protectedsettings-outboxedits. RealQueryhiddenreturndevelopmentdone; fullReactuseQuery-provider/SettingsUI/nativeclearretry remainsunverified. No replayclosed5-solar-old9-clear2/staticcontract/sourceprocessing or guessedframework/paidfacility. Full200MB/fullretentionrefs/nativegesture-time-followcalibration-sourceBack/WXMLFAILED/Android-iOS-newMoon/physicaltotal/whole200DAUcostmonthlyflow/CPU-RSS-DB-Redis-outbox-media/12Mbps10-20capacity/180GB/Bfullqualityrights-publication/independentreview remain. Goalactiveunbudgeted/no commitpushdeployadoption.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps(dict(protected6Exact=True,currentSourcePins=272,goal='active_unbudgeted',next='D_old_binary_JSON_inventory')))
