"""Record the fixed current-runtime consumer and the remaining D capacity dependency."""
from pathlib import Path
import json, hashlib
ROOT = Path(__file__).resolve().parents[4]; TASK = ROOT / '.codex/work-items/cloud-sky-native-2026-09-22'
name = 'experience-current-runtime-static-loader-2026-10-03.md'
summary = ('新增[非deploy实际current/runtime消费者修复](evidence/' + name + ')：load及唯一operatePreview消费者复用现有owner，prepared较新而current/mount较旧时选原正确overlay；check必须观察一致live mount，stop/backup/inspect/maintain在Caddy未运行时只用有效current并明确非运行态。legacy/缺/失败/身份错/变化拒绝，不借prepared；不把无关损坏历史回执变当前操作依赖。receipt步骤保存实际selection，lease/原完整性/HTTP/取消保持。actual operatePreview默认loader+sealed本机文件/注入Docker及Compose核路径通过；替换旧loader复现选错generation并使新增回归失败，四组49检查通过。无实际远端/独审/部署/清理，完整引用/物理保留与容量仍未验。\n\n')
next_step = ('当前唯一下一依赖仍是D：file-bound operation/release/current与非deploy current/receipt/runtime消费者已开发收口；远端读回不可用，actual mounts/receipts、rollback/Sky-backup全集/物理保留继续未知，不重复SSH/runtime矩阵/旧库存/HTTP/dry-run，不清理/部署/发布。独立推进全小程序200DAU成本与混合容量模型：先核已保存测量、全业务资源家族/请求单位/冷热旅程和用户活动假设，仅补真正缺失消费者/参数，不能200DAU当200同时在线或本机static cohort当10/20混合验收。DB backup-v1不冒Sky备份，当前/获准旧URL/来源/未知继续保留。B完整图质开放，局部matching不采用/不循环参数，背景/绿晕/弱结构/coverage、三级显示/来源权益信用加工/独审/批量出版/Source Back仍须交付。ordinary science/Prepared registry空，HST矩形FAILED/M82完整输入缺；实际page/native/Android/iOS/newMoon、全产品总资源/180GB余量、预期生产配置容量义务不缩减。')
p = TASK / 'PLAN.md'; s = p.read_text(encoding='utf-8'); assert '非deploy实际current/runtime消费者修复' not in s
lines = s.splitlines(); i = next(i for i,l in enumerate(lines) if l.startswith('当前唯一下一依赖仍是D：')); lines[i] = summary.rstrip()+'\n\n'+next_step
s = '\n'.join(lines)+'\n'; s = s.replace('D非deploy消费者actual current/receipt/runtime联合绑定；文件引用已开发，远端/全集及B完整图质仍未验', 'D全小程序200DAU成本/混合容量模型的缺失实际输入；文件引用和非deploy绑定已开发，远端/全集及B完整图质未验', 1); p.write_text(s,encoding='utf-8')
p = TASK / 'CONTINUE-CLOUD-SKY.md'; s = p.read_text(encoding='utf-8'); i = s.index('新增[已有回执/current引用绑定开发]'); end = s.index('\n\n',i)
s = s[:end+2]+summary+s[end+2:]; s = s.replace('current-execution-state-2026-10-03-r39.json','current-execution-state-2026-10-03-r40.json'); p.write_text(s,encoding='utf-8')
p = ROOT / 'infrastructure/deployment/README.md'; s = p.read_text(encoding='utf-8')
old = 'Non-deploy `loadSkyStaticDelivery` still selects prepared state and requires further current/receipt/runtime binding.'
new = ('Non-deploy `loadSkyStaticDelivery` selects the current successful preview-deploy receipt and exact existing overlay, validated against the selected revision/digest. `check` requires the same observed running mount. `stop` and backup inspection/maintenance can use the valid current record when no running Caddy is observed, explicitly recording that absence; they do not claim live service or Sky backup. Missing/legacy/failed current, mismatch and changing observations fail without selecting newer prepared state. Unrelated historical receipt corruption belongs to retention review, not this current operation. The selection lease lasts through the existing consumer cleanup, and the `sky-static-load` receipt step records the observation.')
assert old in s; s = s.replace(old,new,1); p.write_text(s,encoding='utf-8')
p = ROOT / 'project_context/deployment/decisions-and-verification.md'; s = p.read_text(encoding='utf-8')
s = s.replace('This does not supply release/rollback/backup reference completeness or fix non-deploy load-by-prepared behavior.', 'Receipt binding and non-deploy current selection remain under this same owner; complete release/rollback/Sky-backup references are still unverified.', 1)
old = 'The inspection CLI enables both observations, while non-deploy load-by-prepared remains unchanged.'
new = ('The inspection CLI enables both observations. Non-deploy preview loading now resolves only the current successful deploy receipt and exact overlay under the same lease, checks the selected environment identity, rechecks current bytes/runtime/prepared pointer and passes operation/execute through its actual consumer. Check requires the matching live mount; stop/backup inspection/maintenance can retain a valid recorded selection with explicit no-running-Caddy status. Missing/legacy/failed/mismatched current cannot fall back to newer prepared state; unrelated historical receipt corruption is not a current-operation dependency. The consumer records selection meaning. This fixes a reproduced prepared-newer/current-mounted-older path in development, including the actual default consumer with injected Docker/Compose/HTTP dependencies. See [current-runtime loader scope](../../.codex/work-items/cloud-sky-native-2026-09-22/evidence/' + name + ').')
assert old in s; s = s.replace(old,new,1); p.write_text(s,encoding='utf-8')
p = TASK / 'scripts/capture-current-execution-2026-10-03.ps1'; s = p.read_text(encoding='utf-8')
new_sources=['tools/deployment/operator-preview.mjs','tools/deployment/sky-static-consumer.test.mjs']
new_sources=[v for v in new_sources if "'"+v+"'" not in s and '"'+v+'"' not in s]
s = s.replace('$sources = @(\n','$sources = @(\n'+''.join("  '"+v+"',\n" for v in new_sources)+'  "$taskRoot/scripts/record-current-loader-continuity-2026-10-03.py",\n  "$taskRoot/scripts/verify-nondeploy-current-regression-2026-10-03.mjs",\n',1)
s = s.replace('$results = @(\n','$results = @(\n  "$taskRoot/evidence/'+name+'",\n  \'output/sky-current-loader-development-1003-r1/result.json\',\n  \'output/sky-current-loader-development-1003-r1/previous-loader-output.txt\',\n',1)
lines=s.splitlines()
for i,l in enumerate(lines):
    if l.strip().startswith("toolObserved='"):
        lines[i]="    toolObserved='Current/receipt/runtime nondeploy loader fixed in existing owner and actual operatePreview consumer. Prepared-newer/current-mounted-older selects actual old overlay; check requires live matching mount, stopped-edge stop/backup/inspect/maintain explicitly use valid recorded current without live claim. Missing/legacy/failed/mismatched/changing observations reject, no prepared fallback or unrelated historical receipt dependency. Selection observation in receipt, lease retained through consumer. Archived old loader makes expected-current regression fail.49affected owner/consumer/release/preview checks pass including actual default consumer with sealed local files/injected Docker/Compose/HTTP dependencies. Not remote acceptance or independent review. DBbackup-v1 not Sky contract/full rollback reference completeness unknown. No cleanup/deploy/publish/restart/SSH retry/reprocessing. Quality/native/device/full disk/200DAU capacity gaps preserved.'"
    if l.strip().startswith("next='"):
        lines[i]="    next='PLAN D: independently inspect existing whole-miniapp200DAU cost/mixed-capacity model inputs and actual business/resource families, activity units/cold-warm journeys; only fill missing consumers/parameters. File references and nondeploy current/runtime binding developed, remote mounts/receipts/full rollback/Sky-backup/physical disk remain unknown. No repeated SSH/runtime matrix/old inventory/HTTP/dryrun or cleanup/deploy. No200DAU as200concurrent or localstatic as10/20mixed acceptance. All admitted URLs/source/unknown retain. B complete quality/source processing/publication/Source Back open; ordinary registry empty/local matching not adopted. Native page/devices/whole resources/180GB and expected production capacity unverified.'"
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
baseline=json.loads((TASK/'evidence/current-execution-state-2026-10-03-r39.json').read_bytes()); count=0
for v in baseline['currentSources']:
    if v['path'].startswith(('data-pipelines/','workers/','apps/','packages/')):
        p=ROOT/v['path']; assert p.stat().st_size==v['bytes'] and hashlib.sha256(p.read_bytes()).hexdigest()==v['sha256']; count+=1
print(json.dumps({'otherProductionFilesExactAgainstR39':count,'currentConsumer':'DEVELOPMENT_FIXED','remote':'UNAVAILABLE_NOT_ABSENT','next':'D_whole_miniapp200DAU_model_inputs'}))
