// Bounded independent CPU/AST/JSX review. No GPU, source image decode, HTTP, native UI or production mutation.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {skyOpticalSourceCredit} from '../../../../apps/wechat-miniapp/src/features/sky/sky-optical-source-credit.ts';
import {skyTargetOpticalFrame} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-frame.ts';
import {completeTargetSkyOptical,completeLegacySkyOptical,liveSkyOpticalCompletion} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-completion.ts';
import {registerSkyNativeImageLifetime} from '../../../../apps/wechat-miniapp/src/features/sky/sky-artwork-loader.ts';
import {celestialInformationSourceRoute} from '../../../../apps/wechat-miniapp/src/services/celestial-information-presentation.ts';
import {skyPresentedTimeCurrent} from '../../../../apps/wechat-miniapp/src/features/sky/sky-observation-time.ts';
import {sdssOpticalPresentation} from '../../../../apps/wechat-miniapp/src/features/sky/sky-sdss-optical-selection.ts';
import {sdssOpticalPublication} from '../../../../packages/miniapp-contracts/src/sdss-optical-publication.ts';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..'),task='.codex/work-items/cloud-sky-native-2026-09-22',sky='apps/wechat-miniapp/src/features/sky/';
const out='output/optical-source-credit-independent-1003-r1';assert(!fs.existsSync(path.resolve(ROOT,out)));fs.mkdirSync(path.resolve(ROOT,out));
const read=p=>fs.readFileSync(path.resolve(ROOT,p)),sha=b=>createHash('sha256').update(b).digest('hex'),json=p=>JSON.parse(read(p).toString('utf8'));
const binding=p=>{const b=read(p);return{path:p,bytes:b.length,sha256:sha(b)};},inputs=new Map();
const bind=(p,expected={})=>{const b=binding(p);if(expected.bytes!==undefined)assert.equal(b.bytes,expected.bytes,p);if(expected.sha256)assert.equal(b.sha256,expected.sha256,p);if(inputs.has(p))assert.deepEqual(b,inputs.get(p));inputs.set(p,b);return b;};
const save=(name,data)=>fs.writeFileSync(path.resolve(ROOT,out,name),JSON.stringify(data,null,2)+'\n',{flag:'wx'});
const copy=(p,name)=>fs.writeFileSync(path.resolve(ROOT,out,name),read(p),{flag:'wx'});
copy(fileURLToPath(import.meta.url),'executed-review.mts');
const require=createRequire(path.resolve(ROOT,'apps/wechat-miniapp/package.json')),ts=require('typescript');assert.equal(ts.version,'5.9.3');
const transpile=(s,jsx=ts.JsxEmit.ReactJSX)=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx}}).outputText;
const publications={prepared:json('output/prepared-optical-publication-1003-r4/publication/manifest.json'),science:json('output/sdss-science-optical-writer-1002-r1/publication/manifest.json')};
const full='NASA, ESA, S. Beckwith (STScI), and The Hubble Heritage Team (STScI/AURA)';
assert.equal(publications.prepared.source.credit,full);
const retirements=[];
function world(pub=publications.prepared,receipt={completed:true,qualification:{fine:'has',coarse:'has',any:'has'},finePhoto:'positive',coarsePhoto:'positive'},draw={submitted:true,finePrepared:true,coarsePrepared:true}){
 const image={},parent={};const retireFine=registerSkyNativeImageLifetime(image,()=>true),retireParent=registerSkyNativeImageLifetime(parent,()=>true);retirements.push(retireFine,retireParent);
 const frame=skyTargetOpticalFrame({image,renderedLevel:'DETAIL',renderedAsset:pub.levels.DETAIL,publication:pub,coarser:{image:parent,level:'MEDIUM',asset:pub.levels.MEDIUM}});assert(frame);
 return{frame,receipt,draw,completion:completeTargetSkyOptical(frame,draw,receipt),retireFine,retireParent};
}
const compileComponent=source=>{const exports={};const jsx=(type,props)=>typeof type==='function'?type(props):({type,props});vm.runInNewContext(transpile(source),{exports,require(name){if(name==='react/jsx-runtime')return{jsx,jsxs:jsx};if(name==='@tarojs/components')return{Button:'Button',Text:'Text',View:'View'};throw Error('unexpected_jsx_dependency:'+name);}});return{render:exports.SkyOpticalImageCredit,jsx};};
const flatten=x=>Array.isArray(x)?x.flatMap(flatten):!x||typeof x!=='object'||!('type'in x)?[]:[x,...flatten(x.props.children)];
try{
 bind(fileURLToPath(import.meta.url));bind('tools/run-node.cjs');bind(process.execPath);bind(require.resolve('typescript/lib/typescript.js'));bind(require.resolve('typescript/package.json'));
 const dev='output/optical-source-credit-1003-r3';const before=json(dev+'/inputs-before.json');assert.deepEqual(before,json(dev+'/inputs-after.json'));assert.equal(before.length,35);for(const b of before)bind(b.path,b);for(const name of fs.readdirSync(path.resolve(ROOT,dev)))bind(dev+'/'+name);assert.equal(json(dev+'/result.json').status,'PASSED_BOUND_SOURCE_CREDIT_DEVELOPMENT');assert(read(dev+'/affected-tests.log').toString().includes('pass 8'));assert.deepEqual(read(task+'/scripts/experience-optical-source-credit-2026-10-03.mjs'),read(dev+'/executed-driver.mjs'));
 for(const dir of['output/optical-source-credit-1003-r1','output/optical-source-credit-1003-r2'])for(const name of fs.readdirSync(path.resolve(ROOT,dir)))if(fs.statSync(path.resolve(ROOT,dir,name)).isFile())bind(dir+'/'+name);assert.equal(json('output/optical-source-credit-1003-r2/result.json').status,'FAILED');
 const protectedPath=task+'/tmp/resume-preserved-hashes-2026-10-01.json';bind(protectedPath);for(const b of json(protectedPath))bind(b.path,b);
 bind('output/prepared-optical-publication-1003-r4/publication/manifest.json',{sha256:'23faa1521ae39a6a7d92f36c87ebf691a75b6bd7b91a3654e9b24f63f4d793f1'});bind('output/sdss-science-optical-writer-1002-r1/publication/manifest.json',{sha256:'3eaf04b366827c86ece835f48ed37089d5406be2ed4d73c2252960e7e9aa1dd5'});
 for(const p of[sky+'sky-observation-time.ts',sky+'sky-sdss-optical-selection.ts','packages/miniapp-contracts/src/index.ts','packages/miniapp-contracts/src/prepared-optical-publication.ts','packages/miniapp-contracts/src/sdss-science-optical-publication.ts',task+'/evidence/experience-optical-source-credit-development-2026-10-03.md',task+'/evidence/experience-prepared-report-footprint-independent-review-2026-10-03.md','.codex/skills/uiux_design/SKILL.md','DESIGN.md','project_context/global.md','project_context/areas/main/screen-contracts/wechat-miniapp.md'])bind(p);
 const fixture=json(sky+'sky-prepared-optical-footprint.fixture.json');assert.deepEqual(fixture.publication,publications.prepared);
 const owner=world(),credit=skyOpticalSourceCredit(owner.completion);assert(credit&&Object.isFrozen(credit));assert.equal(credit.credit,full);assert.equal(credit.license,publications.prepared.source.license);assert.equal(credit.publicationHash,publications.prepared.publicationHash);assert.equal(credit.description,'历史观测处理色 · 非自然真彩');assert.equal(credit.sourceRoute,celestialInformationSourceRoute('M:51',undefined,publications.prepared.publicationHash));
 const survival=[];owner.retireFine();assert.deepEqual(skyOpticalSourceCredit(owner.completion),credit);assert.equal(liveSkyOpticalCompletion(owner.completion).participatingFields[0].slot,'coarse');survival.push('fine-retired/coarse-credit-preserved');owner.retireParent();assert.equal(skyOpticalSourceCredit(owner.completion),null);survival.push('both-retired/no-caption');
 const parentFirst=world();parentFirst.retireParent();assert.deepEqual(skyOpticalSourceCredit(parentFirst.completion),credit);parentFirst.retireFine();assert.equal(skyOpticalSourceCredit(parentFirst.completion),null);survival.push('coarse-retired/fine-credit-preserved');
 const science=world(publications.science);assert.equal(skyOpticalSourceCredit(science.completion).kind,'science');assert.equal(skyOpticalSourceCredit(science.completion).credit,publications.science.source.credit);assert.equal(skyOpticalSourceCredit(science.completion).publicationHash,publications.science.publicationHash);
 const legacyImage={},retire=registerSkyNativeImageLifetime(legacyImage,()=>true);retirements.push(retire);const legacy=completeLegacySkyOptical({reference:'M:51',publicationHash:sdssOpticalPublication('M:51').publicationHash,image:legacyImage,level:'OVERVIEW',fieldDegrees:.2275555555555556},legacyImage);assert.equal(skyOpticalSourceCredit(legacy).credit,'Sloan Digital Sky Survey');assert.equal(skyOpticalSourceCredit({...legacy,publicationHash:publications.prepared.publicationHash}),null);
 const live=world(),negative=[];const checkNull=(name,value)=>{assert.equal(skyOpticalSourceCredit(value),null,name);negative.push(name);};checkNull('null',null);checkNull('foreign-reference',{...live.completion,reference:'M:82'});checkNull('wrong-pub-pin',{...live.completion,publicationHash:'0'.repeat(64)});checkNull('unfinished-receipt',{...live.completion,receipt:{...live.completion.receipt,completed:false}});checkNull('declared-positive-but-unknown',{...live.completion,receipt:{...live.completion.receipt,finePhoto:'unknown'}});checkNull('positive-empty-slot',{...live.completion,receipt:{...live.completion.receipt,qualification:{fine:'empty',coarse:'has',any:'has'}}});checkNull('wrong-field-descriptor',{...live.completion,participatingFields:live.completion.participatingFields.map(f=>({...f,asset:{...f.asset}}))});checkNull('field-degrees-mismatch',{...live.completion,participatingFields:live.completion.participatingFields.map(f=>({...f,fieldDegrees:f.fieldDegrees*2}))});
 for(const[name,receipt,draw]of[['unknown-black-both',{...live.receipt,finePhoto:'unknown',coarsePhoto:'unknown'},live.draw],['unsubmitted',live.receipt,{...live.draw,submitted:false}],['positive-unprepared',live.receipt,{...live.draw,finePrepared:false}],['contradictory-empty-whole',{...live.receipt,qualification:{fine:'has',coarse:'has',any:'empty'}},live.draw]])checkNull(name,world(publications.prepared,receipt,draw).completion);
 const independent=world(publications.prepared,{completed:true,qualification:{fine:'unknown',coarse:'has',any:'has'},finePhoto:'unknown',coarsePhoto:'positive'});assert.equal(skyOpticalSourceCredit(independent.completion).credit,full);assert.equal(independent.completion.participatingFields.length,1);assert.equal(independent.completion.participatingFields[0].slot,'coarse');
 const componentText=read(sky+'sky-optical-image-credit.tsx').toString('utf8'),component=compileComponent(componentText);copy(sky+'sky-optical-image-credit.tsx','actual-component.tsx.txt');copy(sky+'sky-optical-source-credit.ts','actual-credit-owner.ts.txt');copy(sky+'spot-sky-page.tsx','actual-page.tsx.txt');
 let captured=null;const tree=component.render({credit,onOpenSources:value=>captured=value}),elements=flatten(tree);assert(elements.some(e=>e.type==='Text'&&e.props.children===full));const meaning=elements.find(e=>e.type==='Text'&&Array.isArray(e.props.children));assert.deepEqual(Array.from(meaning.props.children),[credit.license,' · ',credit.description]);const action=elements.find(e=>e.type==='Button');assert(action&&typeof action.props.onClick==='function');action.props.onClick();assert.equal(captured,credit);assert.equal(component.render({credit:null,onOpenSources:()=>assert.fail()}),null);
 const pageText=read(sky+'spot-sky-page.tsx').toString('utf8'),page=ts.createSourceFile('page.tsx',pageText,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);assert.equal(page.parseDiagnostics.length,0);const declarations=new Map(),all=[];let jsxCredit;const visit=n=>{all.push(n);if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&n.initializer)declarations.set(n.name.text,n.initializer);if(ts.isJsxSelfClosingElement(n)&&n.tagName.getText(page)==='SkyOpticalImageCredit')jsxCredit=n;ts.forEachChild(n,visit);};visit(page);assert(jsxCredit);
 const names=['orientationData','nativeCanvasMounted','presentedSceneCurrent','presentedSdssOptical','opticalImageCredit'];for(const name of names)assert(declarations.has(name),name);const pageExpressions=names.map(name=>'const '+name+'='+declarations.get(name).getText(page)+';').join('\n')+'\nresult='+jsxCredit.getText(page)+';';fs.writeFileSync(path.resolve(ROOT,out,'actual-page-expressions.tsx.txt'),pageExpressions,{flag:'wx'});
 const code=transpile(pageExpressions),data={context:{spotId:'actual-controlled-context'}},at='2026-10-03T13:00:00.000Z',base={exports:{},require:()=>({jsx:component.jsx,jsxs:component.jsx}),skyPresentedTimeCurrent,liveSkyOpticalCompletion,skyOpticalSourceCredit,SkyOpticalImageCredit:component.render,reportData:data,rawReportData:data,report:{isError:false,data:{dataState:'FRESH'}},pageVisible:true,devicePose:{},manualBasis:null,orientation:{presented:{current:{}}},row:{at},canvasError:null,mode:'NIGHT',timePlaying:false,timeIntent:{runStartAt:null},canvasSize:{width:390,height:844},canvasGenerationRef:{current:11},presentedSkyFrame:{data,mode:'NIGHT',frameAt:at,nativeCanvasGeneration:11,sdssOptical:live.completion},selectedDeepSkyEntry:{objectRef:'M:82'},sdssOptical:{publication:publications.science},openOpticalSources:()=>{},result:null};
 const scenarios=[['accepted/latest-other-focus',{},true],['unaccepted-source-only',{presentedSkyFrame:null},false],['hidden',{pageVisible:false},false],['error',{canvasError:'failed'},false],['zero-size',{canvasSize:{width:0,height:844}},false],['wrong-generation',{canvasGenerationRef:{current:12}},false],['wrong-time',{row:{at:'2026-10-03T14:00:00.000Z'}},false],['wrong-mode',{mode:'OBSERVATION'},false],['new-report-before-paint',{reportData:{context:data.context}},false]];
 const pageResults=[];for(const[name,delta,expected]of scenarios){const env={...base,...delta};vm.runInNewContext(code,env);const exists=flatten(env.result).some(e=>e.type==='Text'&&e.props.children===full);assert.equal(exists,expected,name);pageResults.push({name,fullCaption:exists});}
 const lc=declarations.get('canvasLifecycle');assert(lc&&ts.isCallExpression(lc));const creator=lc.arguments[0].body;assert(ts.isCallExpression(creator)&&creator.expression.getText(page)==='createSkyCanvasLifecycle');const config=creator.arguments[0];assert(ts.isObjectLiteralExpression(config));const port=new Map(config.properties.map(p=>[p.name.getText(page),p.initializer.getText(page)]));assert(port.get('paint').includes('paintAttempt.publish = () =>'));assert(!port.get('paint').split('paintAttempt.publish = () =>')[0].includes('setPresentedSkyFrame('));assert(port.get('presented').includes('attempt.frame !== frame'));assert(port.get('presented').includes('attempt.generation !== canvasGenerationRef.current'));assert(port.get('presented').includes('attempt.publish()'));assert(port.get('invalidated').includes('setPresentedSkyFrame(null)'));assert(port.get('failed').includes('setPresentedSkyFrame(null)'));assert(port.get('releaseContext').includes('canvasGenerationRef.current++'));
 const openText=declarations.get('openOpticalSources').getText(page);const routes=[],notices=[],pending=[];const navEnv={opticalSourcesOpeningRef:{current:false},Taro:{navigateTo:({url})=>{routes.push(url);return new Promise((resolve,reject)=>pending.push({resolve,reject}));}},notify:x=>notices.push(x),celestialInformationSourceRoute};const opener=vm.runInNewContext(transpile('const open='+openText+';open;'),navEnv);
 const first=opener(credit);await opener(skyOpticalSourceCredit(science.completion));assert.deepEqual(routes,[credit.sourceRoute]);assert.equal(navEnv.opticalSourcesOpeningRef.current,true);pending[0].reject(Error('controlled-nav-failure'));await first;assert.equal(navEnv.opticalSourcesOpeningRef.current,false);assert.equal(notices.length,1);assert.equal(notices[0].dedupeKey,'sky-source-navigation');const secondCredit=skyOpticalSourceCredit(science.completion),second=opener(secondCredit);assert.equal(routes[1],secondCredit.sourceRoute);pending[1].resolve();await second;assert.equal(navEnv.opticalSourcesOpeningRef.current,false);
 // Actual-source bounded mutations, explicitly not replaying a complete historical owner.
 const originalOwner=read(sky+'sky-optical-source-credit.ts').toString('utf8'),fixedMutant=originalOwner.replace('credit: publication.source.credit','credit: "Sloan Digital Sky Survey"');assert.notEqual(fixedMutant,originalOwner);fs.writeFileSync(path.resolve(ROOT,out,'fixed-sdss-caption-mutant.ts.txt'),fixedMutant,{flag:'wx'});const module={exports:{}};vm.runInNewContext(transpile(fixedMutant),{exports:module.exports,require(name){if(name==='@starward/miniapp-contracts')return{sdssOpticalPublication};if(name.includes('celestial-information-presentation'))return{celestialInformationSourceRoute};if(name==='./sky-sdss-optical-completion')return{liveSkyOpticalCompletion};throw Error(name);}});const mutantCredit=module.exports.skyOpticalSourceCredit(live.completion).credit;assert.notEqual(mutantCredit,full);
 const routeMutant=openText.replace('url: credit.sourceRoute','url: celestialInformationSourceRoute(credit.reference)');assert.notEqual(routeMutant,openText);fs.writeFileSync(path.resolve(ROOT,out,'unpinned-navigation-mutant.ts.txt'),routeMutant,{flag:'wx'});const mutantRoutes=[],mutantOpen=vm.runInNewContext(transpile('const open='+routeMutant+';open;'),{opticalSourcesOpeningRef:{current:false},Taro:{navigateTo:async({url})=>mutantRoutes.push(url)},notify:()=>{},celestialInformationSourceRoute});await mutantOpen(credit);assert.notEqual(mutantRoutes[0],credit.sourceRoute);assert.equal(mutantRoutes[0],'/sky/sources/index?reference=M%3A51');
 const css=read(sky+'spot-sky-page.scss').toString('utf8');assert(css.includes('white-space: normal;')&&css.includes('.sky-optical-image-credit__attribution'));assert(!componentText.includes('slice(')&&!componentText.includes('ellipsis'));
 const background=json('output/prepared-background-basis-1003-r1/result.json');assert(background.meaning.includes('No physical sky'));assert(background.levels.some(l=>l.belowCandidateBlackPoint>0));
 retirements.forEach(fn=>fn());assert.equal(skyOpticalSourceCredit(live.completion),null);
 const inputBefore=[...inputs.values()],inputAfter=inputBefore.map(x=>binding(x.path));assert.deepEqual(inputBefore,inputAfter);save('bindings.json',{inputBefore,inputAfter,unchanged:true});
 save('result.json',{status:'INDEPENDENT_SOURCE_CREDIT_CPU_CONSUMER_REVIEW_PASS_NATIVE_UNVERIFIED',author:binding(dev+'/result.json'),currentOwner:binding(sky+'sky-optical-source-credit.ts'),component:binding(sky+'sky-optical-image-credit.tsx'),page:binding(sky+'spot-sky-page.tsx'),routeOwner:binding('apps/wechat-miniapp/src/services/celestial-information-presentation.ts'),inputs:inputBefore.length,currentBeforeAfterExact:true,protectedFiles:6,actualPublicationPins:{prepared:publications.prepared.publicationHash,science:publications.science.publicationHash},fullPreparedCaption:credit,scienceCaption:secondCredit,legacySloanCompatibility:true,retirement:survival,negative,independentPositiveParentWithUnknownFine:true,actualJsxFullStringAndCapturedObject:true,actualPageExpressions:pageResults,acceptedPortStaticFences:true,navigation:{firstPinned:routes[0],duplicateSuppressed:true,rejectionNotice:notices[0],finallyRestored:true,secondPinned:routes[1]},meaningfulMutations:{fixedSloanCaption:{detected:true,actualPreparedCredit:full,mutantCredit,label:'Restores old fixed provider meaning in current source only; not complete old owner replay'},unpinnedNavigation:{detected:true,actualPinnedRoute:credit.sourceRoute,mutantRoute:mutantRoutes[0]}},backgroundScope:'Only saved encoded margin diagnostic read; nonuniform/source-structure ambiguity retained, no recomputation/parameter adoption',limits:['Completion positive/UNKNOWN/black and native lease lifetimes are controlled CPU inputs, not new actual GPU provenance','Actual page initializers/action/JSX executed in controlled VM; accepted publication callbacks statically checked, not wholeReact/Hook/WXML/device lifecycle replay','Full caption string/wrapping CSS and action do not prove target WXML geometry/contrast/readability/gesture or native source-return journey','Prepared registry still empty and aux receipt budget unchanged/unadopted; ordinary Prepared/actual visible associated credit remain unverified','No picture/source decode, source/geometry/GPU matrix, HTTP/listener, watch/IDE/native/phone or deployment executed','Background/tone/PSF/approximate AVM/quality/resource/capacity and complete Goal stay open','Selected pre/post snapshots, not complete executed vendor/tool module trace']});
 console.log(JSON.stringify({result:binding(out+'/result.json'),bindings:binding(out+'/bindings.json'),inputs:inputBefore.length,protected:6,negative:negative.length}));
}catch(error){retirements.forEach(fn=>fn());save('failed.json',{status:'FAILED_INDEPENDENT_CPU_REVIEW',error:String(error),inputs:[...inputs.values()]});throw error;}
