// Bounded independent direct metadata owners and actual AST consumers + saved HTTP readback.
// No listener, network, images/GPU, production mutation or broad test replay.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createHash,randomUUID} from 'node:crypto';
import {createRequire,builtinModules} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..');
const task='.codex/work-items/cloud-sky-native-2026-09-22',OUT=path.join(ROOT,'output/prepared-information-independent-1003-r1');
fs.mkdirSync(OUT);
const parent='output/prepared-optical-information-1003-r4/',prior='output/prepared-optical-information-1003-r3/';
const app='apps/wechat-miniapp/src/',worker='workers/miniapp-api/src/';
const appRequire=createRequire(path.join(ROOT,'apps/wechat-miniapp/package.json')),workerRequire=createRequire(path.join(ROOT,'workers/miniapp-api/package.json'));
const ts=appRequire('typescript');assert.equal(ts.version,'5.9.3');
const read=(p:string)=>fs.readFileSync(path.resolve(ROOT,p)),text=(p:string)=>read(p).toString('utf8');
const json=(p:string)=>JSON.parse(text(p)),sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const bind=(p:string)=>{const b=read(p);return{path:p,bytes:b.length,sha256:sha(b)};};
const inputs=new Map<string,ReturnType<typeof bind>>();
const admit=(p:string,expected?:{bytes?:number;sha256?:string})=>{const b=bind(p);if(expected?.bytes!==undefined)assert.equal(b.bytes,expected.bytes,p);if(expected?.sha256)assert.equal(b.sha256,expected.sha256,p);if(inputs.has(p))assert.deepEqual(b,inputs.get(p));inputs.set(p,b);return b;};
const save=(n:string,v:unknown)=>fs.writeFileSync(path.join(OUT,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(OUT,'executed-script.mts'),fs.constants.COPYFILE_EXCL);
const graph=new Set<string>(),bare=new Map<string,string>();
function walk(p:string){p=path.resolve(ROOT,p);if(graph.has(p))return;assert(p.startsWith(ROOT+path.sep));graph.add(p);admit(p);
 for(const imp of ts.preProcessFile(text(p),true,true).importedFiles){const n=imp.fileName;if(n.startsWith('.')){const b=path.resolve(path.dirname(p),n),resolved=[b,b+'.ts',b+'.tsx',b+'.json',path.join(b,'index.ts')].find(x=>fs.existsSync(x)&&fs.statSync(x).isFile());assert(resolved,'relative import '+n+' from '+p);walk(resolved);}
 else if(n.startsWith('@starward/'))walk(createRequire(p).resolve(n));
 else if(!builtinModules.includes(n)&&!builtinModules.includes(n.replace(/^node:/,''))){try{const resolved=createRequire(p).resolve(n);bare.set(n,resolved);admit(resolved);}catch{bare.set(n,'unresolved type/platform entry; not an executed production import in this probe');}}
 }
}
function declarations(p:string){const source=ts.createSourceFile(p,text(p),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);assert.equal(source.parseDiagnostics.length,0,p);return{source,statement:(name:string)=>{const n=source.statements.find((n:any)=>(ts.isFunctionDeclaration(n)||ts.isClassDeclaration(n))&&n.name?.text===name);assert(n,name);return n.getText(source).replace(/^export\s+(?:default\s+)?/u,'');}};}
const selections:any[]=[];
function actualFn(p:string,name:string,bindings:any={},mutate:(s:string)=>string=s=>s){const original=declarations(p).statement(name),changed=mutate(original);selections.push({path:p,name,originalSha256:sha(original),executedSha256:sha(changed),mutation:changed!==original});return vm.runInNewContext(ts.transpileModule(changed+'\n'+name+';',{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText,bindings);}
const importFile=(p:string)=>import(pathToFileURL(path.join(ROOT,p)).href);
const record:any[]=[];
try{
 admit(fileURLToPath(import.meta.url));admit(process.execPath);admit(appRequire.resolve('typescript'));admit(appRequire.resolve('typescript/package.json'));
 admit(parent+'result.json',{sha256:'04908cd89254301596fae7078fdb6a31ebfe34ba1de4210b949af47d095f7430'});const result=json(parent+'result.json');assert.equal(result.status,'PASSED_BOUNDED_PREPARED_INFORMATION_CHAIN');assert.equal(result.inputs,59);
 admit(parent+'inputs-before.json');admit(parent+'inputs-after.json');const beforeAuthor=json(parent+'inputs-before.json');assert.deepEqual(beforeAuthor,json(parent+'inputs-after.json'));for(const row of beforeAuthor)admit(row.path,row);
 for(const file of fs.readdirSync(path.join(ROOT,parent)))if(fs.statSync(path.join(ROOT,parent,file)).isFile())admit(parent+file);
 for(const file of fs.readdirSync(path.join(ROOT,parent)).filter(f=>f.startsWith('executed-')&&f.endsWith('.txt'))){const p=file.slice(9,-4).replaceAll('__','/');assert(beforeAuthor.some((b:any)=>b.path===p),p);assert.deepEqual(read(p),read(parent+file));}
 for(const check of Object.values(result.checks) as any[]){assert.equal(check.exitCode,0);for(const k of ['stdout','stderr'])admit(check[k].path,check[k]);}assert.match(text(parent+'worker-affected.stdout.log'),/pass 7/u);assert.match(text(parent+'app-affected.stdout.log'),/pass 18/u);
 for(const p of [worker+'celestial-object-information.ts',worker+'prepared-optical-imagery.ts',worker+'sdss-optical-imagery.ts',app+'services/api-request-test-support.ts'])walk(p);
 // Dynamic metadata consumers are explicit, not silently treated as imports of the AST-extracted API.
 for(const p of [app+'services/api-client.ts',app+'services/celestial-information-response.ts',app+'services/celestial-information-presentation.ts',app+'hooks/use-celestial-information.ts',app+'sky/sources/index.tsx'])admit(p);
 const protectedPath=task+'/tmp/resume-preserved-hashes-2026-10-01.json';admit(protectedPath);for(const b of json(protectedPath))admit(b.path,b);
 admit(prior+'result.json',{sha256:'3863baddd07c54d3d9564b7951996f2834d4d19585498c864a7149b119e38456'});
 admit(prior+'inputs-before.json');const oldValidator=prior+'executed-apps__wechat-miniapp__src__services__celestial-information-response.ts.txt';admit(oldValidator);const oldRow=json(prior+'inputs-before.json').find((r:any)=>r.path===app+'services/celestial-information-response.ts');admit(oldValidator,oldRow);
 const escapedStale='output/prepared-optical-information-stale-1003-r1/';admit(escapedStale+'result.json');admit(escapedStale+'stdout.log');const escapedStaleResult=json(escapedStale+'result.json');assert.equal(escapedStaleResult.status,'EXPECTED_BEFORE_FIX_FAILURE');assert.equal(escapedStaleResult.exitCode,1);assert.equal(sha(read(escapedStale+'stdout.log')),escapedStaleResult.stdoutSha256);assert.match(text(escapedStale+'stdout.log'),/celestial_information_optical_source_invalid/u);
 const manifestPath='output/prepared-optical-publication-1003-r4/publication/manifest.json',sciencePath='output/sdss-science-optical-writer-1002-r1/publication/manifest.json';admit(manifestPath,{sha256:'23faa1521ae39a6a7d92f36c87ebf691a75b6bd7b91a3654e9b24f63f4d793f1'});admit(sciencePath,{sha256:'3eaf04b366827c86ece835f48ed37089d5406be2ed4d73c2252960e7e9aa1dd5'});
 const manifest=json(manifestPath),science=json(sciencePath),trace=json(result.sourceTrace.path);admit(result.sourceTrace.path,result.sourceTrace);assert.deepEqual(trace.publication,manifest);assert.equal(trace.publicationHash,manifest.publicationHash);assert.deepEqual(trace.httpStatuses,[200,304,200,304,200]);
 assert.equal(trace.partial.dataState,'PARTIAL');assert.deepEqual(trace.partial.warnings,['prepared_optical_publication_unavailable']);assert.equal(trace.fresh.dataState,'FRESH');assert.deepEqual(trace.fresh.warnings,[]);assert.deepEqual(trace.partial.data.facts,trace.fresh.data.facts);assert.deepEqual(trace.partial.data.aliases,trace.fresh.data.aliases);assert.notEqual(trace.partial.etag,trace.fresh.etag);assert.notEqual(trace.partial.data.contentRevision,trace.fresh.data.contentRevision);assert.deepEqual(trace.fresh.sources,trace.fresh.data.sources);
 const etag=(data:any)=>`W/"${sha(JSON.stringify(data)).slice(0,24)}"`;assert.equal(trace.partial.etag,etag(trace.partial.data));assert.equal(trace.fresh.etag,etag(trace.fresh.data));
 const credit=trace.fresh.data.sources.find((s:any)=>s.id.startsWith('prepared-optical-imagery:'));assert(credit);assert.equal(credit.id,`prepared-optical-imagery:${manifest.publicationId}:${manifest.publicationHash}`);assert.equal(credit.attribution.name,manifest.source.credit);assert(credit.attribution.statements.includes(manifest.processing.modification));assert(credit.limitations.includes(manifest.source.colourMeaning));assert(credit.limitations.includes(manifest.source.nominalAvm.spatialNotes));assert.equal(credit.licenseUrl,manifest.source.licenseUrl);assert(!trace.fresh.sources.some((s:any)=>s.id.startsWith('optical-imagery:')));
 const infrared=trace.fresh.sources.find((s:any)=>s.id.startsWith('imagery:'));assert(infrared);assert.deepEqual(trace.partial.sources.find((s:any)=>s.id.startsWith('imagery:')),infrared);const irHash=infrared.id.split(':').at(-1),hash=manifest.publicationHash;
 const before=[...inputs.values()];save('inputs-before.json',before);save('dependency-scope.json',{workspaceGraph:[...graph].map(p=>path.relative(ROOT,p).replaceAll('\\','/')).sort(),bareEntries:[...bare],scope:'Bound relative/workspace sources and resolved bare entries; not a full vendor loaded-module trace. API/source UI functions are explicitly AST extracted.'});
 fs.mkdirSync(path.join(OUT,'sources'));for(const p of [worker+'prepared-optical-imagery.ts',worker+'sdss-optical-imagery.ts',worker+'celestial-object-information.ts',worker+'miniapp-service.ts',app+'services/api-client.ts',app+'services/celestial-information-response.ts',app+'services/celestial-information-presentation.ts'])fs.writeFileSync(path.join(OUT,'sources',p.replaceAll('/','__')+'.txt'),read(p),{flag:'wx'});
 const contracts=await importFile('packages/miniapp-contracts/src/index.ts');const{PreparedOpticalImageryService:Prepared}=await importFile(worker+'prepared-optical-imagery.ts');const{SdssOpticalImageryService:Sdss}=await importFile(worker+'sdss-optical-imagery.ts');const{DeepSkyImageryService:W3}=await importFile(worker+'deep-sky-imagery.ts');const{CelestialObjectInformationService:Info}=await importFile(worker+'celestial-object-information.ts');const{matchingCelestialInformationResponse:matching}=await importFile(app+'services/celestial-information-response.ts');const{celestialInformationPartialDetail:detail}=await importFile(app+'services/celestial-information-presentation.ts');const{transportHarness}=await importFile(app+'services/api-request-test-support.ts');
 const fixtures=path.join(OUT,'fixtures');fs.mkdirSync(fixtures);const local=path.join(fixtures,'prepared-manifest.json'),original=read(manifestPath);fs.writeFileSync(local,original,{flag:'wx'});const descriptor={reference:'M:51',expectedHash:hash,manifestUrl:pathToFileURL(local)};
 const prep=new Prepared([descriptor]),optical=new Sdss(),w3=new W3(),info=new Info(w3,optical,undefined,prep),selection={imageVersion:'source-finite-v3'};
 const get=(owner:any,ref='M:51',pin?:string)=>owner.get(ref,'zh-CN','bsc5p-bright-stars.v3',undefined,selection,pin);
 fs.writeFileSync(local,'{invalid task-owned metadata');assert.equal(prep.hasRegisteredPublicationHash(hash),true);assert.throws(()=>prep.source('M:51',hash));const unavailable=get(info,'M:51',hash),repeated=get(info,'M:51',hash);assert.equal(unavailable.dataState,'PARTIAL');assert.equal(repeated.dataState,'PARTIAL');assert.deepEqual(unavailable.warnings,['prepared_optical_publication_unavailable']);assert(!unavailable.sources.some((s:any)=>/^(?:prepared-)?optical-imagery:/u.test(s.id)));
 fs.writeFileSync(local,original);const recovered=get(info,'M:51',hash);assert.equal(recovered.dataState,'FRESH');assert.deepEqual(recovered.sources.find((s:any)=>s.id===credit.id),credit);assert.deepEqual(recovered.data.facts,unavailable.data.facts);assert.notEqual(recovered.etag,unavailable.etag);assert.deepEqual(read(local),original);record.push({control:'declared ownership is not admission; repeated PARTIAL retries and actual restored same metadata recovers',partialWarnings:unavailable.warnings,recoveredCreditId:credit.id,etagChanged:true});
 const beforeSources=structuredClone(recovered.sources);recovered.data.sources=[];recovered.sources.find((s:any)=>s.id===credit.id).attribution.statements=['caller modified'];assert.deepEqual(get(info,'M:51',hash).sources,beforeSources);
 const foreign=get(info,'M:82',hash),unknown=get(info,'M:51','0'.repeat(64));assert.equal(foreign.dataState,'PARTIAL');assert.deepEqual(foreign.warnings,['prepared_optical_publication_unavailable']);assert.equal(unknown.dataState,'PARTIAL');assert.deepEqual(unknown.warnings,['sdss_optical_publication_unavailable']);for(const response of[foreign,unknown])assert(!response.sources.some((s:any)=>/^(?:prepared-)?optical-imagery:/u.test(s.id)));assert.equal(new Prepared().hasRegisteredPublicationHash(hash),false);assert.throws(()=>new Prepared().manifest(hash));
 const scienceOwner=new Sdss({sciencePublications:[{reference:'M:51',expectedHash:science.publicationHash,manifestUrl:pathToFileURL(path.join(ROOT,sciencePath))}]}),scienceInfo=new Info(w3,scienceOwner,undefined,prep);assert.deepEqual(get(scienceInfo,'M:51',science.publicationHash).sources.find((s:any)=>s.id.startsWith('optical-imagery:')),scienceOwner.source('M:51',science.publicationHash));assert.deepEqual(get(info).data,get(info,'M:51',optical.publicationHash('M:51')).data);record.push({control:'exact foreign and unknown pins do not borrow latest; science/legacy default remain distinct; default Prepared registry empty',foreignWarnings:foreign.warnings,unknownWarnings:unknown.warnings,scienceHash:science.publicationHash});
 let moonCalls=0;const moon={manifest(){moonCalls++;throw new Error('controlled third Moon unavailable');}},moonInfo=new Info(w3,optical,moon,prep);const moonResult=moonInfo.get('SOLAR:MOON');assert.equal(moonCalls,1);assert.deepEqual(moonResult.warnings,['moon_texture_publication_unavailable']);record.push({control:'third constructor argument remains the Moon owner',moonCalls});
 // One precise module/class guard mutant; metadata/default helpers are actual production declarations.
 const conflicting=new Sdss({sciencePublications:[{reference:'M:51',expectedHash:hash,manifestUrl:pathToFileURL(path.join(fixtures,'unread-conflicting-science.json'))}]}),ambiguous=get(new Info(w3,conflicting,undefined,prep),'M:51',hash);assert.equal(ambiguous.dataState,'PARTIAL');assert(!ambiguous.sources.some((s:any)=>/^(?:prepared-)?optical-imagery:/u.test(s.id)));
 const moduleDecl=declarations(worker+'celestial-object-information.ts'),classCode=moduleDecl.statement('CelestialObjectInformationService'),needle='if (this.optical.hasRegisteredPublicationHash(opticalPublicationHash)) throw new Error("optical_publication_family_ambiguous");';assert.equal(classCode.split(needle).length,2);
 const astro=await importFile('packages/astronomy-core/src/deep-sky-catalog.ts'),aliases=await importFile(worker+'celestial-object-aliases.ts'),provider=await importFile(worker+'deep-sky-scene-provider.ts');const mutatedClass=classCode.replace(needle,'');fs.writeFileSync(path.join(OUT,'family-claim-guard-mutant.ts.txt'),mutatedClass,{flag:'wx'});
 const construct=vm.runInNewContext(ts.transpileModule(moduleDecl.statement('digest')+'\n'+moduleDecl.statement('envelope')+'\n'+mutatedClass+'\nCelestialObjectInformationService;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,{...contracts,...astro,...aliases,...provider,DeepSkyImageryService:W3,SdssOpticalImageryService:Sdss,PreparedOpticalImageryService:Prepared,createHash,randomUUID,structuredClone,EDITORIAL_REVISION:'starward-celestial-editorial-zh-cn@2',INTRODUCTIONS:{}});
 const escaped=get(new construct(w3,conflicting,moon,prep),'M:51',hash);assert.equal(escaped.dataState,'FRESH');assert(escaped.sources.some((s:any)=>s.id===credit.id));record.push({control:'cross-family ownership guard removal is detected',actual:ambiguous.dataState,mutant:escaped.dataState});
 const api=app+'services/api-client.ts',bindings={...contracts,__MINIAPP_API_BASE__:'https://source.example.invalid',MINIAPP_API_BASE_PATH:'/v2',matchingCelestialInformationResponse:matching,ADOPTED_SKY_REPORT_CATALOG_VERSION:'bsc5p-bright-stars.v3'};
 const link=actualFn(api,'deepSkyManifestUrl',bindings);assert.equal(link(credit.id),undefined);assert.equal(link(credit.id,hash),`https://source.example.invalid/v2/sky/prepared-optical/${hash}/manifest`);assert.equal(link(credit.id,'0'.repeat(64)),undefined);assert.equal(link(infrared.id,hash),`https://source.example.invalid/v2/sky/deep-sky/${irHash}/manifest`);const badLink=actualFn(api,'deepSkyManifestUrl',bindings,s=>{const n='boundOptical?.[2] === expectedOpticalHash';assert.equal(s.split(n).length,2);return s.replace(n,'boundOptical');});assert(badLink(credit.id,'0'.repeat(64)));record.push({control:'Prepared manifest path and W3 version independent; explicit hash gate mutant wrongly links another version',badLink:badLink(credit.id,'0'.repeat(64))});
 assert.equal(matching(trace.fresh,'M:51',irHash,hash),trace.fresh);assert.equal(matching(trace.partial,'M:51',irHash,hash),trace.partial);
 const mix=structuredClone(trace.fresh);mix.data.sources.push({...credit,id:`optical-imagery:competing:${hash}`});mix.sources=mix.data.sources;assert.throws(()=>matching(mix,'M:51',irHash,hash),/optical_source_invalid/u);const mixedMatcher=actualFn(app+'services/celestial-information-response.ts','matchingCelestialInformationResponse',contracts,s=>{const n='opticalSources.length > 1 ||';assert.equal(s.split(n).length,2);return s.replace(n,'');});assert.equal(mixedMatcher(mix,'M:51',irHash,hash),mix);record.push({control:'single optical-family/version guard mutant accepts conflicting double source',actualRejected:true,mutantAccepted:true});
 const h=transportHarness(),getClient=actualFn(api,'getCelestialObjectInformation',{...bindings,invalidateApiCache:h.invalidateApiCache,requestOperation:(key:string,_op:string,o:any)=>h.request(key,'/information?'+o.query,{signal:o.signal})});
 const first=getClient('M:51',undefined,irHash,hash);h.calls.at(-1).success({statusCode:200,data:trace.partial});assert.deepEqual(await first,trace.partial);await h.flush();const second=getClient('M:51',undefined,irHash,hash);h.calls.at(-1).fail({errMsg:'request:fail independent offline'});const stale=await second;assert.equal(stale.dataState,'STALE_USABLE');assert.deepEqual(stale.data.facts,trace.partial.data.facts);assert(stale.warnings.includes('prepared_optical_publication_unavailable'));assert.match(detail(stale),/光学影像来源暂不可用/u);
 const historicalMatcher=actualFn(oldValidator,'matchingCelestialInformationResponse',contracts);assert.throws(()=>historicalMatcher(stale,'M:51',irHash,hash),/optical_source_invalid/u);const unmarked=structuredClone(stale);unmarked.warnings=[];assert.throws(()=>matching(unmarked,'M:51',irHash,hash),/optical_source_invalid/u);const falseFresh=structuredClone(stale);falseFresh.dataState='FRESH';assert.throws(()=>matching(falseFresh,'M:51',irHash,hash),/optical_source_invalid/u);
 const both=structuredClone(stale);both.data.sources=both.data.sources.filter((s:any)=>!s.id.startsWith('imagery:'));both.sources=both.data.sources;assert.throws(()=>matching(both,'M:51',irHash,hash),/image_source_invalid/u);both.warnings.push('deep_sky_image_publication_unavailable');assert.equal(matching(both,'M:51',irHash,hash),both);const wrong=structuredClone(trace.fresh);wrong.data.sources.find((s:any)=>s.id===credit.id).id=credit.id.replace(hash,'0'.repeat(64));wrong.sources=wrong.data.sources;wrong.dataState='STALE_USABLE';wrong.warnings=['prepared_optical_publication_unavailable'];assert.throws(()=>matching(wrong,'M:51',irHash,hash),/optical_source_invalid/u);
 const retry=getClient('M:51',undefined,irHash,hash);h.calls.at(-1).success({statusCode:200,data:trace.fresh});assert.deepEqual(await retry,trace.fresh);const abort=new AbortController(),cancelled=getClient('M:51',abort.signal,irHash,hash);abort.abort();await assert.rejects(cancelled);assert.equal(h.counts().aborts,1);h.queryClient.clear();assert.equal(h.timers.size,0);record.push({control:'actual request/cache/staleCandidate -> actual client: partial -> stale -> samepin fresh; saved R3 validator fails exact same stale value; abort propagated',staleWarnings:stale.warnings,cancellationAborts:1});
 // Actual source-page function/Hook declarations; native components and query delivery remain controlled.
 const requests:any[]=[],hideCallbacks:any[]=[],showCallbacks:any[]=[];let visible=true,current=trace.fresh,retries=0;
 const page=actualFn(app+'sky/sources/index.tsx','CelestialSourcesPage',{...contracts,React:{createElement:(type:any,props:any,...children:any[])=>({type,props:props??{},children})},View:'View',ScrollView:'ScrollView',CustomNav:'CustomNav',Provenance:'Provenance',StatusPanel:'StatusPanel',useRouter:()=>({params:{reference:'M%3A51',opticalPublicationHash:hash,imagePublicationHash:irHash}}),useState:()=>[visible,(v:boolean)=>{visible=v;}],useDidHide:(f:any)=>hideCallbacks.push(f),useDidShow:(f:any)=>showCallbacks.push(f),useThemeClass:()=>'',isProductSource:()=>true,deepSkyManifestUrl:link,celestialInformationPartialDetail:detail,useCelestialInformation:(...args:any[])=>{requests.push(args);return{data:current,isPending:false,isError:false,refreshError:null,refetch:()=>{retries++;return Promise.resolve();}};}});
 const find=(node:any,predicate:any):any=>{if(Array.isArray(node)){for(const x of node){const value=find(x,predicate);if(value)return value;}return null;}if(predicate(node))return node;for(const x of node?.children??[]){const value=find(x,predicate);if(value)return value;}return null;};
 const tree=page(),provenance=find(tree,(n:any)=>n?.type==='Provenance'&&n.props.source.id===credit.id);assert.equal(provenance.props.source,current.data.sources.find((s:any)=>s.id===credit.id));assert.equal(provenance.props.downloadUrl,link(credit.id,hash));assert.deepEqual(Array.from(requests.at(-1)),['M:51',true,irHash,hash]);current=stale;const retryPanel=find(page(),(n:any)=>n?.type==='StatusPanel'&&n.props.state==='PARTIAL');assert(retryPanel);retryPanel.props.onRecover();assert.equal(retries,1);hideCallbacks[0]();page();assert.equal(requests.at(-1)[1],false);showCallbacks[0]();page();assert.equal(requests.at(-1)[1],true);
 const hook=actualFn(app+'hooks/use-celestial-information.ts','useCelestialInformation',{...contracts,getCelestialObjectInformation:getClient,useResourceQuery:(options:any)=>options});const key=Array.from(hook('M:51',true,irHash,hash).queryKey);assert(key.includes(hash)&&key.includes(irHash));assert.equal(hook('M:51',true,irHash,'bad').enabled,false);assert.equal(hook('SOLAR:MOON',true,undefined,hash).enabled,false);record.push({control:'actual source page preserves full original Prepared credit/selected two hashes and hide/restore query gate; partial retry keeps same pin',preparedDownload:provenance.props.downloadUrl,queryKey:key,retries,scope:'Props/AST controlled native elements and query delivery; not rendered WXML or associated visible credit.'});
 save('observations.json',{savedTraceStatuses:trace.httpStatuses,savedPartialEtag:trace.partial.etag,savedFreshEtag:trace.fresh.etag,fullPreparedCredit:credit,controls:record,selectedDeclarations:selections,taskFixtureRestored:sha(fs.readFileSync(local))===sha(original)});
 const after=before.map(row=>bind(row.path));assert.deepEqual(before,after);save('inputs-after.json',after);save('result.json',{status:'INDEPENDENT_BOUNDED_PREPARED_INFORMATION_PASS',authorResult:bind(parent+'result.json'),sourceTrace:bind(result.sourceTrace.path),scopedSourceCurrentExact:true,inputs:before.length,protectedUnchanged:6,controls:record.length,guardMutantsDetected:3,actualSavedR3StaleFailureDetected:true,sourceKindsPreserved:true,defaultPreparedEmpty:true,originalPreparedFixtureRestored:true,scope:'Saved real loopback HTTP bodies/statuses + direct source owners and actual AST/client request/cache functions. No new HTTP listener/network, image decode/render/GPU/native/ordinary adoption/full visible credit/quality/resources/capacity certification. Workspace graph plus selected bare entry bindings, not full vendor trace.',observations:bind(path.relative(ROOT,path.join(OUT,'observations.json')).replaceAll('\\','/'))});
 console.log(JSON.stringify({result:bind(path.relative(ROOT,path.join(OUT,'result.json')).replaceAll('\\','/')),observations:bind(path.relative(ROOT,path.join(OUT,'observations.json')).replaceAll('\\','/')),inputs:before.length,controls:record.length}));
}catch(error){save('failed.json',{status:'FAILED_INDEPENDENT_INFORMATION_PROBE',message:String(error),inputs:[...inputs.values()],controls:record});throw error;}
