// Generated by tools/miniapp/generate-design-tokens.mjs from DESIGN.md. Do not edit.
// Token SHA256: 66374f88024d68e3283fef8766d65e7c08f4bc6e66229fd7af8561ce43d3c34b

export const MINIAPP_DESIGN = {
  "schema": 1,
  "unit": "logical-px",
  "fontFamily": "\"Noto Sans SC\", \"PingFang SC\", \"Microsoft YaHei UI\", \"Microsoft YaHei\", system-ui, sans-serif",
  "type": {
    "page-title": {
      "size": 18,
      "line": 25,
      "weight": 600
    },
    "spot-title": {
      "size": 20,
      "line": 28,
      "weight": 600
    },
    "section": {
      "size": 16,
      "line": 23,
      "weight": 600
    },
    "body": {
      "size": 15,
      "line": 22,
      "weight": 400
    },
    "body-secondary": {
      "size": 14,
      "line": 21,
      "weight": 400
    },
    "action": {
      "size": 14,
      "line": 20,
      "weight": 500
    },
    "search": {
      "size": 16,
      "line": 23,
      "weight": 400
    },
    "metadata": {
      "size": 12,
      "line": 18,
      "weight": 400
    },
    "data": {
      "size": 18,
      "line": 25,
      "weight": 500
    },
    "article": {
      "size": 16,
      "line": 26,
      "weight": 400
    },
    "critical": {
      "size": 14,
      "line": 20,
      "weight": 500
    },
    "display": {
      "size": 20,
      "line": 28,
      "weight": 600
    }
  },
  "geometry": {
    "target-min": 44,
    "icon-small": 18,
    "icon-medium": 20,
    "icon-large": 24,
    "page-inset": 16,
    "map-inset": 12,
    "space-related": 4,
    "space-inline": 8,
    "space-group": 12,
    "space-section": 18,
    "radius-control": 8,
    "radius-panel": 12,
    "radius-sheet": 18,
    "switch-width": 46,
    "switch-height": 24,
    "switch-thumb": 20,
    "switch-inset": 2,
    "switch-travel": 22,
    "mode-track-height": 36,
    "mode-track-max-width": 320
  },
  "themes": {
    "day": {
      "canvas": "#ffffff",
      "surface": "#ffffff",
      "surface-subtle": "#f6f7f5",
      "surface-elevated": "#ffffff",
      "text-primary": "#282b29",
      "text-secondary": "#5e655f",
      "text-tertiary": "#6d746d",
      "text-muted": "var(--text-tertiary)",
      "border": "#e2e5dd",
      "border-strong": "#8a9088",
      "primary": "#8799f6",
      "primary-pressed": "#4859b8",
      "on-primary": "#202332",
      "accent-cyan": "#62c88b",
      "accent-violet": "#8799f6",
      "accent-warm": "#f2c94c",
      "success": "#1f6b45",
      "positive": "#1f6b45",
      "warning": "#6f5500",
      "danger": "#973d37",
      "focus": "#6174d8",
      "pressed-overlay": "rgba(135, 153, 246, 0.12)",
      "favorite-outline": "#4859b8",
      "favorite-active": "#f2c94c",
      "favorite-fill": "#f2c94c",
      "favorite-stroke": "#6f5500",
      "choice-selected-surface": "#f5f6ff",
      "choice-selected-border": "#8799f6",
      "choice-selected-label": "#4859b8",
      "choice-clipped-star": "#f2c94c",
      "icon-violet-soft": "#f5f6ff",
      "icon-green-soft": "#e9f8ee",
      "icon-gold-soft": "#fff7d6",
      "icon-coral-soft": "#fff0ed",
      "elevation-card": "none",
      "elevation-floating": "0 4rpx 16rpx rgba(40, 43, 41, 0.07)",
      "map-tint": "#ffffff"
    },
    "night": {
      "canvas": "#11120f",
      "surface": "#181a17",
      "surface-subtle": "#242720",
      "surface-elevated": "#181a17",
      "text-primary": "#f5f3ec",
      "text-secondary": "#bec2b8",
      "text-tertiary": "#989e94",
      "text-muted": "var(--text-tertiary)",
      "border": "#343830",
      "border-strong": "#666d62",
      "primary": "#a9b6ff",
      "primary-pressed": "#d1d7ff",
      "on-primary": "#202332",
      "accent-cyan": "#7ed7a1",
      "accent-violet": "#a9b6ff",
      "accent-warm": "#f6d56f",
      "success": "#b7eacb",
      "positive": "#b7eacb",
      "warning": "#ffe5a0",
      "danger": "#ffc0ba",
      "focus": "#b4beff",
      "pressed-overlay": "rgba(169, 182, 255, 0.14)",
      "favorite-outline": "#d1d7ff",
      "favorite-active": "#f6d56f",
      "favorite-fill": "#f6d56f",
      "favorite-stroke": "#ffe5a0",
      "choice-selected-surface": "#292d45",
      "choice-selected-border": "#a9b6ff",
      "choice-selected-label": "#d1d7ff",
      "choice-clipped-star": "#f6d56f",
      "icon-violet-soft": "#292d45",
      "icon-green-soft": "#1b3426",
      "icon-gold-soft": "#3a3118",
      "icon-coral-soft": "#452724",
      "elevation-card": "none",
      "elevation-floating": "0 8rpx 24rpx rgba(0, 0, 0, 0.28)",
      "map-tint": "#11120f"
    },
    "observation": {
      "canvas": "#000000",
      "surface": "#110000",
      "surface-subtle": "#190000",
      "surface-elevated": "#240000",
      "text-primary": "#ff6b58",
      "text-secondary": "#d84a3c",
      "text-tertiary": "#d84a3c",
      "text-muted": "var(--text-tertiary)",
      "border": "#7a1e18",
      "border-strong": "#a83229",
      "primary": "#d84a3c",
      "primary-pressed": "#ff6b58",
      "on-primary": "#000000",
      "accent-cyan": "#d84a3c",
      "accent-violet": "#d84a3c",
      "accent-warm": "#ff6b58",
      "success": "#ff6b58",
      "positive": "#ff6b58",
      "warning": "#ff6b58",
      "danger": "#ff6b58",
      "focus": "#ff6b58",
      "pressed-overlay": "rgba(216, 74, 60, 0.16)",
      "favorite-outline": "#d84a3c",
      "favorite-active": "#ff6b58",
      "favorite-fill": "#d84a3c",
      "favorite-stroke": "#ff6b58",
      "choice-selected-surface": "#190000",
      "choice-selected-border": "#a83229",
      "choice-selected-label": "#ff6b58",
      "choice-clipped-star": "#d84a3c",
      "icon-violet-soft": "#190000",
      "icon-green-soft": "#190000",
      "icon-gold-soft": "#190000",
      "icon-coral-soft": "#240000",
      "elevation-card": "none",
      "elevation-floating": "none",
      "map-tint": "#000000"
    }
  }
} as const;

export const NATIVE_CHROME_THEME = {
  "DAY": {
    "canvas": "#FFFFFF",
    "color": "#5E655F",
    "selectedColor": "#4859B8",
    "backgroundColor": "#FFFFFF",
    "borderStyle": "white",
    "suffix": ""
  },
  "NIGHT": {
    "canvas": "#11120F",
    "color": "#989E94",
    "selectedColor": "#D1D7FF",
    "backgroundColor": "#181A17",
    "borderStyle": "black",
    "suffix": "-night"
  },
  "OBSERVATION": {
    "canvas": "#000000",
    "color": "#D84A3C",
    "selectedColor": "#FF6B58",
    "backgroundColor": "#110000",
    "borderStyle": "black",
    "suffix": "-observation"
  }
} as const;
