import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, minimumTouchTarget, radii, spacing, type as typeToken } from "@starward/ui-system/tokens";
type Key = "pretrip-rule" | "intrip-risk-deeplink" | "long-term-controls" | "calendar-and-station" | "position-tools" | "professional-tool-boundaries" | "educational-content-priority";
const p = colors.planning;
const cases: Record<Key, { action: string; label: string; evidence: Array<[string, string, string, string?]> }> = {
  "pretrip-rule": { action: "tools-create-pretrip-rule", label: "行前提醒", evidence: [["notification-rule-trigger", "出发前提醒 · 银河窗口前 90 分钟首次跨过阈值", "评分由 76 升至 82，阈值 80；地点西涌，窗口 00:35–02:20", "仅边沿触发；同事件/区域冷却 6 小时"], ["notification-rule-channel", "本地提醒 + APP 收件箱", "默认关闭，用户明确 opt-in；远端通道待发行渠道 POC"], ["notification-rule-preview", "预览：23:05 条件改善", "处于 22:00–08:00 免打扰，将延后且不重复发送"]] },
  "intrip-risk-deeplink": { action: "tools-open-risk-notification", label: "途中风险", evidence: [["notification-risk-reason", "路线封路风险上升", "触发于 22:14 · 行程 revision 7 · 道路源 run-18"], ["notification-deeplink-target", "打开当前计划风险段", "先显示触发快照，再刷新当前路线与主备状态"], ["notification-risk-action", "切换备选 / 刷新路线 / 取消出发", "若条件反转，旧通知只保留为历史，不冒充当前结论"]] },
  "long-term-controls": { action: "tools-change-notification-controls", label: "长期控制", evidence: [["notification-topic-control", "长期类别已关闭", "新月、流星雨、收藏地点实况均不发送；可单条恢复"], ["notification-quiet-hours", "免打扰 22:00–08:00", "规则显示上次评估和下一可触发时间"], ["notification-consent-state", "系统权限与产品订阅分离", "撤回产品订阅会停止远端发送；本地状态冲突会显式标出"]] },
  "calendar-and-station": { action: "tools-add-calendar-event", label: "日历/空间站", evidence: [["calendar-event-time", "本地日食不可见", "显示最近可见地点/日期，不生成虚假倒计时"], ["calendar-event-timezone", "2026-08-13 · Asia/Shanghai", "当地时间与 UTC、位置及算法版本可展开"], ["station-mode-state", "固定地点 · 空间站可见过境 · 可信度中", "00:42 开始 东北 12° · 00:45 最高 61° · 00:49 结束 西南 8°；OMM epoch 仍待生产源确认"]] },
  "position-tools": { action: "tools-open-position", label: "位置工具", evidence: [["position-azimuth", "方位 168°", "木星与银河核心复用同一 Astronomy 版本"], ["position-altitude", "高度 34° · 亮度/遮挡分开", "升起、中天、落下与天空地图使用同一地点"], ["position-time", "00:40 · Asia/Shanghai", "指定时间、WGS84 位置和算法版本始终可见"]] },
  "professional-tool-boundaries": { action: "tools-open-professional", label: "专业工具", evidence: [["tool-precision-label", "防脱焦计算 · 可用", "输入焦距、光圈、传感器与距离；输出单位和公式假设可见"], ["tool-data-source", "Starward optics rules v1", "本地确定性公式；其他远端工具逐项通过许可/覆盖 POC 才启用"], ["tool-limitation", "仅供参考 · 精度限制", "极轴镜/极光/彗星等标 V3 实验或 disabled，不显示可点击空壳"]] },
  "educational-content-priority": { action: "tools-open-learning-card", label: "学习内容", evidence: [["learning-prerequisite", "先理解月光与云层", "内容位于工具箱，不占据‘今晚’决策首屏"], ["learning-safety-note", "夜间出行优先安全", "核对开放、返程、天气和同伴；教育内容不替代现场判断"], ["learning-next-action", "查看自己的计划证据", "来源、许可、发布日期和版权状态可见；未确认媒体仅外链"]] },
};
function Evidence({ item }: { item: [string, string, string, string?] }) { return <View testID={item[0]} style={s.evidence}><Text style={s.evidenceTitle}>{item[1]}</Text><Text style={s.evidenceBody}>{item[2]}</Text>{item[3] ? <Text style={s.meta}>{item[3]}</Text> : null}</View>; }
export function ToolsScreen({ fixture }: { fixture?: string }) { const recommended = fixture?.split(":")[1] as Key | undefined; const [active, setActive] = useState<Key | null>(null); return <SafeAreaView testID="screen-notifications-and-toolbox" style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>提醒与专业工具</Text><Text style={s.title}>只在变化值得行动时提醒</Text><Text style={s.subtitle}>事件按受影响网格批量评估、边沿触发、去重和冷却；工具显示位置、时间、版本与限制。</Text><View style={s.actions}>{(Object.keys(cases) as Key[]).map((key) => <Pressable key={key} testID={cases[key].action} onPress={() => setActive(key)} style={[s.action, recommended === key && s.recommended]}><Text style={s.actionText}>{cases[key].label}</Text></Pressable>)}</View>{active ? <View style={s.panel}>{cases[active].evidence.map((item) => <Evidence key={item[0]} item={item} />)}</View> : <View style={s.empty}><Text style={s.emptyTitle}>通知默认全部关闭</Text><Text style={s.emptyBody}>从地点、行程或事件明确创建；MVP 以本地提醒和 APP 收件箱为权威。</Text></View>}</ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: p.canvas }, content: { padding: spacing.x2, paddingBottom: 48, gap: spacing.x2 }, eyebrow: { color: p.primaryActive, fontSize: typeToken.label, fontWeight: "700" }, title: { color: p.text, fontSize: typeToken.title, fontWeight: "700" }, subtitle: { color: p.textSecondary, fontSize: typeToken.body, lineHeight: 23 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x1 }, action: { minHeight: minimumTouchTarget, justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: p.border, borderRadius: radii.pill, backgroundColor: p.surface }, recommended: { borderColor: p.primaryActive }, actionText: { color: p.text, fontWeight: "700", fontSize: typeToken.label }, panel: { gap: spacing.x1, padding: spacing.x2, borderRadius: radii.layer, backgroundColor: p.surface }, evidence: { minHeight: 86, padding: 12, borderRadius: radii.control, backgroundColor: p.surfaceMuted }, evidenceTitle: { color: p.text, fontWeight: "700" }, evidenceBody: { marginTop: 5, color: p.text, lineHeight: 19 }, meta: { marginTop: 5, color: p.textSecondary, fontSize: typeToken.caption }, empty: { minHeight: 150, justifyContent: "center", padding: spacing.x2, backgroundColor: p.surface, borderRadius: radii.layer }, emptyTitle: { color: p.text, fontWeight: "700", fontSize: typeToken.section }, emptyBody: { marginTop: 8, color: p.textSecondary } });
