import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { BASE_CHECKLIST, SHOOTING_RULE_VERSION, buildShootingPlan, mergeChecklist, saveShootingPlanVersion, type ShootingInput } from "@starward/domain/shooting";
import { colors, minimumTouchTarget, radii, spacing, type as typeToken } from "@starward/ui-system/tokens";

type CaseKey = "mobile-plan" | "camera-plan-and-risk" | "preset-boundary" | "checklist-offline" | "versioned-save" | "ai-is-explanation";
const palette = colors.night;
const actions: Record<CaseKey, { id: string; label: string }> = {
  "mobile-plan": { id: "shooting-create-mobile-plan", label: "手机方案" }, "camera-plan-and-risk": { id: "shooting-create-camera-plan", label: "相机方案" },
  "preset-boundary": { id: "shooting-apply-preset", label: "预设" }, "checklist-offline": { id: "shooting-save-checklist", label: "清单" },
  "versioned-save": { id: "shooting-save-version", label: "保存版本" }, "ai-is-explanation": { id: "shooting-open-ai-explanation", label: "为什么" },
};
const conditions = { capturedAt: "2026-08-12T12:00:00Z", sourceVersions: ["weather-fixture-7", "astronomy-fixture-5"], lightPollutionSqm: 20.5, moonIllumination: 0.1, totalCloudPercent: 12, windMps: 2.1, humidityPercent: 60, targetAltitudeDeg: 36 };
const cameraInput: ShootingInput = { target: "milky-way", locationId: "fixture-spot", scheduledAt: "2026-08-12T16:40:00Z", timezone: "Asia/Shanghai", acceptsStacking: true, experience: "intermediate", conditions, equipment: { kind: "camera", model: "全画幅相机", sensorWidthMm: 36, sensorHeightMm: 24, focalLengthMm: 20, maxAperture: 2.8, tracker: false, tripod: true } };
const phoneInput: ShootingInput = { ...cameraInput, experience: "beginner", equipment: { kind: "phone", model: "iPhone 15 Pro（能力夹具）", focalLengthMm: 6.8, equivalentFocalLengthMm: 24, tripod: true, controls: ["iso", "shutter", "white-balance", "focus", "exposure-compensation", "burst", "raw", "night-mode"] } };

function Evidence({ testID, title, body, meta }: { testID: string; title: string; body: string; meta?: string }) { return <View testID={testID} style={styles.evidence}><Text style={styles.evidenceTitle}>{title}</Text><Text style={styles.evidenceBody}>{body}</Text>{meta ? <Text style={styles.evidenceMeta}>{meta}</Text> : null}</View>; }
function MobilePanel() { const plan = buildShootingPlan(phoneInput); return <View style={styles.panel}><Evidence testID="shooting-phone-model" title={phoneInput.equipment.model} body="主摄 · 实际 6.8 mm / 等效 24 mm · 三脚架" meta="仅显示能力目录声明支持的控制" /><Evidence testID="shooting-mobile-settings" title={`曝光 ${plan.settings.shutterSeconds} 秒 · ISO ${plan.settings.iso}`} body={`白平衡 ${plan.settings.whiteBalanceK} K · ${plan.settings.focus} · ${plan.settings.captureMode} · 堆栈 ${plan.settings.stackingFrames} 帧`} meta={`${plan.ruleVersion} · 条件 ${plan.provenance.conditionsCapturedAt}`} /><Evidence testID="shooting-mobile-risk" title="先试拍并放大检查" body={plan.alternatives.join("；")} meta={`可信度 ${Math.round(plan.confidence * 100)}%；设备控制仍需真机验证`} /></View>; }
function CameraPanel() { const plan = buildShootingPlan(cameraInput); return <View style={styles.panel}><Evidence testID="shooting-camera-settings" title={`f/${plan.settings.aperture} · ${plan.settings.shutterSeconds} 秒 · ISO ${plan.settings.iso}`} body={`${plan.settings.focus} · 间隔 ${plan.settings.intervalSeconds} 秒 · 堆栈 ${plan.settings.stackingFrames} 张 · 长曝降噪关闭`} meta={`${plan.ruleVersion} · 用户调整会单独记录`} /><Evidence testID="shooting-lens-field" title="20 mm · 横向银河拱桥" body={String(plan.settings.composition)} meta="实际焦段和传感器尺寸共同参与拖线/视场计算" /><Evidence testID="shooting-risk-note" title="拖线风险 · 必须先试拍" body={`${plan.risks.join("；")}；替代：${plan.alternatives.join("；")}`} /></View>; }
function PresetPanel() { return <View style={styles.panel}><Evidence testID="shooting-preset-source" title="空间站轨迹 · V3 预设" body="当前版本缺少已验证的过境轨迹和设备曝光规则" meta="预设目录 v1；依赖 OMM 新鲜度与专家验证" /><Evidence testID="shooting-preset-assumptions" title="适用条件尚不完整" body="不会生成无依据完整参数；保留地点、时间、设备和基础构图字段" /><Evidence testID="shooting-preset-adjustment" title="进入自定义" body="可改选已支持的手机银河、相机银河、星轨、月亮或流星雨规则" /></View>; }
function ChecklistPanel() { const [items, setItems] = useState(() => mergeChecklist([{ ...BASE_CHECKLIST[0], done: true }, { ...BASE_CHECKLIST[1], done: true }, { ...BASE_CHECKLIST[2], done: true }], [])); const done = items.filter((item) => item.done).length; return <View style={styles.panel}><Evidence testID="shooting-checklist-items" title={`清单 ${done}/${items.length}`} body={items.map((item) => `${item.done ? "✓" : "○"} ${item.label}`).join(" · ")} meta="出发前与现场分组；关键项不能被空模板静默删除" /><Pressable onPress={() => setItems((current) => current.map((item, index) => index === 3 ? { ...item, done: true } : item))}><Evidence testID="shooting-checklist-offline" title="离线可用" body="勾选先写本地 revision，联网后按幂等键合并，不丢历史" /></Pressable><Evidence testID="shooting-checklist-progress" title="关键礼仪保留" body="关闭自动闪光，避免白光干扰；成员分工仅在真实协作时显示" /></View>; }
function VersionPanel() { const v3 = saveShootingPlanVersion(null, { ...cameraInput, equipment: { ...cameraInput.equipment as Extract<ShootingInput["equipment"], { kind: "camera" }>, focalLengthMm: 14 } }, { iso: 1600 }, "2026-08-12T10:00:00Z"); const v4 = saveShootingPlanVersion({ ...v3, revision: 3 }, cameraInput, { iso: 1600 }, "2026-08-12T12:00:00Z"); return <View style={styles.panel}><Evidence testID="shooting-plan-version" title={`拍摄方案版本 ${v4.revision}`} body={`规则 ${v4.result.ruleVersion} · 条件 ${v4.result.provenance.conditionsCapturedAt}`} meta="离线包引用明确版本，天气/设备变化会标 stale" /><Evidence testID="shooting-change-summary" title="变化摘要" body="焦段由 14 mm 调整为 20 mm；拖线限制与构图已重算；用户 ISO 1600 覆盖保留" /><Evidence testID="shooting-restore-version" title="可恢复版本 3" body="旧输入、条件快照、规则结果和用户覆盖均保持不可变" /></View>; }
function AiPanel() { const plan = buildShootingPlan(cameraInput); return <View style={styles.panel}><Evidence testID="shooting-rule-result" title={`规则结果 · ISO ${plan.settings.iso} / ${plan.settings.shutterSeconds} 秒 / f${plan.settings.aperture}`} body={plan.risks.join("；")} meta={plan.ruleVersion} /><Evidence testID="shooting-ai-explanation" title="规则解释可用" body="AI provider 默认禁用；当前解释来自版本化规则和已展示条件，不依赖网络" meta="精确地点、路线、身份、媒体和 EXIF 不会发送" /><Evidence testID="shooting-ai-boundary" title="不会编造或覆盖规则参数" body="未来 AI 仅可解释取舍；超时、撤回同意或未批准时不损坏核心方案" /></View>; }

export function ShootingScreen({ fixture }: { fixture?: string }) {
  const fixtureCase = fixture?.split(":")[1] as CaseKey | undefined; const [active, setActive] = useState<CaseKey | null>(null);
  const context = useMemo(() => `${cameraInput.scheduledAt.slice(0, 16).replace("T", " ")} · ${cameraInput.timezone}`, []);
  return <SafeAreaView testID="screen-shooting-assistant" style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>摄影助手 · 银河</Text><Text style={styles.title}>确定性参数，现场可执行</Text><Text style={styles.subtitle}>地点 fixture-spot · {context}。器材、目标运动与环境规则先计算；AI 只解释。</Text><View style={styles.summary}><Text style={styles.summaryTitle}>条件快照</Text><Text style={styles.summaryBody}>SQM 20.5 · 月相 10% · 云量 12% · 风 2.1 m/s · 湿度 60% · 目标高度 36°</Text></View><View style={styles.actions}>{(Object.keys(actions) as CaseKey[]).map((key) => <Pressable key={key} testID={actions[key].id} accessibilityRole="button" onPress={() => setActive(key)} style={({ pressed }) => [styles.action, fixtureCase === key && styles.actionRecommended, pressed && styles.pressed]}><Text style={styles.actionText}>{actions[key].label}</Text></Pressable>)}</View>{active === "mobile-plan" ? <MobilePanel /> : null}{active === "camera-plan-and-risk" ? <CameraPanel /> : null}{active === "preset-boundary" ? <PresetPanel /> : null}{active === "checklist-offline" ? <ChecklistPanel /> : null}{active === "versioned-save" ? <VersionPanel /> : null}{active === "ai-is-explanation" ? <AiPanel /> : null}{!active ? <View style={styles.empty}><Text style={styles.emptyTitle}>选择设备方案或检查工具</Text><Text style={styles.emptyBody}>条件缺失时降低可信度并列出缺口，不把缺失值当成 0。</Text></View> : null}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.canvas }, content: { padding: spacing.x2, paddingBottom: 48, gap: spacing.x2 }, eyebrow: { color: palette.primary, fontSize: typeToken.label, fontWeight: "700" }, title: { color: palette.text, fontSize: typeToken.title, lineHeight: 32, fontWeight: "700" }, subtitle: { color: palette.textSecondary, fontSize: typeToken.body, lineHeight: 23 }, summary: { padding: spacing.x2, borderRadius: radii.layer, backgroundColor: palette.surface }, summaryTitle: { color: palette.text, fontWeight: "700" }, summaryBody: { marginTop: 6, color: palette.textSecondary, lineHeight: 20 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x1 }, action: { minHeight: minimumTouchTarget, justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: palette.border, borderRadius: radii.pill, backgroundColor: palette.surface }, actionRecommended: { borderColor: palette.primary }, actionText: { color: palette.text, fontSize: typeToken.label, fontWeight: "700" }, panel: { gap: spacing.x1, padding: spacing.x2, borderWidth: 1, borderColor: palette.border, borderRadius: radii.layer, backgroundColor: palette.surface }, evidence: { minHeight: 86, padding: 12, borderRadius: radii.control, backgroundColor: palette.surfaceMuted }, evidenceTitle: { color: palette.text, fontSize: typeToken.body, fontWeight: "700" }, evidenceBody: { marginTop: 5, color: palette.text, fontSize: typeToken.label, lineHeight: 19 }, evidenceMeta: { marginTop: 5, color: palette.textSecondary, fontSize: typeToken.caption, lineHeight: 17 }, empty: { minHeight: 140, justifyContent: "center", padding: spacing.x2, borderWidth: 1, borderColor: palette.border, borderRadius: radii.layer, backgroundColor: palette.surface }, emptyTitle: { color: palette.text, fontSize: typeToken.section, fontWeight: "700" }, emptyBody: { marginTop: spacing.x1, color: palette.textSecondary, lineHeight: 21 }, pressed: { opacity: 0.7 } });
