import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { BASE_CHECKLIST, mergeChecklist, saveShootingPlanVersion, type ChecklistItem, type ShootingPlanVersion } from "@starward/domain/shooting";
import { colors, minimumTouchTarget, radii, spacing, type as typeToken } from "@starward/ui-system/tokens";
import { createShootingClient, type ShootingPreview } from "../../data/shooting-client";
import { loadLocalChecklist, loadLocalShootingVersions, saveLocalChecklist, saveLocalShootingVersion } from "../../data/shooting-storage";
import { useShellStore } from "../../state/shell-store";

type ViewKey = "mobile" | "camera" | "preset" | "checklist" | "version" | "ai";
const palette = colors.night; const client = createShootingClient();
const actions = [{ key: "mobile", id: "shooting-create-mobile-plan", label: "手机方案" }, { key: "camera", id: "shooting-create-camera-plan", label: "相机方案" }, { key: "preset", id: "shooting-apply-preset", label: "预设" }, { key: "checklist", id: "shooting-save-checklist", label: "清单" }, { key: "version", id: "shooting-save-version", label: "保存版本" }, { key: "ai", id: "shooting-open-ai-explanation", label: "为什么" }] as const;
function Evidence({ testID, title, body, meta }: { testID: string; title: string; body: string; meta?: string }) { return <View testID={testID} style={styles.evidence}><Text style={styles.evidenceTitle}>{title}</Text><Text style={styles.evidenceBody}>{body}</Text>{meta ? <Text style={styles.evidenceMeta}>{meta}</Text> : null}</View>; }
function State({ title, body, retry }: { title: string; body: string; retry?: () => void }) { return <View style={styles.panel}><Text style={styles.evidenceTitle}>{title}</Text><Text style={styles.evidenceBody}>{body}</Text>{retry ? <Pressable onPress={retry} style={styles.retry}><Text style={styles.retryText}>重试</Text></Pressable> : null}</View>; }

function PlanPanels({ data, active }: { data: ShootingPreview; active: ViewKey }) {
  const phone = data.phone, camera = data.camera;
  if (active === "mobile") return <View style={styles.panel}><Evidence testID="shooting-phone-model" title={phone.input.equipment.model} body="主摄 · 实际/等效焦段语义分开 · 三脚架" meta="仅输出设备输入声明支持的控制；能力仍需真机验证。" /><Evidence testID="shooting-mobile-settings" title={`曝光 ${phone.result.settings.shutterSeconds ?? "设备夜景模式"} 秒 · ISO ${phone.result.settings.iso ?? "由设备控制"}`} body={`白平衡 ${phone.result.settings.whiteBalanceK ?? "不可控"} · ${phone.result.settings.focus ?? "设备自动"} · 堆栈 ${phone.result.settings.stackingFrames} 帧`} meta={`${phone.result.ruleVersion} · 条件 ${phone.result.provenance.conditionsCapturedAt}`} /><Evidence testID="shooting-mobile-risk" title="先试拍并放大检查" body={[...phone.result.risks, ...phone.result.alternatives].join("；")} meta={`可信度 ${Math.round(phone.result.confidence * 100)}% · 缺失 ${phone.result.missingConditions.join("、") || "无"}`} /></View>;
  if (active === "camera") return <View style={styles.panel}><Evidence testID="shooting-camera-settings" title={`f/${camera.result.settings.aperture} · ${camera.result.settings.shutterSeconds} 秒 · ISO ${camera.result.settings.iso}`} body={`${camera.result.settings.focus} · 间隔 ${camera.result.settings.intervalSeconds} 秒 · 堆栈 ${camera.result.settings.stackingFrames} 张 · 长曝降噪 ${camera.result.settings.longExposureNoiseReduction ? "开" : "关"}`} meta={`${camera.result.ruleVersion} · 条件批次可追溯`} /><Evidence testID="shooting-lens-field" title={`${camera.result.settings.focalLengthMm} mm · 横向银河构图`} body={String(camera.result.settings.composition)} meta="实际焦段和传感器尺寸共同参与拖线限制。" /><Evidence testID="shooting-risk-note" title="拖线风险 · 必须先试拍" body={`${camera.result.risks.join("；")}；替代：${camera.result.alternatives.join("；")}`} /></View>;
  if (active === "preset") return <View style={styles.panel}><Evidence testID="shooting-preset-source" title="空间站轨迹 · V3 预设" body="当前缺少已验证的过境轨迹与设备曝光规则" meta="依赖新鲜 OMM、目标角速度和摄影专家验证。" /><Evidence testID="shooting-preset-assumptions" title="适用条件尚不完整" body="不会生成无依据完整参数；保留地点、时间、设备和基础构图输入。" /><Evidence testID="shooting-preset-adjustment" title="进入自定义" body="改选已有确定性规则，或补齐目标运动与器材参数。" /></View>;
  if (active === "ai") return <View style={styles.panel}><Evidence testID="shooting-rule-result" title={`规则结果 · ISO ${camera.result.settings.iso} / ${camera.result.settings.shutterSeconds} 秒 / f${camera.result.settings.aperture}`} body={camera.result.risks.join("；")} meta={camera.result.ruleVersion} /><Evidence testID="shooting-ai-explanation" title="规则解释可用" body="AI 服务未启用；当前解释直接来自版本化规则、器材输入和已展示条件。" meta="精确位置、路线、身份、媒体与 EXIF 不发送。" /><Evidence testID="shooting-ai-boundary" title="不会编造或覆盖规则参数" body="未来 AI 只能解释取舍；失败、超时或撤回同意不改变确定性结果。" /></View>;
  return null;
}

function ChecklistPanel({ items, revision, onSave }: { items: ChecklistItem[]; revision: number; onSave: (items: ChecklistItem[]) => void }) { const done = items.filter((item) => item.done).length; return <View style={styles.panel}><Evidence testID="shooting-checklist-items" title={`清单 ${done}/${items.length}`} body={items.map((item) => `${item.done ? "✓" : "○"} ${item.label}`).join(" · ")} meta="出发前与现场基础项均可恢复。" /><Pressable onPress={() => onSave(items.map((item, index) => index === done ? { ...item, done: true } : item))}><Evidence testID="shooting-checklist-offline" title={`离线可用 · 本地 revision ${revision}`} body="点击勾选即先写本机；后续同步必须携带 revision 与幂等键。" /></Pressable><Evidence testID="shooting-checklist-progress" title="关键礼仪保留" body="关闭自动闪光，避免白光干扰；关键基础项不会被空模板删除。" /></View>; }

export function ShootingScreen() {
  const location = useShellStore((state) => state.location); const profiles = useShellStore((state) => state.profiles); const activeProfileId = useShellStore((state) => state.activeProfileId);
  const profile = profiles.find((item) => item.id === activeProfileId); const [active, setActive] = useState<ViewKey>("camera"); const [checklist, setChecklist] = useState<ChecklistItem[]>(() => mergeChecklist([], [])); const [checklistRevision, setChecklistRevision] = useState(1); const [saved, setSaved] = useState<ShootingPlanVersion[]>([]);
  const scheduledAt = useMemo(() => new Date(Date.now() + 6 * 60 * 60_000).toISOString(), []); const nightDate = scheduledAt.slice(0, 10); const focalLengthMm = profile?.lensFocalLengthsMm[0] ?? 24;
  const query = useQuery({ queryKey: ["shooting-preview", location.latitude, location.longitude, scheduledAt, focalLengthMm], queryFn: ({ signal }) => client.get({ latitude: location.latitude ?? 22.529, longitude: location.longitude ?? 113.9468, timezone: "Asia/Shanghai", nightDate, locationId: location.label || "manual-location", scheduledAt, focalLengthMm, acceptsStacking: true }, signal), retry: 1 });
  useEffect(() => { void Promise.all([loadLocalChecklist(), loadLocalShootingVersions()]).then(([local, versions]) => { if (local) { setChecklist(mergeChecklist(local.items, [])); setChecklistRevision(local.revision); } setSaved(versions); }); }, []);
  const persistChecklist = (items: ChecklistItem[]) => { const revision = checklistRevision + 1; setChecklist(items); setChecklistRevision(revision); void saveLocalChecklist(items, revision); };
  const persistVersion = () => { if (!query.data) return; const previous = saved.at(-1) ?? null; const next = saveShootingPlanVersion(previous, query.data.camera.input, { iso: query.data.camera.result.settings.iso }, new Date().toISOString()); void saveLocalShootingVersion(next).then(() => setSaved((all) => [...all, next])); setActive("version"); };
  return <SafeAreaView testID="screen-shooting-assistant" style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>摄影助手 · 银河</Text><Text style={styles.title}>确定性参数，现场可执行</Text><Text style={styles.subtitle}>{location.label} · {scheduledAt}。器材、目标运动与实时环境证据先计算；AI 只解释。</Text>
    {query.isLoading ? <State title="正在生成拍摄方案…" body="服务端正在读取天气、月光、目标高度与来源批次，再运行确定性规则。" /> : null}{query.isError ? <State title="拍摄条件暂不可用" body="不会以内置天气或曝光数字替代失败结果。" retry={() => void query.refetch()} /> : null}
    {query.data ? <View style={styles.summary}><Text style={styles.summaryTitle}>条件快照 · {query.data.state}</Text><Text style={styles.summaryBody}>光污染未知 · 月相 {query.data.conditions.moonIllumination === undefined ? "未知" : `${Math.round(query.data.conditions.moonIllumination * 100)}%`} · 云 {query.data.conditions.totalCloudPercent ?? "未知"}% · 风 {query.data.conditions.windMps ?? "未知"} m/s · 湿度 {query.data.conditions.humidityPercent ?? "未知"}% · 目标高度 {query.data.conditions.targetAltitudeDeg ?? "未知"}°</Text><Text style={styles.summaryMeta}>{query.data.conditions.boundary}</Text></View> : null}
    <View style={styles.actions}>{actions.map((action) => <Pressable key={action.key} testID={action.id} onPress={() => action.key === "version" ? persistVersion() : setActive(action.key)} style={[styles.action, active === action.key && styles.actionActive]}><Text style={styles.actionText}>{action.label}</Text></Pressable>)}</View>
    {query.data ? <PlanPanels data={query.data} active={active} /> : null}{active === "checklist" ? <ChecklistPanel items={checklist} revision={checklistRevision} onSave={persistChecklist} /> : null}{active === "version" && query.data ? <View style={styles.panel}><Evidence testID="shooting-plan-version" title={`拍摄方案版本 ${saved.at(-1)?.revision ?? 1}`} body={`规则 ${query.data.camera.result.ruleVersion} · 条件 ${query.data.conditions.capturedAt}`} meta="本地离线版本已保存；加入行程时引用明确 revision。" /><Evidence testID="shooting-change-summary" title="变化摘要" body="条件批次、器材输入、规则结果与用户 ISO 覆盖分别保存；重算不覆盖旧版本。" /><Evidence testID="shooting-restore-version" title={`可恢复历史 ${Math.max(0, saved.length - 1)} 个`} body="旧输入、条件快照、规则结果和用户覆盖保持不可变。" /></View> : null}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:palette.canvas},content:{padding:spacing.x2,paddingBottom:48,gap:spacing.x2},eyebrow:{color:palette.primary,fontSize:typeToken.label,fontWeight:"700"},title:{color:palette.text,fontSize:typeToken.title,fontWeight:"700"},subtitle:{color:palette.textSecondary,lineHeight:23},summary:{padding:spacing.x2,borderRadius:radii.layer,backgroundColor:palette.surface},summaryTitle:{color:palette.text,fontWeight:"700"},summaryBody:{marginTop:6,color:palette.textSecondary,lineHeight:20},summaryMeta:{marginTop:6,color:palette.textSecondary,fontSize:typeToken.caption},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.x1},action:{minHeight:minimumTouchTarget,justifyContent:"center",paddingHorizontal:12,borderWidth:1,borderColor:palette.border,borderRadius:radii.pill,backgroundColor:palette.surface},actionActive:{borderColor:palette.primary},actionText:{color:palette.text,fontSize:typeToken.caption,fontWeight:"700"},panel:{gap:spacing.x1,padding:spacing.x2,borderWidth:1,borderColor:palette.border,borderRadius:radii.layer,backgroundColor:palette.surface},evidence:{minHeight:86,padding:12,borderRadius:radii.control,backgroundColor:palette.surfaceMuted},evidenceTitle:{color:palette.text,fontSize:typeToken.body,fontWeight:"700"},evidenceBody:{marginTop:5,color:palette.text,fontSize:typeToken.label,lineHeight:19},evidenceMeta:{marginTop:5,color:palette.textSecondary,fontSize:typeToken.caption,lineHeight:17},retry:{minHeight:minimumTouchTarget,marginTop:8,alignItems:"center",justifyContent:"center",backgroundColor:palette.primary,borderRadius:radii.control},retryText:{color:palette.onPrimary,fontWeight:"700"} });
