import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, minimumTouchTarget, radii, spacing, type as typeToken } from "@starward/ui-system/tokens";
import { applyItineraryPatch, mergeOfflinePatches, projectSharedItinerary, validateTimeline, type Itinerary } from "../../../../../packages/domain/src/itinerary/index";

type CaseKey = "create-generated-plan" | "overview-consistency" | "candidate-to-plan" | "route-tradeoff" | "refresh-version" | "secure-share-and-offline" | "collaboration-conflict" | "astronomy-timeline";
const palette = colors.planning;
const actions: Record<CaseKey, { id: string; label: string }> = {
  "create-generated-plan": { id: "plan-generate", label: "生成计划" }, "overview-consistency": { id: "plan-open-overview", label: "总览" },
  "candidate-to-plan": { id: "plan-add-candidate", label: "待规划" }, "route-tradeoff": { id: "plan-compare-routes", label: "路线" },
  "refresh-version": { id: "plan-refresh", label: "刷新" }, "secure-share-and-offline": { id: "plan-create-share", label: "分享/离线" },
  "collaboration-conflict": { id: "plan-resolve-conflict", label: "协作" }, "astronomy-timeline": { id: "plan-open-astronomy", label: "天文阶段" },
};
const basePlan: Itinerary = {
  id: "plan-fixture", title: "西涌银河观测夜", timezone: "Asia/Shanghai", revision: 7, sequence: 12, ownerId: "owner-1",
  stops: [{ id: "main", spotId: "西涌观测点", role: "primary", source: "user", coordinateVisibility: "public" }, { id: "backup", spotId: "大鹏备选点", role: "backup", source: "system", coordinateVisibility: "invite_only" }],
  stages: [{ id: "departure", kind: "departure", startsAt: "2026-08-12T11:40:00Z", endsAt: "2026-08-12T12:40:00Z" }, { id: "scouting", kind: "scouting", startsAt: "2026-08-12T12:50:00Z", endsAt: "2026-08-12T13:30:00Z", stopId: "main" }, { id: "blue", kind: "blue-hour", startsAt: "2026-08-12T13:30:00Z", endsAt: "2026-08-12T14:00:00Z", stopId: "main" }, { id: "moonless", kind: "moonless", startsAt: "2026-08-12T16:20:00Z", endsAt: "2026-08-12T16:35:00Z", stopId: "main" }, { id: "milky-way", kind: "target-window", startsAt: "2026-08-12T16:35:00Z", endsAt: "2026-08-12T18:20:00Z", stopId: "main" }, { id: "return", kind: "return", startsAt: "2026-08-12T18:30:00Z", endsAt: "2026-08-12T19:35:00Z" }],
  routeSnapshot: { id: "route-7", generatedAt: "2026-08-12T10:00:00Z", driveMinutes: 58, walkMinutes: 18 }, weatherSnapshot: { id: "weather-7", generatedAt: "2026-08-12T10:05:00Z" }, operationLog: [],
};

function Evidence({ testID, title, body, meta }: { testID: string; title: string; body: string; meta?: string }) { return <View testID={testID} style={styles.evidence}><Text style={styles.evidenceTitle}>{title}</Text><Text style={styles.evidenceBody}>{body}</Text>{meta ? <Text style={styles.evidenceMeta}>{meta}</Text> : null}</View>; }
const panel = (...children: React.ReactNode[]) => <View style={styles.panel}>{children}</View>;

function CasePanel({ kind }: { kind: CaseKey }) {
  if (kind === "create-generated-plan") return panel(<Evidence key="a" testID="plan-observation-window" title="观测窗口 00:35–02:20" body="出发 19:40 · 到达 20:38 · 勘察/蓝调 · 无月窗口 · 银河最佳 · 返回 03:35" meta="Asia/Shanghai；草案 revision 7，尚未确认出发" />, <Evidence key="b" testID="plan-main-spot" title="主地点：西涌 · 备选：大鹏" body="地点、路线、天气与天文均携带独立快照版本" />, <Evidence key="c" testID="plan-safety-checklist" title="安全清单 6 项待确认" body="开放状态、返程、电量、同伴、天气复核、最后一公里" />);
  if (kind === "overview-consistency") return panel(<Evidence key="a" testID="plan-overview-map" title="路线地图" body={`驾车 ${basePlan.routeSnapshot.driveMinutes} 分钟 · 徒步 ${basePlan.routeSnapshot.walkMinutes} 分钟 · 主备 2 地点`} meta={`路线 ${basePlan.routeSnapshot.id} · ${basePlan.routeSnapshot.generatedAt}`} />, <Evidence key="b" testID="plan-overview-timeline" title="真实观星阶段" body="出发 → 勘察 → 蓝调 → 无月 → 银河窗口 → 返回" />, <Evidence key="c" testID="plan-overview-version" title="地图与时间线共享版本 7" body="天气 weather-7；未重算项会标 stale，不混入新条件" />);
  if (kind === "candidate-to-plan") { const result = applyItineraryPatch(basePlan, { idempotencyKey: "candidate-op", actorId: "owner-1", role: "owner", baseRevision: 7, patch: { stops: [...basePlan.stops, { id: "candidate-1", spotId: "盐田候选", role: "backup", source: "friend", coordinateVisibility: "members" }] }, at: "2026-08-12T10:20:00Z" }); return panel(<Evidence key="a" testID="plan-candidate-source" title="候选来自好友" body="来源、加入者、推荐原因和坐标权限保留" />, <Evidence key="b" testID="plan-candidate-role" title="设为备选地点" body="不会静默替换当前主地点" />, <Evidence key="c" testID="plan-candidate-result" title={result.status === "applied" ? "已加入正式 Stop · 版本 8" : "写入失败，候选仍保留"} body="编号、路线和时间需要重算；幂等操作 candidate-op" />); }
  if (kind === "route-tradeoff") return panel(<Evidence key="a" testID="route-distance-tradeoff" title="最快：42 km / 58 分钟" body="徒步 18 分钟 · 预计 20:38 到达" />, <Evidence key="b" testID="route-risk-tradeoff" title="山路风险较高" body="安全路线多 11 km；设施路线可能错过窗口，不用单一‘最佳’遮盖取舍" />, <Evidence key="c" testID="route-arrival-tradeoff" title="安全路线晚到 18 分钟" body="仍可赶上 00:35 银河窗口；选择后生成新 revision" />);
  if (kind === "refresh-version") return panel(<Evidence key="a" testID="plan-change-preview" title="变化预览：低云上升、路线未变" body="用户手调顺序保留；接受/拒绝前不改原 revision" />, <Evidence key="b" testID="plan-saved-version" title="保存为版本 8" body="版本 7、操作日志和恢复点仍可查" />, <Evidence key="c" testID="plan-refresh-result" title="刷新结果可恢复" body="天气、路线与天文快照分别标识新旧状态" />);
  if (kind === "secure-share-and-offline") { const share = projectSharedItinerary(basePlan, "anonymous"); return panel(<Evidence key="a" testID="plan-share-scope" title="公开摘要 · 受限坐标已隐藏" body={share.stops.map((item) => `${item.role}:${item.spotId}`).join(" · ")} meta="邀请撤回或过期后服务端重新投影" />, <Evidence key="b" testID="plan-share-expiry" title="分享链接 24 小时到期" body="APP 深链/复制入口可用；Web 分享页不替代 React Native 专业能力" />, <Evidence key="c" testID="plan-offline-availability" title="观测包待下载 · revision 7" body="自有授权包可含精确主备、路线、天气、天文和工具；下载前复核版本" />); }
  if (kind === "collaboration-conflict") { const merged = mergeOfflinePatches(basePlan, { id: "left", actorId: "小林", baseRevision: 7, sequence: 13, at: "01:00", patch: { title: "A", stages: basePlan.stages } }, { id: "right", actorId: "阿辰", baseRevision: 7, sequence: 14, at: "01:01", patch: { title: "B", stops: basePlan.stops } }); return panel(<Evidence key="a" testID="plan-conflict-original" title="原版本 7 · 小林修改出发时间" body="本地 Patch 保留，断线游标可补齐" />, <Evidence key="b" testID="plan-conflict-incoming" title="来版 8 · 阿辰修改同一字段" body={`非冲突字段已增量合并；冲突字段 ${merged.conflicts.map((item) => item.field).join("、")}`} />, <Evidence key="c" testID="plan-conflict-resolution" title="需要解决冲突 · 保留双方版本" body="owner 逐字段选择；viewer 不可写，editor 不可改角色或暴露受限坐标" />); }
  const timeline = validateTimeline(basePlan.stages); return panel(<Evidence key="a" testID="plan-twilight-event" title="天文昏影结束 21:18" body="勘察和蓝调按当地观星夜组织，不使用 DAY 1 旅游模板" />, <Evidence key="b" testID="plan-moon-event" title="月落 00:20" body="跨午夜仍属于同一观星夜" />, <Evidence key="c" testID="plan-target-event" title="目标银河核心 00:35–02:20" body={timeline.valid ? "时间线无重叠；返程 02:30" : `冲突：${timeline.conflicts.join("、")}`} />);
}

export function ItineraryScreen({ fixture }: { fixture?: string }) {
  const fixtureCase = fixture?.split(":")[1] as CaseKey | undefined; const [active, setActive] = useState<CaseKey | null>(null); const cases = useMemo(() => Object.keys(actions) as CaseKey[], []);
  return <SafeAreaView testID="screen-itinerary-and-collaboration" style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>行程 · revision 7</Text><Text style={styles.title}>{basePlan.title}</Text><Text style={styles.subtitle}>单夜计划使用真实天文阶段。地图、时间线、主备、路线、分享和协作均绑定同一可恢复版本。</Text><View style={styles.actions}>{cases.map((key) => <Pressable key={key} testID={actions[key].id} accessibilityRole="button" onPress={() => setActive(key)} style={({ pressed }) => [styles.action, fixtureCase === key && styles.actionRecommended, pressed && styles.pressed]}><Text style={styles.actionText}>{actions[key].label}</Text></Pressable>)}</View>{active ? <CasePanel kind={active} /> : <View style={styles.empty}><Text style={styles.emptyTitle}>选择总览、阶段、候选或版本操作</Text><Text style={styles.emptyBody}>未保存、更高远端 revision、风险与过期快照会常驻显示。</Text></View>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.canvas }, content: { padding: spacing.x2, paddingBottom: 48, gap: spacing.x2 }, eyebrow: { color: palette.primaryActive, fontSize: typeToken.label, fontWeight: "700" }, title: { color: palette.text, fontSize: typeToken.title, fontWeight: "700" }, subtitle: { color: palette.textSecondary, fontSize: typeToken.body, lineHeight: 23 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x1 }, action: { minHeight: minimumTouchTarget, justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: palette.border, borderRadius: radii.pill, backgroundColor: palette.surface }, actionRecommended: { borderColor: palette.primaryActive }, actionText: { color: palette.text, fontSize: typeToken.label, fontWeight: "700" }, panel: { gap: spacing.x1, padding: spacing.x2, borderWidth: 1, borderColor: palette.border, borderRadius: radii.layer, backgroundColor: palette.surface }, evidence: { minHeight: 86, padding: 12, borderRadius: radii.control, backgroundColor: palette.surfaceMuted }, evidenceTitle: { color: palette.text, fontSize: typeToken.body, fontWeight: "700" }, evidenceBody: { marginTop: 5, color: palette.text, fontSize: typeToken.label, lineHeight: 19 }, evidenceMeta: { marginTop: 5, color: palette.textSecondary, fontSize: typeToken.caption, lineHeight: 17 }, empty: { minHeight: 160, justifyContent: "center", padding: spacing.x2, borderWidth: 1, borderColor: palette.border, borderRadius: radii.layer, backgroundColor: palette.surface }, emptyTitle: { color: palette.text, fontSize: typeToken.section, fontWeight: "700" }, emptyBody: { marginTop: spacing.x1, color: palette.textSecondary }, pressed: { opacity: 0.7 } });
