import { describe, expect, it } from "vitest";
import { applyItineraryPatch, mergeOfflinePatches, projectSharedItinerary, validateTimeline, type Itinerary } from "./index";
const plan: Itinerary = { id: "p1", title: "银河夜", timezone: "Asia/Shanghai", revision: 7, sequence: 12, ownerId: "u1", stops: [{ id: "s1", spotId: "public-spot", role: "primary", source: "user", coordinateVisibility: "public" }, { id: "s2", spotId: "secret-spot", role: "backup", source: "friend", coordinateVisibility: "invite_only" }], stages: [{ id: "depart", kind: "departure", startsAt: "2026-08-12T11:00:00Z", endsAt: "2026-08-12T12:00:00Z" }, { id: "observe", kind: "target-window", startsAt: "2026-08-12T16:20:00Z", endsAt: "2026-08-12T18:45:00Z", stopId: "s1" }], routeSnapshot: { id: "r1", generatedAt: "2026-08-12T10:00:00Z", driveMinutes: 58, walkMinutes: 18 }, weatherSnapshot: { id: "w1", generatedAt: "2026-08-12T10:00:00Z" }, operationLog: [] };
describe("itinerary version model", () => {
  it("rejects overlapping astronomy stages", () => { expect(validateTimeline([...plan.stages, { id: "bad", kind: "moonless", startsAt: "2026-08-12T17:00:00Z", endsAt: "2026-08-12T19:00:00Z" }]).valid).toBe(false); });
  it("applies idempotent optimistic patches", () => { const result = applyItineraryPatch(plan, { idempotencyKey: "op1", actorId: "u1", role: "owner", baseRevision: 7, patch: { title: "新标题" }, at: "2026-08-12T10:10:00Z" }); expect(result.status).toBe("applied"); if (result.status === "applied") expect(result.value).toMatchObject({ revision: 8, sequence: 13 }); });
  it("surfaces same-field offline conflicts while merging independent fields", () => { const result = mergeOfflinePatches(plan, { id: "a", actorId: "u1", baseRevision: 7, sequence: 13, at: "", patch: { title: "A", stops: plan.stops } }, { id: "b", actorId: "u2", baseRevision: 7, sequence: 14, at: "", patch: { title: "B", stages: plan.stages } }); expect(result.conflicts[0]).toMatchObject({ field: "title", originalActor: "u1", incomingActor: "u2" }); expect(result.mergedPatch).toHaveProperty("stops"); });
  it("redacts invite-only spots from anonymous shares", () => { const shared = projectSharedItinerary(plan, "anonymous"); expect(shared.stops[1]).toMatchObject({ spotId: "restricted:s2", preciseCoordinateIncluded: false }); expect(projectSharedItinerary(plan, "invitee").stops[1].spotId).toBe("secret-spot"); });
});
