import assert from 'node:assert/strict';
import test from 'node:test';
import {loadBsc5pStarCatalog} from '@starward/astronomy-core/bsc5p-catalog';
import {CelestialObjectSearchService} from './celestial-object-search.ts';
import {CelestialObjectInformationService} from './celestial-object-information.ts';
import {parseChineseIntroductionPublication,publishedStarIntroduction} from './celestial-object-introductions.ts';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const rows=[{hr:'7337',hd:'181454',hip:'95241',name:'天渊二（人马座β¹ A）',english:'Arkab Prior',terms:['β²','Q671833','Var_ID']},{hr:'7343',hd:'181623',hip:'95294',name:'天渊一（人马座β²）',english:'Arkab Posterior',terms:['F2/3V','Q671815','Var_ID']}];
test('verified Arkab named-star Chinese supply reaches exact existing identities in v2 and v3',()=>{const s=new CelestialObjectSearchService();for(const version of ['bsc5p-bright-stars.v2','bsc5p-bright-stars.v3']as const)for(const row of rows){for(const q of [row.name,row.hr==='7337'?'天淵二（人馬座β¹ A）':'天淵一（人馬座β²）']){const r=s.search(q,20,version);assert.equal(r.dataState,'FRESH');assert.deepEqual(r.data.results.map(r=>r.reference),['HR:'+row.hr]);}for(const q of ['HR'+row.hr,'HD'+row.hd,'HIP'+row.hip,row.english])assert(s.search(q,20,version).data.results.some(r=>r.reference==='HR:'+row.hr));}});
test('finite English translated and primary-component prose preserve measurements and visibly retain source limitations',()=>{const c=loadBsc5pStarCatalog('bsc5p-bright-stars.v3'),i=new CelestialObjectInformationService(),basic=new CelestialObjectInformationService(undefined,undefined,undefined,undefined,()=>null);for(const row of rows){const ref='HR:'+row.hr,star=c.rows.find(r=>r.hr===row.hr)!,r=i.get(ref,'zh-CN','bsc5p-bright-stars.v3'),old=basic.get(ref,'zh-CN','bsc5p-bright-stars.v3');assert.equal(r.data.contentState,'READY');assert.deepEqual(r.data.facts,old.data.facts);for(const alias of old.data.aliases)assert(r.data.aliases.includes(alias));for(const term of row.terms)assert(r.data.limitations.some(l=>l.includes(term)));const src=r.sources.find(s=>s.provider==='Wikipedia contributors')!;assert.equal(src.license,'CC-BY-SA-4.0');assert.equal(src.confidence,null);assert.equal(src.attribution?.url,src.sourceUrl);assert(src.attribution?.statements.some(s=>s.includes(src.licenseUrl!)));assert.equal(star.vMagCode,null);assert(r.data.limitations.some(l=>l.includes('测光')&&l.includes('Var_ID')));assert(!/白矮星|30弧秒|330光年|B1900/u.test(r.data.introduction!));assert.notEqual(r.data.contentRevision,old.data.contentRevision);}});
test('new rows reject incorrect or absent exact catalogue identifiers and do not reinterpret a shared Bayer designation as one system',()=>{const c=loadBsc5pStarCatalog('bsc5p-bright-stars.v3');for(const row of rows){const star=c.rows.find(r=>r.hr===row.hr)!;assert(publishedStarIntroduction(star));for(const change of [{hd:'12217'},{hip:null},{hip:'9599'}])assert.throws(()=>publishedStarIntroduction({...star,...change}),/identity_mismatch/);}const s=new CelestialObjectSearchService();assert.equal(s.search('天渊二',20,'bsc5p-bright-stars.v3').data.results[0].kind,'STAR');});
test('one unavailable Arkab prose row retains the other and original numericEnglish results then recovers',()=>{let failed=true;const publish:typeof publishedStarIntroduction=row=>{if(failed&&row.hr==='7337')throw Error('unavailable');return publishedStarIntroduction(row)},s=new CelestialObjectSearchService(undefined,undefined,publish),i=new CelestialObjectInformationService(undefined,undefined,undefined,undefined,publish);const partial=s.search('天渊二',20,'bsc5p-bright-stars.v3');assert.equal(partial.dataState,'PARTIAL');assert.deepEqual(partial.data.results,[]);for(const q of ['HR7337','Arkab Prior'])assert(s.search(q,20,'bsc5p-bright-stars.v3').data.results.some(r=>r.reference==='HR:7337'));assert.deepEqual(s.search(rows[1].name,20,'bsc5p-bright-stars.v3').data.results.map(r=>r.reference),['HR:7343']);const before=i.get('HR:7337','zh-CN','bsc5p-bright-stars.v3');assert.equal(before.dataState,'PARTIAL');assert.equal(before.data.contentState,'BASIC_ONLY');assert.equal(i.get('HR:7343','zh-CN','bsc5p-bright-stars.v3').data.contentState,'READY');failed=false;const after=s.search('天渊二',20,'bsc5p-bright-stars.v3');assert.equal(after.dataState,'FRESH');assert.deepEqual(after.data.results.map(r=>r.reference),['HR:7337']);assert.notEqual(after.etag,partial.etag);assert.deepEqual(i.get('HR:7337','zh-CN','bsc5p-bright-stars.v3').data.facts,before.data.facts);});

const edition=()=>JSON.parse(readFileSync(new URL('../assets/celestial-object-introductions.zh-cn.v25.json',import.meta.url),'utf8'));
const parse=(p:unknown)=>{const bytes=Buffer.from(JSON.stringify(p));return parseChineseIntroductionPublication(bytes,createHash('sha256').update(bytes).digest('hex'));};
test('English originals are admitted only by the explicit v25 translated fixed-source boundary',()=>{const p=edition(),r=p.rows.find((r:{reference:string})=>r.reference==='HR:7337');assert.equal(parse(p).size,114);assert.equal(r.sourceLanguage,'en');assert(r.source.attribution.statements.some((s:string)=>s.includes('翻译为简体中文')));for(const url of ['https://en.wikipedia.org/wiki/Beta1_Sagittarii','https://en.wikipedia.org/w/index.php?oldid=bad&title=Beta1_Sagittarii','https://en.wikipedia.org.evil.test/w/index.php?oldid=1374806485&title=Beta1_Sagittarii','https://user@en.wikipedia.org/w/index.php?oldid=1374806485&title=Beta1_Sagittarii','http://en.wikipedia.org/w/index.php?oldid=1374806485&title=Beta1_Sagittarii','https://en.wikipedia.org/w/index.php?oldid=1374806485','https://en.wikipedia.org/w/index.php?oldid=1374806485&oldid=1&title=Beta1_Sagittarii']){const q=structuredClone(p),row=q.rows.find((r:{reference:string})=>r.reference==='HR:7337');row.source.sourceUrl=url;row.source.attribution.url=url;assert.throws(()=>parse(q),/row_invalid/,url);}for(const version of Array.from({length:23},(_,i)=>'starward-celestial-introductions.zh-cn.v'+(i+2)))assert.throws(()=>parse({...p,version}),/row_invalid/);});
test('an English source cannot be silently presented as an untranslated Chinese original',()=>{const p=edition();assert.equal(parse(p).size,114);for(const mutation of ['missingLanguage','unsupportedLanguage','missingTranslationNotice','wrongAttribution','missingShareAlikeNotice']){const q=structuredClone(p),row=q.rows.find((r:{reference:string})=>r.reference==='HR:7337');if(mutation==='missingLanguage')delete row.sourceLanguage;if(mutation==='unsupportedLanguage')row.sourceLanguage='fr';if(mutation==='missingTranslationNotice')row.source.attribution.statements[0]='Wikipedia contributors';if(mutation==='wrongAttribution')row.source.attribution.url='https://en.wikipedia.org/wiki/Beta1_Sagittarii';if(mutation==='missingShareAlikeNotice')row.source.attribution.statements.pop();assert.throws(()=>parse(q),/row_invalid/,mutation);}});
