import { createHash } from "node:crypto";
import { buildLocationShare, planOfflineReplay, startSafetySession, switchOfflineBackup, validateObservationPack, type SafetySession } from "../../../../../packages/domain/src/offline/index";
export type FieldCommand = "verify-pack" | "toggle-red" | "switch-backup" | "start-session" | "share-location" | "save-report" | "enter-offline";
export class FieldService {
  private redMode=false; private activeSpot="西涌主点"; private rollbackSpot:string|null=null; private session:SafetySession|null=null; private share:ReturnType<typeof buildLocationShare>|null=null; private offline=false; private queueState="idle";
  constructor(private readonly now=()=>new Date().toISOString()){}
  get(){const now=this.now(); const raw=[{id:"manifest",kind:"manifest" as const,version:"plan-7",bytes:8192,required:true,licenseAllowsOffline:true},{id:"coordinates",kind:"coordinate" as const,version:"grant-7",bytes:2048,required:true,licenseAllowsOffline:true,coordinateGrant:"exact-device-encrypted" as const},{id:"route",kind:"route" as const,version:"route-18",bytes:2400000,required:true,licenseAllowsOffline:true},{id:"weather",kind:"weather" as const,version:"forecast-42",bytes:240000,required:true,licenseAllowsOffline:true,expiresAt:"2026-07-21T03:00:00+08:00"},{id:"astronomy",kind:"astronomy" as const,version:"astronomy-engine-2.1.19",bytes:128000,required:true,licenseAllowsOffline:true},{id:"shooting",kind:"shooting" as const,version:"rules-v1",bytes:48000,required:true,licenseAllowsOffline:true},{id:"checklist",kind:"checklist" as const,version:"rev-7",bytes:12000,required:true,licenseAllowsOffline:true},{id:"contact",kind:"contact" as const,version:"encrypted-1",bytes:1024,required:true,licenseAllowsOffline:true},{id:"map",kind:"map" as const,version:"licensed-region-7",bytes:32000000,required:true,licenseAllowsOffline:true}]; const components=raw.map(i=>({...i,sha256:createHash("sha256").update(`${i.id}:${i.version}`).digest("hex"),observedSha256:createHash("sha256").update(`${i.id}:${i.version}`).digest("hex")})); const pack=validateObservationPack({id:"field-plan-7",revision:7,components},{now,availableBytes:12*1024**3,globalUsedBytes:310*1024**2}); const saved=[{id:"report",idempotencyKey:"report-7-2331",revision:1,dependsOn:[],state:"queued" as const,createdAt:now},{id:"image-1",idempotencyKey:"image-1-7",revision:1,dependsOn:["report"],state:"queued" as const,createdAt:now},{id:"image-2",idempotencyKey:"image-2-7",revision:1,dependsOn:["report"],state:"queued" as const,createdAt:now},{id:"checklist",idempotencyKey:"checklist-7",revision:7,dependsOn:[],state:"conflict" as const,createdAt:now}]; const replay=planOfflineReplay(saved,new Set()); return {schemaVersion:"starward-field-v1",generatedAt:now,redMode:this.redMode,activeSpot:this.activeSpot,rollbackSpot:this.rollbackSpot,pack:{revision:7,totalBytes:pack.totalBytes,canActivate:pack.canActivate,reserveBytes:pack.reserveBytes,components:pack.componentResults},route:{parking:{bearingDeg:286,distanceM:1200,accuracyM:9,cachedAt:"2026-07-20T23:06:00+08:00"},walk:{distanceM:820,minutes:14,version:"route-18"},backup:{name:"东涌备选",window:"00:55–02:10",routeVersion:"route-12"}},session:this.session,share:this.share,queue:{state:this.queueState,ordered:replay.ordered,conflicts:replay.conflicts,draftsRetained:true},offline:{active:this.offline,cachedAt:"2026-07-20T23:06:00+08:00",tools:["地图","停车","天空方向","拍摄","清单","实况","备选"],networkOnly:["实时天气","活动预警","实时路况","外部送达回执"]},boundaries:["系统 UI 与外部地图不保证红光","安全会话不是救援服务","离线天气/路况可能过期"]};}
  command(c:FieldCommand){if(c==="toggle-red")this.redMode=!this.redMode;if(c==="switch-backup"){const x=switchOfflineBackup(this.activeSpot,"东涌备选");this.activeSpot=x.current;this.rollbackSpot=x.rollback;}if(c==="start-session")this.session=startSafetySession({now:this.now(),plannedEndAt:new Date(Date.parse(this.now())+3.5*3600_000).toISOString(),requestedHours:4,backgroundPermission:true});if(c==="share-location")this.share=buildLocationShare({latitude:22.529,longitude:113.9468,accuracyM:9,capturedAt:this.now(),access:"invite_only",recipient:"系统分享面板：家人",expiresAt:new Date(Date.parse(this.now())+4*3600_000).toISOString()});if(c==="save-report")this.queueState="replay-ready";if(c==="enter-offline")this.offline=true;return this.get();}
}
