import fs from 'node:fs';
const changed = new Map();
function read(p) { if (!changed.has(p)) changed.set(p, fs.readFileSync(p,'utf8').replaceAll('\r\n','\n')); return changed.get(p); }
function replace(p,a,b) { const s=read(p); if (!s.includes(a)) throw new Error(`Missing anchor ${p}: ${a.slice(0,90)}`); changed.set(p,s.replaceAll(a,b)); }
function append(p,s) { changed.set(p,read(p).trimEnd()+'\n\n'+s.trim()+'\n'); }
const pc='project_context/';
const map=pc+'areas/main/screen-contracts/wechat-miniapp/map-and-finder.md';
const sky=pc+'areas/main/screen-contracts/wechat-miniapp/spot-and-sky.md';
const shared=pc+'areas/main/screen-contracts/wechat-miniapp/shared-state-and-recovery.md';
const root=pc+'areas/main/screen-contracts/wechat-miniapp.md';
const surfaces=pc+'areas/main/product-surfaces/wechat-miniapp.md';
const controls=pc+'areas/main/screen-contracts/wechat-miniapp/surfaces-and-controls.md';
const arch=pc+'architecture/runtime-and-domain.md';
replace(pc+'global.md', 'Starward owns 《今晚去观星》, a mobile-first stargazing trip decision product. Help users decide whether to go tonight, where and when to go, how to arrive, and how to observe safely. Conclusions lead to an executable plan and then supporting evidence; uncertain or unavailable data must remain explicit.', 'Starward owns 《今晚去观星》. The native App leads from a trip conclusion to an executable plan and supporting evidence. The independent Mini Program helps users choose places, arrange travel and observe through trustworthy place, weather, astronomy, arrival and safety facts; users decide whether to go. It does not present a combined departure recommendation. Both products keep uncertainty and restrictions explicit.');
replace(pc+'global.md','External-service budget is CNY 200/month;','External-service budgets are scoped by product: native App CNY 200/month; Mini Program CNY 350/calendar month excluding application/database IaaS;');
const profile=pc+'product-profile.md';
for (const [a,b] of [
 ['- Help a user move from','- For the native App, help a user move from'],
 ['- Users need a decision and next action before professional data, so the experience uses three layers: conclusion, executable plan, then evidence.','- Native App uses conclusion, executable plan, then evidence. Mini Program uses objective place/arrival/safety and selected-time astronomy/weather facts plus user-owned plans; it removes combined recommendation presentation and recommendation filters while retaining safety restrictions.'],
 ['- Primary users are people deciding on a same-night','- Native App primary users are people deciding on a same-night'],
 ['- Core flow: tonight conclusion','- Native App core flow: tonight conclusion'],
 ['- Durable acceptance signals are a clear first-screen recommendation','- Native App durable acceptance signals are a clear first-screen recommendation'],
 ['- External-service ceiling: CNY 200 per month / CNY 2,400 per year.','- External-service ceiling: native App CNY 200/month; independent Mini Program CNY 350/calendar month excluding application/database IaaS. The Mini Program ceiling supersedes its former 200/300 wording, is not additive, and does not promise complete provider coverage or availability.'],
 ['- The first layer answers whether to go and when;','- In the native App, the first layer answers whether to go and when;'],
 ['with a CNY 200/month external-service ceiling and qualifying free sources preferred.','with the product-scoped external-service ceilings above and qualifying free sources preferred.']
]) replace(profile,a,b);
replace(profile,'## Current Release Profile','Mini Program acceptance asks whether users can find the relevant trustworthy facts and arrange an executable, revisitable plan. Its discovery filters do not include 今晚推荐 or 最佳窗口时长. Formal restrictions and action checks remain even when combined recommendations are not displayed.\n\n## Current Release Profile');
replace(pc+'areas/main.md','- Tonight home answers','- Native App Tonight home answers');
replace(pc+'areas/main.md','- Principles: conclusion first, action continuity, professional evidence on demand, honest uncertainty, stable layout, and outdoor accessibility.','- Principles: native App conclusion first; Mini Program facts supporting user judgment. Both preserve action continuity, evidence on demand, honest uncertainty, stable layout and outdoor accessibility.');
replace(pc+'areas/main.md','## Core Data / API / State','The independent Mini Program follows Map/My and the current Mini Program Screen Contract: objective facts, private contribution states and user-authored plans. The native App Tonight, alternate-place and system-preparation responsibilities above do not create Mini Program routes, recommendation filters or fixed checklists.\n\n## Core Data / API / State');
replace(pc+'areas/main.md','- Motion is restrained and supports reduced motion; flashing, ambient particles, broad glow, and large glass surfaces are forbidden.','- Motion is restrained and supports reduced motion. Apply DESIGN.md per-product and adopted-scope material rules, including the Mini Program My plan card; a native App material restriction does not invalidate that scoped adoption.');
const surfroot=pc+'areas/main/product-surface-contract.md';
replace(surfroot,'- The CNY 200/month ceiling and paid-default-zero policy','- The native App CNY 200/month ceiling and paid-default-zero policy');
replace(surfroot,'CNY 300/month excluding application/database IaaS','CNY 350/calendar month excluding application/database IaaS');
replace(surfroot,'That budget does not authorize purchase','This 2026-09-09 owner decision replaces earlier Mini Program 200/300 ceilings; budgets are not added together. It is a spending limit for the current personal non-commercial trial, not proof of capability, reachability or sufficient quota. That budget does not authorize purchase');
replace(surfroot,'- Main mobile surfaces show decision, next action, and decision-relevant uncertainty.','- Native App main surfaces show decision, next action, and decision-relevant uncertainty. Mini Program surfaces show relevant objective facts, user plans and explicit uncertainty rather than a combined departure conclusion.');
replace(pc+'architecture.md','a CNY 200/month ceiling','the product-scoped ceilings in product-profile.md (native App CNY 200/month; Mini Program CNY 350/calendar month excluding application/database IaaS)');
for (const p of [root,map,shared,surfaces,controls]) replace(p,'none | spot-panel | layer-sheet','none | spot-panel | layer-sheet | spot-editor');
replace(root,'Map Search and the information panel receive only formal spots.','Public Map Search receives only formal spots. The same Map information component also renders authorized private drafts and submitted pending proposals under the identity/capability rules in Map and Search; private records never enter public spot queries.');
replace(root,'`sky/detail` is reachable only from `云观星` in a visible formal spot information panel carrying valid `spot_id` and Observation Context; ordinary POIs or current location cannot synthesize it.','`sky/detail` is reachable from `云观星` in a visible formal-spot or current-account pending-proposal information panel, carrying a server-validated typed identity and Observation Context. Private drafts, ordinary POIs and current location do not synthesize this entry.');
replace(root,'owns the one physical map, selected formal spot,','owns the one physical map, one selected typed location (formal spot or authorized private draft/pending proposal),');
replace(root,'It inherits the formal `spot_id`, selected date/time, timezone and data/algorithm revision;','It inherits the formal `spot_id` or authorized pending `proposal_id`, selected date/time, timezone and data/algorithm revision;');
replace(map,'all 18 existing terminal filters','the 16 current terminal filters');
replace(map,'A strip `spot-search-filter-choice` commits immediately.','A parameter-free strip `spot-search-filter-choice` commits immediately. The driving-duration item opens the existing filter sheet at 到达方式 for its enabled state and minutes input; it does not silently apply an unseen value.');
replace(map,'the current 18 values and their grouping are defined in the adopted Search resource, without inventing new filter semantics.','the 16 current values and their meaning are owned by the Filter semantics section below; the adopted Search visual structure supplies grouping/layout, not business predicates. The two retired recommendation values must be removed during migration.');
replace(map,'My shows eligible plans with now <= selectedAt <= now + 24 hours, ordered by absolute selectedAt then stable planId, at most three. Refresh on foreground and as time passes so past plans expire.','My shows ongoing plans (start <= now < end) and plans starting within now <= start <= now + 24 hours, ordered ongoing first, then absolute start and stable planId, at most three. Refresh on foreground and as time passes; an ongoing plan remains across midnight until its end. Display ongoing state and its local ending time without enlarging the card into a separate timeline.');
replace(map,'- 新增、正式点信息、图层呈现互斥。点击正式点时关闭新增弹层、移动同一个地图并打开该点 medium 信息组件；有未保存修改时先确认放弃，取消则保留表单。','- 新增/编辑表单、点信息、图层由同一个 bottomPresentation 协调器互斥，spot-editor 内区分新建与编辑，不新增旁路可见布尔。点击其他点、关闭或返回时，有未保存修改先确认放弃；确认前不提交选点、相机移动、Observation Context 或依赖请求切换。取消保留表单、媒体、候选位置和原呈现；确认后才关闭编辑并切到目标点的 medium 信息组件。');
replace(map,'草稿不开放想去/分享，不伪造正式点身份。','草稿不开放想去/分享/计划/云观星，不伪造正式点身份。');
replace(map,'Unknown route duration is unavailable, not zero.','Unknown or stale route duration is unavailable, not zero. With a current, attributable estimate matching the chosen origin/destination/travel mode and departure assumptions, compare departure plus travel duration with observing start; if late, show estimated arrival and the delay. The user may still save; neither an estimate nor its failure rewrites the chosen times.');
replace(map,'Store reminder intent separately from platform subscription authorization and actual send/delivery state.','Store each reminder group’s intent separately from its own platform authorization/send eligibility and actual send/delivery state; a global enabled switch cannot promise all groups will arrive.');
replace(map,'Changing departure, deleting a reminder or deleting a plan must reschedule/cancel pending jobs with server idempotency.','Changing departure, deleting a reminder or deleting a plan must reschedule/cancel pending jobs with server idempotency. Dispatch must recheck plan/reminder versions and authorization; expired/superseded jobs do not send. Missed triggers after recovery are skipped and recorded; confirmed failures may retry within bounded policy before departure, while unknown send outcomes require receipt reconciliation rather than blind resend. Checklist access remains available regardless of notification state.');
append(map,`## Location identity and capability lifecycle

| Input | Identity and authoritative facts | Current account actions |
| --- | --- | --- |
| Formal spot | Published canonical spot_id and current restrictions | Existing browse/favorite/share/plan/navigation/sky actions, each subject to its existing safety and authorization checks |
| Private draft | Account-owned remote working copy and revision | View/edit/explicit save; no favorite/share/plan/sky; no implied formal navigation permission |
| Pending creation | Account-owned frozen submission, proposal_id and current attempt | View and cloud stargazing with authorized submitted coordinates; no favorite/share/plan; no inherited formal publication or action clearance |
| Formal spot with own pending feedback | Formal facts plus separately loaded own frozen feedback | Formal actions remain governed by the formal spot; feedback is not a pending new location |

Publication/merge returns a durable mapping from stable proposal identity to canonical spot_id, including merge into an existing published point. Replace the private marker/selection with that formal identity atomically at the client’s committed transition, deduplicate by canonical ID, and refresh panel capabilities and fact sources. Contribution history retains the frozen attempt rather than relabelling it as a mutable formal record. If currently in sky, the next authoritative refresh resolves the same mapping and updates the typed context and return target; Back must not recreate the retired pending marker. Review acceptance without publication remains pending-publication. Rejection or loss of access removes pending-sky permission and offers a truthful return path; stale requests cannot restore it. Account changes remove private selection/cache/read models before another account is shown.

## Filter semantics and coverage

Confirmed 2026-09-09: exactly 16 terminal conditions in the existing five presentation categories. 今晚推荐 and 最佳窗口时长 are retired from Mini Program discovery; this does not delete algorithms serving other accepted consumers. The existing Search resource’s old 18 labels await visual revision and do not override this rule.

| Condition | Matching evidence / parameter |
| --- | --- |
| 驾车时长 | Current route from the explicit valid origin to this point, within the chosen integer minutes; default 180, allowed 30–360; straight-line distance is never a substitute |
| 光害 | Published attributable LOW or VERY_LOW annual nightlight product band; no Bortle/SQM inference |
| 少云 | Total cloud <=45% at selectedAt |
| 停车 | Published parking availability is AVAILABLE |
| 厕所 | Published toilet availability is AVAILABLE |
| 可驾车直达 | Explicit DRIVE_TO access evidence; material restrictions still govern actions |
| 有实拍照片 | At least one valid, authorized, displayable site-specific photo belonging to this spot; not a photography-quality judgment |
| 可露营/驻车 | Explicit permission/evidence for camping or overnight vehicle stay; ordinary parking availability does not imply overnight permission |
| 特定天象 | An attributable published occurrence applicable to the selected observing night and spot visibility; directory/time coverage is evaluated separately from whether any occurrence matches |
| 低云阈值 | Low-layer cloud <=30% at selectedAt; total cloud does not establish this field |
| 月亮影响 | LOW under the existing selected-time rule: moon below/on horizon or illumination <25%, with adequate inputs; this is not a whole-trip recommendation |
| 徒步难度 | Explicit NO_HIKE access evidence; it does not promise accessibility or a particular difficulty grade |
| 信号 | Explicit published AVAILABLE signal evidence |
| 充电 | Explicit published AVAILABLE charging evidence |
| 天空开阔方向 | At least one attributable recorded open direction; show its actual direction, never imply the user’s target direction is clear |
| 最近核验时间 | Attributable verification timestamp within the preceding 180 days as of evaluation time; future timestamps do not qualify |

Each condition evaluates MATCH / NO_MATCH / UNKNOWN for each candidate. Static missing evidence and absent permission are not affirmative facts. A known logical alternative can establish a match without inventing its missing counterpart; otherwise required missing inputs mean UNKNOWN. Explicit negative evidence is NO_MATCH. Dynamic evidence binds selectedAt and its real sample/freshness, never an adjacent frame or nightly average. No valid origin means driving UNKNOWN without automatic location collection.

Compute each condition’s AVAILABLE / PARTIAL / UNAVAILABLE coverage over the geographic/query candidate set before applying any business filters. All known results means AVAILABLE even if none match; some known means PARTIAL; none means UNAVAILABLE. An empty candidate population is an empty search scope, not evidence of provider coverage. Keep zero matches, unavailable coverage and partial results distinct; explain the affected condition and offer edit/remove/retry, not a generic successful empty list. Multiple conditions combine with AND: any definite NO_MATCH excludes the point; all MATCH includes it; the remainder are unknown, not silently proven unsuitable. These are future BFF/contracts obligations, not a new client evaluation engine.

The driving parameter is part of the one committed filter state and its sheet-local copy. Editing enabled state/minutes and 清空 changes only that copy; 确定 validates and commits it, while Close/Back/backdrop cancels both. Display the committed limit in the strip when active. Clearing resets disabled/default-180 in the draft. Hidden legacy ranking preferences do not control this parameter; reopening retains the last committed value. Retired recommendation selections are discarded during later migration, preserving query/time and the remaining valid conditions.

## Plan editing, dates and resource revision

The plan’s draft owns its explicit destination, observing start/end, departure arrangement, event links and checklist changes. Browser Observation Context can initialize a new plan but is not the save authority; keep the existing server re-resolution from submitted plan location/time and versioned snapshot, including recoverable origin. Returning from an event or another place must not overwrite the draft. Saving a valid plan does not require weather success; valid plan dates are independent from the -7/+15 weather/sky browsing target and from published event coverage. Date input validity and end-after-start/departure-before-start still apply. Lack of event/weather coverage is unavailable evidence, not a reason to delete or retime a saved plan.

The 2026-09-09 rules for Search, My ongoing plans, arrival/reminder states, sky context and contribution transitions are confirmed product requirements. Their affected design regions need scoped revisions for owner review; current adopted resources retain unchanged composition/material/interaction authority and are not silently replaced by new candidates. Production implementation and WEAPP validation remain outstanding.
`);
replace(surfaces,'entered only through `云观星` in a valid formal spot information panel.','entered through `云观星` in a valid formal spot or current-account pending-proposal information panel, under the Map identity contract.');
replace(surfaces,'explicit observed time and affected fact topics; concise evidence narrative;','the complete editable site fields, a formal baseline/version for feedback and frozen field/media differences;');
replace(surfaces,'At 200% text the hierarchy must reflow and remain operable rather than preserve compact geometry by clipping or horizontal page scroll.','Current scope is standard text at 320/375/390/430 logical pixels with safe areas and 44px hit targets; 200%/large-font work remains paused by the owner.');
replace(surfaces,'One owner exposes at most one full notification at a time, deduplicates repeated events, preserves concurrent material states through deterministic severity order and an accessible residual count/queue, and never replaces the sole recovery path with an auto-dismissing toast or a stack of full-height cards.','One shared owner exposes at most three compact floating notices, deduplicates each transaction and preserves deterministic ordering. Critical failures retain inline recovery; draft save status stays beside the form title. Floating expiry cannot erase the sole recovery path.');
replace(controls,'Strip choices commit immediately;','Parameter-free strip choices commit immediately; the driving-duration parameter opens the same sheet at 到达方式;');
replace(controls,'It inherits the valid formal spot and Observation Context from Map','It inherits the valid formal spot or authorized current-account pending proposal and Observation Context from Map');
replace(controls,'`spot-search-filter-choice`, `spot-search-result-list`','`spot-search-filter-choice`, `spot-search-drive-duration`, `spot-search-result-list`');
replace(controls,'`map-marker-panel-coordinator`.','`map-marker-panel-coordinator`, `map-spot-editor`.');
replace(sky,'- `map-spot-information-panel` is the sole current owner of formal spot basic information and astronomy information.','- `map-spot-information-panel` is the sole current owner of formal spot basic information and astronomy information; private draft/pending views reuse its document under the Map identity/capability contract.');
append(sky,`## Selected location and truthful sky coverage

Cloud stargazing displays the selected location’s name near the existing date/time region, with an accessible full location/timestamp and timezone. Keep the full-screen canvas, light labels and existing date control; do not restore a boxed/top title or new mode toggle. This context is always the selected place/time, not a claim to match the device’s current physical location. Showing it requires no new location request and must not depend on detecting remote viewing. Pending proposal identity remains visible as pending and follows Map publication/authorization transitions.

Production sky usability requires recognizable important bright-star coverage in the actual versioned catalog and BFF frames, not just checksum/count and synthetic astrometric fixtures. Sirius, Vega and Polaris are minimum named regression examples at appropriate location/time/visibility; they are not the complete promised star list. Distinguish bright-source omissions from capacity-limited fainter-star selection; G<=5.5 in a TOP-limited query is not completeness to that magnitude. Missing key bright references cannot be resolved by disclaimer alone. The architecture owner defines provenance/deduplication and unified-pack boundaries; exact acquisition/capacity implementation remains unimplemented by this Context revision. Weather, terrain obstruction and theoretical horizon visibility remain distinct.
`);
replace(shared,'视觉修改稿仍待用户确认，产品规则已按本次明确要求变更。','既有完整表单视觉采用见 Map/Feedback 资源入口；2026-09-09 身份转换的增补演示另待用户审查，产品规则不由候选采用状态决定。');
replace(arch,'before any suitability explanation.','before any suitability explanation for consumers that still expose those outputs. Mini Program discovery and its information panel do not display combined recommendations or the retired recommendation filters; underlying safety facts and navigation restrictions remain effective.');
replace(arch,'A server-owned, fail-closed publication policy evaluates the proposed final record—not only the requested status patch—and returns an attributable missing/invalid evidence list for identity, coordinate source, access/last road, parking, the eight facility states, openness/legal entry, night safety and hard blockers, horizon/open directions, site-media claim, source provenance, verification freshness, visibility policy and operator review.','A server-owned, fail-closed publication policy evaluates the proposed final record—not only the requested status patch—against the core publication criteria in the next paragraph, and returns attributable missing/invalid evidence. Optional enrichment is not a second publication threshold.');
replace(arch,'formal spot selection → the Map-parallel basic-plus-astronomy information panel → hard-blocker-aware Tonight decision, route/facility/guide/source evidence and astronomy evidence','formal spot selection (plus authorized private draft/pending selection under the Map contract) → the Map-parallel basic-plus-astronomy information panel → objective route/facility/safety/guide/source and astronomy evidence');
replace(arch,'Only a formal `spot_id` from the information panel can establish full-sky orientation context.','A formal spot or current-account submitted pending proposal from the information panel can establish typed full-sky context; drafts and arbitrary MAP_POINT input cannot bypass that entry/authorization.');
replace(arch,'A Mini Program observation plan is saved against the caller\'s current server-resolved Observation Context. The BFF derives the plan\'s formal-spot context from that owner,','A Mini Program plan is saved from its own submitted formal spot and local observing time. The existing BFF re-resolves those inputs through Observation Context; the supplied browsing context provides a recoverable route origin, not an overriding destination/time. The BFF');
replace(arch,'- A Mini Program hard safety blocker is evaluated before score aggregation and forces the effective conclusion to “不建议”. The selected design resource\'s retained “推荐” heading under a blocker is a resolved Source conflict and is not production semantics.','- Hard safety blockers remain server-owned and precede any score in consumers that retain decision outputs. Mini Program exposes the objective restriction and enforces the existing action check rather than displaying a combined “不建议/推荐” conclusion. A removed recommendation surface never permits prohibited navigation or turns unknown safety into safe access.');
replace(arch,'The primary result is a continuous observation window derived from the time grid, not an all-night average or a single instant.','For consumers that retain SkyOpportunity, its primary window is continuous and derived from the time grid, not an all-night average or a single instant. It is not restored as a Mini Program recommendation filter or panel result.');
append(arch,`## Mini Program identity, filtering and plan implementation boundaries

The current product rules are owned by [Map/Search/My](../areas/main/screen-contracts/wechat-miniapp/map-and-finder.md). The following are intended changes to existing BFF/contracts/repository owners, not claims of deployed types, endpoints or jobs.

- Extend typed ObservationLocation with an authenticated pending-proposal input. Resolve ownership, current submission state and frozen coordinates server-side on reads/context recovery; never trust a client-supplied owner or fabricate a formal spot ID. Public formal calculations may be shared only after their normal validation; private response caches include account, proposal/attempt/revision and authorization lifecycle. Separate reusable pure coordinate/time calculations from private payloads, keep private media/identity out of public cached scenes, and invalidate obsolete private reads on account/state changes. Map draft view is not an astronomy authorization.
- Publication/merge persists proposal-to-formal mapping and receipt transactionally, including merge to an existing spot. Keep submission history immutable; dependent context recovery resolves authoritative transitions and cannot resurrect a rejected or replaced pending state. The contribution owner retains working revision, immutable attempt and idempotent receipt instead of introducing another location store.
- Media garbage collection distinguishes unattached abandoned uploads from references held by saved working copies, frozen attempts and retained review evidence. Reference attachment/removal and submission must be coordinated so concurrent cleanup cannot delete an acknowledged saved image. Keep the existing sanitization, rights, retention and account-deletion boundaries; retained audit evidence is not permission to expose private media.
- The existing filter contract should carry condition identity, enabled selection, driving-duration parameter and validation; the BFF owns fact/time evaluation. Map evaluates coverage before business filtering, separately per required field and candidate, and returns truthful known/unknown coverage. A catalog-covered zero-event result is known no-match. Client results cannot derive completeness from the already filtered set or recreate predicates. Current anyWeather/anyEvents capability shortcuts and unused shared filterSpots predicates are migration gaps; they are not a justified second rule owner. Retire obsolete selections without clearing unrelated valid query/context state.
- The plan editor owns user input and optimistic revision; save re-resolves the submitted spot/time and captures a server snapshot with recoverable origin. Preserve account-bound late-response protection and idempotent save receipts. Extend that same owner for interval, departure, event and reminder data; forecast success is not a save prerequisite and shared weather-calendar coverage cannot define plan date limits.
- Reminder dispatch validates current subject, plan/reminder version, subscription eligibility, scheduled identity and departure boundary at send time, even if cancellation of an old queued job failed. Missed triggers on recovery are recorded/skipped, superseded/expired jobs never send, known failures retry only under bounded policy before departure, and unknown outcomes reconcile receipts rather than blindly duplicate a message. Group checklist state remains independent from transport state; no new notification platform or center is required.

## Sky catalog and deployment capability acceptance

- Keep astronomy-core and its offline catalog pipeline as the calculation/data owner. A unified versioned pack must describe its actual fainter-star coverage/capacity and include important recognizable bright-star references, using attributable supplemental data where necessary. Match identities and resolve duplicates, reference epochs/proper motion and magnitude-band differences explicitly; a supplemental visual magnitude is not silently labelled Gaia G. No runtime catalog downloads or client ephemeris are introduced. The present TOP-limited Gaia pack and fixture tests do not certify complete bright-star coverage.
- Retain fixture coordinate/projection tests and add a later production-pack → actual BFF projection → returned-frame coverage check, including Sirius/Vega/Polaris under suitable known horizons and times, plus negative below-horizon cases, duplicate identity, capacity and declared completeness checks. This is a required future sky acceptance boundary, not evidence produced by this documentation change.
- The current deployment capability must distinguish actual source reachability, license/account entitlement, field/model/date coverage, route modes, freshness, request cost and error state. Test from the intended execution environment; a workstation proxy or a provider’s advertised feature is insufficient. Under the Mini Program CNY350/calendar-month ceiling (excluding application/database IaaS), meter/bound provider requests and degrade optional model/animation/prewarm work first; unavailable safety inputs stay explicit and never become permissive. Budget is not purchase authority or a guarantee that every required source is reachable.
- Preserve exact-time astronomy independently from missing weather, bounded map/overview work without full star scenes, on-demand full-sky frames, cache validity and request deadlines. Extending date coverage does not prefetch every date/point/model/frame. Public map, private contribution and plan responsibilities keep their distinct lifecycles.
- Early target-runtime acceptance should cover the same physical WEAPP map → panel extents/internal scroll → exclusive layers → date/time → editor/keyboard → cancel/Back restoration. Treat overlays, native composition, touch ownership, interruption and safe areas as production checks; browser resource inspection cannot certify them or deployed provider behavior.
`);
for (const [p,s] of changed) fs.writeFileSync(p,s);
console.log(`Updated ${changed.size} Context files`);
