// Generated runtime projection of the authored values in ../../../DESIGN.md.
// DESIGN.md remains the sole exact-value authority.
export const colors = {
  planning: {
    canvas: "#F3F7FF",
    surface: "#FFFFFF",
    surfaceMuted: "#E8F1FF",
    surfaceElevated: "#FFFFFF",
    text: "#0B1B35",
    textMuted: "#435A78",
    textSecondary: "#435A78",
    border: "#6F89AA",
    primary: "#1677FF",
    primaryHover: "#4096FF",
    primaryActive: "#0958D9",
    onPrimary: "#FFFFFF",
    anchor: "#0B1B35",
    success: "#52C41A",
    warning: "#FAAD14",
    danger: "#FF4D4F",
    materialHighlight: "#FFFFFF",
    materialBody: "#6F89AA",
    materialSeam: "#435A78",
    lensCore: "#0B1B35",
    lensReflection: "#4096FF",
    rubber: "#0B1B35",
    equipmentPaint: "#0958D9",
    fabric: "#E8F1FF",
    fabricStitch: "#6F89AA",
    contactShadow: "#0B1B35",
    imageBackdrop: "#FFFFFF",
  },
  night: {
    canvas: "#020817",
    surface: "#07152B",
    surfaceMuted: "#0E2444",
    surfaceElevated: "#122E52",
    text: "#EDF5FF",
    textMuted: "#A7BDD9",
    textSecondary: "#A7BDD9",
    border: "#56779E",
    primary: "#1677FF",
    primaryHover: "#4096FF",
    primaryActive: "#0958D9",
    onPrimary: "#FFFFFF",
    anchor: "#EDF5FF",
    success: "#52C41A",
    warning: "#FAAD14",
    danger: "#FF4D4F",
    materialHighlight: "#EDF5FF",
    materialBody: "#56779E",
    materialSeam: "#A7BDD9",
    lensCore: "#020817",
    lensReflection: "#4096FF",
    rubber: "#020817",
    equipmentPaint: "#0958D9",
    fabric: "#0E2444",
    fabricStitch: "#56779E",
    contactShadow: "#020817",
    imageBackdrop: "#07152B",
  },
  redLight: {
    canvas: "#050000",
    surface: "#170000",
    surfaceMuted: "#170000",
    surfaceElevated: "#170000",
    text: "#FF9B9B",
    textMuted: "#E77474",
    textSecondary: "#E77474",
    border: "#A63F3F",
    primary: "#FF5454",
    primaryHover: "#FF5454",
    primaryActive: "#FF5454",
    onPrimary: "#050000",
    anchor: "#FF9B9B",
    success: "#FF9B9B",
    warning: "#FF9B9B",
    danger: "#FF5454",
    materialHighlight: "#FF9B9B",
    materialBody: "#A63F3F",
    materialSeam: "#E77474",
    lensCore: "#050000",
    lensReflection: "#FF5454",
    rubber: "#050000",
    equipmentPaint: "#FF5454",
    fabric: "#170000",
    fabricStitch: "#A63F3F",
    contactShadow: "#050000",
    imageBackdrop: "#FF5454",
  },
} as const;

export type DisplayMode = keyof typeof colors;
export type ColorPalette = (typeof colors)[DisplayMode];

export const modeAliases = {
  day: "planning",
  observation: "redLight",
  "red-light": "redLight",
} as const satisfies Record<string, DisplayMode>;

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  // Compatibility aliases. New implementation should prefer the named scale.
  x1: 8,
  x2: 16,
  x3: 24,
  x4: 32,
  x5: 48,
} as const;
export const radii = { compact: 5, control: 8, layer: 16, sheet: 24, pill: 999 } as const;
export const minimumTouchTarget = 44;
export const fontStacks = {
  display:
    '"Bahnschrift", "DIN Alternate", "Aptos Display", "PingFang SC", "Microsoft YaHei UI", "Microsoft YaHei", system-ui, -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  body:
    '"Aptos", "PingFang SC", "Microsoft YaHei UI", "Microsoft YaHei", system-ui, -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  data: '"Cascadia Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace',
  delivery: "unbundled-platform-dependent-fallback-safe",
} as const;
export const type = {
  displayFamily: "Bahnschrift",
  bodyFamily: "Aptos",
  dataFamily: "Cascadia Mono",
  displayStack: fontStacks.display,
  bodyStack: fontStacks.body,
  dataStack: fontStacks.data,
  // Compatibility aliases for existing React Native consumers.
  family: "Aptos",
  mono: "Cascadia Mono",
  display: 38,
  displayLineHeight: 47.5,
  title: 22,
  titleLineHeight: 27.5,
  section: 16,
  sectionLineHeight: 21,
  body: 14,
  bodyLineHeight: 22,
  label: 12,
  labelLineHeight: 15.6,
  caption: 11,
  captionLineHeight: 16.5,
  data: 14,
  dataLineHeight: 22,
} as const;
